ScottPlot/ScottPlot

demos/src/plot-types/Form1.Designer.cs
demos/src/plot-types/Form1.cs
src/ScottPlot/Plot.cs
src/ScottPlot/ScottPlot.csproj
src/ScottPlot/plottables/PlottableSignal.cs
src/ScottPlot/plottables/PlottableSignalConst.cs

Finding MinMax in RenderHighDensity (bottleneck for large signals) using Segmented Tree.
Responsitive rendering in cost of additional memory, preprocessing time and losing ability change source signal after adding.

PlotSignalConst() - faster rendering for millions of points

---

demos/src/plot-types/Form1.Designer.cs
demos/src/plot-types/Form1.cs
src/ScottPlot/Plot.cs
src/ScottPlot/plottables/PlottableSignalConst.cs

Manualy updating source signal not allowed.
To update signal SignalConst.updateData must be call.
Updates work much slower compare to Signal class.
Update  range work faster then updating by single element in loop.
Added demo button in plot types project for testing updates.

Add ability to update SignalConst

---

src/ScottPlot/MouseTracker.cs
src/ScottPlot/ScottPlotUC.cs
src/ScottPlot/ScottPlotWPF.xaml.cs
src/ScottPlot/Tools.cs

Additional speed improvement to PR #89.
Allow zoom with mouse wheel at high speed.
Mouse Wheel event render whith AA off, after configurable delay it render with current setting.
This PR will make legend looks bad on mouse wheel scroll too. #92

Delayed HQ render after mousewheel event

---

demos/src/legend/Form1.Designer.cs
demos/src/legend/Form1.cs
src/ScottPlot/Legend.cs
src/ScottPlot/Plot.cs
src/ScottPlot/Renderer.cs
src/ScottPlot/Settings.cs

Fix for Issue #92.  Legend rendered at small bitmap with separate AA settings, and draw to figure layer after data drawed.

Legend rendered at separate layer

---

src/ScottPlot/UserControls/FormsPlot.cs

Get process info on each render result lag on interactions.
Designer mode now checks only once at FormsPlot constructor.

Fix lagging on interactions

---

src/ScottPlot/plottables/PlottableSignal.cs

Add missed yOffset param to color distribution mode.

Fix for Issue #194.

---

src/ScottPlot/Plot.cs
src/ScottPlot/plottables/PlottableFunction.cs

This PR lets you pass in a delegate of type `Func<double, double>`, and plot that function.
I used the following code to test it out:
```
using System;
using System.Diagnostics;
namespace ScottPlotTesting
{
class Program
{
static void Main(string[] args)
{
var plt = new ScottPlot.Plot(600, 400);
string filename = "test.png";
plt.PlotFunction((x) => 10 * Math.Sin(x), -10, 10, -10, 50);
plt.PlotFunction((x) => Math.Pow(x, 3), -10, 10, -10, 50);
plt.SaveFig(filename);
using (Process proc = new Process())
{ // This is to open the file automatically, if you're on linux, you need xdg-open
proc.StartInfo.FileName = filename;
proc.StartInfo.UseShellExecute = true;
proc.Start();
}
}
}
}
```
This plots `y=10sinx` and `y=x^3` on the domain [-10,10] and the range [-10,50]

Creates a PlottableFunction, for plotting expressions

---

demos/WinForms/Demos/FormBillion.Designer.cs
demos/WinForms/Demos/FormBillion.cs
demos/WinForms/Demos/FormSignalConst.cs

Reduce data points generation time by using parallel calculations.
Check `x64 mode` and `treesReady` flag. Notify user about errors.
I need some help with MessageBox text messages in this PR.
Additionaly smal fix to signalConst demo to make it look better.

Billion demo improovements

---

src/ScottPlot.Demo.WPF/CookbookControl.xaml
src/ScottPlot.Demo.WPF/CookbookControl.xaml.cs
src/ScottPlot.Demo.WPF/CookbookWindow.xaml
src/ScottPlot.Demo.WPF/CookbookWindow.xaml.cs
src/ScottPlot.Demo.WPF/DemoNodeItem.cs
src/ScottPlot.Demo.WinForms/FormCookbook.cs
src/ScottPlot.Demo/DemoNodeItem.cs
src/ScottPlot.Demo/Reflection.cs

Hi Scott.
Take a look at new interactive demo. Very impressed, the architecture looks solid, you seriously approached the task.
This PR contains small refactorings which simplifies `Demo` code a bit for my opinion.

Refactor demos to use DemoNodeItem

---

src/ScottPlot/Plot.cs

As suggested in #301
Build of the project was successfull, but i was unable to build or run the whole solution in vcode online.  
Could you check whether this is working as expected?
Cheers

add SetCulture overload

---

src/ScottPlot/Tools.cs
tests/Axis/LogAxis.cs

**Purpose:**
Fix issue #376 
N/A
N/A

Unbreaks logplot for sets containing 0

---

README.md

New contributors should review [CONTRIBUTING.md](https://github.com/swharden/ScottPlot/blob/master/CONTRIBUTING.md)
**Purpose:**
Improve readme formatting around emojis
**Before:**
**After:**
N/A
N/A
**Autoformat your code:**
The build will fail if your code is not auto-formatted. Auto-format your code in Visual Studio, or from the console using these commands:
```
cd ScottPlot/src/
dotnet tool install --global dotnet-format
dotnet format
```

Mission critical changes (readme formatting)

---

README.md

Reverts swharden/ScottPlot#460
GitHub fixed their emoji spacing/rendering problem today.

Revert "GitHub change broke emoji rendering in markdown files"

---

dev/changelog.md
src/ScottPlot/Enums/RadarAxis.cs
src/ScottPlot/Plottable/RadarPlot.cs
src/cookbook/ScottPlot.Demo/PlotTypes/Radar.cs

**Purpose:**
Allows polygonal and no axis on radar charts #628
Describe what this pull request does using code and/or images.
```cs
var radarPlot = plt.PlotRadar(values);
radarPlot.axisType = RadarAxis.Polygon; // This could also be RadarAxis.None
```
**Polygonal Axis**
**No Axis**
**No Axis with Axis Labels Turned Off**

Polygonal radar axis

---

src/demo/ScottPlot.Demo.Avalonia/AvaloniaDemos/LiveDataFixed.axaml.cs
src/demo/ScottPlot.Demo.Avalonia/AvaloniaDemos/LiveDataGrowing.axaml.cs
src/demo/ScottPlot.Demo.WPF/WpfDemos/LiveDataFixed.xaml.cs
src/demo/ScottPlot.Demo.WPF/WpfDemos/LiveDataGrowing.xaml.cs
src/demo/ScottPlot.Demo.WinForms/WinFormsDemos/LiveDataIncoming.cs
src/demo/ScottPlot.Demo.WinForms/WinFormsDemos/LiveDataUpdate.cs

**Purpose:**
See #650
Fixes #649

Live Data Demos: Fix timers still running after form is closed

---

src/ScottPlot/Tools.cs

In ScottPlot.Tools.XYToIntensities
**Purpose:**
Improved performance for `ScottPlot.Tools.XYToIntensities` when using gaussian intensity mode.
The gaussian blur is separable, instead of using an n x n matrix as the kernel one can use a 1 x n matrix followed by an n x 1 matrix. This gives O(n) complexity instead of O(n^2).
Note that the previous code did not explicitly use a blur filter, but instead applied the gaussian after adding each coordinate. This is still O(n^2).
This code also precomputes the kernel, which ought to bring a performance boost of its own.
N/A

Implemented separable gaussian blur for improved performance.

---

src/ScottPlot/Drawing/GDI.cs
src/ScottPlot/Enums/IntensityMode.cs
src/ScottPlot/Plot/Plot.Add.cs
src/ScottPlot/Plot/Plot.Obsolete.cs
src/ScottPlot/Plottable/Heatmap.cs
src/ScottPlot/Tools.cs
src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/Heatmap.cs
src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/Signal.cs
src/demo/ScottPlot.Demo.WinForms/WinFormsDemos/ColormapViewer.cs
src/tests/Cookbook/Validate.cs

refactor heatmaps to address #677, #675, and #678

Refactor heatmaps

---

src/controls/ScottPlot.Avalonia/AvaPlotViewer.axaml.cs
src/controls/ScottPlot.Avalonia/ScottPlot.Avalonia.NUGET.csproj
src/controls/ScottPlot.Avalonia/ScottPlot.Avalonia.csproj
src/demo/ScottPlot.Demo.Avalonia/Avalonia Demo.csproj
src/demo/ScottPlot.Demo.Avalonia/AvaloniaDemos/PlotViewer.axaml.cs
src/demo/ScottPlot.Demo.Avalonia/CookbookWindow.axaml.cs
src/demo/ScottPlot.Demo.Avalonia/MainWindow.axaml

**Purpose:**
Adds support for Avalonia 0.10.0rc1. #571
Works correctly on the latest Avalonia Release Candidate.
I created this pull request in anticipation of an imminent non-prerelease version of Avalonia. In theory, all one would have to do is change the package references to the new version. I said earlier that I would do this once it had actually been released, however, I currently have finals and I would like to have the actual work done in advance (turned out there wasn't much work to do anyways) so I can focus on those. So even if the new version drops right in the middle of finals no one would have to wait for support on the latest …

Avalonia 0.10.0

---

src/controls/ScottPlot.Avalonia/AvaPlot.axaml.cs
src/controls/ScottPlot.WPF/WpfPlot.xaml.cs
src/controls/ScottPlot.WinForms/FormsPlot.cs
src/demo/ScottPlot.Demo.Avalonia/AvaloniaDemos/LinkedPlots.axaml
src/demo/ScottPlot.Demo.Avalonia/AvaloniaDemos/LinkedPlots.axaml.cs
src/demo/ScottPlot.Demo.WPF/WpfDemos/LinkedPlots.xaml
src/demo/ScottPlot.Demo.WPF/WpfDemos/LinkedPlots.xaml.cs
src/demo/ScottPlot.Demo.WinForms/WinFormsDemos/LinkedPlots.Designer.cs
src/demo/ScottPlot.Demo.WinForms/WinFormsDemos/LinkedPlots.cs

controls send themselves when invoking events #743

Improve user control event senders

---

src/controls/ScottPlot.WinForms/FormsPlot.Designer.cs
src/controls/ScottPlot.WinForms/FormsPlot.cs

* Control automatically renders once after it has loaded
* Detects if control is in designer mode and adds a version title it if is #732
* Defaults to a control background color #734

improve FormsPlot display in designer mode #732

---

src/controls/ScottPlot.WinForms/FormsPlot.cs

forward mouse events to base #892

---

src/ScottPlot/DataGen.cs
src/tests/DataGenTests/RenderTests.cs
src/tests/Documentation/DocumentationTests.cs

Datagen docs

---

src/ScottPlot/Plot/Plot.Add.cs
src/tests/PlotTypes/Bar.cs

AddPlot() now sets negative fill color

---

src/controls/ScottPlot.Avalonia/AvaPlot.axaml.cs
src/controls/ScottPlot.WPF/WpfPlot.xaml.cs
src/controls/ScottPlot.WinForms/FormsPlot.Designer.cs
src/controls/ScottPlot.WinForms/FormsPlot.cs

Adds "Open in New Window" to context menus

---

src/controls/ScottPlot.Avalonia/ScottPlot.Avalonia.NUGET.csproj
src/controls/ScottPlot.Avalonia/ScottPlot.Avalonia.csproj
src/demo/ScottPlot.Demo.Avalonia/Avalonia Demo.csproj

**Purpose:**
Avalonia 0.10.4 was released yesterday afternoon.
N/A

Bump Avalonia versions to 0.10.4

---

src/controls/ScottPlot.Avalonia/ScottPlot.Avalonia.NUGET.csproj
src/controls/ScottPlot.Avalonia/ScottPlot.Avalonia.csproj
src/demo/ScottPlot.Demo.Avalonia/Avalonia Demo.csproj

**Purpose:**
Bumps Avalonia versions to 0.10.5
N/A

Avalonia Version 0.10.4 -> 0.10.5

---

src/controls/ScottPlot.Avalonia/AvaPlot.axaml.cs

**Purpose:**
https://github.com/ScottPlot/ScottPlot/issues/999#issuecomment-843719638
Forwards mouse moved events to the parent object in Avalonia.

Improve mouse interactions in Avalonia control

---

dev/changelog.md
src/ScottPlot/Drawing/GDI.cs
src/controls/ScottPlot.WPF/WpfPlot.xaml
src/controls/ScottPlot.WPF/WpfPlot.xaml.cs
src/controls/ScottPlot.WinForms/FormsPlot.Designer.cs
src/controls/ScottPlot.WinForms/FormsPlot.cs
src/tests/Control/DrawingTest.cs

WpfPlot: Show plot in design mode

---

dev/docfx/.gitignore
dev/docfx/api/index.md
dev/docfx/api/index.md.txt
dev/docfx/build and serve.bat
dev/docfx/build.bat
dev/docfx/docfx.json
dev/docfx/index.md
dev/docfx/toc.yml
dev/docfx/updateVersion.py

create docfx project

---

CONTRIBUTING.md
dev/changelog.md
src/ScottPlot/Control/Backend.cs
src/controls/ScottPlot.Avalonia/AvaPlot.axaml.cs
src/controls/ScottPlot.WPF/WpfPlot.xaml.cs
src/controls/ScottPlot.WinForms/FormsPlot.cs
src/sandbox/WinFormsFrameworkApp/Form1.Designer.cs
src/sandbox/WinFormsFrameworkApp/Form1.cs

Add PlottableDragged and PlottableDropped event handlers to controls

---

dev/changelog.md
src/ScottPlot/Drawing/Colorsets/Custom.cs
src/ScottPlot/Drawing/Palette.cs
src/cookbook/ScottPlot.Cookbook/Recipes/Palette.cs

custom color palette

---

dev/changelog.md
src/ScottPlot/DataGen.cs
src/ScottPlot/Plottable/Heatmap.cs
src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/Heatmap.cs
src/tests/PlottableRenderTests/Heatmap.cs

Heatmap.Smooth - smoothing enabled by bitmap interpolation

---

src/ScottPlot/Control/Backend.cs
src/controls/ScottPlot.Avalonia/AvaPlot.axaml.cs
src/controls/ScottPlot.WPF/WpfPlot.xaml.cs
src/controls/ScottPlot.WinForms/FormsPlot.cs
src/tests/Control/ConfigurationTests.cs

Backend.Resize(): useDelayedRendering argument

---

dev/changelog.md
src/ScottPlot/Plot/Plot.cs
src/sandbox/WinFormsFrameworkApp/Form1.Designer.cs
src/sandbox/WinFormsFrameworkApp/Form1.cs
src/tests/Plot/Move.cs

Plot: Move, MoveFirst, and MoveLast

---

dev/changelog.md
src/ScottPlot/Plot/Plot.Axis.cs
src/sandbox/WinFormsFrameworkApp/Form1.Designer.cs
src/sandbox/WinFormsFrameworkApp/Form1.cs
src/tests/Axis/AutoAxis.cs

1089 autoxy

---

dev/changelog.md
src/ScottPlot/Drawing/GDI.cs
src/sandbox/WinFormsFrameworkApp/Form1.Designer.cs
src/sandbox/WinFormsFrameworkApp/Form1.cs

fix heatmap rendering bug

---

dev/changelog.md
src/ScottPlot/Plot/Plot.Render.cs
src/ScottPlot/Plot/Plot.cs
src/tests/Bitmap.cs

Plot.GetImageBytes()

---

dev/changelog.md
src/ScottPlot/Plot/Plot.Axis.cs
src/ScottPlot/Renderable/Axis.cs
src/ScottPlot/Renderable/AxisTicks.cs
src/cookbook/ScottPlot.Cookbook/Recipes/Axis.cs
src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/Finance.cs
src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/ScaleBar.cs
src/tests/Misc/Drawing.cs
src/tests/Plot/Frameless.cs
src/tests/Plot/ScaleBar.cs
src/tests/PlotTypes/Pie.cs

Improve Frameless() by making it reversible

---

dev/changelog.md
src/ScottPlot/Plottable/AxisLine.cs
src/ScottPlot/Plottable/Crosshair.cs
src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/AxisLineAndSpan.cs
src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/Crosshair.cs
src/tests/PlotTypes/AxisLine.cs
src/tests/PlotTypes/Crosshair.cs

AxisLine: support position labels

---

dev/changelog.md
src/ScottPlot/Plottable/RadarPlot.cs
src/tests/PlotTypes/Radar.cs

Fix radar plot rendering when maxValue is 0

---

dev/changelog.md
src/ScottPlot/Plot/Plot.Axis.cs
src/ScottPlot/Renderable/AxisDimensions.cs
src/sandbox/WinFormsFrameworkApp/Form1.cs
src/tests/Axis/ViewLimits.cs

Patch: Improve pan/zoom behavior when using view limits

---

dev/changelog.md
src/ScottPlot/Plottable/SignalPlotBase.cs
src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/Signal.cs
src/tests/PlotTypes/Signal.cs

Signal Plot: fix fill render error

---

src/ScottPlot/Plottable/Crosshair.cs

Crosshair: Keep compatible with older versions

---

src/demo/ScottPlot.Demo.WPF/WpfDemos/PlotInScrollViewer.xaml
src/demo/ScottPlot.Demo.WPF/WpfDemos/PlotInScrollViewer.xaml.cs
src/demo/ScottPlot.Demo.WinForms/WinFormsDemos/PlotsInScrollViewer.Designer.cs
src/demo/ScottPlot.Demo.WinForms/WinFormsDemos/PlotsInScrollViewer.cs

Update scroll viewer demos to allow toggling between scrolling or zooming (#338)

Demo (WPF): ScrollPanel

---

dev/changelog.md
src/ScottPlot/Plottable/ScatterPlot.cs
src/tests/PlotTypes/Scatter.cs

ScatterPlot: OffsetX and OffsetY

---

dev/changelog.md
src/ScottPlot/Plot/Plot.Add.cs
src/ScottPlot/Plottable/VectorField.cs
src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/VectorField.cs

VectorField: scaled arrowheads and markers

---

dev/changelog.md
src/ScottPlot/Plot/Plot.Render.cs
src/tests/Plot/PlotTests.cs

Ticks: improve positions when using scale lock

---

dev/changelog.md
dev/python/equal-axis/demo.py
src/ScottPlot/Enums/EqualScaleMode.cs
src/ScottPlot/Plot/Plot.Axis.cs
src/ScottPlot/Renderable/AxisDimensions.cs
src/ScottPlot/Settings.cs
src/demo/ScottPlot.Demo.Avalonia/AvaloniaDemos/AxisLimits.axaml.cs
src/demo/ScottPlot.Demo.WPF/WpfDemos/AxisLimits.xaml.cs
src/demo/ScottPlot.Demo.WinForms/WinFormsDemos/AxisLimits.cs
src/sandbox/WinFormsFrameworkApp/Form1.cs
src/sandbox/WpfApp/MainWindow.xaml
src/sandbox/WpfApp/MainWindow.xaml.cs
src/tests/Axis/ViewLimits.cs

This PR explores alternate modes for resizing while zooming. Resolves #1197

improve resize zoom behavior

---

dev/changelog.md
src/ScottPlot/Plottable/SignalPlotBase.cs
src/ScottPlot/Plottable/SignalPlotXYGeneric.cs
src/tests/PlotTypes/SignalXY.cs

SignalXY: Support FillType

---

src/controls/ScottPlot.Avalonia/AvaPlot.axaml.cs
src/controls/ScottPlot.WPF/WpfPlot.xaml.cs
src/controls/ScottPlot.WinForms/FormsPlot.cs

fixes #1246 introduced by #1245

Controls: improve initialization sequence to prevent design time crashes

---

dev/changelog.md
src/ScottPlot/Renderable/AxisTicks.cs
src/ScottPlot/Renderable/AxisTicksRender.cs
src/sandbox/WinFormsFrameworkApp/Form1.cs

Ticks: fix multiplier notation

---

.github/workflows/ci.yaml
.github/workflows/nuget.yaml
dev/changelog.md
src/ScottPlot/ScottPlot.csproj
src/controls/ScottPlot.WPF/ScottPlot.WPF.NUGET.csproj
src/controls/ScottPlot.WinForms/ScottPlot.WinForms.NUGET.csproj

Improve NuGet packages

---

src/demo/ScottPlot.Demo.Avalonia/AvaloniaDemos/StyleBrowser.axaml
src/demo/ScottPlot.Demo.Avalonia/AvaloniaDemos/StyleBrowser.axaml.cs
src/demo/ScottPlot.Demo.Avalonia/MainWindow.axaml
src/demo/ScottPlot.Demo.Avalonia/MainWindow.axaml.cs

**Purpose:**
Describe what this pull request accomplishes. If it addresses an issue, link to it here.
https://github.com/ScottPlot/ScottPlot/pull/1299#issuecomment-930652450
Adds the style browser to the Avalonia demo:

Adds StyleBrowser to Avalonia demo

---

src/controls/ScottPlot.Avalonia/ScottPlot.Avalonia.NUGET.csproj

Avalonia now targets .NET 5

---

README.md

- Change links to new domain.
~~#1307~~ EDIT (@swharden): this PR changes the font GitHub readmes, not the readme packed in the NuGet packages which still requires updating (#1307)

Update URLs in main README

---

src/ScottPlot/Palette.cs
src/ScottPlot/Palettes/Custom.cs
src/ScottPlot/Palettes/HexColorset.cs
src/ScottPlot/Palettes/SummerSplash.cs
src/tests/PaletteTests.cs

added a new fresh summer color palette . 
i hope you like it 
do tell me if there are some errors .
happy hacking !

Palette: SummerSplash

---

dev/changelog.md
src/ScottPlot/Style.cs
src/ScottPlot/Styles/Burgundy.cs

**Purpose:**
* A burgundy-light style that fits many polychromatic and dark palettes such as `Category10`, `Dark`, `Microcharts`, and so on.

Style: Burgundy

---

src/ScottPlot/Style.cs
src/ScottPlot/Styles/Earth.cs
src/demo/ScottPlot.Demo.Avalonia/AvaloniaDemos/StyleBrowser.axaml
src/demo/ScottPlot.Demo.Avalonia/AvaloniaDemos/StyleBrowser.axaml.cs
src/demo/ScottPlot.Demo.WPF/WpfDemos/StyleBrowser.xaml.cs
src/demo/ScottPlot.Demo.WinForms/WinFormsDemos/Styles.cs

**Purpose:**
* New style Earth
* Issue #1315

Style: Earth

---

dev/changelog.md

**Purpose:**
https://github.com/ScottPlot/ScottPlot/pull/1309#issuecomment-933040558

#1309 noted in changelog

---

src/ScottPlot/Drawing/Palette.cs
src/ScottPlot/Palette.cs
src/ScottPlot/Palettes/Redness.cs

**Purpose:**
* New palette - Redness.
* Issue #1315

Palette: Redness

---

src/ScottPlot/Style.cs
src/ScottPlot/Styles/Pink.cs

Added new color style for "Pink" for Hacktoberfest 2021
Issue: https://github.com/ScottPlot/ScottPlot/issues/1315

Style: Pink

---

dev/changelog.md
src/ScottPlot/Renderable/AxisDimensions.cs
src/tests/Plot/GetCoordinate.cs
src/tests/Plot/GetPixel.cs

fix GetPixel()

---

src/ScottPlot/Style.cs
src/ScottPlot/Styles/Hazel.cs

**Purpose:**
* Added new Style - Hazel
* #1315

Style - Hazel

---

src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/Fill.cs

**Purpose:** #1441
```cs
double SupplyFunction(double q) => 5 * q + 1;
double DemandFunction(double q) => -3 * q + 17;
const double priceFloor = 12.5;
double[] xs = DataGen.Consecutive(5);
double[] supply = xs.Select(SupplyFunction).ToArray();
double[] demand = xs.Select(DemandFunction).ToArray();
plt.AddScatter(xs, supply, markerShape: MarkerShape.none, label: "Supply");
plt.AddScatter(xs, demand, markerShape: MarkerShape.none, label: "Demand");
plt.AddHorizontalLine(priceFloor, label: "Price Floor");
double[] maxProducerSurplusBounds = new double[] { 0, 1.5 };
var maxProducerSurplus = plt.AddFill(maxProducerSurplusBounds, maxProducerSurplusBounds.Select(SupplyFunction).ToArray(), maxProducerSurplusBounds, Enumerable.Repeat(priceFloor, 2).ToArray());
maxProducerSurplus.LineWidth = 0; …
```

Creates hatched fill demo

---

dev/changelog.md
src/ScottPlot/Plottable/MarkerPlot.cs

Small fixes for issues #1423 and #1454.

MarkerPlot: respect plot borders and correctly display legend

---

.github/workflows/ci.yaml
dev/changelog.md
src/ScottPlot/Plot/Plot.cs
src/ScottPlot/Plottable/Colorbar.cs
src/ScottPlot/Plottable/IStylable.cs
src/ScottPlot/Plottable/ScaleBar.cs
src/ScottPlot/Plottable/SignalPlotXYGeneric.cs
src/autoformat.bat
src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/Heatmap.cs
src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/ScaleBar.cs

PR for #1447 
- Apply style to Colorbar and ScaleBar

IStylable for plottables like Colorbar and ScaleBar

---

dev/changelog.md
src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/Colorbar.cs

Cookbook: colormap scatter plot

---

.github/workflows/ci.yaml
dev/changelog.md
src/controls/ScottPlot.WinForms/ScottPlot.WinForms.csproj
src/sandbox/WinFormsApp/WinFormsApp.csproj

Update the FormsPlot package to also target .NET 6 to address #1430 and solve #1483

FormsPlot: also target .NET 6

---

dev/changelog.md
src/ScottPlot/Plot/Plot.Axis.cs
src/tests/Axis/AutoAxis.cs

Plot: fix multi-axis AxisAuto()

---

src/ScottPlot/Plot/Plot.Axis.cs
src/ScottPlot/Settings.cs
src/sandbox/WinFormsApp/Form1.Designer.cs
src/sandbox/WinFormsApp/Form1.cs

This PR (an extension of #1497) improves arguments and behavior of AxisAuto methods to better support multi-axis plots

Plot: improve multi-axis support in all AxisAuto() methods

---

dev/changelog.md
src/ScottPlot/Pixel.cs
src/ScottPlot/Plottable/ArrowCoordinated.cs
src/ScottPlot/Plottable/IHasPixelOffset.cs
src/ScottPlot/Plottable/Text.cs
src/tests/PlottableRenderTests/Arrow.cs
src/tests/PlottableRenderTests/Text.cs

IHasPixelOffset for Text and Arrow plots

---

dev/changelog.md
src/ScottPlot/Plottable/Image.cs
src/tests/PlottableRenderTests/Image.cs

Image: add Scale property

---

dev/changelog.md
src/ScottPlot/Plot/Plot.Axis.cs
src/tests/Axis/AutoAxis.cs

Plot.GetDataLimits()

---

dev/changelog.md
src/ScottPlot/Drawing/GDI.cs
src/ScottPlot/Plottable/Image.cs
src/ScottPlot/Plottable/RadialGauge.cs
src/ScottPlot/Plottable/RadialGaugePlot.cs
src/ScottPlot/Plottable/Text.cs
src/ScottPlot/Renderable/AxisLabel.cs
src/ScottPlot/Renderable/AxisTicksRender.cs
src/tests/Plot/Render.cs

Rendering: Re-apply scaling after calling ResetTransform()

---

src/cookbook/ScottPlot.Cookbook/RecipeJson.cs

Cookbook: permit uppercase JSON identifiers

---

dev/changelog.md
src/ScottPlot/Control/Backend.cs
src/ScottPlot/Drawing/GDI.cs

Drawing: default to ClearType font rendering

---

.github/workflows/ci.yaml
.github/workflows/package.yaml

copy of #1528 because auto-merge was failing for unknown reasons

CI: build and deploy packages individually

---

dev/changelog.md
src/ScottPlot/Plot/Plot.Axis.cs

Fix GetDataLimits when AxisLine or AxisSpan is present

---

dev/changelog.md
src/ScottPlot/Plot/Plot.Axis.cs
src/ScottPlot/Plottable/BarPlot.cs
src/ScottPlot/Plottable/BarPlotBase.cs
src/ScottPlot/Plottable/ClevelandDotPlot.cs
src/ScottPlot/Plottable/LollipopPlot.cs
src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/Bar.cs

Bar: add ValueFormatter

---

dev/changelog.md
src/ScottPlot/Statistics/Interpolation/Cubic.cs
src/ScottPlot/Statistics/Interpolation/EndSlopeSpline.cs
src/ScottPlot/Statistics/Interpolation/Matrix.cs
src/ScottPlot/Statistics/Interpolation/MatrixSolver.cs
src/ScottPlot/Statistics/Interpolation/NaturalSpline.cs
src/ScottPlot/Statistics/Interpolation/PeriodicSpline.cs
src/ScottPlot/Statistics/Interpolation/SplineInterpolator.cs
src/cookbook/ScottPlot.Cookbook/Recipes/Misc.cs
src/tests/Statistics/Interpolation.cs

I added a cubic interpolation module using adapted from MIT-licensed code I found online originally written by Ryan Seghers
old code | new code
---|---
old code | new code
---|---
`InvalidOperationException ` | ![image](https://user-images.githubusercontent.com/4165489/150062413-8492a669-22cc-4678-9715-00b4260e3c38.png)

Interpolation: cubic spline interpolation

---

dev/changelog.md
src/ScottPlot/Control/Backend.cs
src/ScottPlot/Plot/Plot.cs
src/ScottPlot/Renderable/Legend.cs
src/tests/Legend/LegendTests.cs

RenderLegend: Improve behavior when legend is empty

---

.github/pull_request_template.md
dev/changelog.md
src/ScottPlot/Coordinate.cs
src/ScottPlot/DataGen.cs
src/ScottPlot/Pixel.cs
src/ScottPlot/Plot/Plot.Add.cs
src/ScottPlot/Plottable/ErrorBar.cs
src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/ErrorBar.cs

Creates errorbar plottable and cookbook

---

src/ScottPlot/Plottable/ErrorBar.cs

Fixes https://github.com/ScottPlot/ScottPlot/pull/1588#issuecomment-1019414200 (re #1588 #1466)

ErrorBar: clip to data area

---

dev/changelog.md
src/ScottPlot/AxisLimits.cs
src/ScottPlot/Coordinate.cs
src/ScottPlot/Plot/Plot.Add.cs
src/ScottPlot/Plottable/ScatterPlotList.cs
src/ScottPlot/Plottable/ScatterPlotListDraggable.cs
src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/ScatterList.cs
src/tests/PlottableRenderTests/ScatterMutable.cs

* support generics - #1463
* create draggable version - #1422

ScatterPlotList<T> improvements

---

dev/changelog.md
src/ScottPlot/Renderable/Axis.cs
src/ScottPlot/Ticks/TickCollection.cs
src/cookbook/ScottPlot.Cookbook/Recipes/AxisAdvanced.cs
src/tests/Axis/LogAxis.cs

Ticks: support custom log-scale tick density

---

src/demo/ScottPlot.Demo.WinForms/WinFormsDemos/LinkedPlots.cs
src/demo/ScottPlot.Demo.WinForms/WinFormsDemos/MouseTracker.cs
src/demo/ScottPlot.Demo.WinForms/WinFormsDemos/PlotsInScrollViewer.cs

Improve demo applications

---

src/ScottPlot/Statistics/Interpolation/Bezier.cs
src/ScottPlot/Statistics/Interpolation/CatmullRom.cs
src/ScottPlot/Statistics/Interpolation/Chaikin.cs
src/ScottPlot/Statistics/Interpolation/PointD.cs
src/cookbook/ScottPlot.Cookbook/Recipes/Misc.cs
src/demo/ScottPlot.Demo.WinForms/DemoListControl.Designer.cs
src/demo/ScottPlot.Demo.WinForms/DemoListControl.cs
src/demo/ScottPlot.Demo.WinForms/DemoListControl.resx
src/demo/ScottPlot.Demo.WinForms/FormMain.Designer.cs
src/demo/ScottPlot.Demo.WinForms/FormMain.cs
src/demo/ScottPlot.Demo.WinForms/FormMain.resx
src/demo/ScottPlot.Demo.WinForms/WinFormsDemos/SplineInterpolation.Designer.cs
src/demo/ScottPlot.Demo.WinForms/WinFormsDemos/SplineInterpolation.cs
src/demo/ScottPlot.Demo.WinForms/WinFormsDemos/SplineInterpolation.resx
src/sandbox/ConsoleApp/Program.cs

Interpolation: Bézier splines and additional curves

---

dev/changelog.md
src/ScottPlot/Plottable/MarkerPlot.cs
src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/Marker.cs

MarkerPlot: add optional Text label

---

src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/Scatter.cs

Cookbook demo for Forest Plots

---

src/ScottPlot/Plot/Plot.Add.cs

Removes incorrect comment

---

src/ScottPlot/DataGen.cs
src/ScottPlot/Plottable/BarPlotBase.cs
src/ScottPlot/Plottable/DataStructures/OHLC.cs
src/ScottPlot/Plottable/FinancePlot.cs
src/demo/ScottPlot.Demo.WinForms/DemoListControl.Designer.cs
src/demo/ScottPlot.Demo.WinForms/DemoListControl.cs
src/demo/ScottPlot.Demo.WinForms/FormMain.cs
src/demo/ScottPlot.Demo.WinForms/WinFormsDemos/FinanceDemo.Designer.cs
src/demo/ScottPlot.Demo.WinForms/WinFormsDemos/FinanceDemo.cs
src/demo/ScottPlot.Demo.WinForms/WinFormsDemos/FinanceDemo.resx

This PR adds a finance demo showing a growing OHLC chart with volume indicators.
This is not easy because bar charts don't support `Add()` at the moment.
Resolves #1611

WinForms demo: finance demo

---

dev/changelog.md
src/ScottPlot/Coordinate.cs
src/ScottPlot/Pixel.cs
src/ScottPlot/PlotDimensions.cs
src/ScottPlot/Settings.cs
src/tests/Plot/PlotDimensionsTests.cs

PlotDimensions: fix GetCoordinateY(), add tests, and refactor

---

dev/changelog.md
src/ScottPlot/Plot/Plot.Add.cs
src/ScottPlot/Plottable/Colorbar.cs
src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/Colorbar.cs

Colorbar: support placement on the left

---

src/cookbook/ScottPlot.Cookbook/Recipes/MultiAxis.cs

```cs
//Before
plt.YAxis.Label("Secondary Y Axis");
//After
plt.YAxis.Label("Primary Y Axis");
```

Change : Change word from Secondary to Primary

---

dev/changelog.md
dev/python/heatmap/1485.py
src/ScottPlot/Plottable/Colorbar.cs
src/ScottPlot/Plottable/Heatmap.cs
src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/Heatmap.cs
src/tests/PlottableRenderTests/Heatmap.cs

Heatmap: improve manual color scaling

---

dev/changelog.md
src/ScottPlot/Plottable/Colorbar.cs

Colorbar: expose DataAreapadding

---

src/cookbook/ScottPlot.Cookbook/RecipeImages.cs
src/tests/Cookbook/Generate.cs

Cookbook: display image hashes

---

src/ScottPlot/Plottable/ArrowCoordinated.cs
src/ScottPlot/Plottable/AxisLine.cs
src/ScottPlot/Plottable/AxisLineVector.cs
src/ScottPlot/Plottable/AxisSpan.cs
src/ScottPlot/Plottable/BarPlot.cs
src/ScottPlot/Plottable/Crosshair.cs
src/ScottPlot/Plottable/DraggableMarkerPlot.cs
src/ScottPlot/Plottable/ErrorBar.cs
src/ScottPlot/Plottable/FunctionPlot.cs
src/ScottPlot/Plottable/IHasColor.cs
src/ScottPlot/Plottable/MarkerPlot.cs
src/ScottPlot/Plottable/Polygon.cs
src/ScottPlot/Plottable/Polygons.cs
src/ScottPlot/Plottable/RepeatingAxisLine.cs
src/ScottPlot/Plottable/ScaleBar.cs
src/ScottPlot/Plottable/ScatterPlot.cs
src/ScottPlot/Plottable/SignalPlotBase.cs
src/ScottPlot/Plottable/Text.cs
src/ScottPlot/Plottable/Tooltip.cs

Plottable: IHasColor

---

dev/changelog.md
src/ScottPlot/Plot/Plot.Obsolete.cs

This method helps create wiggle plots #450

Plot: PlotFillRightLeft()

---

dev/changelog.md
src/ScottPlot/Settings.cs
src/sandbox/WinFormsApp/Form1.Designer.cs
src/sandbox/WinFormsApp/Form1.cs

Plot: Throw exception if AxisAuto() margin is invalid

---

dev/changelog.md
src/ScottPlot/Plottable/SignalPlotXYGeneric.cs
src/sandbox/WinFormsApp/Form1.cs

Reported in #1699, #1697
Resolves #1703

SignalXY: fix StepDisplay render errors

---

src/ScottPlot4/ScottPlot.Eto/PlotView.cs
src/ScottPlot4/changelog.md

should hopefully solve https://github.com/ScottPlot/ScottPlot/discussions/1718

eto: use eventhandlers so events get passed also to others

---

src/ScottPlot4/ScottPlot.Tests/Colormap/ColormapTests.cs
src/ScottPlot4/ScottPlot/Plot/Plot.cs
src/ScottPlot4/ScottPlot/Renderable/Axis.cs
src/ScottPlot4/changelog.md

Axis: ResetLayout()

---

src/ScottPlot4/ScottPlot.Avalonia/AvaPlot.axaml.cs
src/ScottPlot4/ScottPlot.Avalonia/ScottPlot.Avalonia.NUGET.csproj
src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WPF/DemoListControl.xaml
src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WPF/DemoListControl.xaml.cs
src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WPF/MainWindow.xaml
src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WPF/MainWindow.xaml.cs
src/ScottPlot4/ScottPlot.Eto/PlotView.cs
src/ScottPlot4/ScottPlot.Eto/ScottPlot.Eto.NUGET.csproj
src/ScottPlot4/ScottPlot.WPF/ScottPlot.WPF.NUGET.csproj
src/ScottPlot4/ScottPlot.WPF/WpfPlot.xaml.cs
src/ScottPlot4/ScottPlot.WinForms/ScottPlot.WinForms.NUGET.csproj
src/ScottPlot4/ScottPlot/ScottPlot.csproj
src/ScottPlot4/changelog.md

Control: multi-axis support for GetMouseCoordinates()

---

src/ScottPlot4/ScottPlot.Tests/PlotTypes/Bar.cs
src/ScottPlot4/ScottPlot/Plottable/BarPlotBase.cs
src/ScottPlot4/changelog.md

bar plot: improve automatic axis limit detection

---

src/ScottPlot4/ScottPlot.Avalonia/ScottPlot.Avalonia.NUGET.csproj
src/ScottPlot4/ScottPlot.Eto/ScottPlot.Eto.NUGET.csproj
src/ScottPlot4/ScottPlot.WPF/ScottPlot.WPF.NUGET.csproj
src/ScottPlot4/ScottPlot.WinForms/ScottPlot.WinForms.NUGET.csproj
src/ScottPlot4/ScottPlot/Plottable/SignalPlotXYGeneric.cs
src/ScottPlot4/ScottPlot/ScottPlot.csproj
src/ScottPlot4/changelog.md

fixes a bug where the last point was not checked - resolves #1757

SignalPlotXY: improve GetPointNearestX calculation

---

src/ScottPlot4/ScottPlot.Cookbook/Recipes/Quickstart.cs
src/ScottPlot4/ScottPlot.WinForms/FormsPlot.cs
src/ScottPlot4/ScottPlot.WinForms/FormsPlotLegendViewer.cs
src/ScottPlot4/ScottPlot/Plot/Plot.cs
src/ScottPlot4/changelog.md

investigates and resolves #1765

Improve detached legend

---

src/ScottPlot4/ScottPlot.Avalonia/ScottPlot.Avalonia.NUGET.csproj
src/ScottPlot4/ScottPlot.Eto/ScottPlot.Eto.NUGET.csproj
src/ScottPlot4/ScottPlot.Sandbox/WinFormsApp/Form1.Designer.cs
src/ScottPlot4/ScottPlot.Sandbox/WinFormsApp/Form1.cs
src/ScottPlot4/ScottPlot.WPF/ScottPlot.WPF.NUGET.csproj
src/ScottPlot4/ScottPlot.WinForms/ScottPlot.WinForms.NUGET.csproj
src/ScottPlot4/ScottPlot/Plottable/AxisLine.cs
src/ScottPlot4/ScottPlot/Renderable/Axis.cs
src/ScottPlot4/ScottPlot/ScottPlot.csproj
src/ScottPlot4/changelog.md

Improve axis line label support for multi-axis plots

---

src/ScottPlot4/ScottPlot/Plottable/SignalPlotBase.cs
src/ScottPlot4/changelog.md

Signal: respect LineStyle.None in low density mode

---

src/ScottPlot4/ScottPlot.Sandbox/WinFormsApp/Form1.cs
src/ScottPlot4/ScottPlot.WinForms/FormsPlot.cs
src/ScottPlot4/ScottPlot.WinForms/FormsPlotLegendViewer.cs
src/ScottPlot4/changelog.md

LegendViewer: restore initial visibility on close

---

src/ScottPlot4/ScottPlot/Plottable/ScatterPlotDraggable.cs
src/ScottPlot4/changelog.md

ScatterPlotDraggable: fix drag limit logic

---

src/ScottPlot4/ScottPlot.Avalonia/AvaPlot.axaml.cs
src/ScottPlot4/ScottPlot.Eto/PlotView.cs
src/ScottPlot4/ScottPlot.Sandbox/WinFormsApp/Form1.cs
src/ScottPlot4/ScottPlot.WPF/WpfPlot.xaml.cs
src/ScottPlot4/ScottPlot.WinForms/FormsPlot.cs
src/ScottPlot4/ScottPlot/Control/Backend.cs
src/ScottPlot4/ScottPlot/Plottable/Heatmap.cs
src/ScottPlot4/changelog.md

* Adds `Heatmap.GetCellIndexes()`
* Adds `LeftClicked` event to all controls
resolves #1822

Heatmap: improve mouse interactivity

---

src/ScottPlot4/ScottPlot.Avalonia/ScottPlot.Avalonia.NUGET.csproj
src/ScottPlot4/ScottPlot.Eto/ScottPlot.Eto.NUGET.csproj
src/ScottPlot4/ScottPlot.Tests/Validation/ScatterXY.cs
src/ScottPlot4/ScottPlot.Tests/Validation/SignalXY.cs
src/ScottPlot4/ScottPlot.WPF/ScottPlot.WPF.NUGET.csproj
src/ScottPlot4/ScottPlot.WinForms/ScottPlot.WinForms.NUGET.csproj
src/ScottPlot4/ScottPlot/Plottable/SignalPlotBase.cs
src/ScottPlot4/ScottPlot/Plottable/SignalPlotXYGeneric.cs
src/ScottPlot4/ScottPlot/ScottPlot.csproj
src/ScottPlot4/ScottPlot/Validate.cs
src/ScottPlot4/changelog.md

SignalXY: permit duplicate X values and improve exception messages

---

src/ScottPlot4/ScottPlot.Cookbook/Recipes/MultiAxis.cs

Cookbook: fix "Top X Axis" title

---

src/ScottPlot4/ScottPlot.Cookbook/Categories/PlotTypes/Bracket.cs
src/ScottPlot4/ScottPlot.Cookbook/Recipes/Plottable/Bracket.cs
src/ScottPlot4/ScottPlot.Tests/Cookbook/Validate.cs
src/ScottPlot4/ScottPlot.Tests/PlotTypes/Bracket.cs
src/ScottPlot4/ScottPlot/Pixel.cs
src/ScottPlot4/ScottPlot/Plot/Plot.Add.cs
src/ScottPlot4/ScottPlot/Plottable/Bracket.cs
src/ScottPlot4/ScottPlot/ScottPlot.csproj
src/ScottPlot4/changelog.md

**Purpose:**
#1302 #1028
```cs
double x1 = 0;
double y1 = 0;
double x2 = 1;
double y2 = 1;
var defaultBracket = plt.AddBracket(x1, y1, x2, y2);
defaultBracket.Label = "Default";
var invertedBracket = plt.AddBracket(x1, y1, x2, y2);
invertedBracket.Label = "Inverted";
invertedBracket.Invert = true;
```

Bracket Plottable

---

src/ScottPlot4/ScottPlot.Cookbook/Recipes/Plottable/ScatterList.cs
src/ScottPlot4/ScottPlot.Tests/PlotTypes/Scatter.cs
src/ScottPlot4/ScottPlot.Tests/PlotTypes/ScatterPlotList.cs
src/ScottPlot4/ScottPlot/Plottable/ScatterPlot.cs
src/ScottPlot4/ScottPlot/Plottable/ScatterPlotList.cs
src/ScottPlot4/changelog.md

resolves #1852 and resolves #1853

Scatter Plot: Smooth option

---

src/ScottPlot4/ScottPlot.Cookbook/Categories/PlotTypes/BarSeries.cs
src/ScottPlot4/ScottPlot.Cookbook/Recipes/Plottable/BarSeries.cs
src/ScottPlot4/ScottPlot.Sandbox/WinFormsApp/Form1.cs
src/ScottPlot4/ScottPlot.Tests/PlotTypes/BarSeriesTests.cs
src/ScottPlot4/ScottPlot/AxisLimits.cs
src/ScottPlot4/ScottPlot/Pixel.cs
src/ScottPlot4/ScottPlot/Plot/Plot.Add.cs
src/ScottPlot4/ScottPlot/Plottable/Bar.cs
src/ScottPlot4/ScottPlot/Plottable/BarSeries.cs
src/ScottPlot4/ScottPlot/Plottable/ErrorBar.cs
src/ScottPlot4/changelog.md

* Created a `Bar` object to describe features of a single bar
* Created a `BarSeries` plot type that accepts a `List<Bar>`
* Resolves #1749
* Resolves #1891

BarSeries: new bar plot with improved customization and mouse interactivity

---

src/ScottPlot4/ScottPlot.Cookbook/Recipes/Plottable/SignalConst.cs
src/ScottPlot4/ScottPlot/Pixel.cs
src/ScottPlot4/ScottPlot/Plottable/SignalPlotBase.cs
src/ScottPlot4/changelog.md

resolves #1895 and resolves #1893

SignalConst: Fix Update() bug and add cookbook example

---

src/ScottPlot4/ScottPlot.Tests/Misc/Drawing.cs
src/ScottPlot4/ScottPlot/Plottable/ScatterPlot.cs
src/ScottPlot4/ScottPlot/Plottable/SignalPlotBase.cs
src/ScottPlot4/ScottPlot/Plottable/SignalPlotXYGeneric.cs
src/ScottPlot4/changelog.md

Scatter and Signal: add option to control step display orientation

---

src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.CookbookGenerator/Website.cs
src/ScottPlot4/ScottPlot/Palette.cs

Cookbook: add Palette and Colormap pages

---

src/ScottPlot4/ScottPlot.Cookbook/Recipes/MultiAxis.cs

Cookbook: multi-axis SetAxisLimits() example

---

src/ScottPlot4/ScottPlot.Sandbox/WinFormsApp/Form1.Designer.cs
src/ScottPlot4/ScottPlot.Sandbox/WinFormsApp/Form1.cs
src/ScottPlot4/ScottPlot.WinForms/FormsPlot.cs
src/ScottPlot4/ScottPlot/Control/Configuration.cs
src/ScottPlot4/changelog.md

FormsPlot: Fix stack overflow exceptions caused by mouse-move renders

---

src/ScottPlot4/ScottPlot.Cookbook/RecipeJson.cs
src/ScottPlot4/changelog.md

Cookbook: improve message if recipes.json is not found

---

src/ScottPlot4/ScottPlot.Cookbook/Recipes/Layout.cs
src/ScottPlot4/ScottPlot/Settings.cs
src/ScottPlot4/changelog.md

* resolves #1907
* resolves #1901
* resolves #1911

Layout: axes respect ManualDataPadding

---

src/ScottPlot4/ScottPlot.Cookbook/RecipeJson.cs

Cookbook: improve recipes.json search paths

---

src/ScottPlot4/ScottPlot.Tests/FontsTests.cs
src/ScottPlot4/ScottPlot/Drawing/InstalledFont.cs

InstalledFont: use case invariant keys

---

src/ScottPlot4/ScottPlot/Plottable/ScatterPlot.cs
src/ScottPlot4/ScottPlot/Plottable/SignalPlotBase.cs

**Purpose:**
Some fields have been left public after refactoring, this PR makes them private.

Fix accessibility of fields

---

src/ScottPlot4/ScottPlot.Avalonia/ScottPlot.Avalonia.NUGET.csproj
src/ScottPlot4/ScottPlot.Cookbook/Recipes/Layout.cs
src/ScottPlot4/ScottPlot.Cookbook/Website.cs
src/ScottPlot4/ScottPlot.Eto/ScottPlot.Eto.NUGET.csproj
src/ScottPlot4/ScottPlot.WPF/ScottPlot.WPF.NUGET.csproj
src/ScottPlot4/ScottPlot.WinForms/ScottPlot.WinForms.NUGET.csproj
src/ScottPlot4/ScottPlot/Plot/Plot.Render.cs
src/ScottPlot4/ScottPlot/ScottPlot.csproj
src/ScottPlot4/changelog.md

* resolves #1937 
* resolves #1934 
* resolves #1938
* resolves #1925

ScottPlot 4.1.52

---

.github/workflows/ci.yaml
README.md
dev/roadmap.md
src/ScottPlot5/ScottPlot.Tests/ScottPlot.Tests.csproj
src/ScottPlot5/ScottPlot/ScottPlot.csproj

Documentation: update readmes

---

src/Common/ScottPlot.Common/NamedColors/NamedColorsBase.cs
src/Common/ScottPlot.Common/ScottPlot.Common.csproj
src/Common/ScottPlot.Common/Usings.cs
src/ScottPlot4/ScottPlot/ScottPlot.csproj
src/ScottPlot5/ScottPlot/ScottPlot.csproj

Common: import .cs files (not reference .csproj)

---

src/ScottPlot5/Controls/ScottPlot.Avalonia/AvaPlot.axaml.cs
src/ScottPlot5/Sandbox/ScottPlot.Sandbox.WPF/MainWindow.xaml.cs
src/ScottPlot5/ScottPlot.WPF/WpfPlot.xaml.cs
src/ScottPlot5/ScottPlot.WPF/WpfPlotExtensions.cs
src/ScottPlot5/ScottPlot.WinForms/FormsPlot.cs
src/ScottPlot5/ScottPlot/Control/Backend.cs
src/ScottPlot5/ScottPlot/Control/IPlotControl.cs
src/ScottPlot5/ScottPlot/Control/InputMap.cs
src/ScottPlot5/ScottPlot/Control/Interactions/IInteractions.cs
src/ScottPlot5/ScottPlot/Control/Interactions/StandardInteractions.cs
src/ScottPlot5/ScottPlot/Control/MouseButton.cs

Controls now have an InputMap class which defines which mouse buttons and keyboard keys are connected to which actions.
Users who wish to achieve superior UI customization can still implement a custom IInteraction that the backend uses.

ScottPlot5 controls: InputMap

---

src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WinForms/DemoListControl.Designer.cs
src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WinForms/DemoListControl.cs
src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WinForms/DemoListControl.resx
src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WinForms/FormMain.Designer.cs
src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WinForms/FormMain.cs
src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WinForms/FormMain.resx
src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WinForms/WinForms Demo.csproj
src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WinForms/WinFormsDemos/HittableDemo.cs
src/ScottPlot4/ScottPlot.Sandbox/WinFormsApp/Form1.cs

Adds an IHittable demo
resolves #1962

ScottPlot4: improve IHittable

---

src/ScottPlot4/ScottPlot.Cookbook/Recipes/Plottable/AxisLineAndSpan.cs
src/ScottPlot4/ScottPlot.Sandbox/WinFormsApp/Form1.Designer.cs
src/ScottPlot4/ScottPlot.Sandbox/WinFormsApp/Form1.cs
src/ScottPlot4/ScottPlot/Plottable/AxisLine.cs
src/ScottPlot4/ScottPlot/Plottable/AxisLineVector.cs
src/ScottPlot4/ScottPlot/Plottable/AxisSpan.cs
src/ScottPlot4/ScottPlot/Plottable/DraggableMarkerPlot.cs
src/ScottPlot4/ScottPlot/Plottable/DraggableMarkerPlotInVector.cs
src/ScottPlot4/ScottPlot/Plottable/IDraggable.cs
src/ScottPlot4/ScottPlot/Plottable/RepeatingAxisLine.cs
src/ScottPlot4/ScottPlot/Plottable/ScatterPlotDraggable.cs
src/ScottPlot4/ScottPlot/Plottable/ScatterPlotListDraggable.cs
src/ScottPlot4/ScottPlot/Plottable/Text.cs
src/ScottPlot4/changelog.md

Adds `DragSnapX` and `DragSnapY` functions to axis lines, axis spans, vectors, draggable markers, draggable vectors, draggable scatter plot, and draggable text, allowing users to customize snapping behavior
resolves #2007 (extends #2006)

IDraggable: add DragSnapX and DragSnapY functions

---

src/ScottPlot4/ScottPlot/Plot/Plot.Axis.cs
src/ScottPlot4/changelog.md

Plot: MatchAxis no longer modifies limits of unintended axes

---

src/ScottPlot4/ScottPlot/Plot/Plot.Render.cs
src/ScottPlot4/changelog.md

Plot: throw if infinite axis limits in Render()

---

src/ScottPlot4/ScottPlot/Plottable/SignalPlotBase.cs
src/ScottPlot4/changelog.md

resolves #2019
Before | After
---|---

Signal: improve GetPointNearestX()

---

src/ScottPlot5/readme.md

**Purpose:**
I'm assuming this is out of date, but feel free to close the PR if this is still correct.

ScottPlot 5 readme: Clarify that it is not ready for production use

---

src/ScottPlot4/ScottPlot.Cookbook/Recipes/Plottable/Scatter.cs
src/ScottPlot4/ScottPlot/Plot/Plot.Add.cs
src/ScottPlot4/changelog.md

ScottPlot4 Plot: AddFillError()

---

src/ScottPlot4/ScottPlot.Avalonia/ScottPlot.Avalonia.NUGET.csproj
src/ScottPlot4/ScottPlot.Eto/ScottPlot.Eto.NUGET.csproj
src/ScottPlot4/ScottPlot.Tests/GetYDataRange.cs
src/ScottPlot4/ScottPlot.Tests/PlotTypes/Signal.cs
src/ScottPlot4/ScottPlot.WPF/ScottPlot.WPF.NUGET.csproj
src/ScottPlot4/ScottPlot.WinForms/ScottPlot.WinForms.NUGET.csproj
src/ScottPlot4/ScottPlot/Drawing/Palette.cs
src/ScottPlot4/ScottPlot/Plottable/SignalPlotBase.cs
src/ScottPlot4/ScottPlot/ScottPlot.csproj
src/ScottPlot4/changelog.md
src/ScottPlot5/Sandbox/ScottPlot.Sandbox.Avalonia/Sandbox.Avalonia.csproj

* resolved #2044
* added obsolete message to ScottPlot.Drawing.Palette constructor

ScottPlot 4.1.56

---

src/ScottPlot5/Sandbox/ScottPlot.Sandbox.WinForms/Form1.Designer.cs
src/ScottPlot5/Sandbox/ScottPlot.Sandbox.WinForms/Form1.cs
src/ScottPlot5/ScottPlot/AxisLimits.cs
src/ScottPlot5/ScottPlot/Color.cs
src/ScottPlot5/ScottPlot/ColorExtensions.cs
src/ScottPlot5/ScottPlot/CoordinateRange.cs
src/ScottPlot5/ScottPlot/CoordinateRect.cs
src/ScottPlot5/ScottPlot/DataSource/IHasAxisLimits.cs
src/ScottPlot5/ScottPlot/DataSource/ScatterSourceCoordinates.cs
src/ScottPlot5/ScottPlot/DataSource/ScatterSourceXsYs.cs
src/ScottPlot5/ScottPlot/DataSource/SignalSource.cs
src/ScottPlot5/ScottPlot/Generate.cs
src/ScottPlot5/ScottPlot/PixelRangeY.cs
src/ScottPlot5/ScottPlot/PlottableList.cs
src/ScottPlot5/ScottPlot/Plottables/Scatter.cs
src/ScottPlot5/ScottPlot/Plottables/Signal.cs

not optimized for speed - mostly just exploring the API, interfaces, and primitives...

ScottPlot5: basic Signal plot implementation

---

src/ScottPlot4/ScottPlot.Cookbook/Recipes/Plottable/BarSeries.cs

Cookbook: stacked bar chart

---

src/ScottPlot4/ScottPlot/Plottable/AxisLine.cs
src/ScottPlot4/changelog.md

AxisLine: hide line if LineWidth is 0

---

src/ScottPlot5/Sandbox/ScottPlot.Sandbox.WinForms/Examples/HeatmapSandbox.Designer.cs
src/ScottPlot5/Sandbox/ScottPlot.Sandbox.WinForms/Examples/HeatmapSandbox.cs
src/ScottPlot5/Sandbox/ScottPlot.Sandbox.WinForms/Examples/HeatmapSandbox.resx
src/ScottPlot5/ScottPlot/Alignment.cs
src/ScottPlot5/ScottPlot/Colormaps/ArgbColormapBase.cs
src/ScottPlot5/ScottPlot/Colormaps/ByteColormapBase.cs
src/ScottPlot5/ScottPlot/Colormaps/ColormapBase.cs
src/ScottPlot5/ScottPlot/Colormaps/Grayscale.cs
src/ScottPlot5/ScottPlot/Colormaps/GrayscaleReversed.cs
src/ScottPlot5/ScottPlot/CoordinateRect.cs
src/ScottPlot5/ScottPlot/CoordinateSize.cs
src/ScottPlot5/ScottPlot/Extensions.cs
src/ScottPlot5/ScottPlot/Generate.cs
src/ScottPlot5/ScottPlot/IColormap.cs
src/ScottPlot5/ScottPlot/Plottables/Heatmap.cs
src/ScottPlot5/ScottPlot/Range.cs

Improvements to heatmaps, ranges, and other miscellaneous classes following discussions on Discord #1966

ScottPlot 5 improvements

---

src/ScottPlot4/ScottPlot/Control/Backend.cs
src/ScottPlot4/ScottPlot/Control/Configuration.cs
src/ScottPlot4/changelog.md

Configuration: default cursor

---

.github/workflows/ci-v4.yaml
.github/workflows/ci-v5.yaml
README.md
src/ScottPlot4/ScottPlot/Snapping/1D/Nearest1D.cs
src/ScottPlot4/ScottPlot/Snapping/2D/Nearest2D.cs
src/ScottPlot4/changelog.md
src/readme.md

resolves https://github.com/ScottPlot/ScottPlot/issues/2099

ScottPlot4 Snapping.Nearest: expose SnapIndex()

---

src/ScottPlot4/ScottPlot/Control/Backend.cs
src/ScottPlot4/ScottPlot/Plottable/AxisLine.cs
src/ScottPlot4/changelog.md

* resolves #2110
* resolves #2111

ScottPlot4: improve draggable behavior

---

src/ScottPlot4/ScottPlot.Avalonia/ScottPlot.Avalonia.NUGET.csproj
src/ScottPlot4/ScottPlot.Eto/ScottPlot.Eto.NUGET.csproj
src/ScottPlot4/ScottPlot.Sandbox/WinFormsApp/Form1.cs
src/ScottPlot4/ScottPlot.WPF/ScottPlot.WPF.NUGET.csproj
src/ScottPlot4/ScottPlot.WinForms/ScottPlot.WinForms.NUGET.csproj
src/ScottPlot4/ScottPlot/Plottable/Heatmap.cs
src/ScottPlot4/ScottPlot/ScottPlot.csproj
src/ScottPlot4/changelog.md

ScottPlot4 Heatmap: throw if width or height > 2¹⁵

---

src/ScottPlot4/ScottPlot.Tests/PlotTypes/Scatter.cs
src/ScottPlot4/ScottPlot/Plottable/ScatterPlot.cs

Add DataPointList for Scatterplot, to add a label for each marker.

---

src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WinForms/WinFormsDemos/FinanceDemo.cs

instead of random OHLCs they are now random walk

demo: improve finance demo

---

src/ScottPlot4/ScottPlot.Avalonia/ScottPlot.Avalonia.NUGET.csproj
src/ScottPlot4/ScottPlot.Cookbook/Recipes/Plottable/Bar.cs
src/ScottPlot4/ScottPlot.Eto/ScottPlot.Eto.NUGET.csproj
src/ScottPlot4/ScottPlot.WPF/ScottPlot.WPF.NUGET.csproj
src/ScottPlot4/ScottPlot.WinForms/ScottPlot.WinForms.NUGET.csproj
src/ScottPlot4/ScottPlot/ScottPlot.csproj

_not yet published on NuGet..._
* Ticks: Improve datetime tick labels for systems with a 24-hour display format (#2132, #2135) _Thanks @MareMare and @bclehmann_
* Axis: `Plot.AddAxis()` now uses auto-incremented axis index unless one is explicitly defined (#2133) _Thanks @bclehmann and Discord/Nick_
* Axis: `Plot.GetAxesMatching()` was created to obtain a given vertical or horizontal axis (#2133) _Thanks @bclehmann and Discord/Nick_
* Axis: Corner label format can be customized for any axis by calling `CornerLabelFormat()` (#2134) _Thanks @ShannonZ_
* BarSeries: Improved rendering of negative values (#2147, #2152) _Thanks @fe-c_
* Function Plot: Added optional `XMin` and `XMax` fields which limit function rendering to a defined horizontal span (#2158, #2156, #2138) _Thanks @bclehmann and …

ScottPlot 4.1.59

---

.github/workflows/cookbook.yaml
.gitignore
dev/www/index.html
src/ScottPlot5/ScottPlot5 Cookbook/Cookbook.cs
src/ScottPlot5/ScottPlot5 Cookbook/HtmlPages/HtmlFrontPage.cs
src/ScottPlot5/ScottPlot5 Cookbook/HtmlPages/HtmlPageGenerator.cs
src/ScottPlot5/ScottPlot5 Cookbook/HtmlPages/HtmlRecipePage.cs
src/ScottPlot5/ScottPlot5 Cookbook/RecipeBase.cs
src/ScottPlot5/ScottPlot5 Cookbook/SetupAndTeardown.cs

building cookbooks and publishing them to https://scottplot.github.io/ using GitHub Pages

SP5 cookbook: build and deploy using CI system

---

.gitignore
src/ScottPlot5/ScottPlot5 Cookbook/Cookbook.cs
src/ScottPlot5/ScottPlot5 Cookbook/HtmlPages/HtmlFrontPage.cs
src/ScottPlot5/ScottPlot5 Cookbook/HtmlPages/HtmlPageGenerator.cs
src/ScottPlot5/ScottPlot5 Cookbook/HtmlPages/HtmlRecipePage.cs
src/ScottPlot5/ScottPlot5 Cookbook/Info/RecipeInfo.cs
src/ScottPlot5/ScottPlot5 Cookbook/RecipeSource.cs
src/ScottPlot5/ScottPlot5 Cookbook/ScottPlot Cookbook.csproj
src/ScottPlot5/ScottPlot5 Cookbook/SourceReading.cs
src/ScottPlot5/ScottPlot5/ScottPlot.csproj

source code now appears on website https://scottplot.github.io/ScottPlot/cookbook/5.0/

ScottPlot5 Cookbook: source code parsing

---

CHANGELOG.md
src/ScottPlot4/ScottPlot.Sandbox/WinFormsApp/Form1.cs
src/ScottPlot4/ScottPlot.Tests/PlotTypes/Signal.cs
src/ScottPlot4/ScottPlot.Tests/TestTools.cs
src/ScottPlot4/ScottPlot/Drawing/GDI.cs
src/ScottPlot4/ScottPlot/Plot/Plot.Add.cs
src/ScottPlot4/ScottPlot/Plottable/FunctionPlot.cs
src/ScottPlot4/ScottPlot/Plottable/SignalPlotBase.cs
src/ScottPlot5/ScottPlot5/Color.cs

Work toward
* #2304 
Addresses many small issues
* #2227

2022-12-21: resolve multiple small issues

---

CHANGELOG.md
src/ScottPlot4/ScottPlot.Tests/PlotTypes/AxisLine.cs
src/ScottPlot4/ScottPlot/Plottable/AxisLineVector.cs

AxisLineVector: Improve GetDataLimits() support for limited axis lines

---

src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinUI/ScottPlot.WinUI.csproj
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/Axis/DateTimeAxes.cs
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms/Form1.cs
src/ScottPlot5/ScottPlot5 Tests/UnitTests/GenerateTests.cs
src/ScottPlot5/ScottPlot5-tests.slnf
src/ScottPlot5/ScottPlot5-winforms.slnf
src/ScottPlot5/ScottPlot5/Generate.cs
src/ScottPlot5/readme.md

functions to generate DateTime sequences used to test #2386

SP5 Generate.DateTime

---

CHANGELOG.md
src/ScottPlot4/ScottPlot.Cookbook/Recipes/Statistics.cs
src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WinForms/DemoListControl.Designer.cs
src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WinForms/DemoListControl.cs
src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WinForms/FormMain.cs
src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WinForms/WinFormsDemos/HistogramDemo.Designer.cs
src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WinForms/WinFormsDemos/HistogramDemo.cs
src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WinForms/WinFormsDemos/HistogramDemo.resx
src/ScottPlot4/ScottPlot.Tests/ScottPlot.Tests.csproj
src/ScottPlot4/ScottPlot.Tests/Statistics/Histogram.cs
src/ScottPlot4/ScottPlot/Statistics/Common.cs
src/ScottPlot4/ScottPlot/Statistics/Histogram.cs

Hi! This was in my mind as a first implementation. Please have a look.
Thanks!

ScottPlot.Statistics.Histogram

---

CHANGELOG.md
src/ScottPlot4/ScottPlot.Cookbook/Recipes/Plottable/Heatmap.cs
src/ScottPlot4/ScottPlot.Tests/PlottableRenderTests/Heatmap.cs
src/ScottPlot4/ScottPlot/Drawing/Colormap.cs
src/ScottPlot4/ScottPlot/Drawing/Colormaps/Palette.cs

SP4: palette colormap

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Tests/Extensions.cs
src/ScottPlot5/ScottPlot5 Tests/RenderTests/FileFormatTests.cs
src/ScottPlot5/ScottPlot5/Plot.cs
src/Shared/ScottPlot/ImageOperations.cs

SP5: Plot.GetImageHTML()

---

CHANGELOG.md
src/ScottPlot4/ScottPlot/Plottable/FunctionPlot.cs

Tested from Winform, zoom to data works now.
* Resolves #2412

FunctionPlot AxisLimits

---

CHANGELOG.md
src/ScottPlot4/ScottPlot.Sandbox/WinFormsApp/Form1.cs
src/ScottPlot4/ScottPlot.Tests/PlotTypes/Population.cs
src/ScottPlot4/ScottPlot/Plottable/PopulationPlot.cs

SP4: fix bug affecting 1px high population plots

---

CHANGELOG.md
src/ScottPlot4/ScottPlot/Control/Backend.cs
src/ScottPlot4/ScottPlot/Control/Configuration.cs

SP4 Controls: add AltLeftClickDragZoom configuration flag

---

CHANGELOG.md
src/ScottPlot4/ScottPlot.Tests/PlotTypes/ErrorBar.cs
src/ScottPlot4/ScottPlot/Plottable/ErrorBar.cs

SP4 ErrorBar: add legend support

---

src/ScottPlot4/ScottPlot.Tests/PlotTypes/Custom.cs

addresses #2413
addresses https://github.com/ScottPlot/ScottPlot.NET/issues/10
Graphic design is my passion 😜

SP4: Demonstrate custom plot type

---

src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WinForms/FormCookbook.Designer.cs
src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WinForms/FormCookbook.resx

SP4 Demo: fix System.Drawing.Common version

---

.github/workflows/devsite.yaml
.gitignore
dev/CodeAnalysis/CodeAnalysis.csproj
dev/CodeAnalysis/CodeAnalysis.sln
dev/CodeAnalysis/CodeReport.cs
dev/CodeAnalysis/HtmlReports/HtmlTemplate.cs
dev/CodeAnalysis/HtmlReports/ProjectSummaries.cs
dev/CodeAnalysis/HtmlReports/TableBuilder.cs
dev/CodeAnalysis/Metrics.cs
dev/CodeAnalysis/MultiProjectReport.cs
dev/CodeAnalysis/Program.cs
dev/CodeAnalysis/ProjectReport.cs
src/ScottPlot4/ScottPlot.Avalonia/ScottPlot.Avalonia.csproj
src/ScottPlot4/ScottPlot.Cookbook/ScottPlot.Cookbook.csproj
src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.Avalonia/Avalonia Demo.csproj
src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.Eto/Eto.Forms Demo.csproj
src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WPF/WPF Demo.csproj
src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WinForms/WinForms Demo.csproj
src/ScottPlot4/ScottPlot.Eto/ScottPlot.Eto.csproj
src/ScottPlot4/ScottPlot.Tests/ScottPlot.Tests.csproj
src/ScottPlot4/ScottPlot.WPF/ScottPlot.WPF.csproj
src/ScottPlot4/ScottPlot.WinForms/ScottPlot.WinForms.csproj
src/ScottPlot4/ScottPlot/ScottPlot.csproj

CI: code analysis

---

CHANGELOG.md
src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WinForms/WinFormsDemos/FinanceDemo.Designer.cs
src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WinForms/WinFormsDemos/FinanceDemo.cs
src/ScottPlot4/ScottPlot/DataGen.cs
src/ScottPlot4/ScottPlot/Plot/Plot.Add.cs
src/ScottPlot4/ScottPlot/Plottable/DataStructures/OHLC.cs
src/ScottPlot4/ScottPlot/Plottable/FinancePlot.cs
src/ScottPlot4/ScottPlot/Statistics/Finance.cs
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Finance.cs
src/ScottPlot5/ScottPlot5/AddPlottable.cs
src/ScottPlot5/ScottPlot5/DataSources/IOHLCSource.cs
src/ScottPlot5/ScottPlot5/DataSources/OHLCSource.cs
src/ScottPlot5/ScottPlot5/OHLC.cs
src/ScottPlot5/ScottPlot5/Plottables/CandlestickPlot.cs
src/ScottPlot5/ScottPlot5/Plottables/OHLCPlot.cs
src/ScottPlot5/ScottPlot5/RandomDataGeneratorExtensions.cs
src/ScottPlot5/ScottPlot5/autoformat.bat
src/Shared/ScottPlot/IOHLC.cs

Suggested by @mjpz in #2404, SP4 and SP5 now code against a shared `IOHLC` abstraction

Shared: IOHLC

---

CHANGELOG.md
src/ScottPlot4/ScottPlot.Cookbook/Recipes/AxisAdvanced.cs
src/ScottPlot4/ScottPlot/Renderable/Axis.cs

SP4: expose axis configuration objects

---

CHANGELOG.md
src/ScottPlot4/ScottPlot.Tests/PlotTypes/Signal.cs
src/ScottPlot4/ScottPlot/Plottable/SignalPlotBase.cs

SP4 Signal: Fix FillDisable() bug

---

CHANGELOG.md
src/ScottPlot4/ScottPlot.Tests/PlotTypes/RadialGaugePlot.cs
src/ScottPlot4/ScottPlot/Plottable/RadialGaugePlot.cs

SP4 RadialGaugePlot: improve display of 1-3 gauges

---

src/ScottPlot4/ScottPlot.Cookbook/Recipes/Plottable/AxisLineAndSpan.cs

Cookbook: demonstrate axis line label on multi-axis plots

---

CHANGELOG.md
src/ScottPlot4/ScottPlot.Cookbook/Recipes/Plottable/Pie.cs
src/ScottPlot4/ScottPlot/Plottable/PiePlot.cs
src/ScottPlot5/ScottPlot5/TODO.cs

SP4: Pie.LegendLabels

---

CHANGELOG.md
src/ScottPlot4/ScottPlot.Sandbox/WinFormsApp/Form1.cs
src/ScottPlot4/ScottPlot/Control/Backend.cs
src/ScottPlot4/ScottPlot/Control/InputState.cs

SP4 Backend: improve coordinate system initialization

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/Control/Interaction.cs

SP5: disable context menu in non-interactive mode

---

CHANGELOG.md
src/ScottPlot4/ScottPlot.Tests/Statistics/Histogram.cs
src/Shared/ScottPlot/Statistics/Histogram.cs
src/Shared/ScottPlotTests/Statistics/HistogramTests.cs

Histogram: improve support for small bin sizes

---

CHANGELOG.md
src/ScottPlot4/ScottPlot.Tests/Axis/PanAndZoom.cs
src/ScottPlot4/ScottPlot/Plot/Plot.Axis.cs

SP4: Improve Plot.AxisPanCenter() support for non-primary axes

---

CHANGELOG.md
src/ScottPlot4/ScottPlot.Tests/Axis/MultiAxis.cs
src/ScottPlot4/ScottPlot/Plot/Plot.Axis.cs

SP4: Improve MatchAxisLimits() support for multi-axis plots

---

CHANGELOG.md
src/ScottPlot4/ScottPlot/Plot/Plot.Axis.cs

SP4: Improve Plot.XLabel() XML docs

---

src/ScottPlot5/ScottPlot5 Controls/ScottPlot.OpenGL/ScottPlot.OpenGL.csproj
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WPF/MainWindow.xaml.cs
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WPF/Sandbox.WPF.csproj

SP5: TK version agnostic OpenGL plot types

---

CHANGELOG.md
src/ScottPlot4/ScottPlot.Tests/PlotTypes/Lollipop.cs
src/ScottPlot4/ScottPlot/Plot/Plot.Add.cs
src/ScottPlot4/ScottPlot/Plottable/ClevelandDotPlot.cs
src/ScottPlot4/ScottPlot/Plottable/LollipopPlot.cs

SP4 Lollipop and Cleveland plots: Add `LineWidth` property

---

src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WPF/MainWindow.xaml.cs
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WPF/Sandbox.WPF.csproj

SP5 WPF Sandbox: Remove OpenGL

---

CHANGELOG.md
src/ScottPlot4/ScottPlot.Cookbook/Recipes/Plottable/Pie.cs
src/ScottPlot4/ScottPlot/Plottable/PiePlot.cs

SP4 Pie: add SliceLabelPosition property

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms/Form1.cs
src/ScottPlot5/ScottPlot5/Control/Interaction.cs
src/ScottPlot5/ScottPlot5/Control/KeyboardState.cs
src/Shared/ScottPlot/Generate.cs

SP5 Controls: Improve ALT + left-click-drag zoom rectangle behavior

---

CHANGELOG.md
src/ScottPlot4/ScottPlot.Cookbook/Recipes/Axis.cs
src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.Avalonia/AvaloniaDemos/AxisLimits.axaml.cs
src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.Eto/EtoFormsDemos/AxisLimits.cs
src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WPF/WpfDemos/AxisLimits.xaml.cs
src/ScottPlot4/ScottPlot.Tests/Axis/ViewLimits.cs
src/ScottPlot4/ScottPlot/Plot/Plot.Axis.cs
src/ScottPlot4/ScottPlot/Renderable/Axis.cs
src/ScottPlot4/ScottPlot/Renderable/AxisDimensions.cs

SP4: Simplify and demonstrate axis boundaries and scale limiting

---

CHANGELOG.md
src/ScottPlot4/ScottPlot.Sandbox/WinFormsApp/Form1.Designer.cs
src/ScottPlot4/ScottPlot.Sandbox/WinFormsApp/Form1.cs
src/ScottPlot4/ScottPlot/Control/Configuration.cs
src/ScottPlot4/ScottPlot/Control/EventProcess/Events/MouseZoomEvent.cs
src/ScottPlot4/ScottPlot/Settings.cs
src/Shared/ScottPlot/RandomDataGenerator.cs

demonstrates suggestion in #2296
~~I do not favor this behavior so this branch will not be merged into main~~
I'll hide it behind a feature flag
* Resolves #2296

SP4: right-click-drag to cursor

---

CHANGELOG.md
src/ScottPlot4/ScottPlot.Cookbook/Recipes/Plottable/Finance.cs
src/ScottPlot4/ScottPlot/DataGen.cs

SP4: fix DateTime positioning of OHLCs returned by DataGen.RandomStockPrices()

---

CHANGELOG.md
src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WinForms/WinFormsDemos/AxisLimits.cs
src/ScottPlot4/ScottPlot.Sandbox/WinFormsApp/Form1.Designer.cs
src/ScottPlot4/ScottPlot.Sandbox/WinFormsApp/Form1.cs
src/ScottPlot4/ScottPlot.Tests/Axis/LogAxis.cs
src/ScottPlot4/ScottPlot/Renderable/Axis.cs
src/ScottPlot4/ScottPlot/Renderable/AxisTicks.cs
src/ScottPlot4/ScottPlot/Renderable/AxisTicksRender.cs
src/ScottPlot4/ScottPlot/ScottPlot.csproj
src/ScottPlot4/ScottPlot/Ticks/IMinorTickGenerator.cs
src/ScottPlot4/ScottPlot/Ticks/MinorTickGenerators/EvenlySpaced.cs
src/ScottPlot4/ScottPlot/Ticks/MinorTickGenerators/LogDistributed.cs
src/ScottPlot4/ScottPlot/Ticks/TickCollection.cs
src/ScottPlot4/ScottPlot/Ticks/TickGenerator.cs
src/ScottPlot4/ScottPlot/Ticks/TickPositions.cs

ScottPlot 4's tick generation system has been one of the most convoluted systems over the years, making it difficult to debug or extend with custom features. This PR breaks tick generation logic into separate classes to make it easier to work with.
* Also resolves #2289

SP4: Refactor tick generation system

---

CHANGELOG.md
src/ScottPlot4/ScottPlot.Tests/PlotTypes/Signal.cs
src/ScottPlot4/ScottPlot/Plottable/SignalPlotBase.cs

SP4 Signal: Fix bug causing `Update()` to throw an indexing error

---

CHANGELOG.md
src/ScottPlot4/ScottPlot.Cookbook/Recipes/Plottable/Colorbar.cs
src/ScottPlot4/ScottPlot.Tests/PlottableRenderTests/Colorbar.cs
src/ScottPlot4/ScottPlot/Plottable/Colorbar.cs

Colorbar: add `Label` property

---

CHANGELOG.md
src/ScottPlot4/ScottPlot.Cookbook/Recipes/Plottable/Ellipse.cs
src/ScottPlot4/ScottPlot/Plottable/Ellipse.cs

**Purpose:**
Rotating an Ellipse.
Issue: https://github.com/ScottPlot/ScottPlot/issues/2588

ScottPlot4: Ellipse Rotation

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/ScottPlot.csproj

SP5 csproj: use SkiaSharp.NativeAssets.Linux.NoDependencies on Linux

---

CHANGELOG.md
src/ScottPlot4/ScottPlot/Plottable/FinancePlot.cs

FinancePlot.GetBollingerBands(): add sdCoeff argument

---

CHANGELOG.md
src/ScottPlot4/ScottPlot.Tests/PlotTypes/Signal.cs
src/ScottPlot4/ScottPlot/Plottable/SignalPlotBase.cs

SP4 Signal: fix Update() bug

---

CHANGELOG.md
src/ScottPlot4/ScottPlot.Cookbook/Recipes/Plottable/Image.cs
src/ScottPlot4/ScottPlot/Plottable/Image.cs

* resolves https://github.com/ScottPlot/ScottPlot/issues/2649

Image: add AntiAlias option

---

CHANGELOG.md
src/ScottPlot4/ScottPlot.WPF/ScottPlot.WPF.csproj

SP4 WP4: Target .NET Framework 4.6.2

---

CHANGELOG.md
src/ScottPlot4/ScottPlot/Plottable/HSpan.cs

Fixed a small error in the function `ToString`

Fixed `ToString` in HSpan.cs

---

CHANGELOG.md
src/ScottPlot4/ScottPlot/Plottable/Colorbar.cs

Hi !
Please have a look, for sure there are things to fix and improve ;)
thanks very much! :)

Colorbar: automatically adjust label position to prevent overlap with tick labels

---

CHANGELOG.md
src/ScottPlot4/ScottPlot/Plottable/ArrowCoordinated.cs

SP4 Arrow: permit location mutation

---

src/ScottPlot4/ScottPlot.WinForms/FormsPlot.cs
src/ScottPlot4/ScottPlot.WinForms/FormsPlotViewer.cs

Three sync types for the FormsPlotViewer: 
- NoSync,
- SyncToParent,
- SyncFromParent

FormsPlotViewer constructor overload with sync type option

---

CHANGELOG.md
src/ScottPlot4/ScottPlot.Sandbox/WinFormsApp/Form1.Designer.cs
src/ScottPlot4/ScottPlot.Sandbox/WinFormsApp/Form1.cs
src/ScottPlot4/ScottPlot.Sandbox/WinFormsApp/Form1.resx
src/ScottPlot4/ScottPlot.WinForms/FormsPlot.cs
src/ScottPlot4/ScottPlot.WinForms/FormsPlotViewer.Designer.cs
src/ScottPlot4/ScottPlot.WinForms/FormsPlotViewer.cs
src/ScottPlot4/ScottPlot.WinForms/FormsPlotViewer.resx

extends #2710 and resolves #2653

FormsPlotViewer: support bidirectional updates

---

CHANGELOG.md
src/ScottPlot4/ScottPlot.Cookbook/Recipes/Plottable/Marker.cs
src/ScottPlot4/ScottPlot.Cookbook/Recipes/Style.cs
src/ScottPlot4/ScottPlot/Drawing/GDI.cs
src/ScottPlot4/ScottPlot/Enums/LineStyle.cs

* Resolves #2690
* Resolves #2692

SP4: User-configurable line styles

---

CHANGELOG.md
src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WinForms/WinFormsDemos/DataStreamer.Designer.cs
src/ScottPlot4/ScottPlot.Sandbox/WinFormsApp/Form1.Designer.cs
src/ScottPlot4/ScottPlot.Sandbox/WinFormsApp/Form1.cs
src/ScottPlot4/ScottPlot/Plottable/Colorbar.cs

* resolves https://github.com/ScottPlot/ScottPlot/issues/2703

SP4 Colorbar: ResizeLayout()

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Avalonia/AvaPlot.axaml.cs
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Avalonia/AvaPlotExtensions.cs
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Avalonia/ScottPlot.Avalonia.csproj
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.Avalonia/App.axaml
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.Avalonia/MainWindow.axaml.cs
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.Avalonia/Sandbox.Avalonia.csproj

**Purpose:**
This was significantly simpler than the corresponding PR for v4 as there's no cookbook or other large app to migrate as well.

ScottPlot5: Upgrade to Avalonia 11

---

CHANGELOG.md
src/ScottPlot4/ScottPlot.Tests/PlotTypes/ScatterPlotList.cs
src/ScottPlot4/ScottPlot/Plottable/ScatterPlotList.cs

SP4 ScatterPlotList: improve NaN support

---

src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WinForms/FormMain.Designer.cs

adjust the height to show the link

---

CHANGELOG.md
src/ScottPlot4/ScottPlot.Tests/PlotTypes/DataPlots.cs
src/ScottPlot4/ScottPlot/Plottable/DataLogger.cs

SP4 DataLogger: Improve support for single-point datasets

---

CHANGELOG.md
src/ScottPlot4/ScottPlot/Plot/Plot.Add.cs

Use color palette to define DataLogger and DataStream trace color as described in #2733

SP4: Add optional arguments to AddDataLogger() and DataStreamer()

---

src/ScottPlot4/ScottPlot.Avalonia/ScottPlot.Avalonia.NUGET.csproj
src/ScottPlot4/ScottPlot.WPF/ScottPlot.WPF.NUGET.csproj
src/ScottPlot4/ScottPlot.WinForms/ScottPlot.WinForms.NUGET.csproj

SP4: update .NET 5 targets to .NET 6

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/Axis/IAxis.cs

SP5 IAxis: expose `TickFont`

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WPF/MainWindow.xaml
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WPF/MainWindow.xaml.cs
src/ScottPlot5/ScottPlot5 Tests/RenderTests/FontTests.cs
src/ScottPlot5/ScottPlot5/Fonts.cs
src/ScottPlot5/ScottPlot5/Plot.cs
src/ScottPlot5/ScottPlot5/Stylers/PlotStyler.cs

**Purpose:**
add cjk and english char for sandbox test
---
See discussion in https://github.com/ScottPlot/ScottPlot/issues/2746

SP5: Improve support for CJK fonts in user controls

---

CHANGELOG.md
src/ScottPlot4/ScottPlot.Cookbook/Recipes/Plottable/Heatmap.cs
src/ScottPlot4/ScottPlot/Plottable/Heatmap.cs

New property to set the center of axis when we use Rotate.

SP4 Heatmap: `CenterOfRotation` property

---

CHANGELOG.md
src/ScottPlot4/ScottPlot.Avalonia/ScottPlot.Avalonia.csproj
src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.Avalonia/Avalonia Demo.csproj
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Avalonia/ScottPlot.Avalonia.csproj
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.Avalonia/Sandbox.Avalonia.csproj

This fix Avalonia package version formatting in SP5 and bump version to 11.0.1

SP4 & SP5 Update Avalonia to 11.0.1

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Avalonia/AvaPlot.axaml.cs
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Eto/EtoPlot.cs
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/WpfPlot.cs
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms/FormsPlot.cs
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinUI/WinUIPlot.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/MouseTracker.cs
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.Avalonia/MainWindow.axaml.cs
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.Console/Program.cs
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.Eto/MainWindow.cs
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.Eto/MainWindow.eto.cs
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WPF/MainWindow.xaml
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WPF/MainWindow.xaml.cs
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms/Form1.cs
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinFormsFramework/Form1.Designer.cs
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinFormsFramework/Form1.cs
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinFormsFramework/Program.cs
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinFormsFramework/Sandbox.WinFormsFramework.csproj
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinUI/MainPage.xaml.cs
src/ScottPlot5/ScottPlot5.sln
src/ScottPlot5/ScottPlot5/Control/IPlotControl.cs
src/ScottPlot5/ScottPlot5/Plot.cs
src/ScottPlot5/ScottPlot5/RenderPack.cs

SP5 Controls: Added `GetCoordinates()` and logic for display scaling

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/RandomDataGenerator.cs

See issue #2763
Note: Was unable to run AutoFormatter. Attempted to run AutoFormatter in GitHub Codespaces and on my machine as well.

SP5 RandomDataGenerator: Add `slope` argument to `RandomWalk()`

---

CHANGELOG.md
src/ScottPlot4/ScottPlot/Plottable/Heatmap.cs

See issue #2738
Note: Was unable to run AutoFormatter. Attempted to run AutoFormatter in GitHub Codespaces and on my machine as well.

SP4 Heatmap: Fix XML docs error

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/Introduction/Legend.cs
src/ScottPlot5/ScottPlot5 Tests/RenderTests/LegendTests.cs
src/ScottPlot5/ScottPlot5/Interfaces/ILegend.cs
src/ScottPlot5/ScottPlot5/Legends/StandardLegend.cs
src/ScottPlot5/ScottPlot5/Plot.cs

SP5: Plot.Legend()

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/Axis/DateTimeAxes.cs
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Finance.cs
src/ScottPlot5/ScottPlot5/Plot.cs
src/ScottPlot5/ScottPlot5/Stylers/AxisStyler.cs

SP5: Plot.Axes → Plot.AxisStyler

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Tests/UnitTests/PrimitiveTests/ColorTests.cs
src/ScottPlot5/ScottPlot5 Tests/UnitTests/PrimitiveTests/CoordinateRectTests.cs
src/ScottPlot5/ScottPlot5 Tests/UnitTests/PrimitiveTests/CoordinateTests.cs
src/ScottPlot5/ScottPlot5 Tests/UnitTests/PrimitiveTests/ExpandingAxisLimitsTests.cs
src/ScottPlot5/ScottPlot5 Tests/UnitTests/PrimitiveTests/PaletteTests.cs
src/ScottPlot5/ScottPlot5 Tests/UnitTests/PrimitiveTests/PixelRectTests.cs
src/ScottPlot5/ScottPlot5 Tests/UnitTests/PrimitiveTests/PixelTests.cs
src/ScottPlot5/ScottPlot5 Tests/UnitTests/PrimitiveTests/VersionTests.cs
src/ScottPlot5/ScottPlot5/DataSources/ScatterSourceCoordinates.cs
src/ScottPlot5/ScottPlot5/Plottables/BarPlot.cs
src/ScottPlot5/ScottPlot5/Plottables/BoxPlot.cs
src/ScottPlot5/ScottPlot5/Plottables/ErrorBar.cs
src/ScottPlot5/ScottPlot5/Primitives/AxisLimits.cs
src/ScottPlot5/ScottPlot5/Primitives/CoordinateRect.cs
src/ScottPlot5/ScottPlot5/Primitives/ExpandingAxisLimits.cs

SP5: Extend `AxisLimits` and create `ExpandingAxisLimits`

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Tests/UnitTests/PlotAxisManipulation.cs
src/ScottPlot5/ScottPlot5/Plot.cs
src/ScottPlot5/ScottPlot5/Primitives/AxisLimits.cs
src/ScottPlot5/ScottPlot5/Rendering/RenderDetails.cs

...with fancy logic to translate pixel to coordinate units based on dimensions of the last render
* resolves #2800

SP5: `Plot.Pan()` and `Plot.Zoom()`

---

CHANGELOG.md
src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WinForms/WinFormsDemos/DataLogger.Designer.cs
src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WinForms/WinFormsDemos/DataLogger.cs
src/ScottPlot4/ScottPlot/Plottable/DataLogger.cs
src/ScottPlot4/ScottPlot/Plottable/DataStreamer.cs

Update DataLogger and DataStream to show line color in Legend
Fix #2829

SP4: fix DataLogger/DataStream legend layout

---

.github/workflows/ScottPlot4-CI.yaml
.github/workflows/ScottPlot5-CI.yaml
CHANGELOG.md
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/Introduction/Axis.cs
src/ScottPlot5/ScottPlot5 Tests/UnitTests/PlotAxisManipulation.cs
src/ScottPlot5/ScottPlot5 Tests/UnitTests/PrimitiveTests/CoordinateRectTests.cs
src/ScottPlot5/ScottPlot5 Tests/UnitTests/PrimitiveTests/ExpandingAxisLimitsTests.cs
src/ScottPlot5/ScottPlot5/DataSources/SignalSource.cs
src/ScottPlot5/ScottPlot5/Plot.cs
src/ScottPlot5/ScottPlot5/Plottables/BarPlot.cs
src/ScottPlot5/ScottPlot5/Plottables/BoxPlot.cs
src/ScottPlot5/ScottPlot5/Plottables/Heatmap.cs
src/ScottPlot5/ScottPlot5/Plottables/Pie.cs
src/ScottPlot5/ScottPlot5/Primitives/Axes.cs
src/ScottPlot5/ScottPlot5/Primitives/AxisLimits.cs
src/ScottPlot5/ScottPlot5/Primitives/CoordinateRect.cs
src/ScottPlot5/ScottPlot5/Primitives/ExpandingAxisLimits.cs
src/ScottPlot5/ScottPlot5/ScottPlot.csproj

SP5: `XMin`, `XMax`, `YMin`, `YMax` → `Left`, `Right`, `Bottom`, `Top`

---

CHANGELOG.md
src/ScottPlot4/ScottPlot.Cookbook/Recipes/Misc.cs
src/ScottPlot4/ScottPlot/Plot/Plot.Add.cs
src/ScottPlot4/ScottPlot/PlotDimensions.cs
src/ScottPlot4/ScottPlot/Plottable/Ellipse.cs
src/ScottPlot4/ScottPlot/Plottable/RectanglePlot.cs

SP4: `Plot.AddAddRectangle()`

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/FillY.cs
src/ScottPlot5/ScottPlot5/Plottables/FillY.cs

Closes https://github.com/ScottPlot/ScottPlot/issues/2886
Seems to work as expected:

Add legend support to FillY Plottable

---

CHANGELOG.md
src/ScottPlot4/ScottPlot.Cookbook/Recipes/Plottable/Heatmap.cs
src/ScottPlot4/ScottPlot/Plot/Plot.Add.cs
src/ScottPlot4/ScottPlot/Plottable/Heatmap.cs

Playing with a 2048x2048 array, i have got about 3X faster rendering with the Update + Refresh method calls in case of parallel=true option.

SP4 Heatmap: bugfix and parallel option

---

CHANGELOG.md

resolve [#2881](https://github.com/ScottPlot/ScottPlot/issues/2881)

SP5: Make LayoutEngines.Matched public

---

src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Blazor/BlazorPlot.razor
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Blazor/BlazorPlotBase.cs
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Blazor/BlazorPlotGL.razor
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Blazor/ExampleJsInterop.cs
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.Blazor.WebAssembly/wwwroot/index.html

Disable right-click browser context menu

SP5 Blazor: Disable right-click browser context menu

---

src/ScottPlot5/ScottPlot5 Tests/Extensions.cs
src/ScottPlot5/ScottPlot5 Tests/RenderTests/LabelTests.cs
src/ScottPlot5/ScottPlot5/Drawing.cs
src/ScottPlot5/ScottPlot5/Primitives/FontStyle.cs
src/ScottPlot5/ScottPlot5/Primitives/LabelExperimental.cs
src/ScottPlot5/ScottPlot5/Primitives/Location.cs
src/ScottPlot5/ScottPlot5/Primitives/LocationUnit.cs

Lays the foundation for #2993 but still doesn't support proper alignment for padded labels with arbitrary rotations

SP5: Improve label rendering

---

CHANGELOG.md
src/ScottPlot4/ScottPlot/Plottable/Text.cs

Issue 2994. Make Text.LastRenderRectangleCoordinates public

SP4 Text: Expose `LastRenderRectangleCoordinates`

---

CHANGELOG.md
src/ScottPlot4/ScottPlot.Sandbox/WpfApp/MainWindow.xaml
src/ScottPlot4/ScottPlot.Sandbox/WpfApp/MainWindow.xaml.cs
src/ScottPlot4/ScottPlot/Control/Backend.cs
src/ScottPlot4/ScottPlot/Plot/Plot.Render.cs
src/ScottPlot4/ScottPlot/PlotDimensions.cs

addresses #3000 and resolves #3002

SP4 controls: resizing invokes OnAxesChanged

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/MultiAxis.Designer.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/MultiAxis.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/MultiAxis.resx
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Program.cs
src/ScottPlot5/ScottPlot5 Tests/Sandbox.cs
src/ScottPlot5/ScottPlot5/AutoScalers/FractionalAutoScaler.cs
src/ScottPlot5/ScottPlot5/Plot.cs
src/ScottPlot5/ScottPlot5/Primitives/AxisLimits.cs
src/ScottPlot5/ScottPlot5/Primitives/IAutoScaler.cs

SP5: improve multi-axis autoscaling support

---

src/ScottPlot5/ScottPlot5/Markers/TriDown.cs
src/ScottPlot5/ScottPlot5/Markers/TriUp.cs
src/ScottPlot5/ScottPlot5/Primitives/MarkerShape.cs

**Purpose:**
* Add TriUp and TriDown markers :)
* Related to https://github.com/ScottPlot/ScottPlot/issues/2999

SP5: Feature - add more plot markers

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/ShowValueOnHover.Designer.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/ShowValueOnHover.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/ShowValueOnHover.resx
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Program.cs
src/ScottPlot5/ScottPlot5/AxisPanels/XAxisBase.cs
src/ScottPlot5/ScottPlot5/AxisPanels/YAxisBase.cs
src/ScottPlot5/ScottPlot5/Generate.cs
src/ScottPlot5/ScottPlot5/Interfaces/IAxis.cs
src/ScottPlot5/ScottPlot5/Plot.cs
src/ScottPlot5/ScottPlot5/Primitives/Coordinates.cs
src/ScottPlot5/ScottPlot5/Rendering/RenderDetails.cs

This PR extends various SP5 classes to make this functionality easier to achieve and adds a WinForms demo to demonstrate how this effect can be achieved:

SP5: Show Value Under Cursor

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Text.cs
src/ScottPlot5/ScottPlot5/PlottableAdder.cs
src/ScottPlot5/ScottPlot5/Plottables/Text.cs

SP5: new Text plot type

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/OpenGLPerformance.cs
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.Blazor.WebAssembly/Pages/Signal.razor
src/ScottPlot5/ScottPlot5/Control/StandardActions.cs
src/ScottPlot5/ScottPlot5/Plot.cs
src/ScottPlot5/ScottPlot5/Plottables/Benchmark.cs
src/ScottPlot5/ScottPlot5/Rendering/RenderActions/RenderBenchmark.cs

It is now a a standalone plottable that users can replace with their own custom benchmarking logic. Resolves #2961

SP5: Plot.Benchmark

---

CHANGELOG.md
src/ScottPlot4/ScottPlot.Cookbook/Recipes/AxisAdvanced.cs
src/ScottPlot4/ScottPlot.Tests/Ticks/TickGeneration.cs
src/ScottPlot4/ScottPlot/Renderable/Axis.cs
src/ScottPlot4/ScottPlot/Ticks/ManualTickCollection.cs
src/ScottPlot4/ScottPlot/Ticks/TickCollection.cs
src/ScottPlot4/ScottPlot/Ticks/TickGenerator.cs

SP4: Axis.SetTicks()

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/Introduction/Legend.cs
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Bar.cs
src/ScottPlot5/ScottPlot5 Tests/RenderTests/Plottable/BarTests.cs
src/ScottPlot5/ScottPlot5/Drawing.cs
src/ScottPlot5/ScottPlot5/Interfaces/IAxes.cs
src/ScottPlot5/ScottPlot5/Legends/Legend.cs
src/ScottPlot5/ScottPlot5/PlottableAdder.cs
src/ScottPlot5/ScottPlot5/Plottables/BarPlot.cs
src/ScottPlot5/ScottPlot5/Primitives/Axes.cs
src/ScottPlot5/ScottPlot5/Primitives/Bar.cs
src/ScottPlot5/ScottPlot5/Primitives/BarSeries.cs
src/ScottPlot5/ScottPlot5/Primitives/CoordinateLine.cs
src/ScottPlot5/ScottPlot5/Primitives/LegendItem.cs
src/ScottPlot5/ScottPlot5/Primitives/Tick.cs
src/ScottPlot5/ScottPlot5/TickGenerators/NumericManual.cs

* resolves #3070
* resolves #3066

SP5: refactor bar plot and legend systems

---

.github/workflows/ScottPlot5-CI.yaml
dev/ScottPlot5/generate-cookbook.bat
src/ScottPlot4/ScottPlot.Cookbook/Template.cs
src/ScottPlot5/ScottPlot5 Cookbook/Website/PageBase.cs

Paired with recent work pushed to https://github.com/ScottPlot/ScottPlot.NET for deployment on https://scottplot.net/

SP5 Cookbook: fix frontmatter issues to improve Hugo build

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Line.cs
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Marker.cs
src/ScottPlot5/ScottPlot5/Generate.cs
src/ScottPlot5/ScottPlot5/Plot.cs
src/ScottPlot5/ScottPlot5/PlottableAdder.cs
src/ScottPlot5/ScottPlot5/Plottables/LinePlot.cs
src/ScottPlot5/ScottPlot5/Primitives/LegendItem.cs
src/ScottPlot5/ScottPlot5/Primitives/Line.cs
src/ScottPlot5/ScottPlot5/Primitives/MarkerStyle.cs

**Purpose:**
* Resolves #2915 
* Add Line primitive
* Add LinePlot plot type
* Add Cookbook entry for Line plot
* Add RandomLinePattern method to Generate
The results of the cookbook plots - I used the Marker cookbook plots as a template:

SP5: Line (new plot type)

---

src/ScottPlot5/ScottPlot5 Cookbook/Recipes/Introduction/Styling.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/MultiAxis.cs
src/ScottPlot5/ScottPlot5 Tests/RenderTests/AxisLabelTests.cs
src/ScottPlot5/ScottPlot5/AxisPanels/AxisBase.cs
src/ScottPlot5/ScottPlot5/AxisPanels/BottomAxis.cs
src/ScottPlot5/ScottPlot5/AxisPanels/LeftAxis.cs
src/ScottPlot5/ScottPlot5/AxisPanels/XAxisBase.cs
src/ScottPlot5/ScottPlot5/AxisPanels/YAxisBase.cs
src/ScottPlot5/ScottPlot5/Interfaces/IAxis.cs
src/ScottPlot5/ScottPlot5/Plot.cs
src/ScottPlot5/ScottPlot5/Primitives/LabelExperimental.cs
src/ScottPlot5/ScottPlot5/Stylers/PlotStyler.cs

SP5: axes use new label

---

src/ScottPlot5/ScottPlot5 Tests/Extensions.cs
src/ScottPlot5/ScottPlot5 Tests/RenderTests/LegendTests.cs
src/ScottPlot5/ScottPlot5/Legends/Legend.cs
src/ScottPlot5/ScottPlot5/Plot.cs
src/ScottPlot5/ScottPlot5/Primitives/SvgImage.cs

SP5: improve thread safety for image generation

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Bar.cs
src/ScottPlot5/ScottPlot5/PlottableAdder.cs
src/ScottPlot5/ScottPlot5/Plottables/BarPlot.cs
src/ScottPlot5/ScottPlot5/Primitives/Bar.cs

**Purpose:**
This PR adds support for horizontal bar charts in SP5.

Add support for horizontal bar charts

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/DataLogger.Designer.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/DataLogger.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/DataLogger.resx
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/DataStreamer.Designer.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/DataStreamer.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/DataStreamer.resx
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Program.cs
src/ScottPlot5/ScottPlot5/AxisManager.cs
src/ScottPlot5/ScottPlot5/AxisManagers/FixedWidth.cs
src/ScottPlot5/ScottPlot5/AxisManagers/Full.cs
src/ScottPlot5/ScottPlot5/AxisManagers/IAxisManager.cs
src/ScottPlot5/ScottPlot5/AxisManagers/Slide.cs
src/ScottPlot5/ScottPlot5/DataSources/DataLoggerSource.cs
src/ScottPlot5/ScottPlot5/DataSources/DataStreamerSource.cs
src/ScottPlot5/ScottPlot5/DataViews/IDataStreamerView.cs
src/ScottPlot5/ScottPlot5/DataViews/Scroll.cs
src/ScottPlot5/ScottPlot5/DataViews/Wipe.cs
src/ScottPlot5/ScottPlot5/Drawing.cs
src/ScottPlot5/ScottPlot5/Generate.cs
src/ScottPlot5/ScottPlot5/NumericConversion.cs
src/ScottPlot5/ScottPlot5/PlottableAdder.cs
src/ScottPlot5/ScottPlot5/Plottables/DataLogger.cs
src/ScottPlot5/ScottPlot5/Plottables/DataStreamer.cs
src/ScottPlot5/ScottPlot5/Primitives/AxisLimits.cs

ScottPlot 5 plot types designed for displaying live data
* resolves #3202

SP5: DataStreamer and DataLogger

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Avalonia/AvaPlotMenu.cs
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Blazor/BlazorPlotMenu.cs
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Eto/EtoPlotMenu.cs
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/WpfPlotMenu.cs
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms/FormsPlotMenu.cs
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinUI/WinUIPlotMenu.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/CustomMenu.cs
src/ScottPlot5/ScottPlot5/Interfaces/IPlotMenu.cs

Resolves [#3224 ](https://github.com/ScottPlot/ScottPlot/issues/3224)

SP5 Controls: Add a Reset function to context menus

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Ellipse.cs
src/ScottPlot5/ScottPlot5/PlottableAdder.cs
src/ScottPlot5/ScottPlot5/Plottables/Ellipse.cs

SP5: Ellipse

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Shapes.cs
src/ScottPlot5/ScottPlot5/Extensions/SkiaSharpExtensions.cs
src/ScottPlot5/ScottPlot5/Hatches/Checker.cs
src/ScottPlot5/ScottPlot5/Hatches/Dots.cs
src/ScottPlot5/ScottPlot5/Hatches/Gradient.cs
src/ScottPlot5/ScottPlot5/Hatches/Grid.cs
src/ScottPlot5/ScottPlot5/Hatches/Square.cs
src/ScottPlot5/ScottPlot5/Hatches/Striped.cs
src/ScottPlot5/ScottPlot5/Interfaces/IHatch.cs
src/ScottPlot5/ScottPlot5/Legends/Common.cs
src/ScottPlot5/ScottPlot5/Markers/Circle.cs
src/ScottPlot5/ScottPlot5/Markers/Diamond.cs
src/ScottPlot5/ScottPlot5/Markers/Square.cs
src/ScottPlot5/ScottPlot5/Markers/TriangleDown.cs
src/ScottPlot5/ScottPlot5/Markers/TriangleUp.cs
src/ScottPlot5/ScottPlot5/Plottables/CandlestickPlot.cs
src/ScottPlot5/ScottPlot5/Plottables/Ellipse.cs
src/ScottPlot5/ScottPlot5/Plottables/Pie.cs
src/ScottPlot5/ScottPlot5/Plottables/Polygon.cs
src/ScottPlot5/ScottPlot5/Plottables/Rectangle.cs
src/ScottPlot5/ScottPlot5/Primitives/Box.cs

Hi @swharden,
this is a very preliminary version of gradient fill support (issue #3157)
Is this way to do okay for you?
Code example:
```cs
myPlot.Add.Signal(Generate.Sin()).Label = "Toto";
var rect = myPlot.Add.Rectangle(10, 33, 22, 45);
rect.FillStyle.Color = Colors.Blue;
rect.FillStyle.HatchColor = Colors.Red;
rect.FillStyle.Hatch = new Gradient();
...

SP5 FillStyle: add gradient fill support

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/RandomDataGenerator.cs

Single character change to stop the IndexOutOfRangeException

#3369 Fix RandomNormalSample from always throwing

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Avalonia/AvaPlot.cs

SP5 Avalonia: Call InvalidateVisual from Dispatcher.UIThread.

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/TickGenerators/TimeUnits/Centisecond.cs
src/ScottPlot5/ScottPlot5/TickGenerators/TimeUnits/Decisecond.cs

Fix snapping for centisecond and decisecond.

Improve automatic tick placement for centiseconds and deciseconds

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Tests/UnitTests/PlotCoordinateConversion.cs
src/ScottPlot5/ScottPlot5/Control/StandardActions.cs
src/ScottPlot5/ScottPlot5/Plot.cs
src/ScottPlot5/ScottPlot5/RenderPack.cs
src/ScottPlot5/ScottPlot5/Rendering/RenderManager.cs

As per the title.  Will fix #3454

Change `Plot.ScaleFactor` from `float` to `double`

---

src/ScottPlot5/ScottPlot5/TickGenerators/TimeUnits/Centisecond.cs
src/ScottPlot5/ScottPlot5/TickGenerators/TimeUnits/Decisecond.cs

@swharden I have screwed in my previous PR. It was originally correct, but then I for some strange reason decided it was not (tired I guess). 
So, to put things short, check if this one works for you. If you think this logic is worse, just drop it.

DateTime ticks: simplify snapping logic

---

src/ScottPlot5/ScottPlot5 Cookbook/Recipes/Axis/DateTimeAxes.cs
src/ScottPlot5/ScottPlot5/AxisPanels/XAxisBase.cs

Ticks: improve measurement of multiline ticks

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Text.cs
src/ScottPlot5/ScottPlot5/Plottables/Text.cs

This PR extends @jamaa's work in #3506. I didn't have push privileges to that branch so I made a new one.

Text: add Offset support (2)

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/ShowValueOnHoverMultiple.Designer.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/ShowValueOnHoverMultiple.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/ShowValueOnHoverMultiple.resx
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/WinForms Demo.csproj
src/ScottPlot5/ScottPlot5/Plottables/Marker.cs

I'm branching #3507 here because I don't have write access to that branch.
* Resolves #3503

Demo: refine "show value on hover" for multiple scatter plots

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Annotation.cs
src/ScottPlot5/ScottPlot5 Tests/RenderTests/Plottable/AnnotationTests.cs
src/ScottPlot5/ScottPlot5/PlottableAdder.cs
src/ScottPlot5/ScottPlot5/Plottables/Annotation.cs
src/ScottPlot5/ScottPlot5/Primitives/Label.cs

Reference to issue  #3356 
Outstanding issues:
- Currently missing the `MarginX/MarginY` implementation
- Needs firming up on the default formatting
- Needs firming up the default (minimum) offset from respective axes to ensure uniform and predictable spacing
- Additional tests?
- Example code/contrib. to the Cookbook

Proposed implementation of an Annotation Plottable

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Finance.cs
src/ScottPlot5/ScottPlot5/Plottables/OHLCPlot.cs

Add Sequential property in the same way as in the CandlestickPlot

SP5: Add Sequential property for OHLCPlot

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/Plot.cs

GetCoordinateRect method, that allows to use specific axis.

SP5: GetCoordinateRect with specific axis

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/SignalXY.cs
src/ScottPlot5/ScottPlot5/Plottables/SignalXY.cs

If I understood correctly, then the solution you propose looks like this. But I'm not sure what's in Drawing.DrawMarkers should be passed pixels, but I haven't quite figured out how I can get the points I need.

SignalXY: add support for markers

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Scatter.cs
src/ScottPlot5/ScottPlot5 Tests/RenderTests/Plottable/ScatterTests.cs
src/ScottPlot5/ScottPlot5/DataSources/ScatterSourceCoordinatesArray.cs
src/ScottPlot5/ScottPlot5/DataSources/ScatterSourceCoordinatesList.cs
src/ScottPlot5/ScottPlot5/DataSources/ScatterSourceDoubleArray.cs
src/ScottPlot5/ScottPlot5/DataSources/ScatterSourceGenericArray.cs
src/ScottPlot5/ScottPlot5/DataSources/ScatterSourceGenericList.cs
src/ScottPlot5/ScottPlot5/DataSources/ScatterSourceWithCachedLimits.cs
src/ScottPlot5/ScottPlot5/Interfaces/IScatterSource.cs
src/ScottPlot5/ScottPlot5/Plottables/Scatter.cs
src/ScottPlot5/ScottPlot5/Primitives/CoordinateRange.cs
src/ScottPlot5/ScottPlot5/Primitives/ExpandingAxisLimits.cs

Scatter Plot: support min/max render indexes

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/Plottables/AxisLine.cs

AxisLine: Do not show markers on AxisLine legend items

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinUI/WinUIPlot.cs
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinUI/WinUIPlotExtensions.cs

Applies patch provided in #3642

WinUI: automatic display scaling detection and correction

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Function.cs

Cookbook: use static inline methods for function plot examples

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Blazor/ScottPlot.Blazor.csproj
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.Blazor.WebAssembly/Pages/Index.razor
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.Blazor.WebAssembly/Pages/Quickstart.razor

Blazor: fix dependency issue and improve layout

---

src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/ShowValueOnHoverMultiple.cs

one-line fix in demo code, see #3680

Fix missing variable update in demo "Show value under mouse, multiple series"

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/PathStrategies/CubicSpline.cs

This fix gives better shape around endpoint in an open spline.

Improve spline shape

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms/Form1.Designer.cs
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms/Form1.cs
src/ScottPlot5/ScottPlot5/Control/Interaction.cs
src/ScottPlot5/ScottPlot5/Control/StandardActions.cs
src/ScottPlot5/ScottPlot5/Control/StandardZoomRectangle.cs
src/ScottPlot5/ScottPlot5/Interfaces/IPlotInteraction.cs
src/ScottPlot5/ScottPlot5/Interfaces/IZoomRectangle.cs
src/ScottPlot5/ScottPlot5/Plot.cs

resolves #3729
```cs
formsPlot1.Interaction.ChangeOpposingAxesTogether = true;
```

Interaction.ChangeOpposingAxesTogether

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/Axis/MultiAxis.cs
src/ScottPlot5/ScottPlot5 Tests/RenderTests/AxisTicksTests.cs
src/ScottPlot5/ScottPlot5/AxisPanels/AxisBase.cs
src/ScottPlot5/ScottPlot5/AxisPanels/LeftAxis.cs
src/ScottPlot5/ScottPlot5/AxisPanels/RightAxis.cs
src/ScottPlot5/ScottPlot5/AxisPanels/XAxisBase.cs
src/ScottPlot5/ScottPlot5/AxisPanels/YAxisBase.cs

The core fix is bfafd468f3caca6c5cba5ef7a21bb06f95f5e0fd which resolves #3736

Automatic numeric tick generator: fix label measurement bug

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Signal.cs
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/SignalXY.cs
src/ScottPlot5/ScottPlot5 Tests/RenderTests/Plottable/SignalTests.cs
src/ScottPlot5/ScottPlot5/DataSources/SignalSourceBase.cs
src/ScottPlot5/ScottPlot5/DataSources/SignalSourceDouble.cs
src/ScottPlot5/ScottPlot5/DataSources/SignalSourceGenericArray.cs
src/ScottPlot5/ScottPlot5/DataSources/SignalSourceGenericList.cs
src/ScottPlot5/ScottPlot5/DataSources/SignalXYSourceDoubleArray.cs
src/ScottPlot5/ScottPlot5/DataSources/SignalXYSourceGenericArray.cs
src/ScottPlot5/ScottPlot5/Interfaces/ISignalSource.cs
src/ScottPlot5/ScottPlot5/Interfaces/ISignalXYSource.cs
src/ScottPlot5/ScottPlot5/Plottables/Signal.cs

Signal: Add `YScale` to support vertical scaling

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/ShowValueOnHover.Designer.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/ShowValueOnHover.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/ShowValueOnHoverMultiple.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/ShowValueUnderMouseSignalXY.Designer.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/ShowValueUnderMouseSignalXY.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Program.cs
src/ScottPlot5/ScottPlot5/DataSources/ScatterSourceCoordinatesArray.cs
src/ScottPlot5/ScottPlot5/DataSources/ScatterSourceCoordinatesList.cs
src/ScottPlot5/ScottPlot5/DataSources/ScatterSourceDoubleArray.cs
src/ScottPlot5/ScottPlot5/DataSources/ScatterSourceGenericArray.cs
src/ScottPlot5/ScottPlot5/DataSources/ScatterSourceGenericList.cs
src/ScottPlot5/ScottPlot5/DataSources/ScatterSourceWithCachedLimits.cs
src/ScottPlot5/ScottPlot5/DataSources/SignalXYSourceDoubleArray.cs
src/ScottPlot5/ScottPlot5/DataSources/SignalXYSourceGenericArray.cs
src/ScottPlot5/ScottPlot5/Interfaces/IScatterSource.cs
src/ScottPlot5/ScottPlot5/Interfaces/ISignalXYSource.cs

Optimized function that returns the point nearest the cursor's X position (ignoring Y)
Resolves #3807

SignalXY and Scatter: GetNearestX()

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/Control/StandardActions.cs
src/ScottPlot5/ScottPlot5/Generate.cs

* resolves #3810
* resolves #3897

Controls: ignore middle-click-drag on axes with no data

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/DataSources/SignalXYSourceDoubleArray.cs
src/ScottPlot5/ScottPlot5/DataSources/SignalXYSourceGenericArray.cs

SignalXY: Ensure the final point is always drawn in high density mode

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/TickGenerators/DateTimeFixedInterval.cs

Added LabelFormatter to DateTimeFixedInterval, like done with the DateTimeAutomaticInterval.

Added LabelFormatter to DateTimeFixedInterval

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WebApi/Program.cs
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WebApi/Sandbox.WebApi.csproj
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WebApi/appsettings.Development.json
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WebApi/appsettings.json
src/ScottPlot5/ScottPlot5.sln

This is a sample sandbox project of a web api that return a data uri to embed an image generated by scott plot.
#3824

Demonstrate how to generate plots with a .NET API

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/Primitives/CoordinateRect.cs

CoordinateRect: BottomRight has X and Y reversed

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Scatter.cs

I implemented the Stacked Filled Line Plot Cookbook
This is my first time writing a Cookbook, please correct me if there are any mistakes.
If there is anything wrong with the description, please help me correct it because my English is terrible.
#3967

Cookbook: add recipe demonstrating stacked filled line chart

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/Plottables/Benchmark.cs

fix rendered FPS text position

Rendered FPS text position

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/Plottables/SignalXY.cs

Fix typo in SignalXY MIn/MaxRenderIndex property definition.

Fix SignalXY Min/MaxRenderIndex typo

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/Primitives/Platform.cs
src/ScottPlot5/ScottPlot5/ScottPlot.csproj

csproj: remove `System.Runtime.InteropServices.RuntimeInformation` dependency

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/Generate.cs

Generate: add RandomNormalNumber() to return a double

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/PlotStyles/Dark.cs
src/ScottPlot5/ScottPlot5/PlotStyles/Light.cs
src/ScottPlot5/ScottPlot5/Primitives/PlotStyle.cs

Close #4036 (PlotStyle: rename properties)

PlotStyle: fix properties naming

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/DataSources/SignalConstSource.cs

Fix wrong index rounding in SinglaConst (#4083).

SignalConst: Improve placement of first point

---

CHANGELOG.md
src/ScottPlot4/ScottPlot.Cookbook/ScottPlot.Cookbook.csproj

Remove `System.Text.Jason` package in ScottPlot 4 Cookbook

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Tests/Unit Tests/CodeTests/CodeFormatTests.cs
src/ScottPlot5/ScottPlot5/PlottableAdder.cs

resolves #4105 
mentioned in #4152

PlottableAdder: ignore some plot types when indexing palette

---

CHANGELOG.md
dev/ScottPlot5/hugo-serve.bat
src/ScottPlot5/ScottPlot5 Cookbook/SetupAndTeardown.cs
src/ScottPlot5/ScottPlot5 Cookbook/Website/ColormapsPage.cs
src/ScottPlot5/ScottPlot5 Cookbook/Website/FrontPage.cs
src/ScottPlot5/ScottPlot5 Cookbook/Website/Generate.cs
src/ScottPlot5/ScottPlot5 Cookbook/Website/PageBase.cs
src/ScottPlot5/ScottPlot5 Cookbook/Website/PalettesPage.cs
src/ScottPlot5/ScottPlot5 Cookbook/Website/SearchPage.cs
src/ScottPlot5/ScottPlot5/Primitives/Color.cs
src/ScottPlot5/ScottPlot5/Primitives/Colormap.cs
src/ScottPlot5/ScottPlot5/Primitives/Palette.cs

Cookbook: add palettes and colormaps pages

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/Plottables/Marker.cs

add alias Position and Coordiantes for X and Y

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Avalonia/AvaPlotMenu.cs
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Eto/EtoPlotMenu.cs
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/WpfPlotMenu.cs
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms/FormsPlotMenu.cs
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinUI/WinUIPlotMenu.cs
src/ScottPlot5/ScottPlot5/Plot.cs
src/ScottPlot5/ScottPlot5/Primitives/ImageFormat.cs

Plot: Save() autodetect format from filename

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/Plottables/AxisSpan.cs

AxisSpan: IsUnderMouse()

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/Primitives/AxisLimits.cs

AxisLimits: Contains()

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Tests/Unit Tests/GenerateTests.cs
src/ScottPlot5/ScottPlot5/Generate.cs

Generate.Range(): fix floating point accumulation error

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Phasor.cs
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Polar.cs
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Radar.cs
src/ScottPlot5/ScottPlot5 Cookbook/SetupAndTeardown.cs
src/ScottPlot5/ScottPlot5/Drawing.cs
src/ScottPlot5/ScottPlot5/PlottableAdder.cs
src/ScottPlot5/ScottPlot5/Plottables/PolarAxis.cs
src/ScottPlot5/ScottPlot5/Plottables/Radar.cs
src/ScottPlot5/ScottPlot5/Primitives/LabelStyle.cs
src/ScottPlot5/ScottPlot5/Primitives/PolarAxisCircle.cs
src/ScottPlot5/ScottPlot5/Primitives/PolarAxisSpoke.cs
src/ScottPlot5/ScottPlot5/Primitives/RadarSeries.cs

* resolves #4187
* resolves #4186
* extends #4055

Radar: refactor to use polar axis

---

src/ScottPlot5/ScottPlot5 Cookbook/Recipes/Axis/AdvancedAxis.cs

Cookbook: need recipe to show how to hide axis ticks

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/RandomDataGenerator.cs

Generate: Use `Random.Shared` if possible

---

.github/workflows/task-full.yaml
dev/BuildTimeTester/BuildTimeTester.csproj
dev/BuildTimeTester/BuildTimeTester.sln
dev/BuildTimeTester/Program.cs
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinUI/ScottPlot.WinUI.csproj
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/RecipeBase.cs
src/ScottPlot5/ScottPlot5 Cookbook/ScottPlot Cookbook.csproj
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.Blazor.WebAssembly/Sandbox.Blazor.WebAssembly.csproj
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.Maui/Sandbox.Maui.csproj
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.UnoPlatform/Sandbox.UnoPlatform/Sandbox.UnoPlatform.csproj
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinUI.Desktop/Sandbox.WinUI.Desktop.csproj
src/ScottPlot5/ScottPlot5 Tests/Unit Tests/ScottPlot Unit Tests.csproj

Improves speed of the "full build" action by excluding Maui, WinUI, and Blazor projects. Also no longer builds and tests ScottPlot4 on every commit.
resolves #4223

CICD: Improve pipeline speed

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/PlottableAdder.cs

Plot: improve GetNextColor() performance

---

src/ScottPlot5/ScottPlot5 Tests/Unit Tests/PlotAssertions.cs
src/ScottPlot5/ScottPlot5 Tests/Unit Tests/RenderTests/Plottable/SignalTests.cs
src/ScottPlot5/ScottPlot5/DataSources/SignalXYSourceDoubleArray.cs

SignalXY: throw if X values are not ascending

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/Interfaces/IAxes.cs

Axes: SetSpanX() and SetSpanY()

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Pie.cs
src/ScottPlot5/ScottPlot5/Plottables/Pie.cs
src/ScottPlot5/ScottPlot5/Plottables/PieBase.cs
src/ScottPlot5/ScottPlot5/Primitives/PieSlice.cs

Bring the feature of Pie plot which ScottPlot 4 owns to 5.

Pie: respect `LineStyle`, fix automatic axis limits, and demonstrate percent labels

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Pie.cs
src/ScottPlot5/ScottPlot5/Plottables/Coxcomb.cs
src/ScottPlot5/ScottPlot5/Plottables/Pie.cs
src/ScottPlot5/ScottPlot5/Plottables/PieBase.cs
src/ScottPlot5/ScottPlot5/Primitives/LabelStyle.cs
src/ScottPlot5/ScottPlot5/Primitives/PieSlice.cs

Fix #3295 . It should be compatible to old codes.

Pie:  Make the label and legend text settings independent

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/DataSources/SignalXYSourceDoubleArray.cs

SignalXY: fix GetRangeY() variable error

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Tests/Unit Tests/RenderTests/AxisTicksTests.cs
src/ScottPlot5/ScottPlot5 Tests/Unit Tests/UnitTests/PrimitiveTests/CoordinateRangeTests.cs
src/ScottPlot5/ScottPlot5/AxisLimitManagers/Full.cs
src/ScottPlot5/ScottPlot5/DataSources/DataStreamerSource.cs
src/ScottPlot5/ScottPlot5/DataSources/FunctionSource.cs
src/ScottPlot5/ScottPlot5/DataSources/ScatterSourceDoubleArray.cs
src/ScottPlot5/ScottPlot5/DataSources/ScatterSourceGenericArray.cs
src/ScottPlot5/ScottPlot5/DataSources/ScatterSourceGenericList.cs
src/ScottPlot5/ScottPlot5/Plottables/HorizontalSpan.cs
src/ScottPlot5/ScottPlot5/Plottables/VerticalSpan.cs
src/ScottPlot5/ScottPlot5/Primitives/CoordinateRange.cs
src/ScottPlot5/ScottPlot5/TickGenerators/DecimalTickSpacingCalculator.cs
src/ScottPlot5/ScottPlot5/TickGenerators/NumericFixedInterval.cs

I reorganized `CoordinateRange` and added new properties and methods.
If something is wrong, please tell me. 😉

CoordinateRange: refactor and improve tests

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Maui/MauiPlot.cs
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Maui/MauiPlotMenu.cs
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Maui/Register.cs
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.Maui/MauiProgram.cs
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.Maui/Sandbox.Maui.csproj

Hello, thank you for developing this useful library. As mentioned in the following issue:
https://github.com/ScottPlot/ScottPlot/issues/4023
There are some problems when implementing MauiPlot due to the class it inherits from, as well as issues with SkiaSharp:
https://github.com/mono/SkiaSharp/issues/2999 which causes exceptions on desktop.
I have made modifications to the class so it can be implemented in the XAML file as a control. I encountered some issues running the Sandbox, so I tested it in a new MAUI project (.NET 8), but I’ve also left the modifications in Sandbox.Maui. You can pan, zoom (double-click on desktop), and it now includes a contextual menu. Clipboard functionality and saving are still pending.
I’ve added a MauiQuickstart based on the work by @ByteSore.
**Step 1**: …

Maui support

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/AutoScalers/FractionalAutoScaler.cs
src/ScottPlot5/ScottPlot5/AxisManager.cs

Plot.Axes.MarginX() and Plot.Axes.MarginY()

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/Introduction/Styling.cs
src/ScottPlot5/ScottPlot5/Colormaps/LinearSegmented.cs
src/ScottPlot5/ScottPlot5/Primitives/Colormap.cs

Added `Colormap.FromColors()` to generate colormaps using interpolated gradients between a user defined collection of colors (#4247)

Colormap: FromColors()

---

src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Avalonia/ScottPlot.Avalonia.csproj
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Blazor/ScottPlot.Blazor.csproj
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Eto/ScottPlot.Eto.csproj
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Maui/ScottPlot.Maui.csproj
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.OpenGL/ScottPlot.OpenGL.csproj
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/ScottPlot.WPF.csproj
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms/ScottPlot.WinForms.csproj
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinUI/ScottPlot.WinUI.csproj
src/ScottPlot5/ScottPlot5 Tests/Unit Tests/CodeTests/CsprojTests.cs
src/ScottPlot5/ScottPlot5/ScottPlot.csproj

Tests: ensure license and copyright is in all nuget package files

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/ScaleBar.cs
src/ScottPlot5/ScottPlot5/PlottableAdder.cs
src/ScottPlot5/ScottPlot5/Plottables/ScaleBar.cs

ScaleBar: new plot type

---

src/ScottPlot5/ScottPlot5 Cookbook/Console.cs
src/ScottPlot5/ScottPlot5 Tests/Unit Tests/Console.cs

Tests: suppress console output in CI system

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/Plottables/ScaleBar.cs

Scalebar: fix rendering artifact (#4329)

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Tests/Unit Tests/RenderTests/FileFormatTests.cs
src/ScottPlot5/ScottPlot5/Plot.cs

Plot: GetImageXml() and GetSvgXml()

---

src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/SignalXY.cs

Cookbook: SignalXY with DateTime units

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Cookbook/Query.cs
src/ScottPlot5/ScottPlot5 Cookbook/RecipeTests.cs
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/Miscellaneous/Layout.cs
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/Miscellaneous/MultiplotRecipes.cs
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/MultiplotRecipeBase.cs
src/ScottPlot5/ScottPlot5 Cookbook/SourceDatabase.cs
src/ScottPlot5/ScottPlot5 Cookbook/Website/CategoryPage.cs
src/ScottPlot5/ScottPlot5 Cookbook/Website/ColormapsPage.cs
src/ScottPlot5/ScottPlot5 Cookbook/Website/FrontPage.cs
src/ScottPlot5/ScottPlot5 Cookbook/Website/PageBase.cs
src/ScottPlot5/ScottPlot5 Cookbook/Website/RecipePage.cs
src/ScottPlot5/ScottPlot5 Tests/Unit Tests/Extensions.cs
src/ScottPlot5/ScottPlot5 Tests/Unit Tests/RenderTests/MultiPlotTests.cs
src/ScottPlot5/ScottPlot5/Interfaces/IMultiplotLayout.cs
src/ScottPlot5/ScottPlot5/Multiplot.cs
src/ScottPlot5/ScottPlot5/MultiplotLayouts/Columns.cs
src/ScottPlot5/ScottPlot5/MultiplotLayouts/Custom.cs
src/ScottPlot5/ScottPlot5/MultiplotLayouts/Grid.cs
src/ScottPlot5/ScottPlot5/MultiplotLayouts/Rows.cs
src/ScottPlot5/ScottPlot5/Primitives/Colormap.cs
src/ScottPlot5/ScottPlot5/Primitives/FractionRect.cs
src/ScottPlot5/ScottPlot5/Primitives/Palette.cs

Multiplot: improve layout system and add examples to cookbook

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/PathStrategies/Straight.cs

PathStrategies: make Straight public

---

src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinFormsFinance/Program.cs
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinFormsFinance/Sandbox.WinFormsFinance.csproj
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinFormsFinance/TradingViewForm.Designer.cs
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinFormsFinance/TradingViewForm.cs
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinFormsFinance/TradingViewForm.resx
src/ScottPlot5/ScottPlot5.sln

Sandbox: start finance demo

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Finance.cs
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinFormsFinance/TradingViewForm.Designer.cs
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinFormsFinance/TradingViewForm.cs
src/ScottPlot5/ScottPlot5 Tests/Unit Tests/SourceCodeParsing.cs
src/ScottPlot5/ScottPlot5 Tests/Unit Tests/UnitTests/PrimitiveTests/ColorTests.cs
src/ScottPlot5/ScottPlot5/PlottableAdder.cs
src/ScottPlot5/ScottPlot5/Plottables/Annotation.cs
src/ScottPlot5/ScottPlot5/Primitives/FractionRect.cs
src/ScottPlot5/ScottPlot5/Primitives/PixelOffset.cs
src/ScottPlot5/ScottPlot5/Primitives/PixelRect.cs

* resolves #4395 
* related #4385

Plot.Add.BackgroundText()

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Finance.cs
src/ScottPlot5/ScottPlot5/DataGenerators/FinancialDataGenerator.cs
src/ScottPlot5/ScottPlot5/DataSources/OHLCSourceArray.cs
src/ScottPlot5/ScottPlot5/DataSources/OHLCSourceBase.cs
src/ScottPlot5/ScottPlot5/DataSources/OHLCSourceList.cs
src/ScottPlot5/ScottPlot5/Finance/SimpleMovingAverage.cs
src/ScottPlot5/ScottPlot5/Generate.cs
src/ScottPlot5/ScottPlot5/Interfaces/IOHLCSource.cs
src/ScottPlot5/ScottPlot5/PlottableAdder.cs
src/ScottPlot5/ScottPlot5/Plottables/CandlestickPlot.cs
src/ScottPlot5/ScottPlot5/Plottables/OHLCPlot.cs
src/ScottPlot5/ScottPlot5/Primitives/Color.cs

Resolves #4397 
Also improves support for `List<OHLC>` and `OHLC[]` in data sources and adds a few helper methods to other classes like `Color`

Generate: simplify creation of financial data

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/DataSources/DataLoggerSource.cs
src/ScottPlot5/ScottPlot5/Plottables/DataLogger.cs

DataLogger: Clear()

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinFormsFinance/TradingViewForm.cs
src/ScottPlot5/ScottPlot5/Interactivity/KeyboardState.cs
src/ScottPlot5/ScottPlot5/Interactivity/UserActionResponses/MouseDragPan.cs
src/ScottPlot5/ScottPlot5/Interactivity/UserActionResponses/MouseDragZoom.cs
src/ScottPlot5/ScottPlot5/Interactivity/UserInputProcessor.cs

improves support for financial charting #4385

UserInputProcessor: add axis locking arguments to LeftClickDragPan() and RightClickDragZoom()

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Tests/Unit Tests/RenderTests/Plottable/CandlestickTests.cs
src/ScottPlot5/ScottPlot5/DataSources/OHLCSourceBase.cs
src/ScottPlot5/ScottPlot5/Plottables/CandlestickPlot.cs
src/ScottPlot5/ScottPlot5/Primitives/OHLC.cs

Candlestick Plot: Improve visibility of candles with zero price movement

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/TriangularAxis.cs
src/ScottPlot5/ScottPlot5/PlottableAdder.cs
src/ScottPlot5/ScottPlot5/Plottables/TriangularAxis.cs
src/ScottPlot5/ScottPlot5/Primitives/CoordinateLine.cs
src/ScottPlot5/ScottPlot5/Primitives/Coordinates.cs
src/ScottPlot5/ScottPlot5/Primitives/TriangularAxisEdge.cs

Extends #4421
default | rotated
---|---

TriangularAxis: support clockwise and counter-clockwise orientations

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/AxisManager.cs

Plot.Axes.SquareUnits(): use SquarePreserveX in controls

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Bar.cs
src/ScottPlot5/ScottPlot5/Drawing.cs
src/ScottPlot5/ScottPlot5/PlottableAdder.cs
src/ScottPlot5/ScottPlot5/Plottables/BarPlot.cs
src/ScottPlot5/ScottPlot5/Plottables/Rectangle.cs
src/ScottPlot5/ScottPlot5/Primitives/BackgroundStyle.cs
src/ScottPlot5/ScottPlot5/Primitives/Bar.cs

Bar: improve support for hatched fills

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Scatter.cs
src/ScottPlot5/ScottPlot5/Generate.cs

Cookbook: demonstrate stacked scatter plot with shading

---

src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/MicrophoneDemo.Designer.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/MicrophoneDemo.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/MicrophoneDemo.resx
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Program.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/WinForms Demo.csproj

WinForms demo: live audio monitor

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/VectorField.cs
src/ScottPlot5/ScottPlot5/Plottables/VectorField.cs

VectorField: MaximumArrowLength

---

src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/LiveData.cs
src/ScottPlot5/ScottPlot5/Generate.cs

Cookbook: DataStreamer and DataLogger

---

src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Heatmap.cs

Cookbook: heatmap with labeled cells

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/Primitives/OHLC.cs

OHLC: throw if constructed with bad values

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/WpfPlotBase.cs

WpfPlot: GetPlotPixelPosition() and GetCurrentPlotPixelPosition()

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/Plottables/Callout.cs

Callout: improve automatic limit detection

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/AxisLines.cs
src/ScottPlot5/ScottPlot5/Plottables/HorizontalLine.cs
src/ScottPlot5/ScottPlot5/Plottables/VerticalLine.cs

Axis Lines: add Minimum and Maximum properties

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/AxisManager.cs

Axes: SquareUnits(false)

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.Console/Program.cs
src/ScottPlot5/ScottPlot5/AxisManager.cs

AxisManager: NumericTicksBottom()

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/Interfaces/IColormap.cs

Colormap.GetImage()

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/General/TickRecipes.cs
src/ScottPlot5/ScottPlot5/TickGenerators/DateTimeManual.cs

DateTimeManual tick generator

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/General/AxisRecipes.cs
src/ScottPlot5/ScottPlot5/Grids/DefaultGrid.cs

DefaultGrid: add Color, LineWidth, and LineStyle properties

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/DataSources/DataLoggerSource.cs

DataLoggerSource: Expose `HasNewData`

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Tests/Unit Tests/RenderTests/Plottable/MarkerTests.cs
src/ScottPlot5/ScottPlot5/Plottables/Marker.cs

Marker: improve support for filled markers with outlines

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Tests/Unit Tests/InteractivityTests/UserInputActionTests/LeftClickDragPanTests.cs
src/ScottPlot5/ScottPlot5/Primitives/CoordinateRangeMutable.cs
src/ScottPlot5/ScottPlot5/Primitives/MultiAxisLimits.cs

Controls: improve mouse interactivity behavior for inverted axes

---

src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Heatmap.cs
src/ScottPlot5/ScottPlot5/LayoutEngines/Automatic.cs

Cookbook: fix heatmap colorbar recipe layout

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/Plottables/PopulationSymbol.cs

Population: deterministic horizontal randomness

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinFormsFinance/TradingViewForm.Designer.cs
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinFormsFinance/TradingViewForm.cs
src/ScottPlot5/ScottPlot5/DataSources/OHLCSourceArray.cs
src/ScottPlot5/ScottPlot5/DataSources/OHLCSourceBase.cs
src/ScottPlot5/ScottPlot5/DataSources/OHLCSourceList.cs
src/ScottPlot5/ScottPlot5/Interfaces/IOHLCSource.cs
src/ScottPlot5/ScottPlot5/Plottables/CandlestickPlot.cs

Improve finance demo

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/DataSources/SignalConstSource.cs

SignalConstSource: GetAxisLimits() include X and Y offset

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/Interactivity/UserInputProcessor.cs

UserInputProcessor: reset drag events on disable

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/Interactivity/UserActionResponses/MouseWheelZoom.cs
src/ScottPlot5/ScottPlot5/Plottables/CandlestickPlot.cs

Candlestick: fix FallingColor setter

---

src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/DemoWindowInfo.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/DemoWindows.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/LiveHistogram.Designer.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/LiveHistogram.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/LiveHistogram.resx
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/WinForms Demo.csproj

Demo: live histogram

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/Miscellaneous/Histograms.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/LiveHistogram.cs
src/ScottPlot5/ScottPlot5/PlottableAdder.cs
src/ScottPlot5/ScottPlot5/Plottables/HistogramBars.cs

resolves #4557
```cs
public partial class LiveHistogram : Form, IDemoWindow
{
readonly System.Windows.Forms.Timer Timer = new() { Enabled = true, Interval = 20 };
public LiveHistogram()
{
var histogram = Histogram.WithBinCount(count: 50, minValue: 0, maxValue: 100);
var histogramPlot = formsPlot1.Plot.Add.Histogram(histogram);
// simulate live incoming data
Timer.Tick += (s, e) =>
{
int numberOfNewValues = Generate.RandomInteger(50, 100);
for (int i = 0; i < numberOfNewValues; i++)
{
double randomValue = Generate.RandomNormalNumber(mean: 50, stdDev: 10);
histogram.Add(randomValue);
}
formsPlot1.Plot.Title($"Total: {histogram.Counts.Sum():N0}");
formsPlot1.Plot.Axes.AutoScale();
formsPlot1.Refresh();
};
}
}
```

HistogramBars: new plot type

---

src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/MultiplotAdvancedLayout.Designer.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/MultiplotAdvancedLayout.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/MultiplotAdvancedLayout.resx
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/MultiplotAlignment.Designer.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/MultiplotAlignment.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/MultiplotAlignment.resx
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/MultiplotSharedAxis.Designer.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/MultiplotSharedAxis.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/MultiplotSharedAxis.resx
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Program.cs
src/ScottPlot5/ScottPlot5/Multiplot.cs

This PR adds interactive multiplot demos to the WinForms demo application.
This PR is part of larger work tracked by #4600

Demo: add multiplot windows

---

src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/MultiplotAdvancedLayout.Designer.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/MultiplotAdvancedLayout.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/MultiplotCollapsed.Designer.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/MultiplotCollapsed.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/MultiplotCollapsed.resx
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Program.cs
src/ScottPlot5/ScottPlot5/Multiplot.cs

This PR adds additional example windows to the WinForms demo application showcasing advanced layout functionality.
This PR is part of larger work tracked by #4600

Demo: multi-plot with collapsed subplots

---

src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/MultiplotCollapsed.cs

Extends work discussed in #4600

Demo: collapsed financial multiplot with right axis

---

src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/MultiplotCollapsed.cs

This PR extends the WinForms collapsed subplot demo to enable draggable borders between subplots.
See #4600 for additional discussion

Demo: multiplot with resizable borders

---

src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/ScrollViewerDemo.Designer.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/ScrollViewerDemo.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/ScrollViewerDemo.resx
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Program.cs

Demo: control mouse behavior in scroll viewer

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/Plot.cs
src/ScottPlot5/ScottPlot5/Primitives/Legend.cs

Legend: allow inheritance and assignment

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/Plottables/ZoomRectangle.cs

ZoomRectangle: improve support for inverted axis limits

---

src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Heatmap.cs

Cookbook: heatmap with DateTime units

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Avalonia/ScottPlot.Avalonia.csproj
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Blazor/ScottPlot.Blazor.csproj
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Eto/ScottPlot.Eto.csproj
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Maui/ScottPlot.Maui.csproj
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.OpenGL/ScottPlot.OpenGL.csproj
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/ScottPlot.WPF.csproj
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/WpfPlotGL.cs
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms/ScottPlot.WinForms.csproj
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinUI/ScottPlot.WinUI.csproj
src/ScottPlot5/ScottPlot5/ScottPlot.csproj

Extends #4667 and resolves #4666

WpfPlotGL: improve multiplot render behavior

---

src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Avalonia/AvaPlot.cs

AvaPlot: fix multiplot implementation

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/WpfPlotViewer.cs
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms/FormsPlotViewer.cs

WinForms and WPF controls: reset context menu after viewer is launched

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Blazor/BlazorPlot.razor
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Blazor/BlazorPlotGL.razor
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Maui/MauiPlot.cs
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms/FormsPlotGL.cs
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinUI/WinUIPlot.cs
src/ScottPlot5/ScottPlot5/Plot.cs

Multiplot: Improve interactive behavior in Maui, Blazor, and WinUI controls

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Cookbook/Website/ColorsPage.cs
src/ScottPlot5/ScottPlot5 Cookbook/Website/FrontPage.cs
src/ScottPlot5/ScottPlot5 Cookbook/Website/Generate.cs
src/ScottPlot5/ScottPlot5 Tests/Unit Tests/UnitTests/PrimitiveTests/ColorTests.cs
src/ScottPlot5/ScottPlot5/Primitives/Colors.cs

resolves #4681
https://scottplot.net/cookbook/5.0/colors

Cookbook: add colors page

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Avalonia/AvaPlot.cs
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Blazor/BlazorPlotBase.cs
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Eto/EtoPlot.cs
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Maui/MauiPlot.cs
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/WpfPlotBase.cs
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms/FormsPlotBase.cs
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinUI/WinUIPlot.cs
src/ScottPlot5/ScottPlot5/Interfaces/IMultiplot.cs
src/ScottPlot5/ScottPlot5/Interfaces/IPlotControl.cs
src/ScottPlot5/ScottPlot5/Multiplot.cs
src/ScottPlot5/ScottPlot5/Testing/MockPlotControl.cs

IPlotControl: use IMultiplot instead of Multiplot

---

.github/workflows/pr1.yaml
src/ScottPlot5/ScottPlot5 Cookbook/ScottPlot Cookbook.csproj
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/MultiplotGrowingAxis.Designer.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/MultiplotGrowingAxis.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/MultiplotGrowingAxis.resx
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Program.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/WinForms Demo.csproj
src/ScottPlot5/ScottPlot5 Tests/Unit Tests/ScottPlot Unit Tests.csproj
src/ScottPlot5/ScottPlot5/Rendering/RenderManager.cs

demo: multiplot with growing axes

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Ellipse.cs
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Shapes.cs
src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/PlottableDrag.cs
src/ScottPlot5/ScottPlot5/Drawing.cs
src/ScottPlot5/ScottPlot5/PlottableAdder.cs
src/ScottPlot5/ScottPlot5/Plottables/Ellipse.cs

resolve #4721, #4653
- `Rotation` and change type to `Angle`
- Synchronized rotation with the angular direction of the Cartesian coordinate system  
same as `PolarAxis` in #4321
- Drawing
- Fixed `DrawArc()` distortion on ellipse
- Added `DrawSector()`
- Added `FillSector()`
- Enhanced Ellipse plot
- Added `IsSector` property
- Added `StartAngle` property
- Added `SweepAngle` property
- Added new plot
- `Arc`
- `CircleSector`
- `EllipticalArc`
- `EllipticalSector`
```cs
formsPlot1.Plot.Axes.SquareUnits();
var sector = formsPlot1.Plot.Add.Arc(
0, 0, 100,
startAngle: Angle.FromDegrees(0),
sweepAngle: Angle.FromDegrees(90));
sector.LineWidth = 3;
sector.LineColor = Colors.Black;
```
```cs
formsPlot1.Plot.Axes.SquareUnits();
var sector = formsPlot1.Plot.Add.CircleSector(
0, 0, 100, …
```

Plottables: add several new elliptical curve and area plot types

---

src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Ellipse.cs
src/ScottPlot5/ScottPlot5/Drawing.cs

Resolves issue reported by https://github.com/ScottPlot/ScottPlot/pull/4739#issuecomment-2614560381

Drawing: fix DrawArc()

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/WpfPlotMenu.cs

WPF: add autoscale to default context menu

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/SignalXY.cs
src/ScottPlot5/ScottPlot5 Tests/Unit Tests/RenderTests/Plottable/SignalTests.cs
src/ScottPlot5/ScottPlot5/DataSources/SignalXYSourceGenericList.cs
src/ScottPlot5/ScottPlot5/Interfaces/IDataSource.cs
src/ScottPlot5/ScottPlot5/PlottableAdder.cs

Hello @swharden 
btw it's my first PR in total :-)
is this, what you had in mind with #4746 
I did not test it in my application but in the WinForms Demo. There it's working
In the Cookbook I wanted to refresh with modified data, but did not find a way to call the Refresh-Method
best regards
Josef

SignalXY: Improve support for generic lists

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms/FormsPlotBase.cs
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms/Form1.Designer.cs
src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms/Form1.cs
src/ScottPlot5/ScottPlot5/Interfaces/IMultiplot.cs
src/ScottPlot5/ScottPlot5/Plottables/SmithChartAxis.cs
src/ScottPlot5/ScottPlot5/Primitives/MultiplotLayoutSnapshot.cs

Multiplot: improve interactivity after Reset()

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/Plottables/PopulationSymbol.cs

Population: use stable horizontal offset

---

src/ScottPlot5/ScottPlot5 Cookbook/Recipes/General/ColorRecipes.cs
src/ScottPlot5/ScottPlot5/Primitives/Color.cs

Cookbook: demonstrate Color features

---

.devcontainer/devcontainer.json
CHANGELOG.md

GitHub codespace is an online Linux environment with a vscode web UI. It is useful for developers who don't have a Linux device but want to test and debug their code on Linux.

Add devcontainer.json to add GitHub Codespace support

---

src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/PolarAxis.cs

Adding a new cookbook recipe to answer the question in issue #5016.  How to draw a line in a polar axis plot.  There may be other ways to do it, but this one seemed to work.

Cookbook: adding recipe for drawing a line for a polar axis plot

---

src/ScottPlot5/ScottPlot5 Demos/Avalonia Demo/Demos/CustomMarkerWindow.axaml.cs
src/ScottPlot5/ScottPlot5 Demos/Avalonia Demo/Demos/CustomPlotTypeWindow.cs
src/ScottPlot5/ScottPlot5/Drawing.cs
src/ScottPlot5/ScottPlot5/Markers/OpenCircleWithDot.cs

to resolve warnings when building this project

Drawing: use FillCircle() when passing FillStyle

---

CHANGELOG.md
src/ScottPlot5/ScottPlot5/DataSources/SignalXYSourceDoubleArray.cs
src/ScottPlot5/ScottPlot5/DataSources/SignalXYSourceGenericArray.cs
src/ScottPlot5/ScottPlot5/DataSources/SignalXYSourceGenericList.cs
src/ScottPlot5/ScottPlot5/Interfaces/ISignalXYSource.cs
src/ScottPlot5/ScottPlot5/Plottables/Scatter.cs
src/ScottPlot5/ScottPlot5/Plottables/SignalXY.cs

Discussed in #5078, a breaking change seems fine here given that discussion.

ISignalXYSource: Allow IReadOnlyList implementations
