- demos/src/plottable-const/Form1.cs
- src/ScottPlot/MouseTracker.cs
- src/ScottPlot/Plot.cs
- src/ScottPlot/ScottPlotUC.cs
- src/ScottPlot/ScottPlotWPF.xaml.cs
- src/ScottPlot/Tools.cs
Mode enabled by set lowQualityWhileDragging=true in ScottPlotUC.
In this mode AA disabled for user interactions with plot like paning or zooming.
But then user stop interacting last render call with settings.antiAliasData.
This makes good speed improvment during user interactions, in cost of image quality.
But plot always looks perfect at static.
AA for figure never turned off, only for data.
> plot low quality (anti-aliasing off) while dragging

- src/ScottPlot/Plot.cs
- src/ScottPlot/plottables/PlottableSignalConst.cs
With singlePrecision=true SignalConst allocate and use float[] Trees. That halves memory usage, without visible changes. singlePrecision = false by default.
Additional maked small improvments on SignalConst Class.
This PR makes a lot of code duplicates in SignalConst class. I don't see another way to make it.
> singlePrecision trees for SignalConst

- demos/src/plottable-const/Form1.cs
- src/ScottPlot/Plot.cs
- src/ScottPlot/Settings.cs
- src/ScottPlot/plottables/PlottableSignal.cs
- src/ScottPlot/plottables/PlottableSignalConst.cs
Signal and SignalConst maked generic, thats allow plot different types of struct data types (float, int, byte etc). This types must be convertable to Double.
With generic data types all comparation calculation goes slower by 30-40%.
SignalConst overall render not visibly affected by this.
PlottableSignal Render slower by 10-20% for 10M points at high resolution chart. Posible improvement commented in MinMaxRangeQuery(), but it will give lots of code duplicates for all posible data types.
> Make PlottableSignalConst generic

- tests/ScottPlotTests/UnitTest1.cs
Caught an unexpected exception while saving figure without rendering first.   Saving an empty bitmap might be more appropriate.
> ScottPlotTests: add more tests

- src/ScottPlot/Config/Fonts.cs
- src/ScottPlot/Config/TextLabel.cs
- tests/FontsTests.cs
Initially in PR #212 `GetDefaultFontName()` return installed font with name containing preferred words (not strictly). 
In final implementation, return installed font with name exactly as preferred.
This PR brings initial algoritm back, (with priority order).
Also this PR adds durty `public` `GetDefaultFontName(IEnumerable<string> installedFonts)`. This method needed to substitute  `static` `FontFamily.Families`. That allow  to write some unit tests. Can be collapsed back to single `GetDefaultFontName()`, but with loosing tests.
I actualy not see big benefits of this PR (anyway `GetDefaultFontName()` return existing `SystemFonts.DefaultFont.Name` in worst cases ). All the time i thinked "does it really need". So feel free to reject this PR.
If this PR will be rejected, small improvement …
> Alternative font select implementation

- src/ScottPlot/Config/Axes.cs
- src/ScottPlot/Settings.cs
- tests/AxesTests.cs
Implement not used `Settings.AxisAuto()` `xExpandOnly` and `yExpandOnly` params.
> Implement Settings.AxisAuto ExpandOnly params

- src/ScottPlot/plottables/PlottableAxSpan.cs
`PlottableAxSpan` produce strange effect, if deeply zoomed in on one of of `AxSpan` border . During paning, border start "dancing" around correct coordinate.
In `Render()` of axis span it try to draw huge rectangle, say from (-1000000, 0) to (574, 800). And this huge rectangle clipped to bitmap size by GDI, which possible produce this effect.
This PR manualy clip huge coordinates outside of `DataBitmap` and fix AxSpan border "dancing".
> AxSpan Fix

- src/ScottPlot/Statistics/BoxAndWhisker.cs
- src/ScottPlot/Statistics/BoxAndWhiskerFromData.cs
- src/ScottPlot/Statistics/PopulationStats.cs
- src/ScottPlot/plottables/PlottableBoxAndWhisker.cs
… individual points
As before, here is the code that I used to test:
```
using System;
using System.Diagnostics;
namespace ScottPlotTesting
{
class Program
{
static void Main(string[] args)
{
Random rand = new Random();
var plt = new ScottPlot.Plot(600, 400);
string filename = "test.png";
double[] xs = new double[3];
double[][] ys = new double[3][];
for (int i = 0; i < ys.Length; i++)
{
xs[i] = i;
ys[i] = new double[10];
for (int j = 0; j < 10; j++)
{
if (j == 0)
{
ys[i][j] = 2;//Just to guarantee that there is an outlier
continue;
}
ys[i][j] = rand.NextDouble();
}
}
ScottPlot.Statistics.BoxAndWhisker[] boxAndWhisker = new ScottPlot.Statistics.BoxAndWhisker[ys.Length];
for (int i = 0; i < ys.Length; i++) {
boxAndWhisker[i] = …
```
> BoxAndWhisker improvements

- src/ScottPlot/Settings.cs
- src/ScottPlot/plottables/PlottableSignal.cs
- src/ScottPlot/plottables/PlottableSignalConst.cs
- tests/MultiThreadingTests.cs
Add tests for currently implemented parallel renderers.
Additionaly tests for thread safe calls of `Settings.GetPixel` and `Settings.GetLocation` methods.
This PR prevents future Issues like #245.
Replaced `Settings.GetPixel(0, value).Y` with new `Settings.GetPixelY()` in `Signal` and `SignalConst`.
> optimize Signal & create parallel processing tests

- dev/changelog.md
- src/ScottPlot/plottables/PlottableSignal.cs
- src/ScottPlot/plottables/PlottableSignalConst.cs
Fix for issue #263.
Add ability to disable drawing lines by setting `lineWidth` to 0 for `Signal` and `SignalConst`.
Add ability to disable drawing points by setting `markerSize` to 0 for `Signal` and `SignalConst`.
This implemented only for `RenderLowDensity` mode.
`RenderHighDensity` mode stay as before.
> Add zero lineWidth and zero markerSize support to Signal and SignalConst

- dev/changelog.md
- src/ScottPlot.Demo.WinForms/FormDemos.Designer.cs
- src/ScottPlot.Demo.WinForms/FormDemos.cs
- src/ScottPlot.Demo.WinForms/ScottPlot.Demo.WinForms.csproj
- src/ScottPlot.Demo.WinForms/WinFormsDemos/TransparentBackground.Designer.cs
- src/ScottPlot.Demo.WinForms/WinFormsDemos/TransparentBackground.cs
- src/ScottPlot.Demo.WinForms/WinFormsDemos/TransparentBackground.resx
- src/ScottPlot.WinForms/FormsPlot.cs
- tests/Cookbook/Chef.cs
This PR allow user to set `formsPlot.BackColor = Color.Transparent` and get transparency over `Form` `BackGroundImage` #286.
Transparency over other controls requires a more complex solution (https://github.com/swharden/ScottPlot/issues/286#issuecomment-596084208)
> Set pbPlot.BackColor equal to FormsPlot.BackColor

- dev/changelog.md
- src/ScottPlot.Demo/Customize/Axis.cs
- src/ScottPlot/Tools.cs
This time the conversion is done in `src/ScottPlot/Tools.cs`, not in the PlotScatter function. The only thing is this returns a tuple, I would be happy to change the return type if you feel like that would better reflect the direction of the project.
> Tools.ConvertPolarCoordinates()

- src/ScottPlot.Demo/PlotTypes/Function.cs
- src/ScottPlot/plottables/PlottableFunction.cs
New contributors should review CONTRIBUTING.md:
https://github.com/swharden/ScottPlot/blob/master/CONTRIBUTING.md
**Purpose:**
This makes plotting functions with restricted domain easier.
Previously, if I wanted to plot the function `ln x`, I would have to do it like this:
`x => x > 0 ? Math.Log(x) : (double?)null`
Now I can just do `x => Math.Log(x)` and it will be taken care of.
> Easier function plotting

- dev/changelog.md
- src/ScottPlot.Demo.WinForms/WinFormsDemos/LinkedPlots.Designer.cs
- src/ScottPlot.Demo.WinForms/WinFormsDemos/LinkedPlots.cs
- src/ScottPlot.WinForms/FormsPlot.cs
- src/ScottPlot/Plot.cs
**Purpose:**
Fix linked axes lagging. #451 
The reasone is full `Render()` loop in second `formsPlot` on each mouse move.
This PR add `skipIfCurrentRendered = true` to demo,
Add extra param to `Render(bool processEvents)`. This param allow to make `Application.DoEvents()` in `Render()` for not interactive formsPlot (no mouse pan on zoom).
`Resize()` in `MatchAxis()` was commented. I have no idea why it was implemented in this method, But it create new bitmaps for all layers on each `MatchAxis()` call.
//TODO
Demo contain not optimal render call in `formsPlot2.AxisChanged()`.
This is for demonstration benefits of this PR. It must be changed to optimal before merge.
Extra parameter in `Render()` to process events in not interacted `formsPlot`.
Combined with …
> Fix lag on linked axes.

- dev/changelog.md
- src/ScottPlot/Plot.cs
- src/ScottPlot/plottables/PlottableSignal.cs
- src/ScottPlot/plottables/PlottableSignalXY.cs
**Purpose:**
Fix not used `maxRenderIndex` in `RenderHighDensity()` mode. #448
Additionaly refactored `RenderHighDensity()`.
For now it easy to switch between parallel and sequental implementation without code duplicates.
`useParallel` return back as `Signal` public field. No idea how better implement it in API, but let it stay configurable (imho). Parallel calculations not always better... #419
User can switch to sequental calculations by
```cs
var signal = plt.PlotSignal(....);
signal.useParallel = false;
```
Growing data demo correct render:
> Signal RenderHighDensity fix and refactor

- src/ScottPlot/Plot.cs
- src/ScottPlot/plottables/PlottableBar.cs
- tests/PlotTypes/Bar.cs
New contributors should review [CONTRIBUTING.md](https://github.com/swharden/ScottPlot/blob/master/CONTRIBUTING.md)
**Purpose:**
#461
N/A
Now bar plots with negative values look as they should:
**Autoformat your code:**
The build will fail if your code is not auto-formatted. Auto-format your code in Visual Studio, or from the console using these commands:
```
cd ScottPlot/src/
dotnet tool install --global dotnet-format
dotnet format
```
> fixed issues w/ barplots and negative values

- src/ScottPlot.Demo/PlotTypes/Bar.cs
- src/ScottPlot/Plot.cs
- src/ScottPlot/plottables/PlottableBar.cs
New contributors should review [CONTRIBUTING.md](https://github.com/swharden/ScottPlot/blob/master/CONTRIBUTING.md)
**Purpose:**
#463
Provide a code example demonstrating new functionality achieved with this pull request (if applicable):
```cs
Random rand = new Random(0);
int pointCount = 10;
double[] xs = DataGen.Consecutive(pointCount);
double[] ys = DataGen.RandomNormal(rand, pointCount, 5, 10);
double[] yOffsets = Enumerable.Range(0, pointCount).Select(count => ys.Take(count).Sum()).ToArray();
plt.PlotBar(xs, ys, yOffsets: yOffsets);
```
I wonder if `PlottableBar` should take a delegate to decide the colour of the bar, something like this:
```cs
Func<double y1, double y2, System.Drawing.Color> delegate = y2 - y1 > 0 ? …
```
> bar plot support for Y offset

- src/ScottPlot/plottables/PlottableSignal.cs
- src/ScottPlot/plottables/PlottableSignalXY.cs
**Purpose:**
Parallel processing for `PlottableSignalXY` #419
For now `PlottableSignalXY` support `useParallel` flag to enable/disable parallel processing.
Existing code has been substantially reworked, to make it unrelated between iterations and  without parallel/sequental code duplicates. Similar to the `PlottableSignal` #454 approach
Binary search is now used to find indexes in `xs` array. This should also improve performance.
`PlottableSignalXY` now respects to `minRenderIndex` and `maxRenderIndex` #493.  PR #495 deprecated now.
Additionaly fix `PlottableSignal` limits calculations.
```cs
plt.PlotSignalXY(xs, ys, minRenderIndex: 4000, maxRenderIndex: 200000, useParallel: true);
```
> SignalXY support for parallel processing and render index limits

- dev/changelog.md
- src/ScottPlot.Demo/PlotTypes/Pie.cs
- src/ScottPlot/Plot.cs
- src/ScottPlot/plottables/PlottablePie.cs
New contributors should review [CONTRIBUTING.md](https://github.com/swharden/ScottPlot/blob/master/CONTRIBUTING.md)
**Purpose:**
#533
Provide a code example demonstrating new functionality achieved with this pull request (if applicable):
```cs
plt.PlotPie(values, donut: true);
```
If this pull request changes how a plot is rendered, provide an image or screenshot demonstrating the new functionality:
Note this screenshot uses both an exploded and a donutted pie chart.
**Autoformat your code:**
The build will fail if your code is not auto-formatted. Auto-format your code in Visual Studio, or from the console using these commands:
```
cd ScottPlot/src/
dotnet tool install --global dotnet-format
dotnet format
```
> Donut pie chart

- dev/changelog.md
- src/ScottPlot.WPF/WpfPlot.xaml.cs
- src/ScottPlot.WinForms/FormsPlot.cs
**Purpose:**
Greatly improve render speed for `ScrollWheel` interactions #543.
1. Fix multiple event handler subscibe bug (`Control.Reset`).
2. All Scroll Wheel events puts in Render requests queue. At the end of the current rendering, all new requests are selected, the axes are scaled for each request, and then a new render is started. All renders are done in low quality. If no new request is received within 500 ms, then high quality rendering starts.
The code is durty, and shoud be refactored. But the functionality can already be tested.
There is no new `API` for now. But control settings like `HQDelayTime`, `LQDuringScrollWheel` should appear.
> Improve mouse wheel zoom speed

- src/ScottPlot.WPF/WpfPlot.xaml.cs
- src/ScottPlot.WinForms/FormsPlot.cs
**Purpose:**
Continuing a #545 .
1. Implement the same Render queue for WPF Control.
2. Small refactoring.
3. WPF Control `Render()` now have `bool processEvents` argument like WinForms Control. Improve WPF control pan/zoom speed.
```c#
WPFControl.Configure(lowQualityOnScrollWheel: true, lowQualityScrollWheelDelay: 500);
Render(processEvents: true);
```
> Improve mouse wheel zoom speed (WPF control)

- src/ScottPlot/MinMaxSearchStrategies/SegmentedTreeMinMaxSearchStrategy.cs
- src/ScottPlot/plottables/PlottableSignalBase.cs
- src/ScottPlot/plottables/PlottableSignalConst.cs
- src/ScottPlot/plottables/PlottableSignalXYConst.cs
**Purpose:**
Small additional fix to #504.
For now `PlottableSignalConst` and`PlottableSignaXYConst` returns correct `TreesReady` flag. `PlottableSignalBase` don't contain `TreesReady` flag.
The presence of this flag in the `PlottableSignal` is still doubtful, since the current implementation locks the current thread at the time the trees are calculated. As a result, if you poll `TreesReady` from the current thread, then there will always be `true`.
There is api and it's easy to do: Run trees calculation on another thread, and dont lock creation of `PlottableSignalConst`. Before trees calculated it rendered as `PlottableSignal`. When I did #504 I made the decision that this behavior was useless (discussable).
> PlottableSignalConst now return correct TreesReady flag.

- src/ScottPlot/Config/DateTimeTickUnits/DateTimeUnitFactory.cs
- src/ScottPlot/Config/DateTimeTickUnits/MonthToMinutes/DateTimeTickDay.cs
- src/ScottPlot/Config/DateTimeTickUnits/MonthToMinutes/DateTimeTickMonth.cs
- tests/Ticks/DateTimeTicksTests.cs
**Purpose:**
`DateTimeTickMonth` now always return 2 lines labels for any `Culture`. #539
Only first space replaced with `newLine`. It can divide a month that is described in few words in some cultures, But it's better then previous behavior.
Additionally fix #564 bug.
> All DateTimeTick units return 2 lines labels.

- dev/changelog.md
- src/ScottPlot/Config/TickCollection.cs
- src/ScottPlot/Tools.cs
- tests/Cookbook/Chef.cs
- tests/Tools/ChangingBase.cs
**Purpose:**
#581 
This is a comparison from the cookbook. Note that the only radices which currently have "nice" numbers are decimal and hexadecimal.
Before:
After:
**Other Concerns**
I noticed when writing this PR that in some situations the helper function `ScottPlot.Tools.ToDifferentBase` gave wrong answers, most noticeably in the case of numbers of the form r^k where r is the radix and k is some integer. It's hard to notice these cases when the numbers are not nice because the odds of that number also being a nice number in decimal are low; therefore it will not show up on the tick labels.
> Nice hexnumbers

- dev/changelog.md
- src/ScottPlot/Plot/Plot.PlotMisc.cs
- src/ScottPlot/Plottable/RadarPlot.cs
- src/cookbook/ScottPlot.Demo/PlotTypes/Radar.cs
**Purpose:**
#628 
Adds two options, a parameter `bool independentAxes` which determines whether the axes should be separate. And a public property `bool showAxisLabels` which determines whether axis labels are shown.
The following demo shows both:
```cs
double[,] values = { { 5, 3, 10, 15, 3, 2, 256 }, { 5, 2, 10, 10, 1, 4, 252 }, };
string[] categories = { "Wins", "Poles", "Podiums", "Points Finishes", "DNFs", "Fastest Laps", "Points" };
string[] groups = { "Sebastian Vettel", "Fernando Alonso" };
var radarPlot = plt.PlotRadar(values, categories, groups, independentAxes: true);
radarPlot.showAxisLabels = false;
plt.Legend();
// customize the …
```
> Radar multi axis

- src/ScottPlot/Plot/Plot.PlotMisc.cs
- src/ScottPlot/Plottable/RadarPlot.cs
- src/cookbook/ScottPlot.Demo/PlotTypes/Radar.cs
**Purpose:**
cf. #628
Added the option to pre-define the max values, independent of the provided values to plot.
```cs
double[,] values = { { 5, 3, 10, 15, 3, 2, 256 }, { 5, 2, 10, 10, 1, 4, 252 }, };
double[] maxValues = { 13, 15, 17, 15, 10, 10, 413 };
string[] categories = { "Wins", "Poles", "Podiums", "Points Finishes", "DNFs", "Fastest Laps", "Points" };
string[] groups = { "Sebastian Vettel", "Fernando Alonso" };
plt.PlotRadar(values, categories, groups, independentAxes: true, maxValues: maxValues);
plt.Legend();
// customize the plot
plt.Grid(false);
plt.Frame(false);
plt.Ticks(false, false);
plt.Title("2010 Formula One World Championship");
/* Data represents the 2010 Formula One World Championship
* …
```
> Radar with pre-defined max values

- src/ScottPlot/Drawing/Colormap.cs
- src/ScottPlot/Plot/Plot.Obsolete.cs
- src/ScottPlot/Plottable/Heatmap.cs
- src/demo/ScottPlot.Demo.WinForms/WinFormsDemos/ColormapViewer.cs
**Purpose:**
Currently when using the `TransparencyThreshold` parameter on heatmaps it compares the intensity on a range from 0 to 255 to the given threshold. This threshold, however, is given on a range from 0 to 1. This PR corrects that issue.
N/A
> Fixes transparency threshold to compare with normalized values

- src/ScottPlot/Plottable/AxisSpan.cs
- src/tests/PlottableRenderTests/AxisSpan.cs
**Purpose:** (bug fix)
Then zoom to `AxisSpan`, it shoud fill whole plot with its color. But on extreme zoom `AxisSpan` disapear.
This is a known `GDI+` bug with clipping objects that go far beyond the clipping region.
To fix bug, this PR manually clip `AxisSpan` by 1 pixel more then `Plottable area` before passing it to` GDI+`.
Additional added 2 integration tests that reproduce this bug.
This tests fails without this PR fix.
> Fix AxisSpan disapear on extreme zoom in

- src/ScottPlot/Plot/Plot.Add.cs
- src/ScottPlot/Plot/Plot.Obsolete.cs
- src/ScottPlot/Plottable/Colorbar.cs
- src/ScottPlot/Plottable/Heatmap.cs
- src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/Colorbar.cs
- src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/Heatmap.cs
- src/tests/PlottableRenderTests/Colorbar.cs
Previously colorbar rendering was achieved inside the heatmap module. This PR gives colorbar its own plot type, and `AddColorbar()` can be called on any plot. This addresses #678
The colorbar could benefit from continued refinement/refactoring (especially the tick system), but this is a strong start.
```cs
var hm = plt.AddHeatmap(intensities);
var cb = plt.AddColorbar(hm.Colormap);
cb.SetTicks(hm.ColorbarMin, hm.ColorbarMax);
```
This PR also makes some changes suggested by #680
> Colorbar Plottable

- src/ScottPlot/Statistics/Common.cs
- src/cookbook/ScottPlot.Cookbook/Recipes/Misc.cs
- src/tests/Statistics/OrderStatistics.cs
**Purpose:**
An ith order statistic is an element of an array that is the ith smallest value. It is a generalization of the min (the 0th order statistic*), the max (the last order statistic), the median (the n/2 th order statistic), as well as all quantiles.
I also added a test for the selection algorithm. It validates the algorithm against naïve algorithm (sorting and then indexing) for a large array of doubles.
*it is the 1st order statistic if you index from one. The algorithm I implemented indexes from zero.
Describe what this pull request does using code and/or images.
```cs
double nthOrderStatistic = …
```
> Used QuickSelect to add a NthOrderStatistic method

- src/ScottPlot/Plottable/VectorField.cs
**Purpose:**
In [this block](https://github.com/ScottPlot/ScottPlot/blob/master/src/ScottPlot/Plottable/VectorField.cs#L26-L39) we compute the min and max length of all the vectors. However, it mixes `Length` and `LengthSquared`, which means it can get incorrect min or max values. I changed line 26 and 27 to remove this concern.
In this case, it would only happen if the first vector was the min or the max, and it would give an incorrect min for magnitudes > 1, and an incorrect max for magnitudes < 1. (Because x^2 < x for x < 1)
N/A
> Don't mix Length and LengthSquared in VectorField

- src/ScottPlot/Statistics/Finance.cs
- src/tests/Finance/TechnicalIndicators.cs
The calculation must include the current period `values[i]`.
If `period` have a value of 3, it's copying `values[i-3]`,`values[i-2]`,`values[i-1]` to `periodValues[]`
but it should copy `values[i-2]`,`values[i-1]`,`values[i-0]`
> Fix SMA() and SMStDev() calculation

- src/ScottPlot/Renderable/Axis.cs
- src/ScottPlot/Renderable/AxisTicksRender.cs
- src/cookbook/ScottPlot.Cookbook/Recipes/Axis.cs
**Purpose:**
This is #706 but cherry-picked to remove the collapsing of invisible axes.
ditto
> Improve support for rotated tick labels

- src/ScottPlot/ScottPlot.csproj
- src/sandbox/WinFormsFrameworkApp/WinFormsFrameworkApp.csproj
This PR modifies the ScottPlot project to specifically target multiple platforms:
* .NET Framework 4.6.1
* .NET Standard 2.0
* .NET 5.0
Special packages are required for .NET Framework 4.6.1 and for MacOS so the csproj file has been modified to conditionally install those.
These topics are discussed in #691
> Multi-target ScottPlot.csproj

- src/ScottPlot/Control/Backend.cs
**Purpose:**
Referenced in https://github.com/ScottPlot/ScottPlot/issues/741#issuecomment-772740349
Currently when `Configuration.MiddleClickDragZoom` is disabled the rectangle will still be drawn, and it will not disappear upon release of the mouse. With this fix the rectangle will not be drawn at all.
N/A
> Fix Configuration.MiddleClickDragZoom and rendering artifact if Alt is lifted prematurely

- src/ScottPlot/Plottable/SignalPlotBase.cs
**Purpose:**
Fix for incorrect `PlottableSignal` rendering when using `MaxRenderIndex`. #744
> improve signal rendering when using maxRenderIndex (Fix #744)

- src/ScottPlot/Plot/Plot.Add.cs
- src/ScottPlot/Plottable/Colorbar.cs
- src/ScottPlot/Plottable/CoordinatedHeatmap.cs
- src/ScottPlot/Plottable/Heatmap.cs
- src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/Heatmap.cs
**Purpose:**
Allows to use an existing coordinate system to get additional coordinate information about `HeatMap`. #701
Additionaly Fix `ColorBar`, with this PR it will not affect AxisLimits calculation.
User can provide coordinated boundaries for provided rectangular distribution.
Missing bounds are calculated based on the size of the `intensities` array.
```cs
double[,] intensities = ....; 
var hmc = plt.AddHeatmapCoordinated(intensities, -100, 500, 200, 201);
var hmc1 = plt.AddHeatmapCoordinated(intensities, xMin: -100, yMax: 50);
```
> Add CoordinatedHeatmap

- src/ScottPlot/Plottable/Heatmap.cs
**Purpose:**
Current `Heatmap` implementation render wrong on the edges, This is especially noticeable at small `Heatmaps`.
This PR setup additional params for Graphics.DrawImage() to make correct edges render.
Also more accurate pixel calculation were done, as result `Heatmap` perfect align with axis grid.
Negative side: I remove minScale calculation, as result `Heatmap` cells may be not square if `EqualAxis` will be disabled.
All Demo already have equal axis scales, and additional math not needed.
Old version (incorrect)  3x2 HeatMap from cookbook:
The same demo with this PR:
> Heatmap edges fix

- src/ScottPlot/Plottable/ScatterPlot.cs
**Purpose:**
Implement `MinRenderIndex` and `MaxRenderIndex` for ScatterPlot. #737
API implemented based on the existing stub. Feel free to change.
The unresolved question was what to do when `XS` and `YS` arrays were changed, whether to change `Indexes` automatically or leave it to the user's discretion. Current second option.
A demo is also required for this mode...
```c#
double[] xs = DataGen.Consecutive(51);
double[] sin = DataGen.Sin(51);
double[] cos = DataGen.Cos(51);
var scatter = plt.AddScatter(xs, sin);
scatter.MinRenderIndex = 12;
scatter.MaxRenderIndex = 42;
```
> Scatter min/max render indexes

- src/ScottPlot/Plot/Plot.Axis.cs
**Purpose:**
Fix typo in `EqualAxis` migration tip.
> Fix typo in migration tip.

- dev/devops/azure-pipelines.yml
- src/ScottPlot/Drawing/Colormap.cs
- src/ScottPlot/Drawing/ColormapFactory.cs
- src/tests/Colormap/Colormap.cs
- src/tests/Colormap/ColormapFactoryTests.cs
**Purpose:**
Extends Colormap API with `ColormapFactory` class. #767
`ColormapFactory` allow get available colormaps names without creating `Colormap` instances.
And then create only `Colormap` with requested name.
For adding new types of `IColormap` it needs manual add single line in `availableColormaps` dictionary initializer.
Failed pipline report:
`Unrecognized command or argument '--dry-run'
`
It looks like not my fault.
```cs
var factory = new ColormapFactory();
var names = factory.GetAvailableNames();
var lastColorMap = factory.Create(names.Last());
var oxyColormap = factory.Create("Oxy");
```
> Extend Colormap API

- src/ScottPlot/Plottable/ScatterPlotList.cs
**Purpose:**
Removes an unnecessary, performance-degrading `Console.WriteLine()` call inside the `ScatterPlotList`s `Render` method.
> Remove a Console.WriteLine() Call in ScatterPlotList.Render()

- src/ScottPlot/Plottable/DataStructures/SegmentedTree.cs
- src/tests/MinMaxSearchStrategies/SegmentedTreeMinMaxSearchStrategyTests.cs
**Purpose:**
Segmented tree sometimes (l - odd, or r - even) grabbed several additional elements to provided range querry.
This wrong values was close to provided range, Therefore, it was not so noticeable and avoid existed UnitTests.
All `Const` plottables was affected by this.
Thanks to the report from @AlgoExecutor #783,  this error has now been fixed.
> Fix Segmented tree wrong first layer calculation

- src/ScottPlot/Plottable/SignalPlotXYGeneric.cs
**Purpose:**
Fix SignalXY border glitch. #794 
It looks like the introducing `Dims.DataOffsetX` was not entirely painless for `SignalXY`.  
f337a8a fix did not take into account the fact that the points at the edges already had an increase in `DataOffsetX`, since they were obtained through `GetPixelX()`. As a result, edge interpolation went wrong and produced this result #794 .
For now all points( inluding `VisiblePoints` array) are initially calculated using `DataOffsetX`. and everything works as it should. No additional correction like f337a8a is required.
> Fix SignalXY border glitch

- src/ScottPlot/Plottable/FinancePlot.cs
- src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/Finance.cs
**Purpose:**
Fixes the drawing of "Doji" candlesticks (i.e. open == close) #800 
Adds a check for the Doji case and adds a red line where otherwise the candle body would not be drawn.
```cs
OHLC[] arr = DataGen.RandomStockPrices(new Random(0), 10);
arr[5] = new OHLC(arr[5].open, arr[5].high, arr[5].low, arr[5].open, arr[5].time); // Ensure a doji session exists
plt.AddCandlesticks(arr);
```
Before:
After:
> Improve small candlestick rendering and support custom wick color

- src/ScottPlot/Ticks/TickCollection.cs
**Purpose:**
OLE Automation date support negative values, and it's minimum value is midnight, 1 January 0100.##806
This PR allow to use negative values and expand avalable range.
> Add support of negetive OLE Automation Date values

- src/ScottPlot/Plottable/Tooltip.cs
**Purpose:**
Removes `Plottable.Tooltip` from `AxisAuto` calculations to fix #805 
From the demo provided in https://github.com/ScottPlot/ScottPlot/issues/805#issue-810258752:
Before:
After:
> Tooltip GetAxisLimits now returns all NaN instead of all zero

- src/ScottPlot/Plot/Plot.Add.cs
Adds bar to BarPlot array so it now returns an array of BarPlots instead of a null array.
**Purpose:**
Beforehand, calling AddBarGroups would result in it returning an array with a single null element in it as seen below:
All that had to be changed was actually adding the bar to the array within the loop! A nice quick fix and now I can change the styles of the bars in that group, which I wasn't able to do before. I created a quick extension method that copied the original with that addition and now you get the expected result:
> Updated Plot.Add.cs to return a correct array of BarPlots

- src/ScottPlot/Plot/Plot.Add.cs
**Purpose:**
#849 
Allows calling `AddHeatmap` with `double?[,]`. Null values are mapped to transparent.
```cs
double?[,] data2D = { { 1, null, 3 },
{ 4, 5, 6 } };
plt.AddHeatmap(data2D);
```
There is an overload for both `AddHeatmap` and `AddCoordinatedHeatmap`
> Adds AddHeatmap overload for double?[,]

- src/ScottPlot/Enums/Orientation.cs
- src/ScottPlot/Plot/Plot.Add.cs
- src/ScottPlot/Plot/Plot.Obsolete.cs
- src/ScottPlot/Plottable/BarPlot.cs
- src/ScottPlot/Plottable/BarPlotBase.cs
- src/ScottPlot/Plottable/ClevelandDotPlot.cs
- src/ScottPlot/Plottable/LollipopPlot.cs
- src/controls/ScottPlot.WPF/WpfPlot.xaml.cs
- src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/Bar.cs
- src/tests/PlotTypes/Bar.cs
- src/tests/PlottableRenderTests/Bar.cs
**Purpose:**
#817 
So far this only adds Lollipop plots because I'm still working on it.
I'm also unsure whether dot plots are worth the effort, dot plots offer no benefit compared to bar plots that I know of other than being easy to draw with typewriters or ASCII art. And adding dot plot support looks like it would be non-trivial if one wants to minimize the number of fractional dots drawn. If someone has a compelling use case I can come back to them.
```cs
double[] values = { 26, 20, 23, 7, 16 };
var bar = plt.AddBar(values);
bar.DisplayStyle = BarStyle.Lollipop;
bar.HorizontalOrientation = true;
```
> Dot, Lollipop and Cleveland Dot Plots

- src/ScottPlot/Plottable/PiePlot.cs
- src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/Pie.cs
**Purpose:**
#844 
A new `SliceLabelColors` array is exposed.
```cs
double[] values = { 778, 43, 283, 76, 184 };
string[] labels = { "C#", "JAVA", "Python", "F#", "PHP" };
var pie = plt.AddPie(values);
pie.SliceLabels = labels;
pie.ShowLabels = true;
pie.SliceFillColors = new Color[] { // From https://github.com/ozh/github-colors
Color.FromArgb(0x17, 0x86, 0x00),
Color.FromArgb(0xB0, 0x72, 0x19),
Color.FromArgb(0x35, 0x72, 0xA5),
Color.FromArgb(0xB8, 0x45, 0xFC),
Color.FromArgb(0x4F, 0x5D, 0x95)
};
pie.SliceLabelColors = new Color[] { Color.White, Color.Silver, Color.Silver, Color.Silver, Color.Silver }; // Highlight the largest section
```
> Custom pie chart slice and label colors

- src/ScottPlot/Plot/Plot.Obsolete.cs
- src/ScottPlot/Plottable/IHasPoints.cs
- src/ScottPlot/Plottable/SignalPlotBase.cs
- src/ScottPlot/Plottable/SignalPlotXYGeneric.cs
- src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/Signal.cs
- src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/SignalXY.cs
**Purpose:**
`PlottableSignalXY` used the implementation from `PlottableSignal` due to inheritance, which led to inconsistent results when calling the `GetPointNearestX`. #809, #882
This PR brings to `PlottableSignalXY` it's own `GetPointNearestX` implementation with correct behavior.
This pull request consists of 2 commits. The very first one fixes the described problem.
In the second commit, I decided to go further, split the original interface into several, and make it so that `PlottableSignals` explicitly implement only what it is capable of `IHasPointsXCalculatable` with a single `GetPointNearestX()` method
On top of that, I made interfaces generic, since signals inherently support generics and this is more natural for them.
Old nongeneric `IHasPoints` are derived from these …
> Improve GetPointNearest support for generic signal plots

- src/ScottPlot/Plottable/SignalPlotXYGeneric.cs
**Purpose:**
Fix for `SignalXY` wrong clipping on right edge. https://github.com/ScottPlot/ScottPlot/issues/889#issuecomment-803582419
The problem was not at incorrect clipping, but that `float` `DataWidth`, when cast to `int`, is not correctly rounded. thus, for example, with a width of `627.998`, a simple conversion to int gives 627 instead of 628.
And the points that should have gotten into the last column did not get there. as a consequence, interpolation did not go from the last point of the last column, but from the last point of the previous colomn. Which gave such an effect if points in last and previous columns had many difference.
In general, it is very strange to use `float` variable for the pixels count, a quick glance at the project showed that cast to int is still used in …
> Fix SignalXY right edge clipping bug

- src/ScottPlot/Plottable/SignalPlotXYGeneric.cs
**Purpose:**
Implement OffsetX/OffsetY support for SignalXY.#890
The implementation is in its simplest form, it will be possible to use precompiled lambdas in the future. But I don't like the offsetX / offsetY approach itself, so I would like to discuss its necessity before moving on.
```cs
var sig = plt.AddSignalXY(xs, ys);
sig.OffsetX = 10_000;
sig.OffsetY = 100;
```
> Implement OffsetX/OffsetY support for SignalXY.

- src/ScottPlot/Control/Backend.cs
- src/ScottPlot/Settings.cs
Don't deploy right-click menu if the right mouse button was dragged a large distance and returned to its original location
> track click-drag travel distance #891

- src/ScottPlot/Renderable/Axis.cs
- src/ScottPlot/Renderable/AxisTicksRender.cs
- src/ScottPlot/Ticks/TickCollection.cs
- src/cookbook/ScottPlot.Cookbook/Recipes/AxisAdvanced.cs
- src/tests/Ticks/DateTimeTickSpacing.cs
This PR addresses #725 by using the longest month name to calculate the width for tick labels when plotting on a DateTime axis.
This PR also addresses #828 by giving the tick collection the ability to change the density of tick labels.
Before|After
---|---
> improve DateTime tick spacing #725

- src/ScottPlot/Plottable/SignalPlotBase.cs
**Purpose:**
Fix wrong pen for Signal in low density mode. #929
> Fix wrong pen for Signal in low density mode.

- src/ScottPlot/Enums/EqualScaleMode.cs
- src/ScottPlot/Plot/Plot.Axis.cs
- src/ScottPlot/Settings.cs
- src/sandbox/WinFormsFrameworkApp/Form1.Designer.cs
- src/sandbox/WinFormsFrameworkApp/Form1.cs
**Purpose:**
This PR allow user to customize behaviour of EqualAxisScale mode. Discussed in detail in #857.
By default behavior stay as before.
But `Settings` have 2 additional fields `EqualScaleUseX = true` and `EqualScaleUseY=true`.
If User disable one of them, then remain axis only used for `EqualScale` calculation. 
This close to old behavior used in `EqualScale` on `Control` level.
```c#
Plot.AxisScaleLock(true); // stay as it was
Plot.AxisScaleLock(true, false, true); // YAxisScale used for EqualAxisScale calculation, old `Control` behavior
```
> Allow user to select axises used for scale calculation for EqualScale mode

- src/ScottPlot/Tools.cs
**Purpose:**
- Refactors `XYToIntensities` and adds comments
- Adds support for different decimal points in `ToDifferentBase` 
- You can get the decimal separator of a locale with `CultureInfo.NumberFormat.NumberDecimalSeparator`
- However it looks like axes with non-decimal radixes has been removed, so this may be immaterial unless you want to move to reimplement it
N/A
> Minor houskeeping on ScottPlot.Tools

- src/ScottPlot/Control/Configuration.cs
- src/ScottPlot/Control/EventProcess/Events/MouseScrollEvent.cs
- src/tests/Control/ConfigurationTests.cs
**Purpose:**
Allow user to setup mouse wheel zoom speed. #937
Introduce new `ScrollWheelZoomIncrement` property for `Control.Configuration`.
Available range is (0, 1).
`0.15` default value match to previous behaviour.
```cs
Control.Configuration.ScrollWheelZoomIncrement = 0.01; // very slow mouse wheel zoom
Control.Configuration.ScrollWheelZoomIncrement = 0.5 // fast mouuse wheel zoom
Control.Configuration.ScrollWheelZoomIncrement = 0.15 // default value
```
> Allow user to customize mouse wheel Zoom speed.

- dev/devops/azure-pipelines.yml
- src/ScottPlot/plottables/PlottableScatter.cs
- src/autoformat.bat
**Purpose:**
#948 
I don't know how you feel about backporting fixes to 4.0.x right now, I guess it depends on how soon you plan to release 4.1. In my opinion, even if you released 4.1.0 tomorrow trivial fixes like this should continue for at least a little while because 4.0 -> 4.1 does entail a sizeable number of breaking changes, even if many of them can be alleviated by search and replace. This is made easier by the fact that 4.0.48 seems pretty stable, so it shouldn't be too difficult to maintain.
The only difficulty is that 4.0.x and 4.1.x have different directory structures and the solution file has a different name. Which means you have to close Visual Studio and …
> 4.0.x Fixes crash with ScatterPlots containing a single point

- src/ScottPlot/Plot/Plot.Add.cs
- src/ScottPlot/Plot/Plot.Obsolete.cs
- src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/Heatmap.cs
**Purpose:**
#955 
This renaming preserves the previous method signature but marks it as obsolete. The warning points to the new method.
I also used ` [EditorBrowsable(EditorBrowsableState.Never)]` so that IDEs which respect this attribute will not show it in code completion. Note it will always be shown on the ScottPlot assembly, but not in projects which use the library. I think this attribute can be controversial, I'm using it here because the previous method signature is nearly identical and does the same thing, which can make the two difficult to differentiate. I wouldn't use this attribute on obsolete methods like `PlotHeatmap` because that method does actually do …
> AddHeatMapCoordinated → AddHeatmapCoordinated

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/question-about-scottplot.md
**Purpose:**
I've noticed that a lot of recent issues have stemmed from users attempting to use ScottPlot 4.1 methods in 4.0 or vice versa. 
Additionally, when answering a lot of questions one has to preface them with "If you're using 4.1.x do ... If you're using 4.0.x do ...". This also happens to a lesser degree when answering GUI questions, one has to modify their answer for WinForms or WPF or Avalonia.
I think to help mitigate this we should edit the issue templates so that they ask the user for this information up front. I modified the `bug_report` and the `question-about-scottplot` templates to ask for this information:
- ScottPlot version
- Operating System
- …
> Adds request for environment info on applicable issue templates.

- src/ScottPlot/Statistics/Histogram.cs
- src/cookbook/ScottPlot.Cookbook/Recipes/Statistics.cs
addresses #930 and #932 by adding a `Histogram.probability` field and improving cookbook examples
> Improve Histogram probability calculation and documentation

- src/demo/ScottPlot.Demo.Avalonia/MainWindow.axaml
**Purpose:**
Fixes a tiny visual issue in the Avalonia Demo. Note the left margin on the title, and that the "Website" button is no longer cut off.
Before:
After:
> Fixes visual issue in Avalonia Demo with incorrect left margin

- src/controls/ScottPlot.Avalonia/ScottPlot.Avalonia.NUGET.csproj
- src/controls/ScottPlot.Avalonia/ScottPlot.Avalonia.csproj
- src/demo/ScottPlot.Demo.Avalonia/Avalonia Demo.csproj
**Purpose:**
Avalonia versions go from 0.10.0 -> 0.10.2
(0.10.1 does exist but they released a new version a few hours later to undeprecate something: https://github.com/AvaloniaUI/Avalonia/discussions/5820)
N/A
> Bump Avalonia versions to 0.10.2

- src/ScottPlot/ScottPlot.csproj
- src/controls/ScottPlot.WPF/ScottPlot.WPF.csproj
- src/sandbox/WinFormsFrameworkApp/WinFormsFrameworkApp.csproj
- src/sandbox/WinFormsFrameworkApp/packages.config
This PR rolls System.Drawing.Common package from version 5 to version 4.6.1 to match the minimum supported version of .NET Framework and reduce pain associated with downgrading from version 5 to 4 
A detailed description is in #1004
> System.Drawing.Common version downgrade

- src/ScottPlot/Plottable/SignalPlotXYGeneric.cs
**Purpose:**
Allow to customize `LineStyle` for `SignalXY`.
Although changing the style from a solid gives an incorrect result, it happens that someone really needs it #1016.
Works for now:
```cs
SignalXY.LineStyle = LineStyle.Dash;
```
> Allow to customize LineStyle for SignalXY

- src/ScottPlot/Control/Backend.cs
- src/ScottPlot/Control/EventProcess/Events/RenderDelayedHighQuality.cs
- src/ScottPlot/Control/EventProcess/Events/RenderHighQuality.cs
- src/ScottPlot/Control/EventProcess/Events/RenderLowQuality.cs
- src/ScottPlot/Control/EventProcess/EventsProcessor.cs
- src/ScottPlot/Control/EventProcess/RenderType.cs
- src/ScottPlot/Control/QualityConfiguration.cs
- src/ScottPlot/Enums/RenderType.cs
- src/controls/ScottPlot.Avalonia/AvaPlot.axaml.cs
- src/controls/ScottPlot.WPF/WpfPlot.xaml.cs
- src/controls/ScottPlot.WinForms/FormsPlot.cs
**Purpose:**
It is useful enough to provide the user with the ability to manually update Plot using the RenderQueue. #1032
This PR redirects all available rendering methods from the backend to controls.
- RenderLowQuality()
- RenderHighQuality()
- RenderDelayedHighQuality()
- RenderLowThenImmediateHighQuality() - already present
Avalonia control was left without these possibilities, I'm afraid to break something there because I have no experience.
```cs
formsPlot1.RenderHighQuality();
formsPlot1.RenderLowQuality();
formsPlot1.RenderDelayedHighQuality();
```
> Add RenderRequest() to controls for non-blocking rendering

- dev/changelog.md
- src/ScottPlot/Plottable/FinancePlot.cs
**Purpose:**
I added in your suggested change from #827. Have been building it locally with my own project that uses ScottPlot and it works great!
Adds the following to `FinancePlot.cs`:
```cs
public OHLC Last() => OHLCs.Last();
```
This allows users to mutate the last item of the list, allowing for realtime plotting updates.
**Notes:**
Although, I am unable to horizontally zoom the plot. Maybe the key bindings from that type of zoom have been changed in the beta, but that is unrelated.
I don't think I am being much help here since you already proposed the change, but at the very least I am using it and it works!
Thanks for the project, it's one of the few C# graphing libraries that has what I need and doesn't make me pay for it :)
> Allow realtime updates of OHLC plots

- dev/changelog.md
- src/controls/ScottPlot.Avalonia/AvaPlot.axaml.cs
- src/controls/ScottPlot.WPF/WpfPlot.xaml.cs
- src/controls/ScottPlot.WinForms/FormsPlot.cs
**Purpose:**
#1073 
I tested this by simply hiding the `PlotImage` to see if anything was behind it, rather than trying to replicate the styling.
N/A
> Prevent designer error messages from showing in non-error conditions

- src/tests/Misc/Drawing.cs
tests ensure characters don't render as rectangles #1079
> font render tests

- dev/changelog.md
- src/ScottPlot/Plottable/AxisLine.cs
- src/ScottPlot/Plottable/AxisSpan.cs
- src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/AxisLineAndSpan.cs
- src/tests/PlottableUnitTests/AxisLineAndSpanTests.cs
Adds `IgnoreAxisAuto` field to axis lines and spans so their positions are ignored when automatically resetting axis limits to fit the data (by calling `AxisAuto()` or middle-clicking a control).
Addresses one of the issues raised in #999
> add IgnoreAxisAuto field to axis lines and spans

- dev/changelog.md
- src/ScottPlot/Control/Backend.cs
- src/ScottPlot/Control/Configuration.cs
- src/ScottPlot/Plot/Plot.cs
- src/ScottPlot/Settings.cs
- src/controls/ScottPlot.Avalonia/AvaPlot.axaml.cs
- src/controls/ScottPlot.WPF/WpfPlot.xaml.cs
- src/controls/ScottPlot.WinForms/FormsPlot.cs
- src/sandbox/WinFormsFrameworkApp/Form1.Designer.cs
- src/sandbox/WinFormsFrameworkApp/Form1.cs
- src/tests/Control/ConfigurationTests.cs
fixes #1087
* backend configuration's `RenderIfPlottableCountChanges` is now `RenderIfPlottableListChanges`
* automatic render detection is no longer based on the length of `Plottables`
* `Plottables` is now an `ObservableCollection` instead of a `List`
> 1087 auto render

- dev/changelog.md
- src/ScottPlot/Plot/Plot.Add.cs
- src/ScottPlot/Plottable/RadarPlot.cs
**Purpose:**
Pull request for issue [#1086](https://github.com/ScottPlot/ScottPlot/issues/1086)
**New functionality:**
Implements an `Update()` method.
The class initializer calls this `Update()` method.
`Norm`, `NormMax`, and `NormMaxes` are no longer `readonly`.
Added documentation.
Suggestions (as comments) for leaving out the `Array.Copy` as well as for moving the normalization to the `Render()` method.
> 1086 Implement an update method in RadarPlot

- dev/changelog.md
- src/ScottPlot/Renderable/Axis.cs
- src/ScottPlot/Ticks/TickCollection.cs
- src/cookbook/ScottPlot.Cookbook/Recipes/AxisAdvanced.cs
- src/tests/Axis/TickLabel.cs
This PR adds an option for the user to use a `Func<double, string>` to define how to generate tick labels from positions. 
Unlike current methods which only control the _format_ of labels or require the user to interact with a complex inheritance system, this is a quick and simple way to control tick label format in a way that uses logic.
```cs
plt.AddSignal(ScottPlot.DataGen.Sin(51));
plt.AddSignal(ScottPlot.DataGen.Cos(51));
static string customTickFormatter(double position)
{
if (position == 0)
return "zero";
else if (position > 0)
return $"+{position:F2}";
else
return $"({Math.Abs(position):F2})";
}
plt.XAxis.TickLabelFormat(customTickFormatter);
plt.YAxis.TickLabelFormat(customTickFormatter);
```
This PR was motivated by #926 and #1070
> Axis: TickLabelFormat accepts Func<double, string>

- src/ScottPlot/Plottable/SignalPlotBase.cs
- src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/Signal.cs
**Purpose:**
Step Display is very useful to show digital signals. 
**New Functionality:** This PR implements #1092
- added function for `StepDisplay` (take-over from Scatter Plot)
- added Cookbook example
- all tests are passing
> Implemented Step Signal Plot

- src/tests/Documentation/DocumentationTests.cs
**Purpose:**
The current documentation tests are not very informative, they do not show which method is missing documentation.
This PR adds a message indicating the method/field/class name in which there is no xml documentation.
> Add hints for failed documentation tests.

- dev/changelog.md
- src/ScottPlot/Plottable/Crosshair.cs
- src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/Crosshair.cs
**Purpose:**
Current Crosshair implementation doesn't work well when you want to attach it to Right or Top axis. 
After setting YAxisIndex to 1, I would expect the label with the value on the right axis. 
After setting XAxisIndex to 1, I would expect the label with the value on the top axis. 
This Pull Request contains a small fix to handle this case.
Below is the code of a sample recipe for multiple crosshairs attached to different axes.
```cs
public class CrosshairMultipleForDifferentAxes : IRecipe
{
public string Category => "Plottable: Crosshair";
public string ID => "crosshair_multiple_different_axes";
public string Title => "Multiple crosshairs for different axes";
public string Description => "Chrosshair for right and top axis";
public void ExecuteRecipe(Plot plt)
{ …
```
> Improve multi-axis support for crosshair labels

- dev/changelog.md
- src/ScottPlot/Control/Backend.cs
- src/sandbox/WinFormsFrameworkApp/Form1.cs
This PR fixes a bug where fast-drag-dropping a plottable would cause unexpected placement or unintended panning in addition to missing a final render. This PR fixes #1076
> Drag processing

- dev/changelog.md
- src/ScottPlot/Plottable/ClevelandDotPlot.cs
**Purpose:**
Fixes the axis limits calculations for ClevelandDotPlot, where a small typo was accidentally introduced in fc1ecbdd9c240d5ca6433fedb7bcb90bfa30f8b0.
None
> ClevelandDotPlot: Fix typo in GetAxisLimits()

- src/autoformat.sh
**Purpose:**
Creates an `autoformat.sh` script, just like there's an `autoformat.bat` script. Note that the bash script doesn't pause until the user presses a key, as I don't know why that was there in the first place.
Linux and Mac users can now use an autoformat script.
We could consider creating a `ps1` script as well, but I don't know if that's necessary or not. Although PowerShell is cross-platform now.
> Creates bash script for autoformatting

- src/demo/ScottPlot.Demo.Avalonia/AvaloniaDemos/MultiAxisLock.axaml
- src/demo/ScottPlot.Demo.Avalonia/AvaloniaDemos/MultiAxisLock.axaml.cs
- src/demo/ScottPlot.Demo.Avalonia/MainWindow.axaml
- src/demo/ScottPlot.Demo.Avalonia/MainWindow.axaml.cs
**Purpose:**
#1210
Adds multi-axis lock demo for Avalonia. There are some bigger changes from the WPF version as Avalonians normally do MVVM with observables, often with `INotifyPropertyChanged`, not event handlers. This is because event handlers can be fired before the data context is updated. So generally event handlers are used only for code-behind where you're setting the value in the handler. I think most Avalonia users use something like ReactiveUI so their viewmodels are less verbose.
> Demo (Avalonia): Multi-Axis Lock

- dev/changelog.md
- src/ScottPlot/Renderable/AxisTicksRender.cs
- src/tests/Axis/RotatedTicks.cs
fixes #1201
```cs
plt.YAxis2.TickLabelStyle(rotation: 45);
```
default | rotated | ruler
---|---|---
> Improved tick label rotation

- dev/changelog.md
- src/ScottPlot/Plottable/ScatterPlot.cs
- src/tests/PlottableRenderTests/Scatter.cs
**Purpose:**
Fixes bug #1237.   
It appears that there was a copy/paste from the XError to the YError section of the GetAxisLimits method on ScatterPlot.  Some of the code was fixed to have y instead of x, but one case was missed.
Test that illustrates the issue (if the other change is backed out) is included in this PR.
> ScatterPlot: Fix YError data limit bug

- dev/changelog.md
- src/ScottPlot/Coordinate.cs
- src/ScottPlot/Enums/ArrowAnchor.cs
- src/ScottPlot/Markers.cs
- src/ScottPlot/Pixel.cs
- src/ScottPlot/Plot/Plot.Add.cs
- src/ScottPlot/PlotDimensions.cs
- src/ScottPlot/Plottable/ArrowCoordinated.cs
- src/ScottPlot/Plottable/ScatterPlot.cs
- src/ScottPlot/Plottable/VectorField.cs
- src/ScottPlot/Renderable/ArrowStyle.cs
- src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/Arrow.cs
- src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/VectorField.cs
- src/tests/PlotTypes/Arrow.cs
- src/tests/PlottableRenderTests/Scatter.cs
* abstracts styling/rendering of arrows in the VectorField plot type
* creates `ScottPlot.Coordinate` and `ScottPlot.Pixel` types
* creates a new `ArrowCoordinated` plot type
* deprecates arrow functionality from scatter plots
This PR resolves #1228 and #1241
> Arrow plot type

- dev/changelog.md
- src/ScottPlot/Plottable/RadarPlot.cs
**Purpose:**
This pull request intends to give RadarPlot users the option to show category labels instead of it being shown when IndependentAxes property is set to true. Solves #1261
There is no new functionality apart from giving the RadarPlot users direct control whether to show category labels or not.
> Radar: ShowCategoryLabels

- dev/changelog.md
- src/ScottPlot/Plottable/RadialGaugePlot.cs
**Purpose:**
Avoid division by zero when computing rotational angles.
https://github.com/ScottPlot/ScottPlot/blob/83b3da7ad94779780c59eda9cc02d4552c4d931c/src/ScottPlot/Plottable/RadialGaugePlot.cs#L184
Sometimes, the values fed to RadialGauge plot could be equal to 0. That would be the case when the user is plotting data from a sensor and, for some reason, no data is received (all values would be 0). In that case, division by zero must be avoided and a value of 0 degrees must be assigned to each gauge.
```cs
double angleSwept = 0;
if (scaleRange > 0)
angleSwept = angleRange * values[i] / scaleRange;
```
> RadialGaugue plot: division by zero

- dev/changelog.md
- src/controls/ScottPlot.Avalonia/AvaPlotViewer.axaml.cs
- src/controls/ScottPlot.WinForms/FormsPlotViewer.cs
- src/sandbox/WinFormsFrameworkApp/Form1.Designer.cs
- src/sandbox/WinFormsFrameworkApp/Form1.cs
Fixes bug caused by plot viewers not calling `Refresh()` after resetting the plot.
Interestingly the WpfPlot already made this call, so the fix affects only FormsPlot and AvaPlot.
Fixes #1283 and fixes #1264
> refresh after loading plot viewer

- dev/changelog.md
- src/ScottPlot/Palette.cs
- src/ScottPlot/Palettes/Tsitsulin.cs
- src/ScottPlot/Palettes/xgfs25.cs
**Purpose:**
* A qualitative 25-color palette based on Anton Tsitsulin (@xgfs)'s 12-color palette discussed [in his blog](http://tsitsul.in/blog/coloropt/).
* Regarding copyright and any related issue, I contacted Anton (September, 2nd) and he graciously allowed the use of his color palettes. We quickly agreed that a specific written license would be appropriate and he graciously added a license note stating: _specifically, assume public domain license on the colors_. At the time the license file was accessed (September 3rd, 2021) in the …
> Palette: Tsitsulin (25-colors)

- dev/changelog.md
- src/ScottPlot/Renderable/AxisTicks.cs
- src/ScottPlot/Renderable/AxisTicksRender.cs
- src/ScottPlot/ScottPlot.csproj
- src/ScottPlot/Ticks/TickCollection.cs
- src/controls/ScottPlot.Avalonia/ScottPlot.Avalonia.NUGET.csproj
- src/controls/ScottPlot.WPF/ScottPlot.WPF.NUGET.csproj
- src/controls/ScottPlot.WinForms/ScottPlot.WinForms.NUGET.csproj
**Purpose:** #1420 
Note that this will create minor ticks even if there are no major ticks on-screen (but the minor ticks may be above or below the drawn area).
> Always generate at least 2 major ticks (#1420)

- src/tests/Misc/OS.cs
This code block has been reported to throw an exception on Linux (#1431)
The CI system will test it on Windows, MacOS, and Linux
Closes #1431
> Test AxisAuto on Linux

- dev/changelog.md
- src/ScottPlot/Plottable/SignalPlotBase.cs
- src/tests/PlotTypes/Signal.cs
- src/tests/PlotTypes/SignalXY.cs
avoid draw 0px width or height rectangle, fix #1476
> SignalXY: improve support for fills with zero area

- dev/changelog.md
- src/ScottPlot/Renderable/Axis.cs
- src/ScottPlot/Renderable/AxisTicks.cs
- src/cookbook/ScottPlot.Cookbook/Recipes/AxisAdvanced.cs
```cs
plt.XAxis.TickMarkDirection(outward: false);
plt.YAxis.TickMarkDirection(outward: false);
```
Resolves #1475
> Add options to invert tick mark direction

- dev/changelog.md
- src/ScottPlot/Drawing/GDI.cs
- src/ScottPlot/Plottable/Text.cs
- src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/Text.cs
- src/tests/PlotTypes/Text.cs
before | after
---|---
fixes #1417
> Text: improve alignment

- dev/changelog.md
- src/ScottPlot/Plot/Plot.Axis.cs
- src/tests/Axis/MultiAxis.cs
```cs
var plt = new ScottPlot.Plot(600, 400);
plt.AddSignal(ScottPlot.DataGen.Sin(51));
plt.AddSignal(ScottPlot.DataGen.Cos(51));
var extraAxis = plt.AddAxis(ScottPlot.Renderable.Edge.Left, axisIndex: 2);
plt.SaveFig("a.png");
plt.RemoveAxis(extraAxis);
plt.SaveFig("b.png");
```
additional axis | removed
---|---
resolves #1458
> Plot.RemoveAxis()

- dev/changelog.md
- src/ScottPlot/Plot/Plot.cs
- src/ScottPlot/Renderable/Message.cs
- src/tests/Benchmark/Scatter.cs
`Plot.BenchmarkTimes()` now returns an array of recent frame render times suitable for averaging
resolves #1493
> Plot: BenchmarkTimes()

- dev/changelog.md
- src/ScottPlot/Renderable/Axis.cs
- src/tests/Axis/LogAxis.cs
> Ticks: disabling log scaling should disable integer rounding

- src/controls/ScottPlot.WPF/ScottPlot.WPF.NUGET.csproj
- src/controls/ScottPlot.WPF/ScottPlot.WPF.csproj
- src/controls/ScottPlot.WinForms/ScottPlot.WinForms.NUGET.csproj
- src/demo/ScottPlot.Demo.Eto/Eto.Forms Demo.csproj
- src/sandbox/EtoApp/EtoApp.csproj
* Adds more targets and adjusts target order to improve support in .NET 6 and VS 2022
* Also silences Eto warnings about dependency version mismatches (#1438)
resolves #1500
> csproj: improve TargetFrameworks

- dev/changelog.md
- src/ScottPlot/Drawing/GDI.cs
- src/ScottPlot/ScottPlot.csproj
- src/controls/ScottPlot.Avalonia/ScottPlot.Avalonia.NUGET.csproj
- src/controls/ScottPlot.Eto/ScottPlot.Eto.NUGET.csproj
- src/controls/ScottPlot.WPF/ScottPlot.WPF.NUGET.csproj
- src/controls/ScottPlot.WinForms/FormsPlot.cs
- src/controls/ScottPlot.WinForms/ScottPlot.WinForms.NUGET.csproj
- src/sandbox/WinFormsApp/Form1.Designer.cs
- src/sandbox/WinFormsApp/Form1.cs
- src/tests/FontsTests.cs
This PR sets default text rendering hint to anti-alias, revering the ClearType default set in #1496. 
This PR also exposes `ScottPlot.Drawing.GDI.ClearType()` to let the user opt-in to clear type.
Related: #1553, #1550
> Text rendering: opt-in to ClearType (anti-alias by default)

- dev/changelog.md
- src/ScottPlot/Control/Backend.cs
- src/ScottPlot/Control/EventProcess/Events/PlottableDragEvent.cs
- src/ScottPlot/Plot/Plot.Axis.cs
- src/controls/ScottPlot.WinForms/FormsPlot.cs
- src/demo/ScottPlot.Demo.WinForms/WinFormsDemos/MultiAxisLock.cs
- Former behavior only worked for `AxisIndex` 0
This PR is related to the discussion on #1545 
There is still work to generalize this to other axis indexes, but I don't know to reach other axes at the moment.
> Fix - Support for draggable plottables on `AxisIndex` 0 and 1

- dev/changelog.md
- src/ScottPlot/Plottable/DraggableMarkerPlot.cs
- src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/Marker.cs
- `DraggableMarkerPlot` is a `MarkerPlot` that can be dragged through a `Plot`. This can serve as a *static* way to pinpoint a location on the axes. By *static* I mean that does not move with the mouse unless dragged
- `DraggableMarkerPlotInVector` behaves somewhat similar to as `ScatterPlot` that in addition has a draggable point. When you drag the point, it goes to the coordinates in the vector closest to the mouse position.
> New plottables - `DraggableMarkerPlot` and `DraggableMarkerPlotInVector`

- dev/changelog.md
- src/ScottPlot/Settings.cs
This PR fixes #1537 to preserve the aspect ratio between axes during a Zoom.
In fact, the current behavior seems in contradiction with the fact that by default axes limits are free and should (to my understanding) be affected in the same manner by the drag zoom, regardless of the axis.
> Fix - `MouseZoomRect` affects all axes

- dev/changelog.md
- src/ScottPlot/Plottable/ScatterPlotDraggable.cs
- src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/Scatter.cs
This PR implements the functionnalities described in #1422.
The code inherits `ScatterPlot` and `IDraggable` to reduce code duplication
Two additional options (both true by default) are provided in addition to `DragEnabled`
- `DragEnabledX` : allows to free/lock horizontal drag of the scatter points
- `DragEnabledY` : allows to free/lock vertical drag of the scatter points
> New plottable : `ScatterPlotDraggable`

- dev/changelog.md
- src/ScottPlot/Plot/Plot.Axis.cs
When plot is empty meaning no `plottable in GetPlottables()` then the returned limits have the initial values:
https://github.com/ScottPlot/ScottPlot/blob/a214b94102c107db3799197655b5255c464c7eda/src/ScottPlot/Plot/Plot.Axis.cs#L355-L358
Now, if the user calls:
```cs
AxisLimits limits = formsPlot1.Plot.GetDataLimits();
formsPlot1.Plot.SetOuterViewLimits(limits.XMin, limits.XMax, limits.YMin, limits.YMax);
```
if is not possible to interract with the plot anymore (zoom, pan, etc.) beacause the limits set are flipped. This PR fixes the returned limits to the correct ones.
> Fix bug on `GetDataLimits` when plot is empty

- dev/changelog.md
- src/ScottPlot/Plottable/AxisLineVector.cs
- src/ScottPlot/Plottable/RepeatingAxisLine.cs
- src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/AxisLineAndSpan.cs
This PR implements some missing features from #1557 
- `AxisLineVector` now has an example in the cookbook and is draggable as a `ScatterPlotDraggable`
- The bug making `PositionLabel`s disappearing is fixed
> 1557 plottable repeatingaxisline continued

- dev/changelog.md
- src/ScottPlot/Plot/Plot.Axis.cs
This aims at solving #1584.
Implementation is based on https://github.com/ScottPlot/ScottPlot/issues/1584#issue-1110565204 and previous work in #1556
> `GetPixel` : Support of arbitrary `AxisIndex`

- dev/changelog.md
- src/ScottPlot/Plot/Plot.Add.cs
- src/ScottPlot/Plottable/Heatmap.cs
> Heatmaps with custom X and Y sizing or positioning no longer call `AxisScaleLock()` automatically

- dev/changelog.md
- src/ScottPlot/PlotDimensions.cs
- src/ScottPlot/Plottable/Text.cs
- src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/Text.cs
This PR implements drag functionality for `Text` plottables. 
The current `isUnderMouse` test fails, but that seems internal to GDI. 
Another implementation, not pushed though, works fine using this test 
https://math.stackexchange.com/questions/190111/how-to-check-if-a-point-is-inside-a-rectangle
~This PR also contains a patch for `GetCoordinateY` in 650f60e29f3d405331d84a1ac344791ca68fbab7~ _EDIT: moved to #1625/#1626_
> Text: implement IDraggable

- src/ScottPlot/Renderable/Axis.cs
- src/tests/Plot/Frameless.cs
resolves #1605
... although _technically_ there is a 1-pixel area on the upper and left edge which does not render plot graphics. This is due to clipping. It probably does not need to be fixed, but if so I think the fix is to adjust the `GDI.Graphics()` call and have it clip 1 pixel upward and to the left
> Frameless: remove 3px border

- dev/changelog.md
- src/ScottPlot/Plottable/BubblePlot.cs
- Added `GetPointNearest`, `GetPointNearestX` and `GetPointNearestY` to `BubblePlot`
- I believe the code should be working, and it seems a good adaptation from `ScatterPlot`s but I had noting to test it.
Resolves #1652
> BubblePlot: Add methods to get the bubble nearest the mouse

- dev/changelog.md
- src/ScottPlot/Plottable/BubblePlot.cs
- src/tests/PlotTypes/BubblePlot.cs
**Purpose:**
#1657 introduced an obvious out-of-range error. The index `i` reaches `Bubbles.Count`.
> BubblePlot: fix GetPointNearest calculations

- dev/changelog.md
- src/ScottPlot/Marker/MarkerTools.cs
- src/ScottPlot/Plottable/DraggableMarkerPlot.cs
- src/ScottPlot/Plottable/ErrorBar.cs
- src/ScottPlot/Plottable/IHasMarker.cs
- src/ScottPlot/Plottable/LegendItem.cs
- src/ScottPlot/Plottable/MarkerPlot.cs
- src/ScottPlot/Plottable/ScatterPlot.cs
- src/ScottPlot/Plottable/SignalPlotBase.cs
- src/ScottPlot/Renderable/Legend.cs
- src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/Marker.cs
This PR implements a `MarkerLineWidth` property and subsequent modifications to allow to change the stroke width of a marker. 
This is still a WIP.
Commit cea499473b3e44cc15f3f7fd0bf5df7294654f61 breaks the legend for pie chart and maybe other plot types. 
This **might** be the occasion to create a `IHasArea` interface handling all plots that are related (visually at least) to an area / surface with respect to `IHasLine`. This would avoid to use the `isRectangle` property in `Legend`.
Here is how looks the "All Markers" example with the new capabilities and `sp.LineWidth = 2 --> sp.LineWidth = i;`
> Marker markerlinewidth

- .gitignore
- src/ScottPlot4/ScottPlot/Renderable/Axis.cs
- src/ScottPlot4/ScottPlot/Renderable/AxisTicks.cs
- src/ScottPlot4/ScottPlot/ScottPlot.xml
- src/ScottPlot4/changelog.md
**Purpose:**
Fixes usage of `AxisTick.SnapPx` so that tick lines and lines appear crisp and clean, as intended.
See #1721
> Fix pixel snap

- src/ScottPlot4/ScottPlot.Cookbook/Recipes/Plottable/SignalXY.cs
- src/ScottPlot4/ScottPlot/Plottable/SignalPlotXYGeneric.cs
- src/ScottPlot4/changelog.md
**Purpose:**
#1763
This also fixes a similar issue where `LineWidth` of zero was ignored, as well as `LineStyle.None`.
> SignalXY respect marker settings

- src/ScottPlot4/ScottPlot.Avalonia/ScottPlot.Avalonia.NUGET.csproj
- src/ScottPlot4/ScottPlot.Eto/ScottPlot.Eto.NUGET.csproj
- src/ScottPlot4/ScottPlot.Sandbox/Notebook/ScottPlotQuickstart.ipynb
- src/ScottPlot4/ScottPlot.Tests/Plot/Render.cs
- src/ScottPlot4/ScottPlot.Tests/TestTools.cs
- src/ScottPlot4/ScottPlot.WPF/ScottPlot.WPF.NUGET.csproj
- src/ScottPlot4/ScottPlot.WinForms/ScottPlot.WinForms.NUGET.csproj
- src/ScottPlot4/ScottPlot/Plot/Plot.Render.cs
- src/ScottPlot4/ScottPlot/ScottPlot.csproj
- src/ScottPlot4/changelog.md
Adds `Plot.GetImageHTML()` to simplify inclusion of plots in .NET Interactive notebooks
resolves #1772
> Improve support for notebooks

- src/ScottPlot4/ScottPlot.Tests/PlotTypes/SignalXY.cs
- src/ScottPlot4/ScottPlot/Plot/Plot.Render.cs
- src/ScottPlot4/ScottPlot/Plottable/SignalPlotXYGeneric.cs
- src/ScottPlot4/ScottPlot/Settings.cs
- src/ScottPlot4/changelog.md
**Purpose:**
Fix for #1803 
SignalXY in some cases, due to rounding errors when converting to `PointF`, the `PointBefore` has the same x coordinate as the first drawn point. As a result, interpolation between these points results in an `Overflow Exception`. Although ScottPlot catches this exception and continues to work, it becomes impossible to display SignalXY.
Since interpolation between these points was introduced for only one reason - GDI does not correctly draw points with strongly negative coordinates. In our case, the error occurs when both points have a coordinate close to 0. Therefore, this fix simply skips interpolation if the x coordinates are equal, because it is definitely not needed in this case.
I decided to keep the test that I used to reproduce the error, but it can be …
> SignalXY: Fix bug where extrapolated pixel location could be infinity and crash GDI

- src/ScottPlot4/ScottPlot.Cookbook/Recipes/Axis.cs
- src/ScottPlot4/ScottPlot/Plot/Plot.Axis.cs
- src/ScottPlot4/ScottPlot/Plot/Plot.Render.cs
- src/ScottPlot4/ScottPlot/Plot/Plot.cs
- src/ScottPlot4/ScottPlot/Settings.cs
- src/ScottPlot4/changelog.md
**Purpose:**
#1779 
```cs
// You can insert code examples like this
plt.DrawGridAbovePlottables = true;
```
I have one small note about these changes, it doesn't technically draw just the grid lines after the plottables, it draws the entire axes after. This should be the same thing as I don't believe any other part of the axis can be drawn in the data area (or any plottables can be drawn outside the data area). Just a note in case that isn't a safe assumption.
> Plot: Allows drawing gridlines above the plottables

- src/ScottPlot4/ScottPlot.Tests/PlotTypes/SignalXY.cs
- src/ScottPlot4/ScottPlot/Plottable/SignalPlotBase.cs
- src/ScottPlot4/ScottPlot/Plottable/SignalPlotXYGeneric.cs
- src/ScottPlot4/ScottPlot/Validate.cs
- src/ScottPlot4/changelog.md
Hi @swharden,
I have tried to solve #1771 by validating X only between min/max render index.
Doing the check only between min/max render index in the setter didn't worked out very well:
- min/max render index must be set before
- before setting max render index Ys must be set
- min/max render index would have been added to `AddSignalXY` which then already started to look like the obsolete `PlotSignalXY`
Therefore I decided to only use the already present check in `ValidateData`.
> SignalPlotXY: defer ascending X check to ValidateData and only validate between min/max render index

- src/ScottPlot4/ScottPlot.WinForms/FormsPlot.cs
- src/ScottPlot4/ScottPlot/Plottable/Annotation.cs
- src/ScottPlot4/ScottPlot/Plottable/BubblePlot.cs
- src/ScottPlot4/ScottPlot/Plottable/Colorbar.cs
- src/ScottPlot4/ScottPlot/Plottable/CoxcombPlot.cs
- src/ScottPlot4/ScottPlot/Plottable/Crosshair.cs
- src/ScottPlot4/ScottPlot/Plottable/ErrorBar.cs
- src/ScottPlot4/ScottPlot/Plottable/FinancePlot.cs
- src/ScottPlot4/ScottPlot/Plottable/IPlottable.cs
- src/ScottPlot4/ScottPlot/Plottable/Image.cs
- src/ScottPlot4/ScottPlot/Plottable/PiePlot.cs
- src/ScottPlot4/ScottPlot/Plottable/RadarPlot.cs
- src/ScottPlot4/ScottPlot/Plottable/RadialGaugePlot.cs
- src/ScottPlot4/ScottPlot/Plottable/ScaleBar.cs
- src/ScottPlot4/ScottPlot/Plottable/Text.cs
- src/ScottPlot4/ScottPlot/Plottable/Tooltip.cs
- src/ScottPlot4/changelog.md
**Purpose:**
I tried solve #1791.
Fixed a `NullReferenceException` exception raised by right mouse click on a WinForms Plot with Crosshair.
> FormsPlot: Fix exception when right mouse clicking on a plot with Crosshair.

- src/ScottPlot4/ScottPlot/Control/Backend.cs
- src/ScottPlot4/changelog.md
**Purpose**
Middle-click-drag zooming was not working consistently for the Avalonia control. It would only actually zoom in about half the time.
**Details**
The difference in behavior between Avalonia and WinForms/WPF/Eto seems to be in the semantics of MiddleWasJustPressed. For the other platforms, MiddleWasJustPressed is essentially identical to IsMiddleDown when evaluated within Backend.MouseMove(). However, in the Avalonia implementation, MiddleWasJustPressed==true only within MouseDown. The result of MiddleWasJustPressed always being false in Backend.MouseMove() was that IsZoomingRectangle would toggle between true and false on each event when the middle button was down, causing the actual zoom to randomly fail 50% of the time when MouseUp() eventually fired.
I tried to streamline …
> Fix middle-click-drag zooming for Avalonia

- src/ScottPlot4/ScottPlot.Avalonia/AvaPlot.axaml.cs
- src/ScottPlot4/changelog.md
**Purpose:**
After adding this, double-clicking to toggle the benchmark display works correctly:
> Add double-click event handling to Avalonia control

- src/ScottPlot4/ScottPlot.Tests/Axis/TickLabel.cs
- src/ScottPlot4/ScottPlot/Renderable/Axis.cs
- src/ScottPlot4/changelog.md
I don't know if this is a bug, a wanted behaviour or a corner case which wasn't considered before.
I have a plot which is used to display one or more ScatterPlot series coming from different measures. Each measure has a different duration (from 2 minutes to 45 minutes), so I've added a checkbox to my WPF form in order to switch the X axis from normal to logarithmic. In this way, multiple series are displayed more clearly.
This means that I have to switch from a DateTime format X axis:
`simPlot.Plot.XAxis.TickLabelFormat("HH:mm:ss", true);`
to a logarithmix X axis with custom format:
`static string logTickLabels(double x) => DateTime.FromOADate(Math.Pow(10, x)).ToString("HH:mm:ss");
simPlot.Plot.XAxis.TickLabelFormat(logTickLabels);`
But I noticed that when switching the axis from the …
> Axis: improve support for switching between formatting strings and functions

- src/ScottPlot4/ScottPlot/Ticks/TickCollection.cs
- src/ScottPlot4/changelog.md
**Purpose:**
* Fixes a bug where manual tick labels were not reversed with the other labels
**Example:**
```c#
double[] positions = { Math.PI, 2 * Math.PI };
string[] labels = { "π", "2π" };
plt.XAxis.AutomaticTickPositions(positions, labels);
plt.XAxis.TickDensity(0.5);
plt.XAxis.TickLabelNotation(invertSign: true);
```
**Before:**
**After:**
> Fix inverted sign handling for additional axis ticks

- src/ScottPlot4/ScottPlot.Tests/PlotTypes/Bar.cs
- src/ScottPlot4/ScottPlot/Plottable/BarPlot.cs
- src/ScottPlot4/changelog.md
This PR clips rendering of large rectangles to the size of the data area to overcome limitations related to extremely large rectangles. Resolves #1849
> BarPlot: clip fills to data area

- src/ScottPlot4/ScottPlot/Plottable/BarPlotBase.cs
- src/ScottPlot4/ScottPlot/Plottable/Crosshair.cs
- src/ScottPlot4/changelog.md
**Purpose:**
#1855
There were two issues:
- `ValueOffsets` was not taken into account when calculating `ValueMin`
- `ValueOffsets` was not taken into account when ensuring the base of the bar was between `ValueMin` and `ValueMax`
The second one is a little hard to explain without referencing the code, but there used to be these two lines:
```cs
valueMin = Math.Min(valueMin, ValueBase);
valueMax = Math.Max(valueMax, ValueBase);
```
This calculation is incorrect because the base of the bar is really `ValueBase + ValueOffsets[i]`, so for non-zero `ValueOffsets[i]` you get incorrect results, such as with the following code:
```cs
double[] values = { 23, 17, 19, 24, 22 };
double[] yOffsets = { -100, -100, -100, -100, -100 }; // This is in the cookbook, but I think the better way to do this is …
```
> BarPlotBase: Fixes axis calculation.

- src/ScottPlot4/ScottPlot.Eto/PlotView.cs
- src/ScottPlot4/ScottPlot/Renderable/AxisTicksRender.cs
- src/ScottPlot4/changelog.md
**Purpose:**
#1848 
Replication (note that this doesn't quite match the code in #1848, as I don't have access to their data. I also shoehorned it into WPF for debugging)
```cs
var plt = WpfPlot1.Plot;
double[] ROParray = new double[] { 1, 0, -1, -2, -3 };
double[] RPMarray = new double[] { 1000, 1200, 1400, 1600, 1800 };
double[] iarray = new double[] { 1, 2, 3, 4, 5 };
var x3 = plt.AddAxis(ScottPlot.Renderable.Edge.Top, axisIndex: 2);
x3.Label("RPM");
x3.Ticks(true);
x3.Grid(true);
x3.SetSizeLimit(0, 300);
plt.XAxis.Ticks(false);
plt.XAxis.Grid(false);
plt.XAxis2.Ticks(true);
plt.XAxis2.Grid(true);
plt.YAxis.SetSizeLimit(-2, 2);
WpfPlot1.Refresh();
plt.Clear();
plt.AddScatter(ROParray, iarray, lineWidth: 2f, markerShape: ScottPlot.MarkerShape.none).XAxisIndex = 1; …
```
> Additional X Axes: Tick labels respect PixelOffset

- src/ScottPlot4/ScottPlot.Cookbook/Recipes/Plottable/Heatmap.cs
- src/ScottPlot4/ScottPlot/Plottable/Heatmap.cs
- src/ScottPlot4/changelog.md
**Purpose:**
#1864
```cs
double[,] data2D = { { 1, 2, 3 },
{ 4, 5, 6 } };
var hm = plt.AddHeatmap(data2D);
hm.FlipVertically = true;
```
> Heatmap: Adds FlipVertically to allow bottom-to-top drawing

- src/ScottPlot4/ScottPlot/Plottable/Bracket.cs
**Purpose:**
#1869
The same snippet as in #1869:
> Bracket: Use pixels for calculating normal vector

- src/ScottPlot4/ScottPlot.Cookbook/Recipes/Plottable/Image.cs
- src/ScottPlot4/ScottPlot.Tests/Plot/Image.cs
- src/ScottPlot4/ScottPlot.Tests/PlottableRenderTests/Image.cs
- src/ScottPlot4/ScottPlot/Plot/Plot.Add.cs
- src/ScottPlot4/ScottPlot/Plottable/Image.cs
- src/ScottPlot4/changelog.md
**Purpose:**
* Add axis dependent sizing. This can be used to draw a background.
* The alignment was ignored with non-zero rotation. I'm not sure if that's on purpose, but seems strange. So I fixed it.
* The border was not scaled with the image. Fixed in this PR.
* Also added tests for scale and sizing.
* Fixed some typos.
> Image: Add axis dependent sizing and bugfixes

- src/ScottPlot4/ScottPlot.Tests/PlotTypes/SignalXY.cs
- src/ScottPlot4/ScottPlot.Tests/TestTools.cs
- src/ScottPlot4/ScottPlot/Plottable/SignalPlotXYGeneric.cs
- src/ScottPlot4/changelog.md
before | after
---|---
resolves #1896
> SignalXY: only draw markers at original data points when step mode is enabled

- src/ScottPlot4/ScottPlot/Marker/MarkerTools.cs
- src/ScottPlot4/ScottPlot/Plottable/ScatterPlotList.cs
- src/ScottPlot4/ScottPlot/Plottable/SignalPlotBase.cs
- src/ScottPlot4/changelog.md
`.DrawMarkers()` was allocating a `SolidBrush` and a `Pen` without using them, this bug is fixed and now the `IMarker` is also reused.
Plots affected:
- Scatter
- Signal
- Error bar
Repro:
```cs
var rnd = new Random(Seed: 123);
var ys = Enumerable.Range(0, 500).Select(_ => rnd.NextDouble()).ToArray();
var xs = Enumerable.Range(0, 500).Select(_ => rnd.NextDouble()).ToArray();
var ctrl = new ScottPlot.FormsPlot { Dock = DockStyle.Fill };
var sPlot = ctrl.Plot.AddScatter(xs, ys);
for (int i = 0; i < 1; i++)
ctrl.Refresh();
```
|Points|Iters|Type|Alloc. before|Alloc. after|
|-|-|-|-|-|
|500|1|ScottPlot.MarkerShapes.FilledCircle|500|1|
|500|1|System.Drawing.Pen|525|25|
|500|1|System.Drawing.SolidBrush|509|9|
|500|100|ScottPlot.MarkerShapes.FilledCircle|51.500|103| …
> Reduce resources used to draw multiple markers

- src/ScottPlot4/ScottPlot.Cookbook/Recipes/Layout.cs
- src/ScottPlot4/ScottPlot/PixelPadding.cs
- src/ScottPlot4/ScottPlot/PixelRect.cs
- src/ScottPlot4/ScottPlot/Plot/Plot.Axis.cs
- src/ScottPlot4/ScottPlot/Settings.cs
- src/ScottPlot4/changelog.md
`Plot.ManualDataArea()` function allows users to define pixel-perfect layouts
* Resolves #1907
* Resolves #1901
> Plot.ManualDataArea for pixel-perfect layouts

- src/ScottPlot4/ScottPlot.Avalonia/ScottPlot.Avalonia.NUGET.csproj
- src/ScottPlot4/ScottPlot.Eto/ScottPlot.Eto.NUGET.csproj
- src/ScottPlot4/ScottPlot.Sandbox/WinFormsApp/Form1.Designer.cs
- src/ScottPlot4/ScottPlot.Sandbox/WinFormsApp/Form1.cs
- src/ScottPlot4/ScottPlot.Tests/NumericConversionTests.cs
- src/ScottPlot4/ScottPlot.WPF/ScottPlot.WPF.NUGET.csproj
- src/ScottPlot4/ScottPlot.WinForms/ScottPlot.WinForms.NUGET.csproj
- src/ScottPlot4/ScottPlot/NumericConversion.cs
- src/ScottPlot4/ScottPlot/Plottable/SignalPlotBase.cs
- src/ScottPlot4/ScottPlot/Plottable/SignalPlotXYGeneric.cs
- src/ScottPlot4/ScottPlot/ScottPlot.csproj
- src/ScottPlot4/changelog.md
The goal of this PR is to add support for `byte[]` back into generic signal (SignalConst and SignalXY) types
* extends #1927
> Generic Signal plots: add support for byte arrays

- src/ScottPlot4/ScottPlot.Tests/GetYDataRange.cs
- src/ScottPlot4/ScottPlot/Plottable/IHasPoints.cs
- src/ScottPlot4/ScottPlot/Plottable/ScatterPlot.cs
- src/ScottPlot4/ScottPlot/Plottable/SignalPlotBase.cs
- src/ScottPlot4/ScottPlot/Plottable/SignalPlotXYGeneric.cs
- src/ScottPlot4/changelog.md
**Purpose:**
Adds `GetYDataRange` to `IHasPointsGenericX`. This interface is implemented by ScatterPlots and SignalPlots (and their derivatives). #1942, #1929
```cs
(double yMin, double yMax) = scat.GetYDataRange(xStart, xEnd);
```
I wrote some tests, though they might be a little sparse. I'm not sure how this should be put in the cookbook? I suppose we could just draw a line at the bounds like we did for nth-order statistics and quantiles: https://scottplot.net/cookbook/4.1/category/statistics/#quantiles
> Signal and Scatter: GetYDataRange()

- src/ScottPlot4/ScottPlot.Cookbook/Recipes/Plottable/Coxcomb.cs
- src/ScottPlot4/ScottPlot.Cookbook/Recipes/Plottable/Function.cs
- src/ScottPlot4/ScottPlot.Cookbook/Recipes/Plottable/Pie.cs
- src/ScottPlot4/ScottPlot.Cookbook/Recipes/Plottable/Radar.cs
- src/ScottPlot4/ScottPlot.WPF/WpfPlot.xaml.cs
- src/ScottPlot4/ScottPlot/HatchOptions.cs
- src/ScottPlot4/ScottPlot/Plottable/CoxcombPlot.cs
- src/ScottPlot4/ScottPlot/Plottable/PiePlot.cs
- src/ScottPlot4/ScottPlot/Plottable/RadarPlot.cs
- src/ScottPlot4/changelog.md
**Purpose:**
#1943 
```cs
pie.HatchOptions = new HatchOptions[] {
new () { HatchStyle = HatchStyle.StripedUpwardDiagonal, HatchColor = Color.FromArgb(100, Color.Gray) },
new () { HatchStyle = HatchStyle.StripedDownwardDiagonal, HatchColor = Color.FromArgb(100, Color.Gray) },
new () { HatchStyle = HatchStyle.LargeCheckerBoard, HatchColor = Color.FromArgb(100, Color.Gray) },
new () { HatchStyle = HatchStyle.SmallCheckerBoard, HatchColor = Color.FromArgb(100, Color.Gray) },
new () { HatchStyle = HatchStyle.LargeGrid, HatchColor = Color.FromArgb(100, Color.Gray) },
};
```
Pie: 
Cocxomb:
Radar:
I promise they look better than in the screenshots, I used right-click and copy to paste the images in, and that disables anti-aliasing, which might be worth looking into separately.
> Hatched fills for Pie, Coxcomb, and Radar

- src/ScottPlot4/ScottPlot.Tests/PlottableRenderTests/Signal.cs
- src/ScottPlot4/ScottPlot/Plottable/SignalPlotBase.cs
- src/ScottPlot4/ScottPlot/Plottable/SignalPlotXYGeneric.cs
- src/ScottPlot4/changelog.md
**Purpose:**
#1949
This also necessitated disabling the adaptive marker size for N=1, as it would ordinarily return a very small (not necessarily zero) number. I believe for SignalXY it would always return zero.
> Signal, SignalXY: Ensure markers are drawn for single-point arrays

- src/ScottPlot5/ScottPlot/Control/Interactions/StandardInteractions.cs
- src/ScottPlot5/ScottPlot/Plot.cs
- src/ScottPlot5/ScottPlot/Plottables/ZoomRectangle.cs
Suggested by @BambOoxX in #1968
This PR shows the zoom rectangle as a span if CTRL or ALT is held down while middle-click dragging
> ScottPlot5: zoom rectangle axis span

- src/ScottPlot5/Controls/ScottPlot.Avalonia/AvaPlot.axaml
- src/ScottPlot5/Controls/ScottPlot.Avalonia/AvaPlot.axaml.cs
**Purpose:**
This does two things:
- Overrides `Render` directly, rather than using an `Image` control. I'm unsure of the performance improvement here, it's likely small to negligible. However, it simplifies the control quite a bit
- This doesn't depend on a Skia drawing context like a similar idea I discussed
- No longer saves the `WriteableBitmap` to a stream in order to then construct an Avalonia `Bitmap`
- The only reason we couldn't draw a `WritableBitmap` directly is because we didn't release the lock, causing a deadlock. This is what I get for writing PRs late at night
- The performance impact of skipping these two copies is monstrous.
> ScottPlot5: Drastic AvaPlot performance improvements

- src/ScottPlot5/Controls/ScottPlot.Avalonia/AvaPlot.axaml.cs
- src/ScottPlot5/ScottPlot/Control/PlotActionCommander.cs
**Purpose:**
On Avalonia holding [shift flips the scroll vector](https://github.com/AvaloniaUI/Avalonia/pull/7520), mapping horizontal scrolls to vertical and vice versa. This results in `e.Delta.Y` being 0 (which used to be interpreted as scrolling down, but we now return early for it).
> ScottPlot 5 Avalonia: Fixes Shift+MWheel yielding a deltaY of 0.

- src/ScottPlot5/Controls/ScottPlot.Avalonia/AvaPlot.axaml.cs
- src/ScottPlot5/ScottPlot.Eto/EtoPlot.cs
**Purpose:**
Eto allows us to render directly to the control, rather than setting an image that gets rendered. This is simpler and yields massive performance boosts. It also seems to be more consistent between WPF and WinForms
> EtoPlot: Usse Drawable.OnPaint directly rather than setting ImageView.Image

- src/ScottPlot4/ScottPlot.Sandbox/WinFormsApp/Form1.Designer.cs
- src/ScottPlot4/ScottPlot.Sandbox/WinFormsApp/Form1.cs
- src/ScottPlot4/ScottPlot.Tests/Misc/Drawing.cs
- src/ScottPlot4/ScottPlot/Drawing/GDI.cs
- src/ScottPlot4/ScottPlot/Plottable/AxisLine.cs
- src/ScottPlot4/changelog.md
Adds properties to axis lines for customizing label positions. This allows labels to be moved out of the way to prevent overlapping. See code in #1972 for details.
Resolves #1972
> Axis Line: Label Positioning

- src/ScottPlot4/ScottPlot.Tests/Concurrency/ConcurrencyTests.cs
- src/ScottPlot4/ScottPlot/Plot/Plot.Render.cs
- src/ScottPlot4/changelog.md
**Purpose:**
The current way of handling multithreading is not thread safe.
If one thread change the value of `IsRenderLocked` from `false` to `true`, there is a chance that another thread reading the same field will see `false`. Therefore, a Render might occur even if `RenderLock()` has been previously called.
> Use Monitor for RenderLock

- src/ScottPlot4/ScottPlot.Cookbook/Recipes/Plottable/Scatter.cs
- src/ScottPlot4/ScottPlot.Tests/PlotTypes/Scatter.cs
- src/ScottPlot4/ScottPlot.Tests/PlotTypes/ScatterPlotList.cs
- src/ScottPlot4/ScottPlot.Tests/ScottPlot.Tests.csproj
- src/ScottPlot4/ScottPlot/DataGen.cs
- src/ScottPlot4/ScottPlot/Plottable/ScatterPlot.cs
- src/ScottPlot4/ScottPlot/Plottable/ScatterPlotList.cs
- src/ScottPlot4/changelog.md
This PR adds an `OnNaN` field to `ScatterPlot` which customizes this behavior. 
The default action is `Throw`, but `Ignore` skips NaN points and `Gap` renders the line as multiple lines with gaps where data is NaN.
Related: 
* #203
* #396
* #546 
* #618
* #976
* #1161
Resolves:
* #2040
> Scatter.OnNaN: customizes NaN behavior

- src/ScottPlot4/ScottPlot.Sandbox/WinFormsApp/Form1.cs
- src/ScottPlot4/ScottPlot/Plottable/ScatterPlot.cs
- src/ScottPlot4/changelog.md
previously NaN was always returned for any plot containing NaN
* resolves #2048
> Scatter: improve GetPointNearest() NaN support

- src/ScottPlot4/ScottPlot.Tests/PlottableRenderTests/AxisSpan.cs
- src/ScottPlot4/ScottPlot/Drawing/GDI.cs
- src/ScottPlot4/ScottPlot/Plottable/AxisSpan.cs
- src/ScottPlot4/changelog.md
Cropping results in anti-aliasing artifacts near the edges of the bitmap
resolves #2051
> GDI: do not crop when frameless

- src/ScottPlot4/ScottPlot.Cookbook/Recipes/Plottable/Radar.cs
- src/ScottPlot4/ScottPlot/Plottable/RadarPlot.cs
- src/ScottPlot4/changelog.md
**Purpose:**
This pull request adds a new property Smooth (default false) to RadarPlot. When enabled the radar plot will render as a closed curve instead of a polygon.
```cs
// You can insert code examples like this
var radar = plot.AddRadar(values);
radar.Smooth = true;
plot.Render();
> RadarPlot: Add `Smooth` parameter

- src/ScottPlot4/ScottPlot.Tests/Ticks/TickGeneration.cs
- src/ScottPlot4/ScottPlot/Renderable/Axis.cs
- src/ScottPlot4/ScottPlot/Ticks/TickCollection.cs
- src/ScottPlot4/changelog.md
now throws immediately if manual ticks are supplied with mismatching position/label lengths
resolves #2063
> Ticks: improve manual tick checking

- src/ScottPlot4/ScottPlot.Cookbook/Recipes/Plottable/VectorField.cs
- src/ScottPlot4/ScottPlot/CoordinateVector.cs
- src/ScottPlot4/ScottPlot/Plot/Plot.Add.cs
- src/ScottPlot4/ScottPlot/Plottable/VectorFieldList.cs
- src/ScottPlot4/ScottPlot/Renderable/ArrowStyle.cs
- src/ScottPlot4/changelog.md
The goal of this PR is to create a new plot type which makes it simple to place vector arrows anywhere on the plot (not constrained to a grid like the current `VectorField`)
* Resolves #2064
```cs
ScottPlot.Plot plt = new();
// Create a vector field list and add it to the plot
var field = plt.AddVectorFieldList();
// Optionally color arrows using a colormap and custom scaling function
field.Colormap = Colormap.Turbo;
field.ColormapScaler = (magnitude) => magnitude * 5;
// Additional arrow styling options are here
field.ArrowStyle.ScaledArrowheads = true;
field.ArrowStyle.Anchor = ArrowAnchor.Base;
field.ArrowStyle.LineWidth = 3;
field.ArrowStyle.MarkerSize = 10;
field.ArrowStyle.MarkerShape = MarkerShape.filledDiamond;
// Generate random vectors
Random rand = new(0);
int pointCount = 20; …
```
> VectorFieldList

- src/ScottPlot4/ScottPlot.Cookbook/Recipes/Style.cs
- src/ScottPlot4/ScottPlot/Plot/Plot.cs
- src/ScottPlot4/ScottPlot/Renderable/DataBackground.cs
- src/ScottPlot4/ScottPlot/Renderable/FigureBackground.cs
- src/ScottPlot4/changelog.md
This PR allows background images to be placed behind the figure or data area.
```cs
plt.AddSignal(DataGen.Sin(51), 1, Color.Yellow);
plt.AddSignal(DataGen.Cos(51), 1, Color.Magenta);
Bitmap monaLisaBmp = ScottPlot.DataGen.SampleImage();
plt.Style(
grid: Color.FromArgb(50, Color.White),
dataBackgroundImage: monaLisaBmp);
```
```cs
plt.AddSignal(DataGen.Sin(51), 1, Color.Yellow);
plt.AddSignal(DataGen.Cos(51), 1, Color.Magenta);
Bitmap monaLisaBmp = ScottPlot.DataGen.SampleImage();
plt.Style(
grid: Color.FromArgb(50, Color.White),
tick: Color.White,
dataBackground: Color.FromArgb(50, Color.White),
figureBackgroundImage: monaLisaBmp);
```
> Style: add support for background image

- src/ScottPlot4/ScottPlot/Plot/Plot.cs
- src/ScottPlot4/ScottPlot/Plottable/AxisLine.cs
- src/ScottPlot4/changelog.md
Moves visibility check out of individual plottables and puts it inside the render loop so it applies to all plottables
resolves #2120
resolves #2110
> Plot: only hit test visible draggables

- src/ScottPlot4/ScottPlot/Renderable/Axis.cs
- src/ScottPlot4/ScottPlot/Ticks/TickCollection.cs
Add CornerLabelFormat() for ScottPlot.Renderable.Axis
**Purpose:**
Manually define the string format to use for translating exponential part of a number to corner label.
https://discord.com/channels/716448886889381919/998069111429013564/1022370316770615357
```cs
double[] dataX = new double[] { 1, 2, 3, 4, 5 };
double[] dataY = new double[] { 1E9, 4E9, 9E8, 16E9, 25E12 };
wpfPlot.Plot.AddScatter(dataX, dataY);
wpfPlot.Plot.YAxis.TickLabelNotation(true,offset:true);
wpfPlot.Plot.YAxis.CornerLabelFormat("x 10^{0}");
wpfPlot.Refresh();
```
> Add CornerLabelFormat() for Axis

- src/ScottPlot4/ScottPlot.Cookbook/Recipes/MultiAxis.cs
- src/ScottPlot4/ScottPlot/Plot/Plot.Axis.cs
- src/ScottPlot4/changelog.md
**Purpose:**
#2130, though I elected not to create a `HasAxisMatching` because you can just do `GetAxesMatching(criteria).Any()`. This PR also makes the `axisIndex` parameter optional on `AddAxis`, opting to auto-increment them. This should simplify multi-axis code and the creation of valid axes without breaking existing code.
```cs
var axes = plt.GetAxesMatching(null, false); // IEnumerable holding all horizontal axes.
```
> Adds GetAxesMatching function

- src/ScottPlot4/ScottPlot.Tests/Ticks/DateTimeTicksTests.cs
- src/ScottPlot4/ScottPlot/Ticks/DateTimeTickUnits/DateTimeTickUnitBase.cs
- src/ScottPlot4/ScottPlot/Ticks/DateTimeTickUnits/SecondsAndLess/DateTimeTickCentisecond.cs
- src/ScottPlot4/ScottPlot/Ticks/DateTimeTickUnits/SecondsAndLess/DateTimeTickDecisecond.cs
- src/ScottPlot4/ScottPlot/Ticks/DateTimeTickUnits/SecondsAndLess/DateTimeTickMillisecond.cs
- src/ScottPlot4/ScottPlot/Tools.cs
- src/ScottPlot4/changelog.md
**Purpose:**
#2132
This solution detects if a locale uses a 24-hour clock and adjusts some hard-coded time formats to generate 24-hour times.
> Consistent 12/24 hour clock in DateTime ticks

- src/ScottPlot5/ScottPlot5/Corner.cs
- src/ScottPlot5/ScottPlot5/Drawing.cs
- src/ScottPlot5/ScottPlot5/EnumerableHelpers.cs
- src/ScottPlot5/ScottPlot5/IPlottable.cs
- src/ScottPlot5/ScottPlot5/IsExternalInit.cs
- src/ScottPlot5/ScottPlot5/LegendItem.cs
- src/ScottPlot5/ScottPlot5/PixelSize.cs
- src/ScottPlot5/ScottPlot5/Plot.cs
- src/ScottPlot5/ScottPlot5/PlottableFactory.cs
- src/ScottPlot5/ScottPlot5/Plottables/DebugBenchmark.cs
- src/ScottPlot5/ScottPlot5/Plottables/DebugPoint.cs
- src/ScottPlot5/ScottPlot5/Plottables/Heatmap.cs
- src/ScottPlot5/ScottPlot5/Plottables/Legend.cs
- src/ScottPlot5/ScottPlot5/Plottables/Pie.cs
- src/ScottPlot5/ScottPlot5/Plottables/Scatter.cs
- src/ScottPlot5/ScottPlot5/Plottables/Signal.cs
- src/ScottPlot5/ScottPlot5/Plottables/ZoomRectangle.cs
- src/ScottPlot5/ScottPlot5/ScopedTransform.cs
- src/ScottPlot5/ScottPlot5/Style/Marker.cs
**Purpose:**
Adds legends to ScottPlot 5
```cs
var legend = new Legend(new[]
{
new LegendItem { Label = "Blue", Fill = new Fill(Colors.Blue) },
new LegendItem { Label = "Gray", Fill = new Fill(Colors.Gray) },
new LegendItem { Label = "Line", Line = new Stroke(Colors.Sienna, 1)},
new LegendItem {
Label = "Marker and Line", Line = new Stroke(Colors.Blue, 1),
Marker = new Marker(MarkerShape.Circle, Colors.Blue, 5),
Children = new[] {
new LegendItem { Label = "Red", Fill = new Fill(Colors.Red), Children = new[] {
new LegendItem { Label = "Blue", Fill = new Fill(Colors.Blue) },
new LegendItem { Label = "Cyan", Fill = new Fill(Colors.Cyan) },
}},
new LegendItem { Label = "Green", Fill = new Fill(Colors.Green) },
}
},
new LegendItem { Label = "Marker", Marker = new Marker(MarkerShape.Circle, …
```
> ScottPlot 5 Legends

- src/ScottPlot4/ScottPlot/Plottable/BarSeries.cs
- src/ScottPlot4/changelog.md
> BarSeries rectangle calculation for negative values fixed.

- src/ScottPlot4/ScottPlot.WinForms/FormsPlotLegendViewer.cs
- src/ScottPlot4/changelog.md
**Purpose:**
* Fixes: #2153
* Changing RefreshLegendImage from a private to a public function
* Re-ordering private and public functions
```cs
// From private to public function 
public void RefreshLegendImage()
```
> Making RefreshLegendImage become a public function

- src/ScottPlot4/ScottPlot/DoubleExtensions.cs
- src/ScottPlot4/ScottPlot/Plottable/FunctionPlot.cs
- src/ScottPlot4/changelog.md
**Purpose:**
#2156 
Most of the performance benefit comes from removing the exception-based code (that's my bad, it was my idea in the first place). `XMin` and `XMax` are just gravy, and they also are potentially useful in and of themselves, if someone only wants to consider a function on a narrow domain, this is probably an easier way to restrict that domain then manually modifying the function.
```cs
double? Normalised_Function_F(double z)
{
return 0 <= z && z <= 1 ? z : null;
}
var f = plt.AddFunction(Normalised_Function_F);
f.XMin = 0.3;
f.XMax = 0.7;
```
> FunctionPlot: Massive performance boosts for functions with restricted domains

- src/ScottPlot4/ScottPlot/Plot/Plot.Add.cs
**Purpose:**
Related to https://github.com/ScottPlot/ScottPlot/issues/2146  
Now you can use not only List<Bar> but also Bar[] argument.  
I'm not sure about corner cases related to .ToList() call - in the original approach you potentially can change the passed list after, but while converting an array to a list you can't do it. But in my opinion, we can skip this detail to not introduce additional complexity.
> Plot.AddBarSeries: new Bar[] overload

- src/ScottPlot4/ScottPlot/Palettes/Normal.cs
This commit will add the normal pallette based on xgfs_normal6 from Anton Tsitsulin as described in issue #2010.
> Add pallete based on xgfs_normal6 from Anton Tsitsulin

- src/ScottPlot4/ScottPlot/Plottable/Bar.cs
- src/ScottPlot4/ScottPlot/Plottable/BarPlot.cs
- src/ScottPlot4/ScottPlot/Plottable/BarPlotBase.cs
- src/ScottPlot4/ScottPlot/Plottable/BarSeries.cs
- src/ScottPlot4/changelog.md
**Purpose:**
#2148 
~~Note that this PR doesn't yet add this for `BarSeries`, I'm writing this between classes so I'll add it later.~~
The other question is whether this should be customizable, is drawing the text above negative bars always wrong (i.e. this is a bug fix), or should the user be able to choose that behaviour (i.e. this is a new feature). If it's the latter, I think we should preserve the previous behaviour of `ShowValuesAboveBars` and add `ShowValuesAtTipOfBar` or something similar.
```cs
double[] values = { 27.3, 23.1, -21.2, 16.1, 6.4, 19.2, 18.7, 17.3, 20.3, 13.1 };
var bar = plt.AddBar(values);
bar.ShowValuesAboveBars = true;
bar.Orientation = Orientation.Horizontal;
```
> Bar Plot: Show negative values below bar

- src/ScottPlot5/ScottPlot5/CoordinateRange.cs
**Purpose:**
`Math.Min` and `Math.Max` will return `NaN` if either of its arguments are `NaN` (because `NaN` is by definition less than, greater than, and unequal to any other number, including `NaN`).
Explicit NaN checks prevent this, this fixes an issue where middle-clicking would not zoom out properly (as if the `tight` argument to `AutoScale` were set).
> CoordinateRange.Expand: Add NaN checks

- src/ScottPlot4/ScottPlot/Ticks/DateTimeTickUnits/DateTimeTickUnitBase.cs
**Purpose:**
Under some circumstances (not quite clear when), `DateTimeTickUnitBase.culture` can be null. This prevents a null reference exception that can be triggered by zooming far enough into a plot with DateTime axes (it happens in `Tools.Uses24HourClock`, so you need to zoom in far enough to bring up centiseconds or finer units).
> Always initialize DateTimeTIckUnit.culture

- src/ScottPlot4/ScottPlot.Cookbook/Recipes/Axis.cs
**Purpose:**
Addresses #2196 
New recipe when viewed locally:
> #2196 - add cookbook recipe for datetime axis on a signal plot

- src/ScottPlot4/ScottPlot/DataGen.cs
- src/ScottPlot5/ScottPlot5/Generate.cs
**Purpose:**
RE: suggestion in #2010
Added `Consecutive2D` based on the example data used in the heat map cookbook recipes: https://scottplot.net/cookbook/4.1/category/plottable-heatmap
Saw that `Generate.cs` in ScottPlot5 already had 2D sine and ramp methods so copied those to v4 as well.
> #2010 - Add some data generator methods for 2D arrays

- src/ScottPlot4/ScottPlot/DataGen.cs
- src/ScottPlot4/changelog.md
> Ensure RandomNormalValue uses u1, u2 from (0,1), not [0,1)

- src/ScottPlot4/ScottPlot.Tests/PlottableUnitTests/FinancePlotTests.cs
- src/ScottPlot4/ScottPlot/Plottable/FinancePlot.cs
- src/ScottPlot4/changelog.md
**Purpose:**
#2199 highlighted that `FinancePlot`'s assumption that its `OHLCs` are always sorted by datetime can be confusing to users. This change makes sure `OHLCs` gets sorted before trying to calculate SMAs or BollingerBands, so that those methods work even if the user doesn't provide sorted OHLCs.
> #2199 - make FinancePlot sort OHLCs when getting SMA or Bollinger bands

- src/ScottPlot5/ScottPlot5/Axis/AxisRendering.cs
- src/ScottPlot5/ScottPlot5/Axis/StandardAxes/BottomAxis.cs
- src/ScottPlot5/ScottPlot5/Axis/StandardAxes/LeftAxis.cs
- src/ScottPlot5/ScottPlot5/Axis/StandardAxes/RightAxis.cs
- src/ScottPlot5/ScottPlot5/Axis/StandardAxes/TopAxis.cs
- src/ScottPlot5/ScottPlot5/Axis/StandardAxes/XAxisBase.cs
- src/ScottPlot5/ScottPlot5/Axis/StandardAxes/YAxisBase.cs
- src/ScottPlot5/ScottPlot5/Label.cs
- src/ScottPlot5/ScottPlot5/Plottables/Legend.cs
- src/ScottPlot5/ScottPlot5/ScopedTransform.cs
- src/ScottPlot5/ScottPlot5/Style/Font.cs
**Purpose:**
Adds a `Font` struct for abstracting `SKFont` and `SKTypeface`. #2144
```cs
const int N = 51;
avaPlot.Plot.Plottables.Add(DebugPoint);
avaPlot.Plot.Add.Scatter(Generate.Consecutive(N), Generate.Sin(N), Colors.Blue).Label = "Scatter";
avaPlot.Plot.Add.Scatter(Generate.Consecutive(N), Generate.Cos(N), Colors.Red).Label = "Scatter 2";
avaPlot.Plot.Add.Scatter(Generate.Consecutive(N), Generate.Sin(N, 0.5), Colors.Green).Label = "Scatter 3";
avaPlot.Plot.Add.Pie(new PieSlice[]
{
new() { Value = 6, Fill = new() { Color = Colors.Red}, Label = "Red" },
new() { Value = 4, Fill = new() { Color = Colors.Blue }, Label = "Blue" },
new() { Value = 3, Fill = new() { Color = Colors.Green }, Label = "Green" },
new() { Value = 1, Fill = new() { Color = Colors.DarkCyan }, Label = "Dark Cyan" }, …
```
> ScottPlot 5: Font abstraction

- src/ScottPlot4/ScottPlot.Avalonia/AvaPlot.axaml.cs
- src/ScottPlot4/changelog.md
**Purpose:**
* This PR fixes subscription to changes of `ContextMenu` property of `AvaPlot` control
* Previous implementations subscribes to `ContextMenu` changes of **ALL** controls which is wrong. As a result custom logic of `AvaPlot` `ContextMenu` opening applies to another controls and breaks their behavior.
> AvaPlot: fix subscription to ContexMenu property changes

- src/ScottPlot5/ScottPlot5/Axis/StandardAxes/MirroredXAxis.cs
- src/ScottPlot5/ScottPlot5/Axis/StandardAxes/MirroredYAxis.cs
- src/ScottPlot5/ScottPlot5/Axis/StandardAxes/XAxisBase.cs
- src/ScottPlot5/ScottPlot5/Axis/StandardAxes/YAxisBase.cs
**Purpose:**
In ScottPlot 5 there isn't a way to associate multiple x-axes or multiple y-axes with a single plottable, and this makes it difficult to have (for example) a bottom and a top axis showing the same ticks.
My solution was to simply create a `MirroredXAxis` and `MirroredYAxis`, which mirror the given axis onto the given edge. It derives its ticks and range entirely from the axis it is mirroring.
```cs
var xaxis2 = new MirroredXAxis(avaPlot.Plot.XAxis, Edge.Top);
avaPlot.Plot.XAxes.Add(xaxis2);
var yaxis2 = new MirroredYAxis(avaPlot.Plot.YAxis, Edge.Right);
avaPlot.Plot.YAxes.Add(yaxis2);
```
> ScottPlot 5: Mirrored Axes

- .github/workflows/benchmark.yaml
- .github/workflows/ci-v4.yaml
- .github/workflows/ci-v5.yaml
- .github/workflows/cookbook.yaml
- .github/workflows/package.yaml
- src/ScottPlot5/todo.md
**Purpose:**
Node.js 12 actions are deprecated. The versions of the actions involved have been updated in this PR.
**Details:**
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
> CI: Bump actions

- src/ScottPlot5/ScottPlot5/Axis/AxisRendering.cs
- src/ScottPlot5/ScottPlot5/Axis/IAxis.cs
- src/ScottPlot5/ScottPlot5/Axis/IXAxis.cs
- src/ScottPlot5/ScottPlot5/Axis/IYAxis.cs
- src/ScottPlot5/ScottPlot5/Axis/StandardAxes/MirroredXAxis.cs
- src/ScottPlot5/ScottPlot5/Axis/StandardAxes/MirroredYAxis.cs
- src/ScottPlot5/ScottPlot5/Axis/StandardAxes/XAxisBase.cs
- src/ScottPlot5/ScottPlot5/Axis/StandardAxes/YAxisBase.cs
- src/ScottPlot5/ScottPlot5/IHasColorAxis.cs
- src/ScottPlot5/ScottPlot5/Label.cs
- src/ScottPlot5/ScottPlot5/LayoutSystem/FinalLayout.cs
- src/ScottPlot5/ScottPlot5/LayoutSystem/ILayoutSystem.cs
- src/ScottPlot5/ScottPlot5/LayoutSystem/IPanel.cs
- src/ScottPlot5/ScottPlot5/LayoutSystem/StandardLayoutSystem.cs
- src/ScottPlot5/ScottPlot5/Panels/BoxPanel.cs
- src/ScottPlot5/ScottPlot5/Panels/ColorBar.cs
- src/ScottPlot5/ScottPlot5/Plot.cs
- src/ScottPlot5/ScottPlot5/PlottableFactory.cs
- src/ScottPlot5/ScottPlot5/Plottables/Heatmap.cs
- src/ScottPlot5/ScottPlot5/Rendering/Common.cs
- src/ScottPlot5/ScottPlot5/Rendering/StandardRenderer.cs
- src/ScottPlot5/ScottPlot5/SKBitmapHelpers.cs
**Purpose:**
This refactors `ILayoutSystem` to act on `IPanel` rather than `IAxis`. It also strips a lot of rendering state from `IAxis` like `Offset`, which is instead stored separately. This means we don't expose (and have to keep in sync) rendering state to the user.
~~This PR is intended to enable colorbar axes, but currently the only non-axis plot is a `BoxPanel` intended for debugging purposes.~~
This enables ColorBars (warning, garish):
Source:
```cs
int width = 100;
int height = 100;
double[,] intensities = new double[width, height];
for (int x = 0; x < width; x++)
for (int y = 0; y < height; y++)
intensities[x, y] = (Math.Sin(x * .2) + Math.Cos(y * .2)) * 100;
avaPlot.Plot.Plottables.Add(DebugPoint);
var hm = avaPlot.Plot.Add.Heatmap(intensities);
avaPlot.Plot.Add.ColorBar(hm, …
```
> ScottPlot 5: Refactor layout system to use IPanel, adds ColorBar

- CHANGELOG.md
- src/ScottPlot4/ScottPlot.Avalonia/ScottPlot.Avalonia.NUGET.csproj
- src/ScottPlot4/ScottPlot.Eto/ScottPlot.Eto.NUGET.csproj
- src/ScottPlot4/ScottPlot.Tests/data/sample.csproj
- src/ScottPlot4/ScottPlot.WPF/ScottPlot.WPF.NUGET.csproj
- src/ScottPlot4/ScottPlot.WinForms/ScottPlot.WinForms.NUGET.csproj
- src/ScottPlot4/ScottPlot/ScottPlot.csproj
The previously used version (4.6.1) has a vulnerability on non-Windows systems as described by https://github.com/advisories/GHSA-ghhp-997w-qr28
resolves #2303
> Project: target System.Drawing.Common 4.7.2

- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/Introduction/Quickstart.cs
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/Introduction/Styling.cs
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Bar.cs
- src/ScottPlot5/ScottPlot5/LegendItem.cs
- src/ScottPlot5/ScottPlot5/Legends/LegendItemSize.cs
- src/ScottPlot5/ScottPlot5/Legends/LegendRendering.cs
- src/ScottPlot5/ScottPlot5/Legends/SizedLegendItem.cs
- src/ScottPlot5/ScottPlot5/Legends/StandardLegend.cs
- src/ScottPlot5/ScottPlot5/Plot.cs
- src/ScottPlot5/ScottPlot5/PlottableFactory.cs
- src/ScottPlot5/ScottPlot5/Plottables/BarPlot.cs
- src/ScottPlot5/ScottPlot5/Style/Fill.cs
- src/ScottPlot5/ScottPlot5/Style/Stroke.cs
- src/ScottPlot5/ScottPlot5/TODO.cs
**Purpose:**
- Fixes an issue where children of a legend item could be duplicated
- Fixes an issue where legend symbols did not respect padding
- Eliminates remeasuring of child legend items
- Fixes indentation of child legend items
Outstanding issues:
- You cannot customize what items go in a legend (this might be out of scope for this issue)
Before:
After:
> ScottPlot 5 Legend: Fixes symbols, reduces remeasuring

- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/Introduction/Styling.cs
- src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/SignalPerformance.cs
- src/ScottPlot5/ScottPlot5/Style/MarkerShape.cs
- src/ScottPlot5/ScottPlot5/Style/MarkerStyle.cs
**Purpose:**
`MarkerStyle` no longer stores a `MarkerShape`, instead taking one in its constructor. Also adds hollow marker shapes.
> SP5: Simplifies MarkerStyle and adds hollow variants

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/ErrorBar.cs
- src/ScottPlot5/ScottPlot5/AddPlottable.cs
- src/ScottPlot5/ScottPlot5/Generate.cs
- src/ScottPlot5/ScottPlot5/Plottables/ErrorBar.cs
- src/ScottPlot5/ScottPlot5/PublicAPI.Unshipped.txt
**Purpose:**
Adds an ErrorBar plottable with a similar API as the one in 4.1. This does not add errorbars to other plottables (scatter, signal, etc) although that may be a good enhancement.
```cs
int N = 50;
double[] xs = Generate.Consecutive(N);
double[] ys = Generate.RandomWalk(N);
double[] xErrPositive = Generate.Random(N, 0.1, 0.25);
double[] xErrNegative = Generate.Random(N, 0.1, 0.25);
double[] yErrPositive = Generate.Random(N, 0.1, 0.25);
double[] yErrNegative = Generate.Random(N, 0.1, 0.25);
var scatter = myPlot.Add.Scatter(xs, ys);
var errorBars = myPlot.Add.ErrorBar(xs, ys, xErrPositive, xErrNegative, yErrPositive, yErrNegative, scatter.LineStyle.Color);
```
> ScottPlot5: Error Bars

- CHANGELOG.md
- src/ScottPlot4/ScottPlot/Statistics/Population.cs
This small correction lets the population plot calculate the median in the correct way.
(If the value count is even, the two values in the middle of a sorted array need to be averaged.)
> Correction for median calculation in population plot

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/Introduction/Styling.cs
- src/ScottPlot5/ScottPlot5/Extensions/SkiaSharpExtensions.cs
- src/ScottPlot5/ScottPlot5/LineStyle.cs
- src/ScottPlot5/ScottPlot5/Plottables/Signal.cs
- src/ScottPlot5/ScottPlot5/TODO.cs
**Purpose:**
Allows dotted/dashed lines using `SKPathEffect`
```cs
WpfPlot.Plot.Add.Signal(Generate.Sin(51)).LineStyle.Pattern = LinePattern.Dot;
WpfPlot.Plot.Add.Signal(Generate.Cos(51)).LineStyle.Pattern = LinePattern.Dash;
```
> ScottPlot 5: dashed lines

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/Stylers/PlotStyler.cs
**Issue:** If I'm understanding this code correctly, then setting a custom background color currently does nothing. The arguments are simply not used and the colors are hard coded in. I noticed this when following the [Cookbook Style Helper Functions](https://scottplot.net/cookbook/5.0/styling-plots/#style-helper-functions). 
```cs
namespace ScottPlot.Stylers;
public class PlotStyler
{
...
/// <summary>
/// Apply background colors to the figure and data areas
/// </summary>
public void Background(Color figure, Color data)
{
Plot.FigureBackground = Color.FromHex("#07263b");
Plot.DataBackground = Color.FromHex("#0b3049");
}
...
```
This pull request simply replaces the hardcoded values with the function arguments.
> ScottPlot5: Fix Plot.Style.Background() bug

- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/SKGLElement.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/ScottPlot.WPF.csproj
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/WpfPlot.xaml
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/WpfPlot.xaml.cs
- src/ScottPlot5/ScottPlot5-wpf.slnf
**Purpose:**
SkiaSharp haven't GPU accelerated control for WPF.
But there is PR in SkiaSharp with such control started at Nov 22. https://github.com/mono/SkiaSharp/pull/2317
I tested a bit, and it looks finished.
So i grab the code and place it in ScottPlot.WPF.
If and when the PR is approved we can simply remove the code and change the link.
> ScottPlot.WPF based on GL accelerated control

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Avalonia/AvaPlot.axaml.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Eto/EtoPlot.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms/OpenGL/AddPlottableExtensions.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms/OpenGL/FallbackStrategy.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms/OpenGL/GLFallbackRenderStrategy.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms/OpenGL/GLShader.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms/OpenGL/ScatterGL.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms/ScottPlot.WinForms.csproj
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinUI/WinUIPlot.cs
- src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/SignalPerformance.cs
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.Wasm/Sandbox.Wasm.csproj
- src/ScottPlot5/ScottPlot5/Control/IPlotControl.cs
- src/ScottPlot5/ScottPlot5/IPlottableGL.cs
- src/ScottPlot5/ScottPlot5/Rendering/Common.cs
- src/ScottPlot5/ScottPlot5/Rendering/StandardRenderer.cs
**Purpose:**
Some improvements for ScatterGL:
1. Before `Benchmark.Stop()` we call `GL.Finish()`. This block CPU thread until all GPU operations finished. So benchmark now shows correct numbers when using ScatterGL plottables.
2. Optimization for  data to Vertices array copy.
3. `GRContext` => `Func<GRContext>`. This allow us create `ScatterGL` at form constructor. GRContext is null at creation time.
4. `ScatterGL` can be configured to skip render or make `Scatter.Render()` if `GRContext` is null.
5. `Add.ScatterGL` extension method now return added `ScatterGL`.
Extends:
* #2383
> Scatter gl improvements

- CONTRIBUTING.md
- src/ScottPlot4/ScottPlot.Cookbook/Recipes/Axis.cs
Add newline before `class TicksDateTimeSignal` so that .cs file parses correctly for the website.
Related:
* https://github.com/ScottPlot/ScottPlot.NET/pull/25
> Cookbook: fix datetime recipe

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/Axis/CustomizingTicks.cs
- src/ScottPlot5/ScottPlot5/Axis/StandardAxes/BottomAxis.cs
- src/ScottPlot5/ScottPlot5/Axis/StandardAxes/LeftAxis.cs
- src/ScottPlot5/ScottPlot5/Axis/StandardAxes/RightAxis.cs
- src/ScottPlot5/ScottPlot5/Axis/StandardAxes/TopAxis.cs
- src/ScottPlot5/ScottPlot5/ITickGenerator.cs
- src/ScottPlot5/ScottPlot5/Layouts/StandardLayoutMaker.cs
- src/ScottPlot5/ScottPlot5/Panels/ColorBar.cs
- src/ScottPlot5/ScottPlot5/Rendering/StandardRenderer.cs
- src/ScottPlot5/ScottPlot5/TickGenerators/DateTimeAutomatic.cs
- src/ScottPlot5/ScottPlot5/TickGenerators/DateTimeFixedInterval.cs
- src/ScottPlot5/ScottPlot5/TickGenerators/ITimeUnit.cs
- src/ScottPlot5/ScottPlot5/TickGenerators/NumericAutomatic.cs
- src/ScottPlot5/ScottPlot5/TickGenerators/NumericFixedInterval.cs
- src/ScottPlot5/ScottPlot5/TickGenerators/TimeUnits/Centisecond.cs
- src/ScottPlot5/ScottPlot5/TickGenerators/TimeUnits/Day.cs
- src/ScottPlot5/ScottPlot5/TickGenerators/TimeUnits/Decisecond.cs
- src/ScottPlot5/ScottPlot5/TickGenerators/TimeUnits/Hour.cs
- src/ScottPlot5/ScottPlot5/TickGenerators/TimeUnits/Millisecond.cs
- src/ScottPlot5/ScottPlot5/TickGenerators/TimeUnits/Minute.cs
- src/ScottPlot5/ScottPlot5/TickGenerators/TimeUnits/Month.cs
- src/ScottPlot5/ScottPlot5/TickGenerators/TimeUnits/Second.cs
- src/ScottPlot5/ScottPlot5/TickGenerators/TimeUnits/Year.cs
- src/ScottPlot5/ScottPlot5/Usings.cs
* modify `ITickGenerator` so the `Edge` is passed into the tick generation function instead of being stored
* modify the `DateTimeAutomatic` tick generator to store time units in a list (created not using reflection), making them easier to modify or replace individually
* added cookbook demo showing how to customize tick label format
* resolves #2500
> SP5: improve tick label format customization

- CHANGELOG.md
- src/ScottPlot4/ScottPlot.Cookbook/Recipes/Plottable/Annotation.cs
- src/ScottPlot4/ScottPlot.Tests/PlotTypes/Annotation.cs
- src/ScottPlot4/ScottPlot.Tests/PlottableRenderTests/Annotation.cs
- src/ScottPlot4/ScottPlot/Drawing/GDI.cs
- src/ScottPlot4/ScottPlot/Enums/Alignment.cs
- src/ScottPlot4/ScottPlot/Plot/Plot.Add.cs
- src/ScottPlot4/ScottPlot/PlotDimensions.cs
- src/ScottPlot4/ScottPlot/Plottable/Annotation.cs
Deprecate `X` and `Y` positioning in favor of `Alignment` and `Margin`
* Resolves #2302
> SP4 Annotation: improve alignment options

- src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WPF/CookbookControl.xaml
- src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WPF/WpfDemos/AxisLimits.xaml
- src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WPF/WpfDemos/DisplayScaling.xaml
- src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WPF/WpfDemos/Layout.xaml
- src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WPF/WpfDemos/LinkedPlots.xaml
- src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WPF/WpfDemos/LiveDataFixed.xaml
- src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WPF/WpfDemos/LiveDataGrowing.xaml
- src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WPF/WpfDemos/MouseTracker.xaml
- src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WPF/WpfDemos/MultiAxisLock.xaml
- src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WPF/WpfDemos/PlotInScrollViewer.xaml
- src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WPF/WpfDemos/RightClickMenu.xaml
- src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WPF/WpfDemos/ShowValueOnHover.xaml
- src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WPF/WpfDemos/StyleBrowser.xaml
- src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WPF/WpfDemos/TransparentBackground.xaml
- src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WPF/WpfDemos/WpfConfig.xaml
- src/ScottPlot4/ScottPlot.Sandbox/WpfApp/MainWindow.xaml
- src/ScottPlot4/ScottPlot.WPF/README.md
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WPF/MainWindow.xaml
Always use `x:Name` for naming components in XAML code.
This is to most "common" way to name components in XAML/WPF as the XAML compiler will ensure this name will be unique and it cannot be changed later in code behind via `SetValue()`. 
This way, any naming conflicts would be avoid.
> WPF: fix XAML component naming

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/SKGLElement.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/ScottPlot.WPF.csproj
**Purpose:**
Two plot control and keyboard input will stackoverflow #2609
This bug refers to `GLWPFControl`. https://github.com/opentk/GLWpfControl/issues/82
They made it possible to bypass incorrect keypress handling in version 4.2.3.
This PR updates the version of `GLWPFControl`, and disables incorrect event handling by `GLWPFControl` itself. ScottPlot.WPF's keyboard handlers continue to work correctly if the control gets focus.
> SP5 OpenGL Control: Fix keyboard input bug #2609

- CHANGELOG.md
- src/ScottPlot4/ScottPlot/Plottable/PopulationPlot.cs
**Purpose:**
make the box border and error/std dev bar color configurable in population plot, currently hardcoded as black and that is kept as the default
```cs
PopulationPlot popPlot = plt.AddPopulations(populations);
popPlot.BoxBorderColor = Color.Red;
popPlot.ErrorStDevBarColor = Color.Blue;
```
> population plot: add line color options

- CHANGELOG.md
- src/ScottPlot4/ScottPlot/Plottable/CoxcombPlot.cs
- src/ScottPlot4/ScottPlot/Plottable/RadarPlot.cs
- src/ScottPlot4/ScottPlot/StarAxis.cs
> SP4 coxcomb and radar: improve vertical spacing

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Tests/RenderTests/Plottable/ScatterTests.cs
- src/ScottPlot5/ScottPlot5/Plot.cs
- src/ScottPlot5/ScottPlot5/Rendering/Common.cs
- src/ScottPlot5/ScottPlot5/Rendering/StandardRenderer.cs
> SP5: Correct zero-size axes inside the render loop

- CHANGELOG.md
- src/ScottPlot4/ScottPlot.Cookbook/Recipes/Plottable/ScatterList.cs
The Scatter List as been added for over a year. I think it's time to graduate it from an experimental feature and make it an official fully launched feature.
> Remove "experimental" from Scatter List

- CHANGELOG.md
- src/ScottPlot4/ScottPlot.WPF/WpfPlot.cs
Corrects the `PlottableDragged` event accessor adding a handler to the dropped event.
> SP4 WPF: Fix PlottableDragged add event accessor

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/Extensions/SkiaSharpExtensions.cs
- src/ScottPlot5/ScottPlot5/Primitives/FontStyle.cs
Update FontStyle to add a typeface cache to avoid to call too often the font face lookup table.
This should solve issue #2833
> SP5: Cache typefaces

- CHANGELOG.md
- src/ScottPlot4/ScottPlot.Cookbook/Categories/PlotTypes/DataLogger.cs
- src/ScottPlot4/ScottPlot.Cookbook/Recipes/Plottable/DataLogger.cs
- src/ScottPlot4/ScottPlot/Plot/Plot.Add.cs
- src/ScottPlot4/ScottPlot/Plottable/DataLogger.cs
**Purpose:**
This PR is to enable `Markers` support for `DataLogger`.
Per default, markers are disabled to not change current behavior.
I know that SP4 is in "frozen" state, but it would be nice if this PR could be included 😄
> SP4: Add markers support to DataLogger

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Avalonia/AvaPlot.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Eto/EtoPlot.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/WpfPlot.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms/FormsPlot.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinUI/WinUIPlot.cs
- src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/SharedAxes.Designer.cs
- src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/SharedAxes.cs
- src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/SharedAxisManager.cs
- src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/SharedLayoutManager.cs
- src/ScottPlot5/ScottPlot5/Control/RenderQueue.cs
- src/ScottPlot5/ScottPlot5/Interfaces/IPlotControl.cs
- src/ScottPlot5/ScottPlot5/Plot.cs
This PR makes several changes that facilitate synchronizing axis limits and layouts across multiple controls:
* Created a `RenderQueue` manager (required by `IPlotControl` now) to make it easy for one control to request a render of another control the next time it's rendered. This prevents infinite loops and artifacts from simultaneous renders.
* Created `SharedAxisManager` and `SharedLayoutManager` classes to make it easy to sync across multiple controls
This WinForms example shows how to share axes/layouts
```cs
public partial class SharedAxesForm : Form, IDemoWindow
{
SharedAxisManager SharedAxes = new(shareX: true, shareY: false);
SharedLayoutManager SharedLayout = new(shareX: true, shareY: false);
public SharedAxesForm()
{ …
```
> SP5 Controls: shared axis and layout functionality

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Chapter.cs
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Box.cs
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/Statistics/Regression.cs
- src/ScottPlot5/ScottPlot5 Tests/Statistics/LinearRegressionTests.cs
- src/ScottPlot5/ScottPlot5/PlottableAdder.cs
- src/ScottPlot5/ScottPlot5/Plottables/Polygon.cs
- src/ScottPlot5/ScottPlot5/Plottables/Signal.cs
- src/ScottPlot5/ScottPlot5/Primitives/LineStyle.cs
- src/ScottPlot5/ScottPlot5/Statistics/LinearRegression.cs
- src/ScottPlot5/ScottPlot5/Statistics/LinearRegressionLine
Please review.  Adds LinearRegressionLine to ScottPlot5.  So it can be used with code similar to the following:
``` cs
// Linear regression line
double firstDate = dates[0];
double lastDate = dates[dates.Length - 1];
var regressionLine = new ScottPlot.Statistics.LinearRegressionLine(dates, chartValues);
AddLine(_plot.Plot, regressionLine.slope, regressionLine.offset, (firstDate, lastDate), lineWidth: 0.5F, color: XkcdColors.LightGreyBlue, label: "Trend");
}
private void AddLine(Plot plot, double slope, double offset, (double x1, double x2) xLimits, string label = "", Color? color = null, float lineWidth = 1)
{
double y1 = xLimits.x1 * slope + offset;
double y2 = xLimits.x2 * slope + offset;
var scatter = plot.Add.Scatter(new double[] { xLimits.x1, xLimits.x2 }, new double[] { y1, y2 }, …
```
> SP5: Linear Regression

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Avalonia/AvaPlot.cs
For AvaPlot to be displayed correctly alongside other controls, ClipToBounds should be true.
Correct rendering size is Bounds.Size and correct rendering position is always origin (0,0).
> Fix AvaPlot rendering issues

- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms/Form1.cs
- src/ScottPlot5/ScottPlot5 Tests/RenderTests/Plottable/SignalTests.cs
- src/ScottPlot5/ScottPlot5/DataSources/ISignalSource.cs
- src/ScottPlot5/ScottPlot5/DataSources/SignalSource.cs
- src/ScottPlot5/ScottPlot5/Plottables/Signal.cs
- src/ScottPlot5/ScottPlot5/Primitives/PixelColumn.cs
This PR changes how ScottPlot 5's signal plot draws lines to cover edge cases like extended repeated values and vertical gaps. 
Resolves #2949
> SP5 Signal: improve rendering for special cases

- .github/workflows/ScottPlot5-CI.yaml
- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.OpenGL/AddPlottableExtensions.cs
- src/ScottPlot5/ScottPlot5 Tests/RenderTests/Plottable/AxisLineTests.cs
- src/ScottPlot5/ScottPlot5/Extensions/SkiaSharpExtensions.cs
- src/ScottPlot5/ScottPlot5/Grids/DefaultGrid.cs
- src/ScottPlot5/ScottPlot5/Interfaces/IGrid.cs
- src/ScottPlot5/ScottPlot5/Interfaces/IPlottable.cs
- src/ScottPlot5/ScottPlot5/Plot.cs
- src/ScottPlot5/ScottPlot5/PlottableAdder.cs
- src/ScottPlot5/ScottPlot5/Plottables/AxisLine.cs
- src/ScottPlot5/ScottPlot5/Plottables/HorizontalLine.cs
- src/ScottPlot5/ScottPlot5/Plottables/VerticalLine.cs
- src/ScottPlot5/ScottPlot5/Primitives/Alignment.cs
- src/ScottPlot5/ScottPlot5/Primitives/Axes.cs
- src/ScottPlot5/ScottPlot5/Primitives/AxisLimits.cs
- src/ScottPlot5/ScottPlot5/Primitives/Label.cs
- src/ScottPlot5/ScottPlot5/Primitives/LegendItem.cs
- src/ScottPlot5/ScottPlot5/Primitives/PixelLine.cs
- src/ScottPlot5/ScottPlot5/RenderPack.cs
- src/ScottPlot5/ScottPlot5/Rendering/RenderActions/RenderPlottables.cs
- src/ScottPlot5/ScottPlot5/TODO.cs
This PR adds `VerticalLine` and `HorizontalLine` plot types and refactors the `Crosshair` plot type.
A separate PR will be opened to refactor the render system to allow the label to render above the axes.
Partially addresses #2945
> SP5: Axis Lines

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms/FormsPlot.cs
- src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/DraggableAxisLines.Designer.cs
- src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/DraggableAxisLines.cs
- src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/DraggableAxisLines.resx
- src/ScottPlot5/ScottPlot5/Control/Interaction.cs
- src/ScottPlot5/ScottPlot5/Interfaces/IRenderLast.cs
- src/ScottPlot5/ScottPlot5/Plot.cs
- src/ScottPlot5/ScottPlot5/Plottables/AxisLine.cs
- src/ScottPlot5/ScottPlot5/Plottables/HorizontalLine.cs
- src/ScottPlot5/ScottPlot5/Plottables/VerticalLine.cs
- src/ScottPlot5/ScottPlot5/Primitives/CoordinateRect.cs
- src/ScottPlot5/ScottPlot5/Primitives/PixelRect.cs
- src/ScottPlot5/ScottPlot5/Rendering/RenderActions/RenderPlottables.cs
- src/ScottPlot5/ScottPlot5/Rendering/RenderActions/RenderPlottablesLast.cs
- src/ScottPlot5/ScottPlot5/Rendering/RenderManager.cs
resolves #2993
Notably this PR adds a "draggable axis line" demo to the WinForms demo app. The strategy for mouse-interactive plot types is very different in ScottPlot 5 than it was in ScottPlot 4: all dragging logic is implemented by the user! This strategy is a little more code for the user to sling, but with good documentation and copy/paste-ready demos I don't think it will be too much of a burden. The advantage is that it greatly simplifies the code in plottables, and removes the need for interactive vs. non-interactive plottables.
> SP5: create `IRenderLast` for plottables that render above axes

- CHANGELOG.md
- src/ScottPlot4/ScottPlot/Plottable/ArrowCoordinated.cs
**Purpose:**
- fix typo in `ArrowCoordinated(Coordinate arrowBase, Coordinate arrowTip)`
**Testing:**
- test suite passed - but since this particular overload isn't referenced anywhere it would be quite surprising if it broke something
> Fix typo in ArrowCoordinated function

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Tests/RenderTests/FileFormatTests.cs
- src/ScottPlot5/ScottPlot5/AxisPanels/AxisBase.cs
- src/ScottPlot5/ScottPlot5/Rendering/RenderManager.cs
> SP5: Improve SVG support for axis frame and tick marks

- src/ScottPlot4/ScottPlot.Cookbook/Categories/PlotTypes/SignalXY.cs
- src/ScottPlot4/ScottPlot.Cookbook/Recipes/Plottable/SignalXY.cs
- src/ScottPlot4/ScottPlot.Cookbook/Recipes/Plottable/SignalXYConst.cs
**Purpose:**
* Fix "vaues" typo to "values" in source classes so auto doc generation builds with corrections.
closes #3011
> fixed "vaues" typo in source files.

- src/ScottPlot4/ScottPlot.Cookbook/Recipes/Plottable/Population.cs
- src/ScottPlot4/ScottPlot.Tests/PlotTypes/Population.cs
- src/ScottPlot4/ScottPlot/Plottable/PopulationPlot.cs
**Purpose:**
* Add option to use custom alpha values from series colors in population plots via `AutomaticOpacity` field
* Add option to set ratio of marker alpha to box alpha via `MarkerOpacityRatio` field
* Add test for these two fields
* Remove the now redundant `MarkerAlpha` and `BoxAlphaOverride` fields
* Remove deprecated tests
* Update relevant cookbook example
* resolve #2967 (previously closed, but it is the relevant issue to this pull request)
> SP4: Custom alpha for population plots

- CHANGELOG.md
- src/ScottPlot4/ScottPlot/Generate.cs
- src/ScottPlot4/ScottPlot/RandomDataGenerator.cs
- src/ScottPlot5/ScottPlot5/RandomDataGenerator.cs
Use a global Random number generator when `seed` is null to enforce values randomness. Should fix #2893
> SP4: Improves Generate class.

- CHANGELOG.md
- src/ScottPlot4/ScottPlot.Avalonia/AvaPlot.axaml.cs
- src/ScottPlot4/ScottPlot.Eto/PlotView.cs
- src/ScottPlot4/ScottPlot.WPF/WpfPlot.cs
- src/ScottPlot4/ScottPlot.WinForms/FormsPlot.cs
- src/ScottPlot4/ScottPlot/Control/Backend.cs
ControlBackEnd implements now `IDisposable`.
When disposing (or on destruction), all bitmaps in `OldBitmaps` queue and `Bmp` are disposed to avoid memory overflow.
This should fix issue #2902
> SP4: Improve Bitmap disposal as controls are unloaded

- CHANGELOG.md
- src/ScottPlot4/ScottPlot/Plottable/ScatterPlot.cs
- src/ScottPlot4/ScottPlot/Plottable/ScatterPlotDraggable.cs
**Purpose:**
This should resolve issues with `ScatteerPlotDraggable` (#2870 and #2969):
- remove duplicated members `Xs` and `Ys`, they are already managed by base class `ScatterPlot`
- ensure a valid point is selected before trying to update its position
- avoid possible exception with `PointCount` when no data is set
> SP4: Fix ScatterPlotDraggable

- src/ScottPlot4/ScottPlot.Avalonia/README.md
- src/ScottPlot4/ScottPlot.Eto/README.md
- src/ScottPlot4/ScottPlot.WPF/README.md
- src/ScottPlot4/ScottPlot.WinForms/README.md
- src/ScottPlot4/ScottPlot/README.md
Add missed `Refresh()` statements, this should fix #2948
> SP4: improve quickstart code in NuGet readmes

- CHANGELOG.md
- src/ScottPlot4/ScottPlot.Cookbook/Recipes/Plottable/Radar.cs
- src/ScottPlot4/ScottPlot/Plot/Plot.Add.cs
- src/ScottPlot4/ScottPlot/Plottable/RadarPlot.cs
- src/ScottPlot4/ScottPlot/StarAxis.cs
**Purpose**
Hi, I wanted to modify the appearance of the radar chart to approximate the rendering shown below.
For this, it would be useful if some parameters were accessible.
Here are some suggestions although I haven't yet mastered all the concepts of this very nice library!
- StarAxis.AxisLabelStringFormat : Format used to generate values ​​on axis ; ex : "0.#" to eliminate unnecessary decimals
- RadarPlot.Font: Public access to the Font used for labeling values on the plot
- RadarPlot.AlphaFill: this value overrides the intermediate transparency (alpha) applied by default to the area fill color
- RadarPlot.TickValues: When IndependentAxes is false, TickValues ​​is able to display ticks based on concrete values ​​on the axis instead of ticks expressed as a ratio by default ; ex : { 1, …
> SP4 RadarPlot: Added customization settings

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/Introduction/Legend.cs
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/Introduction/Quickstart.cs
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/Introduction/Styling.cs
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Bar.cs
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/FillY.cs
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Signal.cs
- src/ScottPlot5/ScottPlot5 Tests/RenderTests/LegendTests.cs
- src/ScottPlot5/ScottPlot5 Tests/RenderTests/Plottable/PieTests.cs
- src/ScottPlot5/ScottPlot5/Interfaces/ILegend.cs
- src/ScottPlot5/ScottPlot5/Legends/Legend.cs
- src/ScottPlot5/ScottPlot5/Legends/StandardLegend.cs
- src/ScottPlot5/ScottPlot5/Plot.cs
- src/ScottPlot5/ScottPlot5/Rendering/RenderActions/RenderLegends.cs
This PR refactors the legend system to replace `List<ILegend>` with a single `Legend` object. This makes it easier to customize the legend appearance and behavior. 
However, the way of enabling legends has changed:
```cs
// this is how to enable the legend now
Plot.Legend.IsVisible = true;
```
```cs
// this old strategy no longer works
Plot.Legend(true);
```
resolves #2792
> SP5: Simplify legend system

- CHANGELOG.md
- src/ScottPlot4/ScottPlot/Plottable/PopulationPlot.cs
For the PopulationPlot, only draw the distribution curve for the visible part of the plot, to avoid performance issues.
This fix was implemented by myself and @cornford 
I have provided an example below, to reproduce the issue. 
Operating System: Windows
Application Type: WPF
```cs
public void CreatePopulationMultiSeries(WpfPlot plot)
{
// Show the legend (not necessary for the issue)
plot.Plot.Legend();  
// 1 group
var groupNames = new[] { "Group A" };
plot.Plot.XTicks(groupNames);
// 1 series
var seriesColours = new System.Drawing.Color[] { System.Drawing.Color.Blue };
var seriesData = new[]
{
new [] // Group 1
{
new double[]{ 1.0, 600000.0 }
}
};
// when setting these axis limits, the performance will suffer, when the distribution curve is rendered
plot.Plot.SetAxisLimits(yMin: 0, …
```
> Fix up a performance issue, that can occur when the population plot draws its' distribution curve

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/AutoScalers/FractionalAutoScaler.cs
**Purpose:**
Solves #3067 by changing the class visibility from `internal` to `public`.
```cs
public class FractionalAutoScaler : IAutoScaler
```
> Modify FractionalAutoScaler class scope

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Function.cs
- src/ScottPlot5/ScottPlot5/DataSources/FunctionSource.cs
- src/ScottPlot5/ScottPlot5/DataSources/IFunctionSource.cs
- src/ScottPlot5/ScottPlot5/Extensions/NumericExtensions.cs
- src/ScottPlot5/ScottPlot5/PlottableAdder.cs
- src/ScottPlot5/ScottPlot5/Plottables/FunctionPlot.cs
**Purpose:**
Adds a function plot, like exists in ScottPlot 4.
One can specify an `IFunctionSource` for more depth:
```cs
var funcSource = new FunctionSource(x => Math.Sin(x) / x);
funcSource.RangeX = new(-10, 10);
funcSource.GetRangeYFunc = (CoordinateRange xs) =>
{
if (Math.Sign(xs.Min) != Math.Sign(xs.Max)) // Crosses 0
return new(-1, 1);
double distanceFromZero = Math.Min(Math.Abs(xs.Min), Math.Abs(xs.Max));
double magnitude = 1 / distanceFromZero;
return new CoordinateRange(-magnitude, magnitude);
};
var fn1 = WpfPlot1.Plot.Add.Function(funcSource);
fn1.Label = "sin(x) / x";
```
Or one can just pass in a lambda:
```
var fn2 = WpfPlot1.Plot.Add.Function(x => 1 / Math.Round(x));
fn2.Label = "1 / round(x)";
```
The result: 
**Note**, if one does not specify `RangeX` and `GetRangeY` then …
> ScottPlot 5: Function Plot

- .github/workflows/ScottPlot5-CI.yaml
- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/AxisPanels/YAxisBase.cs
> SP5: Fix right aligned axis label position

- CHANGELOG.md
- src/ScottPlot4/ScottPlot/Marker/Marker.cs
- src/ScottPlot4/ScottPlot/Marker/MarkerShape.cs
**Purpose: Add missing horizontal line marker shape to enum**
* During development I find out that HorizontalBar.cs is available in MarkerShapes folder. But MarkerShape.horizontalBar was missing. I tried to solve my issue with MarkerShape.cross and it looks not so nice. So, would be great to have it here.
```cs
plt.AddMarker(1, 210, MarkerShape.horizontalBar, color: Color.Black, size: 5);
```
> Add missing horizontal line marker shape to enum

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Box.cs
- src/ScottPlot5/ScottPlot5/Drawing.cs
- src/ScottPlot5/ScottPlot5/Generate.cs
- src/ScottPlot5/ScottPlot5/PlottableAdder.cs
- src/ScottPlot5/ScottPlot5/Plottables/BoxPlot.cs
- src/ScottPlot5/ScottPlot5/Primitives/Box.cs
- src/ScottPlot5/ScottPlot5/Primitives/LegendItem.cs
resolves #3072
Box plots now manage no grouping. 
Additional work could add these nice-to-have features:
- Helper methods for creating grouped box plots can be added in the future. 
- This plot type can be extended in the future to store/display population data points
- The `Box` class could use a helper method to generate itself from a series of data points
> SP5: Refactor box plots

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Tests/Statistics/ArrayTests.cs
- src/ScottPlot5/ScottPlot5/Statistics/Descriptive.cs
**Purpose:**
* Proposes initial solution for #3113 
* Adds new overloaded methods: `NaNMean<T>`, `NaNVariance<T>`, `NaNVarianceP<T>`, `NaNStandardDeviation<T>`, `NaNStandardDeviationP<T>`, and `NaNStandardError<T>`, for both `IReadOnlyList` and 2D (not jagged) arrays.
* Auxiliary functions: `RemoveNaN<T>`, `RemoveNaN`, `ArrayTraspose`, and `ArrayToVector`, are defined as `public` but they are only used internally. Consider making them `private`.
* Auxiliary functions: `RemoveNaN<T>`, `RemoveNaN`, `ArrayTraspose`, and `ArrayToVector` do not really belong to `Descriptive.cs`. Should they be relocated to `NumericConversion.cs`?
> Statistics for 2D arrays

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WPF/MainWindow.xaml
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WPF/MainWindow.xaml.cs
- src/ScottPlot5/ScottPlot5/DataSources/SegmentedTree.cs
- src/ScottPlot5/ScottPlot5/DataSources/SignalConstSource.cs
- src/ScottPlot5/ScottPlot5/DataSources/SignalConstSourceArray.cs
- src/ScottPlot5/ScottPlot5/DataSources/SignalSourceBase.cs
- src/ScottPlot5/ScottPlot5/PlottableAdder.cs
- src/ScottPlot5/ScottPlot5/Plottables/SignalConst.cs
- src/ScottPlot5/ScottPlot5/Primitives/Axes.cs
SignalConst is a high performance plot type for generic numeric data that uses segmented trees to improve range search performance at the expense of storing ranges in memory. Originally discussed in #70. Resolves #3188
> SP5: Implement SignalConst

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/Plot.cs
Tiny PR aimed to remove duplicated render manager initialization.
> SP5: Remove duplicated render manager initialization

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/Introduction/Quickstart.cs
- src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/SelectPoints.cs
- src/ScottPlot5/ScottPlot5 Tests/UnitTests/PlottableManagement.cs
- src/ScottPlot5/ScottPlot5/Plot.cs
- src/ScottPlot5/ScottPlot5/Plottables/Marker.cs
Remove by type.
Fix #3284
Returns false if no items matched that type for debugging purposes.
> SP5: `Plot.Remove()` overload that accepts `Type`

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Tests/UnitTests/PlottableManagement.cs
- src/ScottPlot5/ScottPlot5/Plot.cs
This PR adds overload to `Plot.Remove()` to be able to remove `IPlottable` in generic way.
This should fix issue #3284.
Usage exampes:
```cs
myPlot.Add.Signal(Generate.Sin()).Label = "Toto";
// to remove all Signals
myPlot.Remove<ScottPlot.Plottables.Signal>();
....
// to remove all Signals without Label
myPlot.Remove<ScottPlot.Plottables.Signal>((x) => (x.Label?.Length ?? 0) <= 0);
...
```
> SP5: Plot.Remove() generic overloads

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/CustomMouseActions.cs
- src/ScottPlot5/ScottPlot5/Control/Interaction.cs
A fix for #3304 
This fix stores the plot actions assigned to the Interaction in seperate field during disabled periods (e.g, when dragging axis lines).
It restores the actions on Enable
```.cs
/// <summary>
/// Disable all mouse interactivity
/// </summary>
public void Disable()
{
//back up the enabled plot actions
EnabledPlotActions = Actions;
Actions = PlotActions.NonInteractive();
}
/// <summary>
/// Enable mouse interactivity using the default mouse actions
/// </summary>
public void Enable()
{
Actions = EnabledPlotActions;
}
```
> Interaction.PlotActions improvement

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/Plot.cs
Now matches the inverse GetCoordinates functions
This is helpful when working with mouse events on multi-axes plots and determining nearest data point under the cursor.
> SP5 Plot: allow optional axes as arguments to GetPixel

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Tests/UnitTests/TickGenerators/DecimalTickSpacingCalculatorTests.cs
- src/ScottPlot5/ScottPlot5/AxisPanels/XAxisBase.cs
- src/ScottPlot5/ScottPlot5/AxisPanels/YAxisBase.cs
- src/ScottPlot5/ScottPlot5/Drawing.cs
- src/ScottPlot5/ScottPlot5/Interfaces/IAxis.cs
- src/ScottPlot5/ScottPlot5/Interfaces/ITickGenerator.cs
- src/ScottPlot5/ScottPlot5/LayoutEngines/Automatic.cs
- src/ScottPlot5/ScottPlot5/LayoutEngines/FixedPadding.cs
- src/ScottPlot5/ScottPlot5/Panels/ColorBar.cs
- src/ScottPlot5/ScottPlot5/Rendering/RenderActions/RegenerateTicks.cs
- src/ScottPlot5/ScottPlot5/TickGenerators/DateTimeAutomatic.cs
- src/ScottPlot5/ScottPlot5/TickGenerators/DateTimeFixedInterval.cs
- src/ScottPlot5/ScottPlot5/TickGenerators/DecimalTickSpacingCalculator.cs
- src/ScottPlot5/ScottPlot5/TickGenerators/EmptyTickGenerator.cs
- src/ScottPlot5/ScottPlot5/TickGenerators/NumericAutomatic.cs
- src/ScottPlot5/ScottPlot5/TickGenerators/NumericFixedInterval.cs
- src/ScottPlot5/ScottPlot5/TickGenerators/NumericManual.cs
A SKPaint is now passed throughout the measurement system and tick font size is respected during measurements. The logic for determining tick density is now broken into its own class so it can be more easily customized and tested. #3203
> SP5: refactor tick measurement

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Shapes.cs
- src/ScottPlot5/ScottPlot5/Primitives/Gradient.cs
- src/ScottPlot5/ScottPlot5/Primitives/GradientType.cs
Allow to create gradient fill with more than 2 colors.
This PR also fix a typo in enum name `GradiantType` ==> `GradientType`.
Example 
```cs
Coordinates[] points =
{
new (0, 0.25),
new (0.3, 0.75),
new (1, 1),
new (0.7, 0.5),
new (1, 0)
};
var poly = myPlot.Add.Polygon(points);
poly.FillStyle = new FillStyle
{
Color = Colors.Green,
HatchColor = Colors.Blue,
Hatch = new Gradient()
{
GradientType = GradientType.Radial,
Colors = new Color[] { Colors.Yellow, Colors.DarkBlue, Colors.GreenYellow, Colors.Purple },
ColorPositions = new float[] { 0.4f, 0.6f, 0.75f, 1 }
}
};
poly.LineStyle = new LineStyle
{
AntiAlias = true,
Color = Colors.Black,
Pattern = LinePattern.Dashed,
Width = 2
};
poly.MarkerStyle = new MarkerStyle(MarkerShape.OpenCircle, 8); …
```
> SP5: Add support for polycolor gradients with custom color positions

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/Primitives/FontStyle.cs
- src/ScottPlot5/ScottPlot5/Primitives/Label.cs
Fixes: https://github.com/ScottPlot/ScottPlot/issues/3335
Checked https://github.com/ScottPlot/ScottPlot/pull/2848 and https://github.com/ScottPlot/ScottPlot/issues/2419, but it seems that the issue is not actually fixed in the latest branch.
It causes critical performance issues in Linux systems.
In KUbuntu 23.10 with Avalonia 11.0.7 , the problem still exists as below:
After fixing:
Just simply modifed the code to reach the caching goals:
```cs
// public SKTypeface Typeface => CachedTypeface ?? CreateTypeface(Name, Bold, Italic); // broken
public SKTypeface Typeface => CachedTypeface ??= CreateTypeface(Name, Bold, Italic); // works
```
> SP5: Fix typeface caching

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/Introduction/Legend.cs
- src/ScottPlot5/ScottPlot5/Legends/Legend.cs
Add missed property `Orientation` to `Legend`.
Add also an additional property `AllowMultiline` to support multi-line horizontal `Legend` when legend contains too many items.
This should fix issues #3302 and #3280
> SP5: Add horizontal orientation to legend

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Avalonia/AvaPlotMenu.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Blazor/BlazorPlotMenu.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Eto/EtoPlotMenu.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/WpfPlotMenu.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms/FormsPlotMenu.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinUI/WinUIPlotMenu.cs
- src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/CustomMenu.cs
- src/ScottPlot5/ScottPlot5/Control/ContextMenuItem.cs
- src/ScottPlot5/ScottPlot5/Interfaces/IPlotMenu.cs
As discussed on Discord this PR adds the AddSeparator function to the IPlotMenu interface and the plot controls that implement it.  Each of those plot controls has been tested individually in a sandbox or demo.  Only the WinForms demo has the test checked in.
Now the following code will give you a menu separator between the _Add Text_ and _Clear_ menu items.
```cs
myPlot.Menu.Add("Add Text", (myPlot) =>
{
var txt = formsplot1.Plot.Add.Text("Test", Generate.RandomLocation());
txt.Size = 10 + Generate.RandomInteger(20);
txt.Color = Generate.RandomColor(128);
txt.Bold = true;
formsplot1.Plot.Axes.AutoScale();
formsplot1.Refresh();
});
myPlot.Menu.AddSeparator();
myPlot.Menu.Add("Clear", (formsplot1) =>
{
formsplot1.Plot.Clear(); …
```
> Add AddSeparator method to context menus

- src/ScottPlot5/ScottPlot5/DataViews/Wipe.cs
Streamer.Data.NextIndex might get updated after it's assigned to newestCount, but before it's used when populating oldest[i], which sometimes leads to array index getting out of bounds.
> Fix race condition in ScottPlot.DataViews.Wipe

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/RadialGauge.cs
- src/ScottPlot5/ScottPlot5/PlottableAdder.cs
- src/ScottPlot5/ScottPlot5/Plottables/RadialGauge.cs
- src/ScottPlot5/ScottPlot5/Plottables/RadialGaugePlot.cs
- src/ScottPlot5/ScottPlot5/Primitives/RadialGaugeMode.cs
Creates the radial gauge plottable, based on the v4 version.
Adds the cookbook recipes demonstrating the main features.
There's one caveat. The line caps (`StartCap` and `EndCap` properties) functionality is severely reduced, since Skia doesn't include the `System.Drawing.Drawing2D.LineCap` options. This is commented in the submitted code in case it is owner-implemented in the future. The only functional property is `StartCap`, which only admits one of the values of the `SKStrokeCap` enum, while the `EndCap` property is ignored throughout the code.
> SP5: Radial gauge plot

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Bar.cs
- src/ScottPlot5/ScottPlot5/Plottables/BarPlot.cs
As of 5.0.21, `BarPlot` does not show a legend even after calling `Plot.ShowLegend()` or setting `Plot.Legend.IsVisible = true`. This change is to add that functionality, using the `Scatter` implementation as a reference.
> SP5: Updated LegendItems in BarPlot

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/WpfPlot.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/WpfPlotGL.cs
This is almost exactly the same as #3373 but for WPF. Checks whether Refresh is called on a UI thread, and if not, calls asynchronous Dispatcher.BeginInvoke(Refresh).
> WPF: Redraw plots using a non-blocking background thread

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Shapes.cs
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms/Form1.cs
- src/ScottPlot5/ScottPlot5/Drawing.cs
- src/ScottPlot5/ScottPlot5/Plottables/Ellipse.cs
- src/ScottPlot5/ScottPlot5/Primitives/Color.cs
Work with R, G and B color component to handle `Color.Darken` and `Color.Lighten`  and avoid color mixing.
This should fix issue #3387.
```cs
var c1 = myPlot.Add.Circle(5, 5, 9);
var c2 = myPlot.Add.Circle(10, 0, 9);
var c3 = myPlot.Add.Circle(15, 10, 9);
c1.FillStyle.Color = Colors.Red;
c2.FillStyle.Color = c1.FillStyle.Color.Darken(.5f);
c3.FillStyle.Color = c1.FillStyle.Color.Lighten(.5f);
myPlot.SavePng("DarkenLighten.png", 240, 240);
```
> SP5: fix making colors brighter or darker

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/AxisManager.cs
- src/ScottPlot5/ScottPlot5/Grids/DefaultGrid.cs
- src/ScottPlot5/ScottPlot5/Primitives/CoordinateRange.cs
- src/ScottPlot5/ScottPlot5/TickGenerators/DecimalTickSpacingCalculator.cs
This pull request resolves issue #3397 
The issue stems from the use of terms Min and Max, which are not numerically minimum and maximum values when axes are inverted. 
The fix was to find where the assumptions were in correct and locally calculate a "trueMin" or "trueMax" value.
I believe the proper fix would be to have IAxes retain Min and Max properties, but make them a true numeric minimum and maximum. This woul dbe augmented by an "Inverted" property.
Meanwhile, IXAxis would inherit Min, Max and Inverted, and could add Left and Right properties for convenience.
Similarly, IYAxis would inherit Min, Max and Inverted properties, but could add Top and Bottom peroperties for convenience.
Unfortunately that change would require extensive changes and careful planning and woud likely …
> #3397 Resovles broken Axes labels and ticks on inverted axes

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/Control/Interaction.cs
Avoid extra ZoomRectangleClear when we don't have a zoom rectangle.
> SP5 control interaction: prevent unnecessary call to ZoomRectangleClear

- .gitignore
As per title.  Useful for those of us using the vim editor.
> Gitignore vim editor's swap files

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms/Form1.Designer.cs
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms/Form1.cs
- src/ScottPlot5/ScottPlot5/AxisPanels/XAxisBase.cs
- src/ScottPlot5/ScottPlot5/Drawing.cs
resolves #3436
before | after
---|---
> XAxisBase: improve label measurement

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/Miscellaneous/Internationalization.cs
- src/ScottPlot5/ScottPlot5/Legends/Legend.cs
- src/ScottPlot5/ScottPlot5/Plot.cs
- src/ScottPlot5/ScottPlot5/Primitives/Color.cs
- src/ScottPlot5/ScottPlot5/Primitives/FontStyle.cs
- src/ScottPlot5/ScottPlot5/Primitives/LegendItem.cs
- src/ScottPlot5/ScottPlot5/Primitives/Pixel.cs
- src/ScottPlot5/ScottPlot5/Stylers/PlotStyler.cs
This PR refactors legend rendering to allow fonts to be detected at render time. This behavior is inefficient and hidden behind an opt-in flag. Future refactoring may allow plottable objects to have a `LegendItemStyle` so they can store state. Presently `GetLegendItems()` generates new styles on every call (on every render) so there's not a good way to store font information on a per-item basis across renders.
Resolves #3440
> Legend: Improve international font support

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/Drawing.cs
- src/ScottPlot5/ScottPlot5/Legends/Legend.cs
- src/ScottPlot5/ScottPlot5/Plottables/AxisSpan.cs
- src/ScottPlot5/ScottPlot5/Plottables/Rectangle.cs
- src/ScottPlot5/ScottPlot5/Plottables/Text.cs
- src/ScottPlot5/ScottPlot5/Primitives/BackgroundStyle.cs
- src/ScottPlot5/ScottPlot5/Primitives/Bar.cs
- src/ScottPlot5/ScottPlot5/Primitives/Box.cs
- src/ScottPlot5/ScottPlot5/SampleImages.cs
... because doing so fills pixels anyway due to the default behavior of SkiaSharp
resolves #3384
> Drawing: do not draw rectangles if line width is zero

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/Axis/CustomizingGrids.cs
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/Axis/CustomizingTicks.cs
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/Introduction/Styling.cs
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/Miscellaneous/AdvancedStyling.cs
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/Miscellaneous/Internationalization.cs
- src/ScottPlot5/ScottPlot5 Tests/RenderTests/Plottable/SignalTests.cs
- src/ScottPlot5/ScottPlot5/AxisManager.cs
- src/ScottPlot5/ScottPlot5/Grids/DefaultGrid.cs
- src/ScottPlot5/ScottPlot5/Interfaces/IGrid.cs
- src/ScottPlot5/ScottPlot5/Plot.cs
- src/ScottPlot5/ScottPlot5/Primitives/GridStyle.cs
- src/ScottPlot5/ScottPlot5/Primitives/LineStyle.cs
- src/ScottPlot5/ScottPlot5/Rendering/RenderActions/RenderGridsAbovePlottables.cs
- src/ScottPlot5/ScottPlot5/Rendering/RenderActions/RenderGridsBelowPlottables.cs
- src/ScottPlot5/ScottPlot5/Stylers/FontStyler.cs
- src/ScottPlot5/ScottPlot5/Stylers/PlotStyler.cs
This PR deeply refactors the grid system to simplify how users interact with and customize the grid, as well as improving support for axis-specific grid customization and addition of custom grid systems. Many styling strategies are being simplified along the way.
* Resolves #3291 
* Resolves #3293
```cs
myPlot.Add.Signal(Generate.Sin(51));
myPlot.Add.Signal(Generate.Cos(51));
myPlot.Grid.XAxisStyle.MajorLineStyle.Color = Colors.Magenta.WithAlpha(.1);
myPlot.Grid.XAxisStyle.MajorLineStyle.Width = 5;
myPlot.Grid.YAxisStyle.MajorLineStyle.Color = Colors.Green.WithAlpha(.3);
myPlot.Grid.YAxisStyle.MajorLineStyle.Width = 2;
```
> Refactor Grid system

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/DataSources/SignalXYSourceDoubleArray.cs
- src/ScottPlot5/ScottPlot5/DataSources/SignalXYSourceGenericArray.cs
This will fix issue #3423 
<details><summary>test code:</summary>
```cs
namespace Sandbox5;
public partial class Form1 : Form
{
public Form1()
{
Size = new Size(800, 450);
Text = "ScottPlot5-WinForms for Issue 3423";
var line = formsPlot1.Plot.Add.Line(0, 0, 1, 0);
line.Label = "SP5:Line";
line.LineWidth = 5;
var signal = formsPlot1.Plot.Add.Signal(new double[] { 1, 1 });
signal.Label = "SP5:Signal";
signal.LineWidth = 5;
// SignalXYSourceDoubleArray
double[] xs1 = Generate.Consecutive(3);
double[] ys1 = Generate.Repeating(3, 2);
var signalXY1 = formsPlot1.Plot.Add.SignalXY(xs1, ys1);
signalXY1.Label = "SP5:SignalXY";
signalXY1.LineWidth = 5;
// SignalXYSourceGenericArray
float[] xs2 = Generate.Consecutive(3).Select(value => (float)value).ToArray(); …
```
> SignalXY: Fix final segment is not being rendered

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/Control/Interaction.cs
When using the middle button to draw a zoom rectangle, it was easy to accidentally roll the wheel and cause the canvas to zoom. This resulted in the zoom rectangle no longer representing the intended extents. 
This simple fix just ignores mousewheel zooming if a zoom window is currently being drawn.
> Controls: Improve ZoomRectangle behavior and axis locking

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Heatmap.cs
- src/ScottPlot5/ScottPlot5 Tests/UnitTests/ColorTests.cs
- src/ScottPlot5/ScottPlot5/Plottables/Heatmap.cs
- src/ScottPlot5/ScottPlot5/Primitives/Color.cs
This PR adds the capability to plot heatmaps with transparency. 
I see it as a stepping stone towards addressing issue #3349 
Intention is that a mask function could be defined (inside or outside of the heatmap class) to set the alpha to zero for all cells outside of a defined polygon.
I am sumbitting as a PR now because I may not tackle the masking functionality, and I think this capability stands on its own as a useful update. 
I've implemented two options. 
**A globalAlpha value** 
This sets the heatmap tansaparency to the same value over all cells.
Shown here with an underlying SignalXY:
```cs
double[] Xs = Enumerable.Range(1, 5000).Select(i => (double)i / 1000).ToArray();
var signal = WpfPlot1.Plot.Add.SignalXY(Xs, Generate.Sin(count: 5000, oscillations: 4));
double[,] data2 = …
```
> Heatmap transparency

- src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/ShowValueOnHoverMultiple.Designer.cs
- src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/ShowValueOnHoverMultiple.cs
- src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/ShowValueOnHoverMultiple.resx
- src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/WinForms Demo.csproj
As suggested in #3503, this adds a a demo for hovering over the nearest point of multiple scatter plots.
Title is "Show Value Under Mouse, Multiple Series", please advise whether to name it differently to differentiate it more from the existing demo "Show Value Under Mouse".
Also, maybe I went a little overboard by also adding a marker and a text to the hovered point?
> Demo: show value near cursor with multiple scatter plots

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/Plottables/Polygon.cs
When update polygon coordinates, xMin and xMax values are incorrectly calculated.
This with wrong xMin and xMax values
This with correct values
```cs
BlazorPlot.Plot.Add.Plottable(new ScottPlot.Plottables.Polygon(new Coordinates[]
{
new Coordinates(230326,  20654),
new Coordinates(234604,  20696),
new Coordinates(234603,  72121),
new Coordinates(233163,  72076),
new Coordinates(233047,  69547),
new Coordinates(160908,  69311),
new Coordinates(160737,  77781),
new Coordinates(158938,  77273),
new Coordinates(158717,  73368),
new Coordinates(155658,  73687),
new Coordinates(155560,  68718),
new Coordinates(155645,  67517),
new Coordinates(155300,  52133),
new Coordinates(162674,  52258),
new Coordinates(163929,  64912),
new Coordinates(231187,  65342),
new Coordinates(230949,  21750),
new …
```
> Fix IPlottable Polygon axis limits calculation

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/Rendering/RenderManager.cs
This reverts commit dc0c4b345eb3991dfe18de869d860ded7b8aa5b6.
I think the issue occurs because the methods `Canvas.Restore` are called multiple times.
Fix #3516, #3502.
> Fix rendering problems in AvaloniaUI

- CHANGELOG.md
- src/ScottPlot4/ScottPlot/Plottable/Image.cs
Hi @swharden ! 
Following your recommendation, here is a PR. I tested shortly, and it seems to work fine with the Image Plottable Mona Lisa...
thanks! :)
link for the issue: https://github.com/ScottPlot/ScottPlot/issues/3515
> ScottPlot 4 Image: GetAxisLimits() returns incorrect value fix

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/DataSources/SignalSourceDouble.cs
- src/ScottPlot5/ScottPlot5/DataSources/SignalSourceGenericArray.cs
- src/ScottPlot5/ScottPlot5/DataSources/SignalSourceGenericList.cs
- src/ScottPlot5/ScottPlot5/Interfaces/ISignalSource.cs
- src/ScottPlot5/ScottPlot5/Plottables/Signal.cs
Hi Scott,
This is PR to solve the issue of #3229 
at the Signal.LowRenderDensity,
Very slow on **SignalSourceDouble and SignalSourceGenericArray** with large size data.
Because that all of SignalSource are uses GetYs() from RenderLowDensity, and it copy all the data,
and that two sources convert all data by **NumericConversion.GenericToDoubleArray**, it reduced performance.
I refer to the TODO of ISignalSource that you written,
I added IEnumerable<double> GetYs function, have arguments of index range.
(I used IEnumerable instead of IReadOnlyList,
You just decide what you think is better.)
And, SignalSource used it in the following way:
```cs
public IEnumerable<double> GetYs(int i1, int i2)
{
for (int i = i1; i <= i2; i++)
{
yield return NumericConversion.GenericToDouble(ref Ys[i]);
}
} …
```
> improve performance of Signal.RenderLowDensity

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/Plot.cs
Fixes [#3543](https://github.com/ScottPlot/ScottPlot/issues/3543)
The exception was caused because the logic in the ternary operator was reversed. When axesOnly was true, it was returning all panels and vice versa:
```cs
// Reverse here so the "highest" axis is returned in the case some overlap.
var panels = axesOnly
? Axes.GetPanels().Reverse().OfType<IAxis>()
: Axes.GetPanels().Reverse();
```
Added check to ensure type is IAxis before returning it rather than casting the wrong type, which was what threw the exception.
```cs
public IAxis? GetAxis(Pixel pixel)
{
IPanel? panel = GetPanel(pixel, axesOnly: true);
return panel is IAxis axis ? axis : null;
}
```
> Controls: fix `InvalidCastException` when starting mouse interaction in the Title area

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/Primitives/Label.cs
For issue #3538 
In SkiaSharp, setting the StrokeWidth to 0 does not guarantee that no border will be drawn. A StrokeWidth of 0 is interpreted as the thinnest line that can be drawn on the device, which is not the same as not drawing a line at all.
So I just wrapped the code to draw the border with a conditional to only paint it if borderwidth is greater than 0. This works fine on the recipe code when setting BorderWidth = 0;
[Issue 3538](https://github.com/ScottPlot/ScottPlot/issues/3538)
```cs
[ScottPlot.Plot myPlot = new();
if (BorderWidth > 0)
{
ApplyBorderPaint(paint);
canvas.DrawRect(backgroundRect.ToSKRect(), paint);
}
```
> Label: Don't draw border when line width is 0

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Scatter.cs
- src/ScottPlot5/ScottPlot5 Tests/UnitTests/ScatterDataTests.cs
- src/ScottPlot5/ScottPlot5/DataSources/DataLoggerSource.cs
- src/ScottPlot5/ScottPlot5/DataSources/ScatterSourceDoubleArray.cs
- src/ScottPlot5/ScottPlot5/DataSources/ScatterSourceGenericArray.cs
- src/ScottPlot5/ScottPlot5/DataSources/ScatterSourceGenericList.cs
- src/ScottPlot5/ScottPlot5/DataSources/SignalXYSourceDoubleArray.cs
- src/ScottPlot5/ScottPlot5/Drawing.cs
- src/ScottPlot5/ScottPlot5/Generate.cs
- src/ScottPlot5/ScottPlot5/Plottables/DataLogger.cs
- src/ScottPlot5/ScottPlot5/Plottables/Polygon.cs
- src/ScottPlot5/ScottPlot5/Plottables/Scatter.cs
- src/ScottPlot5/ScottPlot5/Primitives/CoordinateRange.cs
Enable plotting noncontinuous lines. For example, when a DataLogger has several NaN values, those are not plotted and just skipped.
> Scatter: Allow `NaN` to draw noncontinuous lines

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/AxisRules.Designer.cs
- src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/AxisRules.cs
- src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/SignalPerformance.cs
- src/ScottPlot5/ScottPlot5/AutoScalers/FractionalAutoScaler.cs
- src/ScottPlot5/ScottPlot5/AxisManager.cs
- src/ScottPlot5/ScottPlot5/AxisRules/SquareZoomOut.cs
- src/ScottPlot5/ScottPlot5/Generate.cs
- src/ScottPlot5/ScottPlot5/RandomDataGenerator.cs
…om: 1.5, top: -1.5);
This PR fixes the axis range setting if you use the SquareZoomOut  and AutoScaler.InvertedX / Y
This code did not "keep" the SetLimit / AutoScaler.InvertedY setting cause SquareZoomOut rule just sets YAxis.Range.Set(yMin, yMax); we need to distinguish if the axis got inverted.
```cs
myPlot.Add.Signal(Generate.Sin());
myPlot.Axes.SetLimitsY(1.5, -1.5);
myPlot.Axes.SquareUnits();
```
> SquareZoomOut Axis Rule: add support for inverted axes

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WPF/MainWindow.xaml.cs
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms/Form1.cs
- src/ScottPlot5/ScottPlot5 Tests/RenderTests/Plottable/SignalTests.cs
- src/ScottPlot5/ScottPlot5/AxisManager.cs
- src/ScottPlot5/ScottPlot5/DataSources/SignalSourceDouble.cs
- src/ScottPlot5/ScottPlot5/Plottables/Signal.cs
Fixed issue  #3570 - enabling the option to invert axes of Signal plots.
- Added direction constants for inverting the axes in Signal plots. 
- Added GetVisibleYRange private method in Signal.
- Refactored variable names inside RenderLowDensity method of Signal.
> Signal: support inverted axes

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Scatter.cs
- src/ScottPlot5/ScottPlot5/Drawing.cs
- src/ScottPlot5/ScottPlot5/Interfaces/IPathStrategy.cs
- src/ScottPlot5/ScottPlot5/PathStrategies/QuadHalfPoint.cs
- src/ScottPlot5/ScottPlot5/PathStrategies/Straight.cs
- src/ScottPlot5/ScottPlot5/Plottables/Scatter.cs
This PR causes Scatter plot line segments to be connected with smooth lines when `Smooth` is `true`.
To avoid manually calculating interpolated pixels, this strategy uses SkiaSharp's built-in quadratic Bezier curved path functionality to draw a curved line from a starting point to an ending point with one control point https://learn.microsoft.com/en-us/dotnet/api/skiasharp.skpath.quadto?view=skiasharp-2.88
This strategy avoids "overshoot" by splitting each line segment in two and drawing a curve to and from that midpoint. The present code doesn't function as expected if X points are not always ascending. Additional strategies could be implemented, and the code could be refactored in the future to allow uses to select one of multiple strategies (including user-defined ones).
Related:
* …
> Scatter: add support for smooth lines

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Heatmap.cs
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms/Form1.cs
- src/ScottPlot5/ScottPlot5/AxisPanels/AxisBase.cs
- src/ScottPlot5/ScottPlot5/AxisPanels/XAxisBase.cs
- src/ScottPlot5/ScottPlot5/AxisPanels/YAxisBase.cs
- src/ScottPlot5/ScottPlot5/DataOperations.cs
- src/ScottPlot5/ScottPlot5/Drawing.cs
- src/ScottPlot5/ScottPlot5/Extensions/SkiaSharpExtensions.cs
- src/ScottPlot5/ScottPlot5/Interfaces/ILayoutEngine.cs
- src/ScottPlot5/ScottPlot5/LayoutEngines/Automatic.cs
- src/ScottPlot5/ScottPlot5/LayoutEngines/FixedDataArea.cs
- src/ScottPlot5/ScottPlot5/LayoutEngines/FixedPadding.cs
- src/ScottPlot5/ScottPlot5/LayoutEngines/MatchedDataRect.cs
- src/ScottPlot5/ScottPlot5/Panels/ColorBar.cs
- src/ScottPlot5/ScottPlot5/Plot.cs
- src/ScottPlot5/ScottPlot5/Primitives/PixelRect.cs
- src/ScottPlot5/ScottPlot5/RenderPack.cs
Addresses:
* #3294 
* #3560 
* #3586
* #3608 
```cs
double[,] data = SampleData.MonaLisa();
var hm1 = myPlot.Add.Heatmap(data);
hm1.Extent = new(0, 1, 0, 1);
hm1.Colormap = new ScottPlot.Colormaps.Turbo();
myPlot.Add.ColorBar(hm1);
var hm2 = myPlot.Add.Heatmap(data);
hm2.Extent = new(1.5, 2.5, 0, 1);
hm2.Colormap = new ScottPlot.Colormaps.Viridis();
myPlot.Add.ColorBar(hm2);
```
> Colorbar: improve layout and add support for multiple colorbars

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/AxisLines.cs
- src/ScottPlot5/ScottPlot5/Plottables/AxisLine.cs
If an AxisLine (horizontal or vertical) has its Text property set it would always be included in any legend - both the automatic or manually built legends. The Text property is also used to display the text along the appropriate axis for the line so it is a valid use case to want the Text set but not add the line to the legend.
This change adds an ExcludeFromLegend property to the AxisLine base class which defaults to false (no change to current default behavior). Setting this property to true keeps the line out of the legend regardless of the Text property being set or not.
A cookbook recipe was added demonstrating how the AxisLines and legend work together.  The recipe code and result is shown below.
```cs
myPlot.Add.Signal(Generate.Sin());
var axLine1 …
```
> AxisLines: Allow them to be excluded from the legend

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/WpfPlot.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/WpfPlotBase.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/WpfPlotExtensions.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/WpfPlotGL.cs
Mouse interaction with `ScottPlot` 5 WPF control is not very user friendly.
There are some internals to know:
- the WPF control is a **Custom Control** to allow customization via a user define style
- the style must contains an item called `PART_SKElement`. For "standard" SkiaSharp it must be a `SKElement`, and for the OpenGL version it must be a `SKGLElement`.
- the plot rendered output will be draw on `PART_SKElement`. So if the style do not contain it, there will be nothing visible for the user.
- as the style can be customized, the origin of `PART_SKElement` may not be the upper left corner of the WPF control
Because this maybe very confusing for the control user, I have updated the SP5 WPF control to:
- use `PART_SKElement` as reference to calculate mouse pixel position on plot …
> SP5 / WpfPlot: simplify mouse coordinate with display scaling

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Scatter.cs
- src/ScottPlot5/ScottPlot5/PathStrategies/CubicSpline.cs
- src/ScottPlot5/ScottPlot5/Plottables/Markers.cs
- src/ScottPlot5/ScottPlot5/Plottables/Scatter.cs
- src/ScottPlot5/ScottPlot5/Primitives/Pixel.cs
Implement cubic spline interpolation.
Catmull-rom splines are converted to Bezier curves according to this article:
https://link.springer.com/article/10.1007/s42979-021-00770-x
> Scatter: Add cubic spline interpolation

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/VectorField.cs
- src/ScottPlot5/ScottPlot5 Tests/CodeTests/ForbiddenCodeTests.cs
- src/ScottPlot5/ScottPlot5/DataSources/VectorFieldDataSourceCoordinatesList.cs
- src/ScottPlot5/ScottPlot5/Drawing.cs
- src/ScottPlot5/ScottPlot5/Interfaces/IVectorFieldSource.cs
- src/ScottPlot5/ScottPlot5/PathStrategies/Arrows.cs
- src/ScottPlot5/ScottPlot5/Plot.cs
- src/ScottPlot5/ScottPlot5/PlottableAdder.cs
- src/ScottPlot5/ScottPlot5/Plottables/VectorField.cs
- src/ScottPlot5/ScottPlot5/Primitives/ArrowAnchor.cs
- src/ScottPlot5/ScottPlot5/Primitives/ArrowStyle.cs
- src/ScottPlot5/ScottPlot5/Primitives/BackgroundStyle.cs
- src/ScottPlot5/ScottPlot5/Primitives/RootedCoordinateVector.cs
- src/ScottPlot5/ScottPlot5/Primitives/RootedPixelVector.cs
This example is lifted from the 4.1 cookbook:
```cs
var vectors = new List<RootedCoordinateVector>();
double[] xs = Generate.Consecutive(20, 0.5, -5);
double[] ys = Generate.Consecutive(20, 0.5, -5);
float r = 0.5f;
for (int i = 0; i < xs.Length; i++)
{
for (int j = 0; j < ys.Length; j++)
{
vectors.Add(new RootedCoordinateVector(new(xs[i], ys[j]), new((float)ys[j], -9.81f / r * (float)Math.Sin(xs[i]))));
}
}
var field = new VectorField(new VectorFieldDataSourceCoordinatesList(vectors));
WpfPlot1.Plot.PlottableList.Add(field);
```
> Vector Field

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/MouseTracker.cs
- src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/ShowValueOnHoverMultiple.cs
- src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Program.cs
- src/ScottPlot5/ScottPlot5 Tests/RenderTests/Plottable/AxisLineTests.cs
- src/ScottPlot5/ScottPlot5/PlottableAdder.cs
- src/ScottPlot5/ScottPlot5/Plottables/AxisLine.cs
- src/ScottPlot5/ScottPlot5/Plottables/Crosshair.cs
Used two AxisLines as Crosshair. This allows more flexible reusage of their features like the Text.
MouseTracker Demo:
> Used two lines in Crosshair to reuse their functionalities

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/AxisLines.cs
- src/ScottPlot5/ScottPlot5/PlottableAdder.cs
- src/ScottPlot5/ScottPlot5/Plottables/AxisLine.cs
- src/ScottPlot5/ScottPlot5/Plottables/HorizontalLine.cs
- src/ScottPlot5/ScottPlot5/Plottables/VerticalLine.cs
Fixes #3624 
New flag on AxisLine objects called UseAutoAlignment.  Defaults to true, if set to false the Label.Alignment property not set to the AxisLine default.  Gives full control over the label positioning, allowing such things as rotating the label sensibly.
New cookbook recipe is included in the PR.  Recipe is shown below along with the resulting plot below that.
```cs
myPlot.Add.Signal(Generate.Sin());
var axLine1 = myPlot.Add.VerticalLine(42);
axLine1.Text = "Line 1";
axLine1.Label.Rotation = -90;
axLine1.UseAutoAlignment = false;   // Disable automatic alignment
axLine1.Label.Alignment = Alignment.MiddleRight;
var axLine2 = myPlot.Add.HorizontalLine(0.75);
axLine2.Text = "Line 2";
axLine2.Label.Rotation = 0;
axLine2.UseAutoAlignment = false; …
```
> AxisLine: Allow override of automatic label alignment

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/DataLogger.Designer.cs
- src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/DataLogger.cs
- src/ScottPlot5/ScottPlot5/AutoScalers/FractionalAutoScaler.cs
- src/ScottPlot5/ScottPlot5/Plottables/DataLogger.cs
There was a little bug in `FractionalAutoScaler`, data were always taken from default axes left and bottom and not from the axes given as parameter.
I have changed the Demo application to add a checkbox to toggle between left and right axis for the `DataLogger`.
This should fix issue #3637.
> SP5: fix DataLogger scrolling when not using default axis

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/AxisRules.cs
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms/Form1.cs
- src/ScottPlot5/ScottPlot5 Tests/UnitTests/AxisRuleTests.cs
- src/ScottPlot5/ScottPlot5/AxisManager.cs
- src/ScottPlot5/ScottPlot5/AxisRules/LockedBottom.cs
- src/ScottPlot5/ScottPlot5/AxisRules/LockedCenterX.cs
- src/ScottPlot5/ScottPlot5/AxisRules/LockedCenterY.cs
- src/ScottPlot5/ScottPlot5/AxisRules/LockedHorizontal.cs
- src/ScottPlot5/ScottPlot5/AxisRules/LockedLeft.cs
- src/ScottPlot5/ScottPlot5/AxisRules/LockedRight.cs
- src/ScottPlot5/ScottPlot5/AxisRules/LockedTop.cs
- src/ScottPlot5/ScottPlot5/AxisRules/LockedVertical.cs
- src/ScottPlot5/ScottPlot5/AxisRules/MaximumBoundary.cs
- src/ScottPlot5/ScottPlot5/AxisRules/MaximumSpan.cs
- src/ScottPlot5/ScottPlot5/AxisRules/MinimumBoundary.cs
- src/ScottPlot5/ScottPlot5/AxisRules/MinimumSpan.cs
- src/ScottPlot5/ScottPlot5/AxisRules/SnapToTicksX.cs
- src/ScottPlot5/ScottPlot5/AxisRules/SnapToTicksY.cs
- src/ScottPlot5/ScottPlot5/AxisRules/SquarePreserveX.cs
- src/ScottPlot5/ScottPlot5/AxisRules/SquarePreserveY.cs
- src/ScottPlot5/ScottPlot5/AxisRules/SquareZoomOut.cs
- src/ScottPlot5/ScottPlot5/Primitives/AxisLimits.cs
Rewrites logic of axis rules to force the user to specify the desired limits rather than taking from from the previous render. This ensures all axis rules can be applied and used immediately upon the first render.
* #3674 
* #3547
> AxisRules: refactor to cut dependence on previous renders

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/Plottables/Markers.cs
Calling ToArray() causes extra memory allocation, as specified in TODO:
```
Large Object Heap: code that allocates a lot of memory in LOH
Allocated object type: Coordinates[]
Last observation: 2024-04-24 11:59 MyApp.exe
Allocated size: 4 278,4 MB
at Enumerable+ListPartition<Coordinates>.ToList()
at Markers.Render(RenderPack) in /_/src/ScottPlot5/ScottPlot5/Plottables/Markers.cs:line 38 column 13
at RenderPlottables.Render(RenderPack) in /_/src/ScottPlot5/ScottPlot5/Rendering/RenderActions/RenderPlottables.cs:line 22 column 17
```
Use lazy Linq query instead.
> Avoid excessive memory allocation in Markers

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/AxisPanels/XAxisBase.cs
- src/ScottPlot5/ScottPlot5/AxisPanels/YAxisBase.cs
If the zoom level is too big, no ticks are generated an Measure methods throw an exception.
> Prevent exception when no ticks have been generated

- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms3D/Form1.Designer.cs
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms3D/Form1.cs
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms3D/Form1.resx
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms3D/FormsPlot3D.cs
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms3D/IPlottable3D.cs
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms3D/Plot3D.cs
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms3D/Plottables3D/Axis3D.cs
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms3D/Plottables3D/Line3D.cs
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms3D/Plottables3D/Scatter3D.cs
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms3D/Primitives3D/Line3D.cs
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms3D/Primitives3D/Point3D.cs
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms3D/Primitives3D/Rotation3D.cs
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms3D/Program.cs
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms3D/RenderPack3D.cs
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms3D/Sandbox.WinForms3D.csproj
- src/ScottPlot5/ScottPlot5.sln
This PR adds a `Sandbox.WinForms3D` project to facilitate experimentation with 3D plot types. A MVP control is provided with a few 3D primitives and interfaces, but there is a lot of room for improvement and extension. 
High priority next steps that come to mind include:
* non-orthographic projection perspective (this may be a 2-line modification)
* improved center of rotation
* ability to render flat surfaces in 3D space by creating a polygon from their vertices
* addition of 3D volume primitives like `Rectangle3D` which have a collection of `Line3D` and `Surface3D` objects
* a more carefully thought out UI which allows rotation along specific axes
> Sandbox: 3D plot

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/DataSources/SignalConstSource.cs
- src/ScottPlot5/ScottPlot5/DataSources/SignalConstSourceDoubleArray.cs
- src/ScottPlot5/ScottPlot5/Plottables/SignalConst.cs
As @StendProg noted in https://github.com/ScottPlot/ScottPlot/pull/3718#issuecomment-2094355113 we were not using the segment tree in `GetLimitsY`, instead falling back to linear search.
This massively improves performance, for me `SignalConst` could actually be slower than `Signal` for very large datasets (though still faster for more moderately-sized ones), possibly because of the memory cost of the tree. With this change `SignalConst` is much faster, and outperforms the new `FastSignalSourceDouble`. Below is a screenshot of the benchmark demo:
> SignalConst: Uses Segment Tree for GetLimitsY

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/Axis/DateTimeAxes.cs
- src/ScottPlot5/ScottPlot5 Tests/Unit Tests/UnitTests/TickGenerators/DateTimeFixedIntervalsTests.cs
- src/ScottPlot5/ScottPlot5/TickGenerators/DateTimeFixedInterval.cs
Fixes #3408
No breaking API changes, only optional params/properties added.
https://github.com/ScottPlot/ScottPlot/assets/41730826/2fbd2061-994a-4b98-a122-f27ff00b0fa2
It would be nice if fixed-width tick labels also had logic to hide when overlap started... but not in this PR.
> Ticks, Tests, Cookbook: Improve DateTimeFixedInterval

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/Axis/CustomizingTicks.cs
- src/ScottPlot5/ScottPlot5/Generate.cs
- src/ScottPlot5/ScottPlot5/TickGenerators/DateTimeAutomatic.cs
Hi! With this request, I want to add a label formatter for the datetimeautomatic tick generator. At the moment, we cannot set a custom label formatter - we are content with "presets" (timeunits), but with labelformatter we can customize the display of date and time.
For example:
```cs
WpfPlot1.Plot.Axes.DateTimeTicksBottom();
((DateTimeAutomatic)WpfPlot1.Plot.Axes.Bottom.TickGenerator).LabelFormatter = LabelFormatter;
string LabelFormatter(DateTime arg)
{
return arg is { Hour: 0, Minute: 0, Second: 0 } ? arg.ToShortDateString() : arg.ToLongTimeString();
}
```
I hope I've brought a useful feature.
> DateTimeAutomatic: Add `LabelFormatter` property

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/LegendLayouts/Wrapping.cs
- src/ScottPlot5/ScottPlot5/Primitives/Legend.cs
- src/ScottPlot5/ScottPlot5/Primitives/PixelRect.cs
Currently the legend overflows the DataRect if the DataRect size is too small:
With this change it will fit the DataRect and the contents will be clipped to the LegendRect:
> Prevent legend overflow

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/Control/InputBindings.cs
- src/ScottPlot5/ScottPlot5/Control/Interaction.cs
Allow users to customize the lock logic for X and Y axes. 
In my use case, the mouse wheel only zooms X. 
If the right mouse button is pressed, the logic remains consistent with previous behavior.
This is due to the fact that under typical circumstances, I am examining signal data and don't need to zoom the Y-axis.
Here is my code
```
public override bool ShouldLockY(IEnumerable<Key> keys, MouseButton? button = null)
{
if (button == DragZoomButton)
{
return base.ShouldLockY(keys);
}
return !base.ShouldLockY(keys);
}
```
> Add override support for axis lock keys in InputBindings

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/Control/Interaction.cs
A double call to `Interactions.Disable()` resulted in the fact that interactions could not be restored with `Enable()` afterwards.
In this PR a special flag `Disabled` was introduced. It is now possible to call `Disable()` many times and then restore interactions with `Enable()` afterwards.
> Disable() double call fix.

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/Control/StandardActions.cs
Addresses #3886 
Moves the line calcualtign a scaled pixel coordinate to the top of the function, then uses the scaled pixel (instead of the passed in pixel) when testing for axisUnderMouse
bug fix verified using same code as described in bug report:
```cs
using System.Windows;
namespace Sandbox.WPF;
public partial class MainWindow : Window
{
public MainWindow()
{
WpfPlot1.Plot.Add.Signal(Generate.Sin());
WpfPlot1.Plot.Add.Signal(Generate.Cos());
WpfPlot1.Plot.ScaleFactor = 2.5;
}
}
```
> GetAxis now uses a scaled pixel (allows for ScaleFactor)

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/Control/Interaction.cs
Alt-left click now used to start drawing the rectangle only.  Alt key is ignored for the remainder of the region's rectangle draw and The zoom occurs upon left click button release only.
Resolves #3845
> Controls: Improve alt-left click to draw zoom region

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/DataSources/SignalXYSourceDoubleArray.cs
Reolution for #3812 had introduced an incorrect final pixel location for rotated SignalXY plots.
This was resolved by a swapping of Xs and Ys coordinates when defining the additional "lastPoint" value. 
_Note, we could consider renaming Xs and Ys to something like independentValues and dependentValues respectively. Not sure if that will be intuitove to all developers though._
Using the sample code provided in comment on #3812  the fix provided no longer shows a distored line at top of the plot:
Second bug was pre-existing, and became apparent when zoomed into the series to observe the final pixel. 
Rotated SignalXY series were performing an incorrect interpolation for the final pixel location (another mix-up of Xs and Ys).
Code to demonstrate this issue is as follows:
```cs …
```
> BugFixes to Rotated SignalXY plots

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/Plot.cs
- src/ScottPlot5/ScottPlot5/Rendering/RenderManager.cs
I had a requirement to synchronise two vertical axes (representing depth and elevation), but:
- Their values would be offset by a user specificed value (i.e. the ground surface elevation)
- The depth axis (only) is snapping to tick intervals (using the SnapToTicksY axis rule). 
I was finding that if the user changed either vertical axis the other axis would update using the invoked AxisLimitsChanged event, but the render was already in progress, so the change was not seen until the next render occurred. This meant the two axes did not have the correct synchronisation.
The solution implemented in this PR is to test for changes made to axis limits by invoked events, and set a flag in the RenderManager to indicate that a repeat render is required. 
However, my scenario was even more complex …
> Repeat render if changes are made in invoked events

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/Primitives/Color.cs
- src/ScottPlot5/ScottPlot5/Primitives/Colors.cs
Adding a method to convert from ScottPlot.Color to System.Drawing.Color.
#3953
function name update to ToColor
sample from linqpad
```cs
var c = ConvertColor(ScottPlot.Color.FromHex("#CCCCCC"));
c.Dump();
static System.Drawing.Color ConvertColor(ScottPlot.Color color)
{
return System.Drawing.Color.FromArgb(color.A, color.R, color.G, color.B);	
}
```
result from dump
> color conversion

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms/FormsPlotExtensions.cs
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.Console/Program.cs
- src/ScottPlot5/ScottPlot5/Primitives/SavedImageInfo.cs
adding requested functionality for writing the file path to the console, briefly looked at the clipboard request too, but it may be a little more involved for different systems, or have to introduce another library to abstract the clipboard, so, i didn't want to introduce a new dependency.  
#3943
```cs
Plot plt = new();
plt.Add.Signal(Generate.Sin());
plt.Add.Signal(Generate.Cos());
plt.SavePng("test.png", 600, 300).ConsoleWriteFilename();
```
> adding console write file name function

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/Axis/AdvancedAxis.cs
- src/ScottPlot5/ScottPlot5/AxisManager.cs
- src/ScottPlot5/ScottPlot5/AxisPanels/AxisBase.cs
- src/ScottPlot5/ScottPlot5/Primitives/GridStyle.cs
- src/ScottPlot5/ScottPlot5/Primitives/TickMarkStyle.cs
Allow users to be able to disable antialiasing on grid lines and ticks, which to my mind creates a more pleasing graph as the aa lines look blurry. The defaults have been left as they were, so this is an "opt into" change.
Before
After (with the configuration code below)
```
WpfPlot1.Plot.Axes.Left.FrameLineStyle.AntiAlias = false;
WpfPlot1.Plot.Axes.Top.FrameLineStyle.AntiAlias = false;
WpfPlot1.Plot.Axes.Right.FrameLineStyle.AntiAlias = false;
WpfPlot1.Plot.Axes.Bottom.FrameLineStyle.AntiAlias = false;
WpfPlot1.Plot.Grid.XAxisStyle.MajorLineStyle.AntiAlias = false;
WpfPlot1.Plot.Grid.YAxisStyle.MajorLineStyle.AntiAlias = false;
WpfPlot1.Plot.Axes.Left.MajorTickStyle.IsAntialias = false;
WpfPlot1.Plot.Axes.Left.MinorTickStyle.IsAntialias = false; …
```
> Axes: improve sharpness of axis lines, tick marks, and grid lines

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.Console/Program.cs
- src/ScottPlot5/ScottPlot5 Tests/Unit Tests/RenderTests/Plottable/SignalTests.cs
- src/ScottPlot5/ScottPlot5/DataSources/SignalSourceGenericList.cs
- src/ScottPlot5/ScottPlot5/PlottableAdder.cs
Added IReadOnlyList adder for creating a new signal.  Just creates a generic list from the read only one.
Not sure this makes sense, as users could easily do the ToList() themselves...
closes #3942
```cs
public Signal Signal<T>(IReadOnlyList<T> ys, double period = 1, Color? color = null)
{
SignalSourceGenericList<T> source = new(ys.ToList(), period);
return Signal(source, color);
}
```
> Signal: improve support for IReadOnlyList<T>

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/Statistics/LinearRegression.cs
This pull request adds a new constructor to the `LinearRegression` struct that accepts a `List<Coordinates>`. It simplifies creating a `LinearRegression` instance from a collection of coordinates.
- Added a constructor overload for `LinearRegression` that accepts `List<Coordinates>`.
> Added a constructor overload that accepts List<Coordinates>

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/Introduction/Styling.cs
- src/ScottPlot5/ScottPlot5/Interfaces/IColormap.cs
I implemented a slightly different version of the `GetColors` method in `IColormapExtensions` based on #3947.
I'm not sure if this meets the requirements of #3947, so feel free to make changes.
> Colormap: shortcut to get a range of colors

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/Primitives/CoordinateLine.cs
- src/ScottPlot5/ScottPlot5/Statistics/LinearRegression.cs
I added the required functions based on this issue 
CoordinateLine: add constructor overloads for accepting a point and slope #3986
> CoordinateLine: add constructor overloads

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/DataSources/DataLoggerSource.cs
This is a small PR to add a way to reset Min/Max values in the DataLoggerSource class.
Mentioned here: https://github.com/ScottPlot/ScottPlot/issues/3969
> Added ResetMinAndMaxValues() to DataLoggerSource.cs

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/Control/StandardActions.cs
- src/ScottPlot5/ScottPlot5/Plot.cs
- src/ScottPlot5/ScottPlot5/Primitives/Pixel.cs
If you set the ScaleFactor to a value greater than 1, then interaction with the Axis Panels (mouse interactions) was incorrect.
To repro the issue (without these changes), set the scale factor to something like 1.5 and then try to perform a marquee select in the **YAxis only** in the area pointed to by the arrow. You'll notice it doesn't work.
These changes scale the mouse pos like we do with all the other functions.
I have also cleaned up some of the Scale factor code
- removed unnecessary checks of Scale factor == 1 (multiply or divide by 1 wont change anything)
- added helper methods to reduce some of the duplicate code.
> Fix interaction of axis panels when scale factor is more than 1

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/Introduction/Styling.cs
- src/ScottPlot5/ScottPlot5/AxisManager.cs
- src/ScottPlot5/ScottPlot5/AxisPanels/AxisBase.cs
- src/ScottPlot5/ScottPlot5/Drawing.cs
- src/ScottPlot5/ScottPlot5/Plot.cs
- src/ScottPlot5/ScottPlot5/Primitives/Box.cs
- src/ScottPlot5/ScottPlot5/Primitives/GridStyle.cs
- src/ScottPlot5/ScottPlot5/Primitives/LineStyle.cs
- src/ScottPlot5/ScottPlot5/Primitives/TickMarkStyle.cs
This PR is in relation to https://github.com/ScottPlot/ScottPlot/issues/3977
`Hairline` is only applicable when `ScaleFactor` is greater than 1. If the `ScaleFactor` is 1, you won't see the visual artefacts mentioned below.
When `Hairline` is set to true, and the `Width` is 0, it will instruct Skia to render a single pixel line no matter the scaling factor.
The first image shows a scaling of 1.5, without `Hairline`, and `AntiAliasing` disabled on the second Box
Notice the lines are inconsistent in their width. Its more evident if you resize the window.
The second image shows the same setup, with `Hairline` enabled on both the Grid and second Box
I have made `Hairline` available on both GridStyles and LineStyles, and it is OptIn - so the current behaviour is not changed.
I have also added …
> LineStyle.Hairline: Option for single pixel line widths regardless of scale factor

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Tests/Unit Tests/RenderTests/Plottable/AxisSpanTests.cs
- src/ScottPlot5/ScottPlot5/Plottables/HorizontalSpan.cs
- src/ScottPlot5/ScottPlot5/Plottables/VerticalSpan.cs
Just a simple patch. 
When the axis span is less than 1, force the mean value ±0.5 as the new range values.
like this
``` csharp
if (vert.Span < 1)
{
float middle = (vert.Top + vert.Bottom) / 2;
vert = new(middle - 0.5F, middle + 0.5F);
}
```
Are there other aspects to consider?
#3968
> Axis span: ensure rendered rectangle is at least 1px wide

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/DataSources/SignalXYSourceDoubleArray.cs
- src/ScottPlot5/ScottPlot5/DataSources/SignalXYSourceGenericArray.cs
The `SignalXY` `GetNearestX()` maximum distance check is now performed for the right mouse position as well.
> Add missing maxDistance check for right border

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Tests/Unit Tests/UnitTests/AxisLimitTests.cs
- src/ScottPlot5/ScottPlot5/Primitives/AxisLimits.cs
`WithZoom` was using property `XRange` instead of local variable `xRange`. Also avoiding heap allocations.
> Fix WithZoom in AxisLimits

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Tests/Unit Tests/Paths.cs
- src/ScottPlot5/ScottPlot5 Tests/Unit Tests/RenderTests/LegendTests.cs
- src/ScottPlot5/ScottPlot5/Primitives/Label.cs
- src/ScottPlot5/ScottPlot5/Primitives/LabelStyleProperties.cs
- src/ScottPlot5/ScottPlot5/Primitives/Legend.cs
Adds `SKTypeface? Typeface` property to `Label`, `LabelStyle`, and `Legend` allowing objects with text to be supplied a custom typeface. This strategy works for automatically generated and manually added legend items too. 
* Resolves #3825
* Resolves #3830
```cs
SKTypeface customTypeface = SKTypeface.FromFile(ttfFilePath);
plot.Legend.ManualItems.Add(new LegendItem()
{
LabelText = "Manual Item",
LabelFontColor = Colors.Blue,
LabelFontSize = 26,
LabelTypeface = customTypeface,
});
```
> Label.Typeface

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Tests/Unit Tests/RenderTests/LabelTests.cs
- src/ScottPlot5/ScottPlot5/Primitives/LabelStyle.cs
- src/ScottPlot5/ScottPlot5/Primitives/MeasuredText.cs
* resolves #3859
* resolves #3958
```cs
Plot plot = new();
var txt1 = plot.Add.Text($"aaa\nbbbbbbbbbbb\nccc", 0, 0);
txt1.Alignment = Alignment.MiddleLeft;
txt1.LabelBackgroundColor = Colors.SkyBlue;
var txt2 = plot.Add.Text($"aaa\nbbbbbbbbbbb\nccc", 1, 1);
txt2.Alignment = Alignment.MiddleCenter;
txt2.LabelBackgroundColor = Colors.SkyBlue;
var txt3 = plot.Add.Text($"aaa\nbbbbbbbbbbb\nccc", 2, 2);
txt3.Alignment = Alignment.MiddleRight;
txt3.LabelBackgroundColor = Colors.SkyBlue;
```
> LabelStyle: improve horizontal alignment for multiline strings

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/AxisLines.cs
- src/ScottPlot5/ScottPlot5/Plottables/AxisLine.cs
- src/ScottPlot5/ScottPlot5/Plottables/AxisSpan.cs
- src/ScottPlot5/ScottPlot5/Plottables/Crosshair.cs
- src/ScottPlot5/ScottPlot5/Plottables/HorizontalLine.cs
- src/ScottPlot5/ScottPlot5/Plottables/HorizontalSpan.cs
- src/ScottPlot5/ScottPlot5/Plottables/VerticalLine.cs
- src/ScottPlot5/ScottPlot5/Plottables/VerticalSpan.cs
Port `IgnoreAxisAuto` feature from `ScottPlot` 4.1 to 5.0
Add support for `Crosshair`, `HorizontalLine`, `VerticalLine`, `HorizonzalSpan` and `VerticalSpan`.
Port Recipe.
This should fix issue #4067.
> Axis line and span: Add `EnableAutoscale` property

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/DataSources/SignalConstSource.cs
- src/ScottPlot5/ScottPlot5/Plottables/SignalConst.cs
`SignalConst` has as `LegendText` field but did not defines `LegendItems`!
Also change `LineStyle` initialization for set `Width` to 1.
This should fix issue #4081.
Doing this, I found a bug in `SignalConst` rendering for first points:
```cs
var sign = myPlot.Add.SignalConst(Generate.Sin(phase:Math.PI));
sign.LegendText = "My fabulous SignalConst LegendText";
var sign2 = myPlot.Add.Signal(Generate.Sin());
sign2.LegendText = "My fabulous Signal LegendText";
myPlot.ShowLegend();
myPlot.SavePng("bug_4081.png", 800, 600);
```
> SignalConst: Enable `LegendText`, increase default marker size, and fix first point position

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/Grids/DefaultGrid.cs
Grid rendering micro-optimization that eliminates unnecessary calculations if the vertical (X) or horizontal (Y) grid is invisible.
> Grid: eliminate allocations for ticks of invisible axes

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/TickGenerators/NumericFixedInterval.cs
This commit fixes a bug where the first tick of a NumericalFixedInterval was not generated.
Adds a simple `- Interval` in the calculation for the lowest bound to generate the lowest tick.
>  Fix : NumericFixedInterval lowest tick was not included

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/TickGenerators/LabelFormatters.cs
- src/ScottPlot5/ScottPlot5/TickGenerators/NumericAutomatic.cs
- src/ScottPlot5/ScottPlot5/TickGenerators/NumericFixedInterval.cs
`NumericFixedInterval` is now able to be instanciated using doubles instead of just integers, without changing the logic behind. 
`NumericFixedInterval`  now has a property `LabelFormatter` like `NumericAutomatic`.
This PR creates a static class `DefaultFormatterHelper` to extract the `DefaultLabelFormatter` from `NumericAutomatic` so that it can be also used in `NumericFixedInterval`.
The modification from int to double in the constructor is not a breaking change, as illustrated by this code extract:
```cs
public class Test(double t = 1.0f)
{
public double T { get; set; } = t;
}
public static class Program
{
public static void Main()
{
int v = 12;  
Test t = new(v);
Console.WriteLine(t.T); // -> 12
}
}
```
> Ticks: Allow `NumericFixedInterval` interval to be a `double`

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/PlottableAdder.cs
Access modified change
Exposing PlottableAdder.Plot as requested in #4107
> PlottablerAdder: make `Plot` public

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/AxisManager.cs
When axes are set to inverted and then an AutoScale is initiated (i.e. middle mouse button) the plot was restoring the axes back to normal directions. 
This was caused by the optional parameters on AutoScale being defaulted to false instead of null. 
The subsequent use of the null-coalescing operator '??' was therefore having no purpose. 
Now the default is null, so if no local parameters are provided AutoScaler parameters are used to decide on axis direction
> AxisManager: Improve `AutoScale()` support for inverted axes

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Scatter.cs
- src/ScottPlot5/ScottPlot5/Plottables/Scatter.cs
Add X-direction gradient fill to `Scatter` plot.
User can set stop points and corresponding colors.
Like Microsoft word - Create a custom gradient
https://support.microsoft.com/en-us/topic/add-a-gradient-color-to-a-shape-11cf6392-723c-4be8-840a-b2dab4b2ba3e
For example the following picture is the spectrum of an LED.
**When `FillX` is set, it will be used instead of the setting of `FillYColor` for rendering.** 
In `Render()`, I set the `Hatch` property in `FillStyle`.
And calculate the `ColorPositions` and `Colors` of `Gradient` based on the current chart position.
- Since in `Gradient`, the range of `ColorPositions` is 0~1, so a conversion calculation has to be done on this.
- When a graph is cut off by an edge, the colors must be interpolated in order to get the correct cutoff point …
> Scatter: Added X-axis gradient fill area

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/DataSources/SignalXYSourceDoubleArray.cs
- src/ScottPlot5/ScottPlot5/DataSources/SignalXYSourceGenericArray.cs
- src/ScottPlot5/ScottPlot5/Interfaces/ISignalXYSource.cs
This PR resolves some minor and some major rendering artefacts that were occurrign in Rotated SignalXY plots.
This incorporates changes made in a prevfious PR (#4102 ) that also attempted to refactor the plottable type to remove confusion between X and Y data types and X and Y axis directions.
The main artefact was best illustrated when plotting a rotated signal on inverted axes
```cs
var size = 500;
var cycles = 1;
double[] xs = Generate.Consecutive(size);
double[] ys = Generate.Sin(count: xs.Length, oscillations: cycles);
var sig1 = WpfPlot1.Plot.Add.SignalXY(xs, ys);
sig1.Data.Rotated = true;
WpfPlot1.Plot.Axes.InvertX();
WpfPlot1.Plot.Axes.InvertY();
```
After this PR the same code produces a smooth sinusoid:
The other artefacts demonstrated in #4102 are also resolved.
The PR also:
- …
> SignalXY: Improvements to rending and handling of rotated plots

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/Plottables/Signal.cs
- src/ScottPlot5/ScottPlot5/Plottables/SignalConst.cs
opt-in flag for improved anti-aliased rendering in static plots. Resolves #4153
> Signal: AlwaysUseLowDensityMode

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/Primitives/SavedImageInfo.cs
Plot: Improved default `ToString()` implementation for the object returned when saving image files. Resolves #4154.
> Plot: SavedImageInfo.ToString()

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Bar.cs
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Lollipop.cs
- src/ScottPlot5/ScottPlot5/PlottableAdder.cs
- src/ScottPlot5/ScottPlot5/Plottables/LollipopPlot.cs
- src/ScottPlot5/ScottPlot5/Primitives/Coordinates.cs
resolve #4183
Copy the Lollipop Cookbook from scottplot 4 and adjust it slightly.
from my added cookbook - Lollipop Plot Customizations
```cs
double[] values = { 26, 20, 23, 7, 16 };
double[] positions = { 2, 4, 8, 10, 20 };
var lollipop = plt.Add.Lollipop(values, positions);
lollipop.Orientation = ScottPlot.Orientation.Horizontal;
lollipop.MarkerColor = ScottPlot.Colors.Red;
lollipop.MarkerSize = 10;
```
> Added Lollipop plot

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Pie.cs
- src/ScottPlot5/ScottPlot5 Tests/Unit Tests/UnitTests/PrimitiveTests/AngleTests.cs
- src/ScottPlot5/ScottPlot5/Plottables/Coxcomb.cs
- src/ScottPlot5/ScottPlot5/Plottables/Phasor.cs
- src/ScottPlot5/ScottPlot5/Plottables/Pie.cs
- src/ScottPlot5/ScottPlot5/Plottables/PieBase.cs
- src/ScottPlot5/ScottPlot5/Plottables/PolarAxis.cs
- src/ScottPlot5/ScottPlot5/Primitives/Angle.cs
- src/ScottPlot5/ScottPlot5/Primitives/Coordinates.cs
- src/ScottPlot5/ScottPlot5/Primitives/PolarCoordinates.cs
- 1277609b19de7c3a6e92b565ea98dc0e103ee6e8 PieBase: Add Rotation property
resolve #3962
- 3fbb04e23544243d342d27b55d552cde60795159 PieBase: Apply AxisRules.SquareZoomOut 
fix display label position
resolve #4216
- 5804220ae9e528078d72c8d3f5ffa73035118d00 Pie: Fixed donut style with only one PieSlice
and some trivial changes.
```cs
PieSlice slice1 = new() { Value = 5, FillColor = Colors.Red, Label = "Red" };
PieSlice slice2 = new() { Value = 2, FillColor = Colors.Orange, Label = "Orange" };
PieSlice slice3 = new() { Value = 8, FillColor = Colors.Gold, Label = "Yellow" };
PieSlice slice4 = new() { Value = 4, FillColor = Colors.Green, Label = "Green" };
PieSlice slice5 = new() { Value = 8, FillColor = Colors.Blue, Label = "Blue" };
List<PieSlice> slices = new() { slice1, slice2, slice3, …
```
> Pie: add `Rotation` property and improve label alignment

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/AxisPanels/AxisBase.cs
- src/ScottPlot5/ScottPlot5/AxisPanels/XAxisBase.cs
- src/ScottPlot5/ScottPlot5/AxisPanels/YAxisBase.cs
It's similar to my PR about legends.
When axis titles are rather long, and the plot window is downsized, the titles start overlapping each other, which is not too esthetic. I have added clipping the titles to the axis panel rectangle, which solves the issue.
| Before | After |
| ------- | ----- |
| ![image](https://github.com/user-attachments/assets/eca9b592-8453-45d4-9c07-4fa4f47053df) | ![image](https://github.com/user-attachments/assets/c7c015de-8de0-4c46-b638-ba6ed2d74eb7) |
I understand, that on the example it's rather ugly both ways, but on bigger plots with longer axis names that makes a difference.
> Axes: Add `ClipLabel` option to opt-in to axis label clipping

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Marker.cs
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.UnoPlatform/Sandbox.UnoPlatform.csproj
- src/ScottPlot5/ScottPlot5/Drawing.cs
- src/ScottPlot5/ScottPlot5/Interfaces/IColormap.cs
- src/ScottPlot5/ScottPlot5/Plottables/Markers.cs
resolves #4143
```cs
var markers = myPlot.Add.Markers(xs, ys);
markers.Colormap = new ScottPlot.Colormaps.Turbo();
```
> Markers: add support for colormap

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/Plottables/DataLogger.cs
Due to the reimplementation of the DataLogger two of the Add overloads were dropped.
But as @jpgarza93 has mentioned in #4114, they can be useful. Bringing them back.
> Bring back Add method overloads to DataLogger

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/Fonts.cs
> Font.GetTypeface(): use caching to improve performance

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/Introduction/Styling.cs
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Scatter.cs
- src/ScottPlot5/ScottPlot5 Tests/Unit Tests/UnitTests/PrimitiveTests/LinePatternTests.cs
- src/ScottPlot5/ScottPlot5/Drawing.cs
- src/ScottPlot5/ScottPlot5/Generate.cs
- src/ScottPlot5/ScottPlot5/PlottableAdder.cs
- src/ScottPlot5/ScottPlot5/Primitives/LinePattern.cs
Under the existing code, I cannot implement the following styles by myself.
So I changed the `LinePattern` from an `enum` to a `readonly struct` to allow the user to set the desired style.
The API is the same as before, except for the method parameter defaults.
Since the method's parameter defaults need to be determined at compile time, I've switched to using `default` instead of `LinePattern.Solid`.
When `struct` is assigned a value of `default`, the internal real-value type member is set to the default value, so I declared a private `bool` flag to detect if the object is generated by `default`.
1. linestyles
https://matplotlib.org/stable/gallery/lines_bars_and_markers/linestyles.html
1. Default values ​​of struct
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin- …
> LinePattern: add support for custom patterns

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Tests/Unit Tests/RenderTests/Plottable/LinePlotTests.cs
- src/ScottPlot5/ScottPlot5/Plottables/LinePlot.cs
Add CoordinateLine getter and setter for LinePlot
#4274
included unit tests
```cs
Coordinates start = new Coordinates(0, 0);
Coordinates end = new Coordinates(5, 6);
LinePlot lp = new();
lp.Line = new CoordinateLine(start, end);
var newStart = lp.Line.Start;
var newEnd = lp.Line.End;
```
Is this what you had in mind @swharden?
> feat: Add CoordinateLine getter and setter for LinePlot

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.OpenGL/Plottables/ScatterGL.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.OpenGL/Plottables/ScatterGLCustom.cs
- src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/OpenGL.cs
- src/ScottPlot5/ScottPlot5/Interfaces/IPlottableGL.cs
- src/ScottPlot5/ScottPlot5/Rendering/RenderActions/RestoreGLState.cs
- src/ScottPlot5/ScottPlot5/Rendering/RenderActions/StoreGLState.cs
- src/ScottPlot5/ScottPlot5/Rendering/RenderManager.cs
Restore broken ScatterGL.
Adapted to changed interfaces.
Update WinForms.OpenGL demo to demonstrate features.
`RenderGridsBelowPlottables` stage uses Path to draw the grid lines. For some reason this completely breaks the OpenGL context needed for further drawing (I couldn't manage it, drawing a mesh with simple lines doesn't break anything). That's why we added stages of saving/restoring OpenGL attributes, before/after the RenderGridsBelowPlottables stage. They should not affect anything and will be just empty when GLPlottables are not used or Control does not support OpenGL acceleration.
> OpenGL Controls: add methods to save/restore GL state

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.OpenGL/GLExtensions.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.OpenGL/GLPrograms/ILinesDrawProgram.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.OpenGL/GLPrograms/IMarkersDrawProgram.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.OpenGL/GLPrograms/LinesProgram.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.OpenGL/GLPrograms/LinesProgramCustom.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.OpenGL/GLPrograms/MarkerOpenCircleProgram.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.OpenGL/GLPrograms/MarkerOpenSquareProgram.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.OpenGL/GLPrograms/MarkerProgram.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.OpenGL/Plottables/ScatterGL.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.OpenGL/ScottPlot.OpenGL.csproj
- src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/WinForms Demo.csproj
The build system of the `ScottPlot.OpenGL` project has been revised.
The `.NET Framework 462` version is now built with `OpenTK 3.3.1`.
And the version for modern `.NET` is built with `OpenTK 4.3.0`.
This allows us to use `ScatterGL` on `WpfPlotGL` control with modern .NET versions. (The old `ScottPlot.OpenGL` version was always built for `OpenTK 3.3.1` and actually resulted in an Exception when using `ScatterGL` on `WpfPlotGL`).
On the downside, `ScottPlot.OpenGL` support for `FormsPlotGL` breaks on modern versions of .NET. As a solution, for such projects it is suggested to include `ScottPlot.OpenGL` in this way:
```xml
<ProjectReference Include="..\..\ScottPlot5 Controls\ScottPlot.OpenGL\ScottPlot.OpenGL.csproj">
<SetTargetFramework>TargetFramework=net462</SetTargetFramework> …
```
> OpenGL: Use version-specific OpenTK dependency

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Polar.cs
- src/ScottPlot5/ScottPlot5/Plottables/PolarAxis.cs
- src/ScottPlot5/ScottPlot5/Plottables/Radar.cs
- fix clockwise and counterclockwise results of `GetCoordinates()`
fixed #4310
- rename `RotationDegrees` to `Rotation` and change type to `Angle`
- refactor `GetCoordinates()` with `PolarCoordinates`
- synchronizes `Rotation` with the angular direction of the Cartesian coordinate system
please refer to the following for differences
``` cs
var polarAxis = plot.Add.PolarAxis();
```
``` cs
polarAxis.Rotation = Angle.FromDegrees(90);
```
> Modify PolarAxis

- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/Statistics/Histograms.cs
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/Statistics/Regression.cs
- src/ScottPlot5/ScottPlot5/Statistics/Histogram.cs
This PR adds a `Histogram` constructor that accepts data values and demonstrates its use in the cookbook (which previously had a very broken histogram recipe page).
The `Histogram` class needs to be extensively refactored to improve support for arbitrary bins and add methods for getting percentage and cumulative probabilities (#4287)
> Coookbook: Fix histogram recipe

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Contour.cs
- src/ScottPlot5/ScottPlot5/Drawing.cs
- src/ScottPlot5/ScottPlot5/Plottables/ContourLines.cs
- src/ScottPlot5/ScottPlot5/Triangulation/RectangularGrid.cs
- src/ScottPlot5/ScottPlot5/Triangulation/RectangularGridPrimitives.cs
Contour lines are now calculated without triangulation of the original grid.
The MarchingSquares algorithm is used to find the contour.
The resulting lines are merged into a common path. There can be several of them for one elevation level.
Since our lines are merged into a path, we can add a label on top of the drawn path.
Grid primitives use indexes instead of real values. This is useful for accurate comparison of integer values, and reduces the number of interpolations by about half (we discard half of the points in the merge process)
It looks like the Heatmap was originally flipped by Y. I did the reverse flip manually in the cookBook example.
> Contour lines on rectangular grid

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Maui/MauiPlot.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Maui/MauiPlotExtensions.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Maui/MauiPlotMenu.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Maui/Platforms/Windows/PlatformClass1.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Maui/nuget-readme.md
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.Maui/MainPage.xaml
Hello again, I made modifications to the MAUI implementation to align with the new pattern mentioned in https://github.com/ScottPlot/ScottPlot/pull/4322 to use `UserInputProcessor`, which will now be enabled by default.
I also implemented a `SaveImageDialog`, which saves images by default to the `MyPictures` folder. I aimed to use only .NET and MAUI methods, and while there are some classes in CommunityToolkit, this was implemented natively. However, clipboard functionality is still missing.
The controls, while limited by MAUI, allow panning, and zooming via the contextual menu on desktop, and on mobile, panning and zooming can be done using touch gestures.
I believe this is what can be achieved within MAUI's current limitations, such as not being able to detect whether the right or left …
> Maui: Update

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Tests/Unit Tests/UnitTests/TickGenerators/DecimalTickSpacingCalculatorTests.cs
- src/ScottPlot5/ScottPlot5/TickGenerators/DecimalTickSpacingCalculator.cs
With very small Plot sizes, MajorTickGenerator sometimes returned only 2 absolutely identical positions. This caused problems when calculating logarithmic axes. #4353
This may be due to a typo corrected in this PR.
> Fix typo in GenerateTickPosition

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Tests/Unit Tests/UnitTests/PrimitiveTests/CoordinateRangeTests.cs
- src/ScottPlot5/ScottPlot5/Primitives/CoordinateRange.cs
Added Center property back to CoordinateRange, removed unintentionally in #4316.
Also added tests for properties `Span`, `Center` and `Length`, to make sure they're not removed unintentionally.
```cs
CoordinateRange range = new(0, 10);
double center = range.Center;
```
> Added Center property back to CoordinateRange

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinUI/WinUIPlotMenu.cs
.NET 8 was recently added as a target framework which exposed this condition as too limited as it is only true for .NET 6.
Since WinUI 3 requires .NET 6 and Windows 10 1809, this condition can be wholly removed; dependents will fail the WASDK conditions regardless.
Closes #4288
> WinUI: fix conditional compilation for .NET 8

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Avalonia/AvaPlot.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Blazor/BlazorPlotBase.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Eto/EtoPlot.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Maui/MauiPlot.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/WpfPlotBase.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms/FormsPlotBase.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinUI/WinUIPlot.cs
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WPF/MainWindow.xaml
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WPF/MainWindow.xaml.cs
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms/Sandbox.WinForms.csproj
- src/ScottPlot5/ScottPlot5/Interactivity/UserInputProcessor.cs
- src/ScottPlot5/ScottPlot5/Testing/MockPlotControl.cs
This allows the correct `Plot` to be acted upon even if `IPlotControl.Reset()` changes it.
* Resolves #4404
> UserInputProcessor: consume an `IPlotControl` instead of a `Plot` when constructing

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Maui/MauiPlot.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Maui/MauiPlotExtensions.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Maui/MauiPlotMenu.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Maui/Platforms/Windows/PlatformClass1.cs
Hi! In https://github.com/ScottPlot/ScottPlot/issues/4416, errors were reported in the desktop version. These errors have been fixed, and some unnecessary parts of the code have also been removed.
These errors were caused because two events were responsible for panning the plot. Mouse buttons as well as the scroll wheel can now be used in desktop versions 😀
There is still a minor issue: when holding down the screen and then adding another finger to zoom, the plot jumps. This is equivalent to holding down the mouse click and then moving the scroll wheel. However, for now, these are the most critical fixes
> MAUI: improvements in pan and zoom

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinFormsFinance/TradingViewForm.cs
- src/ScottPlot5/ScottPlot5/Primitives/OHLC.cs
- src/ScottPlot5/ScottPlot5/TickGenerators/FinancialTickGenerator.cs
resolves #4385
I think ultimately a financial tick rendering system that uses `IPlottable` to place labels is the best solution. In such a case the axis tick generator would be completely disabled.
This is an interesting intermediate solution that demonstrates how the tick system _could_ be harnessed to display improved tick labels for unevenly spaced financial data. It only supports two scales and could use more features (like not returning ticks outside the visible range) but it's a good start if someone wants to extend it.
> FinancialTickGenerator

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinFormsFinance/TradingViewForm.cs
- src/ScottPlot5/ScottPlot5/Interfaces/IFinancialTickGenerator.cs
- src/ScottPlot5/ScottPlot5/Plottables/FinancialTimeAxis.cs
- src/ScottPlot5/ScottPlot5/TickGenerators/Financial/Months.cs
- src/ScottPlot5/ScottPlot5/TickGenerators/Financial/MonthsAndMondays.cs
- src/ScottPlot5/ScottPlot5/TickGenerators/Financial/None.cs
- src/ScottPlot5/ScottPlot5/TickGenerators/Financial/Years.cs
This PR adds a new plottable which simulates the behavior of a horizontal axis, but which is designed to be customized and extended to improve support for showing dates and times on the horizontal axis to represent time data which may not be evenly spaced.
See the `Sandbox.WinFormsFinance` project for a working demo.
This PR is a proof of concept demonstration, and users who may wish to build upon this strategy (e.g., @quantfreedom and @vladislavpweetsoft) are encouraged to refine the work started here and create a pull request which I will review in good time.
See #4385 for additional discussion
> FinancialTimeAxis: A start toward improving support for financial charts with unevenly spaced time data

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/Primitives/Bar.cs
set Rect, ErrorLines, AxisLimits in Class Bar from internal to public
So we can access properties like this from outside the library
> Bar: make `internal` properties `public`

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/General/AxisRecipes.cs
- src/ScottPlot5/ScottPlot5/Plottables/FloatingAxis.cs
- src/ScottPlot5/ScottPlot5/Primitives/LabelStyle.cs
Resolves #3377
```cs
// create floating X and Y axes using one of the existing axes for reference
ScottPlot.Plottables.FloatingAxis floatingX = new(myPlot.Axes.Bottom);
ScottPlot.Plottables.FloatingAxis floatingY = new(myPlot.Axes.Left);
// hide the default axes and add the custom ones to the plot
myPlot.Axes.Frameless();
myPlot.HideGrid();
myPlot.Add.Plottable(floatingX);
myPlot.Add.Plottable(floatingY);
// add sample data last so it appears on top
myPlot.Add.Signal(Generate.Sin(51));
myPlot.Add.Signal(Generate.Cos(51));
```
> FloatingAxis: new plottable for displaying axes anywhere in the data area

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms/FormsPlot.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms/FormsPlotBase.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms/FormsPlotDesignerAlternative.Designer.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms/FormsPlotDesignerAlternative.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms/FormsPlotDesignerAlternative.resx
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms/FormsPlotGL.cs
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms/Form1.Designer.cs
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms/Form1.resx
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms/Program.cs
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms/Sandbox.WinForms.csproj
resolve #4362
After investigation, it was found that `FormsPlot` inherits `FormsPlotBase`, and its member `Plot` will call the method in `SkiaSharp`, so `FormsPlotBase` also needs to be adjusted.
Adjusted to detect whether `FormsPlotBase` throws an exception that `libSkiaSharp.dll` cannot be found, and display the current version and error message on the control.
like this
--- 
I found that I had to be careful whether `FormsPlot` properties were set in `Form.Designer.cs`.
If the property calls `SkiaSharp`, it may also affect the control and cause an error.🤔
> WinForms: improve the designer experience for .NET Framework apps

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/DataSources/SignalSourceBase.cs
- src/ScottPlot5/ScottPlot5/DataSources/SignalSourceDouble.cs
- src/ScottPlot5/ScottPlot5/DataSources/SignalSourceGenericArray.cs
- src/ScottPlot5/ScottPlot5/DataSources/SignalSourceGenericList.cs
- src/ScottPlot5/ScottPlot5/DataSources/SignalXYSourceDoubleArray.cs
- src/ScottPlot5/ScottPlot5/DataSources/SignalXYSourceGenericArray.cs
This functionality is hidden behind a flag so it can still be tested or reverted if necessary
resolves #4050
> Signal data sources: disable pixel overlap

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/WpfPlot.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/WpfPlotBase.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/WpfPlotGL.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms/FormsPlot.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms/FormsPlotBase.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms/FormsPlotExtensions.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms/FormsPlotGL.cs
- src/ScottPlot5/ScottPlot5/Interactivity/UserActionResponses/MouseDragPan.cs
- src/ScottPlot5/ScottPlot5/Interactivity/UserActionResponses/MouseDragZoom.cs
- src/ScottPlot5/ScottPlot5/Interactivity/UserActionResponses/MouseDragZoomRectangle.cs
- src/ScottPlot5/ScottPlot5/Interactivity/UserInputProcessor.cs
This PR implements this feature for the WinForms and WPF controls.
It may be added to the other controls in the future as desired, or invoked manually on the client side.
Resolves #4103
> Controls: abort mouse drags if the window loses focus

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/General/Styling.cs
- src/ScottPlot5/ScottPlot5/Panels/TitlePanel.cs
resolves #4455
```cs
formsPlot1.Plot.Axes.Title.FullFigureCenter = true;
```
default | FullFigureCenter
---|---
> Title: option to align to the figure instead of data area

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Blazor/ScottPlot.Blazor.csproj
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Maui/ScottPlot.Maui.csproj
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/ScottPlot.WPF.csproj
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms/ScottPlot.WinForms.csproj
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinUI/ScottPlot.WinUI.csproj
- src/ScottPlot5/ScottPlot5 Tests/Graphical Test Runner/Graphical Test Runner.csproj
- src/ScottPlot5/ScottPlot5 Tests/Unit Tests/CodeTests/CsprojTests.cs
- src/ScottPlot5/ScottPlot5/ScottPlot.csproj
Fixes WinUI issues on Windows by upgrading to the latest SkiaSharp dependency
resolves #4258
> SkiaSharp 2.88.8 →  2.88.9

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Tests/Unit Tests/RenderTests/Plottable/ScatterTests.cs
- src/ScottPlot5/ScottPlot5/Generate.cs
- src/ScottPlot5/ScottPlot5/Plottables/Scatter.cs
Scatter plot fills now respect both OffsetX and OffsetY. Previously only OffsetX was respected.
Resolves #4433
```cs
// create data points that resemble a "hump"
double[] ys = Generate.Cos(100, oscillations: 0.5, phase: -0.25);
double[] xs = Generate.RangeWithCount(0, 1, ys.Length);
```
```cs
// scatter with no offset
var sp1 = plot.Add.ScatterLine(xs, ys);
sp1.LineWidth = 3;
sp1.LineColor = Colors.Black;
sp1.FillY = true;
// scatter with offset
var sp2 = plot.Add.ScatterLine(xs, ys);
sp2.LineWidth = 3;
sp2.LineColor = Colors.Black;
sp2.FillY = true;
sp2.OffsetX = 2;
sp2.OffsetY = 2;
```
original behavior | new behavior
---|---
> Scatter: Fills now respect both OffsetX and OffsetY

- src/ScottPlot5/ScottPlot5/Interactivity/IUserActionResponse.cs
- src/ScottPlot5/ScottPlot5/Interactivity/UserActionResponses/DoubleClickResponse.cs
- src/ScottPlot5/ScottPlot5/Interactivity/UserActionResponses/KeyPressResponse.cs
- src/ScottPlot5/ScottPlot5/Interactivity/UserActionResponses/KeyboardPanAndZoom.cs
- src/ScottPlot5/ScottPlot5/Interactivity/UserActionResponses/MouseDragPan.cs
- src/ScottPlot5/ScottPlot5/Interactivity/UserActionResponses/MouseDragZoom.cs
- src/ScottPlot5/ScottPlot5/Interactivity/UserActionResponses/MouseDragZoomRectangle.cs
- src/ScottPlot5/ScottPlot5/Interactivity/UserActionResponses/MouseWheelZoom.cs
- src/ScottPlot5/ScottPlot5/Interactivity/UserActionResponses/SingleClickResponse.cs
- src/ScottPlot5/ScottPlot5/Interactivity/UserInputProcessor.cs
Extend the user action response interface to allow actions to be reset if the control loses and regains focus or the processor becomes disabled and re-enabled. Extends #4489 and #4481
> IUserActionResponse: ResetState()

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/DataSources/FastSignalSourceDouble.cs
- src/ScottPlot5/ScottPlot5/DataSources/SignalConstSource.cs
- src/ScottPlot5/ScottPlot5/DataSources/SignalSourceDouble.cs
- src/ScottPlot5/ScottPlot5/DataSources/SignalSourceGenericArray.cs
- src/ScottPlot5/ScottPlot5/DataSources/SignalSourceGenericList.cs
- src/ScottPlot5/ScottPlot5/PlottableAdder.cs
- src/ScottPlot5/ScottPlot5/Plottables/Signal.cs
- src/ScottPlot5/ScottPlot5/Plottables/SignalConst.cs
1. `SignalConstSource` is now based on `SignalSourceGenericArray`, except for `GetLimitsY()` which uses SegmentedTree for fast searching.
`SignalConst<T>` is also based on `Signal`. We can actually get rid of it as a standalone plottable by replacing it with `Signal `with `SignalConstSource` as the `DataSource`. I decided to keep it to preserve the API in this PR.
We lost the rendering version for SignalConst it was very different, and maybe looked like a more optimized version. But in the end `SignalConst` is still very fast.
2. A separate change in this PR is to change the check for an empty array. It was not done in an optimal way. For generic types, the entire array was converted to perform a single check (this slowed `SignalConst` down significantly). I used Enumerable version, but …
> SignalConst simplify

- .github/workflows/pr1.yaml
- .github/workflows/task-full.yaml
- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/General/Legend.cs
- src/ScottPlot5/ScottPlot5 Cookbook/ScottPlot Cookbook.csproj
- src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WPF Demo/DemoWindows/Quickstart.xaml.cs
- src/ScottPlot5/ScottPlot5/Primitives/LabelStyle.cs
- src/ScottPlot5/ScottPlot5/ScottPlot.csproj
Adds support for Right to Left languages. #4306
This change affects the output of absolutely all texts, not just legends as suggested by #4306.
RTL support is disabled by default, and everything works as before, unchanged.
Setting the `LabelStyle.RTLSupport` static property results in additional wrapping of the output text in `Shaper`.
Actually this change may include a lot more than just RTL support, since there's a whole separate engine under the hood for rendering characters, but I'm not good at that.
I really don't like customizing the behavior with a static property, but I don't see any other easy ways to solve this problem. `LabelStyle` constructors are spread all over the project in large numbers.
Added a demo of RTL usage to be displayed in the legend. I'm sure you can fix/extend …
> RTL support

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/General/AxisRecipes.cs
- src/ScottPlot5/ScottPlot5/AxisPanels/XAxisBase.cs
- src/ScottPlot5/ScottPlot5/AxisPanels/YAxisBase.cs
- src/ScottPlot5/ScottPlot5/Primitives/LabelStyle.cs
- src/ScottPlot5/ScottPlot5/SampleImages.cs
This PR adds a nullable `Image` to `LabelStyle` so a bitmap image can be displayed anywhere a text label may be placed.
This enables users to use third-party packages to render rich text or emoji as a bitmap image, then display it as an axis label
* Resolves: #4503
* Resolves: #3222
* Related: #2905
```cs
myPlot.Add.Signal(Generate.Sin(51));
myPlot.Add.Signal(Generate.Cos(51));
// This array holds the bytes of a bitmap. Here it's generated,
// but it could be a byte array read from a bitmap file on disk.
byte[] bytes1 = SampleImages.NoisyText("Horiz", 150, 50).GetImageBytes();
byte[] bytes2 = SampleImages.NoisyText("Vert", 150, 50).GetImageBytes();
// Create a ScottPlot.Image from the bitmap bytes
ScottPlot.Image img1 = new(bytes1);
ScottPlot.Image img2 = new(bytes2);
// Display the image …
```
> LabelStyle: add support for image labels

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/Interactivity/UserActionResponses/MouseWheelZoom.cs
Previously repeated zoom in/out cycles would not restore the original axis limits. This change makes zooming out exactly reverse the zooming in scale, and also exposes a ZoomFraction property to let the user customize mouse scroll wheel sensitivity. Resolves #4516
> Controls: update mouse wheel zoom to zoom in and out identically

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.OpenGL/GLPrograms/LinesProgramCustom.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.OpenGL/GLPrograms/MarkerFillCircleProgram.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.OpenGL/GLPrograms/MarkerFillSquareProgram.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.OpenGL/GLPrograms/MarkerOpenSquareProgram.cs
ScatterGLCustom is not drawing any line due to a small mistake in LinesProgramCustom.cs.
I'm not an expert in OpenGL, but when we write:
"#version 430 core"
instead of:
"# version 430 core"
ScatterGLCustom starts drawing the lines.
> OpenGL: update version line to fix bug causing lines not to be rendered

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/WpfPlotViewer.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms/FormsPlotViewer.cs
This PR addresses an issue in ScottPlot 5 related to the "Open in New Window" functionality in both WinForms and WPF.
- Issue:
- In WPF, after closing the new window, the ContextMenu on the original window would no longer appear.
- In WinForms, the ContextMenu was shown at the wrong position because it was being displayed on the new PlotControl instead of the original one.
- Cause: The issue occurred because, during the process of moving the Plot content to the new window, the original window’s PlotControl was overwritten but not properly restored when the new window was closed.
- Solution: After the new window is closed, the PlotControl on the original window is properly restored, ensuring the ContextMenu behaves as expected.
> Fix: restore original PlotControl after closing new window

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/General/AxisRecipes.cs
- src/ScottPlot5/ScottPlot5/AxisManager.cs
- src/ScottPlot5/ScottPlot5/Plottables/TickModifierLabel.cs
Resolves #4530
```cs
myPlot.Axes.SetupMultiplierNotation(myPlot.Axes.Left);
myPlot.Axes.SetupMultiplierNotation(myPlot.Axes.Bottom);
```
> Axes: SetupMultiplierNotation()

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/AxisPanels/XAxisBase.cs
- src/ScottPlot5/ScottPlot5/AxisPanels/YAxisBase.cs
resolves #4535
```cs
formsPlot1.Plot.XLabel("Line 1\nLine 2\nLine 3");
formsPlot1.Plot.YLabel("Line 1\nLine 2\nLine 3");
```
before | after
---|---
> AxisBase.Measure() improve multiline support

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Heatmap.cs
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms/Form1.cs
- src/ScottPlot5/ScottPlot5/Plottables/Heatmap.cs
This PR adds a `Rectangle` property to `Heatmap` to make it easier to define the _edges_ of a heatmap using a rectangle in coordinate space. 
Note that `Extent` does something similar, but defines the rectangle containing the _centers_ of each cell, and is one cell smaller in size than `Rectangle`
* resolves #4552
* resolves #4550
Extent = new(-5, 5, -5, 5) | Rectangle = new(-5, 5, -5, 5)
---|---
> Heatmap.Rectangle

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Bar.cs
- src/ScottPlot5/ScottPlot5/Palettes/Custom.cs
- src/ScottPlot5/ScottPlot5/PlottableAdder.cs
This PR adds `Plot.Add.Ranges()` and `Plot.Add.StackedRanges()` helper methods to simplify the creation of charts which use bar plots to display ranges of values.
See cookbook for code examples.
Resolves #4548
> Add Range and StackedRange charts

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Bracket.cs
- src/ScottPlot5/ScottPlot5/PlottableAdder.cs
- src/ScottPlot5/ScottPlot5/Plottables/Bracket.cs
This PR brins the `Bracket` plot type from ScottPlot 4 into ScottPlot 5. Thanks @bclehmann for your previous work on this (#1863) this was very easy to bring over and it looks great! 🚀 
resolves #4547
```cs
myPlot.Add.Signal(Generate.Sin());
myPlot.Add.Bracket(0, 1, 0, 0, "Bracket A");
myPlot.Add.Bracket(25, -1, 38, -1, "Bracket B");
myPlot.Add.Bracket(20, .55, 27, -.3, "Bracket C");
```
> Bracket: new plot type

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/DetachedLegend.Designer.cs
- src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/DetachedLegend.cs
- src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/DetachedLegend.resx
- src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Program.cs
- src/ScottPlot5/ScottPlot5/Panels/LegendPanel.cs
- src/ScottPlot5/ScottPlot5/Primitives/Legend.cs
Adds a demo example for the detacheable legend control + plot modification options.
What remains to be done
> Demo: detachable legend and click-to-toggle-visibility

- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Avalonia/AvaPlot.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Blazor/BlazorPlotBase.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Eto/EtoPlot.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Maui/MauiPlot.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/WpfPlotBase.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms/FormsPlot.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms/FormsPlotBase.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinUI/WinUIPlot.cs
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms/Form1.Designer.cs
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms/Form1.cs
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms/Form1.resx
- src/ScottPlot5/ScottPlot5/Interfaces/IPlotControl.cs
- src/ScottPlot5/ScottPlot5/Multiplot.cs
- src/ScottPlot5/ScottPlot5/Testing/MockPlotControl.cs
This PR adds `Multiplot` to `IPlotControl` and improves its support for rendering onto existing surfaces.
This work is part of a multi-step process to add interactive multi-plot support to user controls (#4600)
> IPlotControl: add Multiplot

- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/WpfPlotViewer.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms/FormsPlotViewer.cs
- src/ScottPlot5/ScottPlot5/AxisManager.cs
- src/ScottPlot5/ScottPlot5/Interactivity/MouseAxisManipulation.cs
- src/ScottPlot5/ScottPlot5/Interactivity/UserActionResponses/SingleClickContextMenu.cs
- src/ScottPlot5/ScottPlot5/Plot.cs
This PR removes `Plot.PlotControl` to ensure no logic reaches into a `Plot` to grab its control for the purposes of interacting with it directly. This is in preparation for implementing interactive mulit-plot controls where the `Multiplot` should hold the control, not each `Plot` (although it is preferable that an implementation strategy be devised which passes the `IPlotControl` through calling functions only if/as needed).
This work is part of a multi-step process to add interactive multi-plot support to user controls (https://github.com/ScottPlot/ScottPlot/issues/4600)
> Plot: deprecate PlotControl

- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms/FormsPlot.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms/FormsPlotBase.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms/FormsPlotExtensions.cs
- src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/CustomMouseActions.cs
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms/Form1.Designer.cs
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms/Form1.cs
- src/ScottPlot5/ScottPlot5/Interactivity/IUserActionResponse.cs
- src/ScottPlot5/ScottPlot5/Interactivity/UserActionResponses/DoubleClickBenchmark.cs
- src/ScottPlot5/ScottPlot5/Interactivity/UserActionResponses/DoubleClickResponse.cs
- src/ScottPlot5/ScottPlot5/Interactivity/UserActionResponses/KeyPressResponse.cs
- src/ScottPlot5/ScottPlot5/Interactivity/UserActionResponses/KeyboardAutoscale.cs
- src/ScottPlot5/ScottPlot5/Interactivity/UserActionResponses/KeyboardPanAndZoom.cs
- src/ScottPlot5/ScottPlot5/Interactivity/UserActionResponses/MouseDragPan.cs
- src/ScottPlot5/ScottPlot5/Interactivity/UserActionResponses/MouseDragZoom.cs
- src/ScottPlot5/ScottPlot5/Interactivity/UserActionResponses/MouseDragZoomRectangle.cs
- src/ScottPlot5/ScottPlot5/Interactivity/UserActionResponses/MouseWheelZoom.cs
- src/ScottPlot5/ScottPlot5/Interactivity/UserActionResponses/SingleClickAutoscale.cs
- src/ScottPlot5/ScottPlot5/Interactivity/UserActionResponses/SingleClickContextMenu.cs
- src/ScottPlot5/ScottPlot5/Interactivity/UserActionResponses/SingleClickResponse.cs
- src/ScottPlot5/ScottPlot5/Interactivity/UserInputProcessor.cs
- src/ScottPlot5/ScottPlot5/Interfaces/IPlotControl.cs
- src/ScottPlot5/ScottPlot5/Multiplot.cs
- src/ScottPlot5/ScottPlot5/Primitives/MultiAxisLimits.cs
- src/ScottPlot5/ScottPlot5/Testing/MockPlotControl.cs
This PR updates all `UserInputProcessor` code to pass an `IPlotControl` instead of a `Plot` and adds logic to determine which `Plot` is under the mouse and forward events to that item. This PR is part of #4600
**A single control may now be used to display multiple interactive plots!** This should allow for easier implementation of plots with shared axes and shared layouts because we no longer have to sync settings across multiple plot controls.
```cs
// work with the plot like normal
formsPlot1.Plot.Add.Signal(Generate.Sin());
// add a sub-plot and interact with it
var plot2 = formsPlot1.Multiplot.AddPlot();
plot2.Add.Signal(Generate.Cos());
```
> IPlotControl: support multiplot interactivity

- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/General/MultiplotRecipes.cs
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms/Form1.cs
- src/ScottPlot5/ScottPlot5/Multiplot.cs
- src/ScottPlot5/ScottPlot5/MultiplotLayouts/Columns.cs
- src/ScottPlot5/ScottPlot5/MultiplotLayouts/Grid.cs
- src/ScottPlot5/ScottPlot5/MultiplotLayouts/Rows.cs
- src/ScottPlot5/ScottPlot5/Primitives/AxisLimits.cs
This PR adds support for subplots with shared axis limits in mouse-interactive multiplots
This is part of a larger collection of work tracked by #4600
```cs
public Form1()
{
Plot[] subplots = formsPlot1.Multiplot.AddPlots(4);
for (int i = 0; i < subplots.Length; i++)
{
double scale = Math.Pow(10, i);
double[] data = Generate.RandomWalk(100, scale*2);
subplots[i].Add.Signal(data);
subplots[i].Title($"Subplot {i + 1}");
}
formsPlot1.Multiplot.Layout = new ScottPlot.MultiplotLayouts.Grid(2, 2);
// share the X axis for all subplots
formsPlot1.Multiplot.ShareX(subplots);
// share the Y axis for select subplots
formsPlot1.Multiplot.ShareY([subplots[0], subplots[1]]);
}
```
> Multiplot: add support for shared axis limits

- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms/Form1.cs
- src/ScottPlot5/ScottPlot5/Multiplot.cs
This PR adds `MultiPlot.ApplyFixedPadding()` to quickly apply a fixed size data area to all subplots ensuring alignment in multi-plot figures.
This work is part of #4600
default | fixed padding
---|---
> Multiplot: helper method to enable fixed layout for all subplots

- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/General/MultiAxis.cs
resolves #4565
```cs
// add a plottable to the plot
var sig = myPlot.Add.Signal(Generate.Sin());
// configure the plottable to use the right Y axis
sig.Axes.YAxis = myPlot.Axes.Right;
// configure the grid to display ticks from the right Y axis
myPlot.Grid.YAxis = myPlot.Axes.Right;
// style the right axis as desired
myPlot.Axes.Right.Label.Text = "Hello, Right Axis";
myPlot.Axes.Right.Label.FontSize = 18;
// pass in the custom axis when calling SetLimits()
myPlot.Axes.SetLimitsY(bottom: -2, top: 2, yAxis: myPlot.Axes.Right);
```
> Cookbook: right axis only

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Line.cs
- src/ScottPlot5/ScottPlot5/Plottables/LinePlot.cs
This PR adds `LineOnTop` and `MarkersOnTop` flags to control which components appear in front of `LinePlot` plottables
Resolves #4610
```cs
var line1 = myPlot.Add.Line(0, 0, 1, 1);
line1.LineColor = Colors.Orange;
line1.LineWidth = 5;
line1.MarkerColor = Colors.Red;
line1.MarkerSize = 20;
line1.MarkerShape = MarkerShape.FilledCircle;
line1.LineOnTop = true; // render order is controlled here
var line2 = myPlot.Add.Line(0, 1, 1, 2);
line2.LineColor = Colors.Orange;
line2.LineWidth = 5;
line2.MarkerColor = Colors.Red;
line2.MarkerSize = 20;
line2.MarkerShape = MarkerShape.FilledCircle;
line2.MarkersOnTop = true; // render order is controlled here
```
> LinePlot: add `LineOnTop` and `MarkersOnTop` flags to control render order

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/General/MultiAxis.cs
- src/ScottPlot5/ScottPlot5/Interfaces/IAxis.cs
This PR adds a helper method to simplify removing ticks from unused axes
```cs
myPlot.Axes.Left.RemoveTickGenerator();
```
Related: #2875, #4613, #4608, #4613
> IAxis: RemoveTickGenerator()

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Avalonia/ScottPlot.Avalonia.csproj
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Blazor/ScottPlot.Blazor.csproj
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Eto/ScottPlot.Eto.csproj
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Maui/ScottPlot.Maui.csproj
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.OpenGL/ScottPlot.OpenGL.csproj
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/ScottPlot.WPF.csproj
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/WpfPlot.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms/ScottPlot.WinForms.csproj
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinUI/ScottPlot.WinUI.csproj
- src/ScottPlot5/ScottPlot5/ScottPlot.csproj
This PR fixes plot rendering plots for WPF by calling Render method on `Multiplot` instead of `Plot`. The issue is described here #4666
Fixes #4666.
> WPF: Pass render requests through the new Multiplot system

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Avalonia/AvaPlotMenu.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Blazor/BlazorPlotMenu.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Eto/EtoPlotMenu.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Maui/MauiPlotMenu.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/WpfPlotMenu.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinForms/FormsPlotMenu.cs
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WinUI/WinUIPlotMenu.cs
- src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/CustomMenu.cs
- src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/DetachedLegend.cs
- src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.WinForms/Form1.cs
- src/ScottPlot5/ScottPlot5/AxisManager.cs
- src/ScottPlot5/ScottPlot5/Interactivity/UserActionResponses/SingleClickContextMenu.cs
- src/ScottPlot5/ScottPlot5/Interfaces/IPalette.cs
- src/ScottPlot5/ScottPlot5/Interfaces/IPlotMenu.cs
- src/ScottPlot5/ScottPlot5/Multiplot.cs
- src/ScottPlot5/ScottPlot5/Plot.cs
- src/ScottPlot5/ScottPlot5/Primitives/ContextMenuItem.cs
This PR modifies `ContextMenuItem.OnInvoke` to act on a specific `Plot` instead of the `IPlotControl` to improve support for multi-plot environments.
All user control menu systems required refactoring to support this change.
Resolves #4671
> Controls: improve multiplot support for context menu

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/AxisRules/MaximumBoundary.cs
- src/ScottPlot5/ScottPlot5/AxisRules/MinimumBoundary.cs
PR #4609 (Axis Rules: limit rules do not function property on inverted axes) adds support for inner/outer bounds rules for inverted axes. But it has some peculiarities, when panning the chart to the specified boundary values, zoomming occurs. In my opinion, this is not very correct. This PR fixes this behavior.
`MinimumBoundary` вefore:
https://github.com/user-attachments/assets/c84070d2-a169-495b-94c4-4c7fd42f98ed
`MinimumBoundary` after:
https://github.com/user-attachments/assets/4eb02416-690b-4bde-9610-9b344e3af921
`MaximumBoundary` вefore:
https://github.com/user-attachments/assets/8803d07f-0e41-4836-8ae8-a649556084f7
`MaximumBoundary` after:
https://github.com/user-attachments/assets/0c0fed50-e548-413c-85bc-a8aa35a9e4da
> Axis Rules: Improve support for boundaries on plots with inverted axes

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.OpenGL/Plottables/ScatterGL.cs
Although the InitializeGL method is intended to be called only once, I had to call it many times in a project. Especially in cases where Vertices were recalculated. InitializeGL() causes memory leaks when called again. To prevent this, I added the CleanupGL() method to cleanup OpenGL resources and call it from the beginning of InitializeGL().
> Added CleanupGL() method into ScatterGL class

- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/PolarAxis.cs
Modifies the padding of labels on polar spokes.
```cs
var polarAxis = myPlot.Add.PolarAxis();
polarAxis.SetSpokes(4, 1);
for (int i = 0; i < polarAxis.Spokes.Count; i++)
{
polarAxis.Spokes[i].LineWidth = 4;
polarAxis.Spokes[i].LabelStyle.FontSize = 16;
polarAxis.Spokes[i].LabelPaddingFraction = 0.2 * i;
polarAxis.Spokes[i].LabelText = $"{polarAxis.Spokes[i].LabelLength}";
}
```
related #4716
> Cookbook: Polar Spoke Label Padding

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Tests/Unit Tests/CodeTests/CodeRequirementTests.cs
- src/ScottPlot5/ScottPlot5/Interactivity/UserActionResponses/KeyboardAutoscale.cs
This pull request updates the KeyboardAutoscale class  by changing its access modifier from internal to public. This change ensures consistency with other user action response classes and allows users to remove the KeyboardAutoscale action using the UserInputProcessor.RemoveAll<T> method.
[#4664](https://github.com/ScottPlot/ScottPlot/issues/4664)
> Make KeyboardAutoscale.cs public to allow removal from UserInputProcessor

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/AxisRules/MaximumSpan.cs
- src/ScottPlot5/ScottPlot5/AxisRules/MinimumSpan.cs
This PR fixes the behavior of MinimumSpan and MaximumSpan rules when an axis is inverted (Min > Max). Previously, these rules did not correctly account for inverted axes, leading to incorrect enforcement of span constraints.
➜ If MinimumSpan or MaximumSpan is used alongside a minimum or maximum boundary, the constraints were not being applied correctly.
➜ If MinimumSpan or MaximumSpan is used alone (without min/max boundary constraints), the axis ticks would not be displayed as inverted.
[#4735](https://github.com/ScottPlot/ScottPlot/issues/4735)
> Fix inverted axis min max span

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Controls/ScottPlot.Avalonia/AvaPlot.cs
This fixes #4732, and in a more permanent way than just fixing the workaround that we used to have. That workaround is no longer necessary.
What I believe happened is our `Render` method was permitted to overwrite the SKCanvas of controls beneath us, Avalonia was not implicitly creating new canvases for different controls and blending them during compositing according to each control's depth. Instead, we need to do that ourselves.
My starting point for all of these examples is the Avalonia Sandbox project in `src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.Avalonia.Desktop`
I replaced `MainView.axaml.cs` with this:
```cs
using Avalonia.Controls;
using ScottPlot.Avalonia;
namespace Sandbox.Avalonia;
public partial class MainView : UserControl
{
public MainView()
{ …
```
> AvaPlot: Always render to new layer

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Tests/Unit Tests/UnitTests/PrimitiveTests/CoordinateRangeTests.cs
- src/ScottPlot5/ScottPlot5/Primitives/CoordinateRange.cs
Fix for issue here:
https://github.com/ScottPlot/ScottPlot/issues/4665
Simple fix. I also added 5 unit test cases to test for it.
```cs
public static CoordinateRange Extrema(IEnumerable<double> values)
{
var nonNanValues = values.Where(i => !double.IsNaN(i)).ToList();
return nonNanValues.Any()
? new CoordinateRange(nonNanValues.Min(), nonNanValues.Max())
: NoLimits;
}
```
> CoordinateRange: improve NaN support

- .github/workflows/task-autoformat-check.yaml
- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/Plottables/SmithChartAxis.cs
- src/ScottPlot5/ScottPlot5/Plottables/TriangularAxis.cs
This PR fixes an issue with the `GetCoordinates` method in `TriangularAxis`. The original method incorrectly enforced `leftFraction + rightFraction = 1`, which violates ternary plot rules.
- Ensures that `bottomFraction + leftFraction + rightFraction = 1` as required for valid ternary plots.
- Supports both clockwise and counterclockwise transformations.
#4797
> Fix ternary coordinate validation in TriangularAxis

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/DataSources/SignalXYSourceGenericList.cs
This requires a binary search implementation for IReadOnlyList. I tested this by calling both Array.BinarySearch on Xs.ToArray() and my implementation on every received input and throwing if they didn't match.
The performance is much improved, the previous implementation dropped below 60fps for relatively modest input lengths (much past 10000 points) At this point `System.Linq.Enumerable.ToArray<T>` takes up ~75% of the CPU time in the profiler. On the new one I left it running by accident and it's still going strong at 1 million+ points, even on a debug build.
Discussed in my review comment on #4753
I tested it with this Avalonia app:
```cs
using Avalonia.Controls;
using ScottPlot.Avalonia;
using System.Collections.Generic;
using Avalonia.Threading;
using System.Linq; …
```
> SignalXYSourceGenericList: Reduce allocations and copying to improve performance

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/Primitives/CoordinateRangeMutable.cs
The previous `Equals` implementation was incorrect. This was noted in #4795 but I figured it should be picked out since I'm not sure if that PR should/will be merged.
> CoordinateRangeMutable: Corrects `Equals`

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Tests/Unit Tests/RenderTests/Plottable/BarTests.cs
- src/ScottPlot5/ScottPlot5 Tests/Unit Tests/RenderTests/Plottable/SignalTests.cs
- src/ScottPlot5/ScottPlot5/Plottables/BarPlot.cs
- src/ScottPlot5/ScottPlot5/Primitives/Bar.cs
* resolves #4760
```cs
List<Bar> bars = [];
for (int i = 0; i < 10; i++)
{
double value = Generate.RandomInteger(-100, 100);
bars.Add(new()
{
Position = i,
Value = value,
Label = value.ToString(),
FillColor = Colors.C0,
LineWidth = 0,
});
}
Plot plot = new();
var barPlot = plot.Add.Bars(bars);
barPlot.ValueLabelStyle.FontSize = 18;
barPlot.ValueLabelStyle.Bold = true;
plot.Axes.Margins(0.1, 0.25); // increase vertical margins to make room for labels
plot.Add.HorizontalLine(0, 1, Colors.Black, LinePattern.DenselyDashed);
plot.HideGrid();
```
> bar: place value below bars when value is negative

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/CustomMarkerDemo.cs
- src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/CustomPlotType.cs
- src/ScottPlot5/ScottPlot5/ArrowShapes/Arrowhead.cs
- src/ScottPlot5/ScottPlot5/ArrowShapes/Chevron.cs
- src/ScottPlot5/ScottPlot5/ArrowShapes/Double.cs
- src/ScottPlot5/ScottPlot5/ArrowShapes/Pentagon.cs
- src/ScottPlot5/ScottPlot5/ArrowShapes/Single.cs
- src/ScottPlot5/ScottPlot5/Drawing.cs
- src/ScottPlot5/ScottPlot5/Markers/FilledCircle.cs
- src/ScottPlot5/ScottPlot5/Markers/FilledDiamond.cs
- src/ScottPlot5/ScottPlot5/Markers/FilledSquare.cs
- src/ScottPlot5/ScottPlot5/Markers/FilledTriangleDown.cs
- src/ScottPlot5/ScottPlot5/Markers/FilledTriangleUp.cs
- src/ScottPlot5/ScottPlot5/Plottables/Pie.cs
- src/ScottPlot5/ScottPlot5/Plottables/Radar.cs
- src/ScottPlot5/ScottPlot5/Plottables/Scatter.cs
Rename `DrawXXX()` methods using `FillStyle` to `FillXXX()`.
The old methods still exist but are now marked as obsolete and forward calls to the new methods, with a reminder for users to migrate.
---
I noticed that FillRectangle had duplicate implementations, so I merged and simplified them.
> Drawing: Improve DrawPath/FillPath and DrawPath/FillCircle name consistency

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/General/Legend.cs
- src/ScottPlot5/ScottPlot5/Primitives/Legend.cs
This is to hopefully implement a default marker type, in case you want to keep all of legend defaults, but change the marker style.  Looking for feedback from @swharden or anyone else familiar with the Legend/LegendItems, but hopefully fixes issue #5005
I included a new cookbook item for Legend > Default Marker style
```cs
var sig1 = myPlot.Add.Signal(Generate.Sin(51));
sig1.LegendText = "Sin";
var sig2 = myPlot.Add.Signal(Generate.Cos(51));
sig2.LegendText = "Cos";
myPlot.Legend.MarkerShapeDefault = MarkerShape.FilledCircle;
LegendItem item1 = new()
{
MarkerColor = Colors.Red,
MarkerShape = MarkerShape.Cross,
LabelText = "Alpha"
};
LegendItem item2 = new()
{
MarkerColor = Colors.Green,
MarkerShape = MarkerShape.FilledSquare,
LabelText = "Beta"
}; …
```
> Legend: default marker style

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/Drawing.cs
- src/ScottPlot5/ScottPlot5/Plottables/Pie.cs
**This PR is divided into two parts:**
1. Replace hard-coded radius with a `Radius` property
2. Use `Drawing`’s static methods for slice rendering
3. Refactor `Render` by extracting slice logic into `RenderSlice()` and `RenderDonutSlice()`
1. Raster `ClipPath + Difference` works on pixels but most SVG exporters emit a `<clipPath>` definition with spotty support, leading to missing or malformed rings.
2. Switched to a single vector path with an Even-Odd fill rule so that the annulus always exports correctly.
```cs
Plot plot1 = formsPlot1.Plot;
plot1.HideLegend();
plot1.HideAxesAndGrid();
var pie1 = plot1.Add.Pie([new PieSlice()
{
Value = 100,
FillColor = Colors.Red,
Label = "A"
}]);
pie1.DonutFraction = .5;
File.WriteAllText("./pie.html", $"""
<html>
{plot1.GetSvgHtml(300, 300)}
</html> …
```
> Pie: Reorganized code and fixed SVG rendering

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/PolarAxis.cs
- src/ScottPlot5/ScottPlot5/PlottableAdder.cs
- src/ScottPlot5/ScottPlot5/Plottables/PolarAxis.cs
- src/ScottPlot5/ScottPlot5/Primitives/Angle.cs
Resolves #4884 
Default | `Rotation=-90` and `Clockwise=true`
---|---
> PolarAxis: Add a `Clockwise` property

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/Rendering/RenderManager.cs
Fixes #5026
**Problem**
Transparent backgrounds in WinUI3 cause frame accumulation when using axis rules (`SquareZoomOut`, `SquarePreserveX`, etc.) due to improper canvas clearing between iterations.
**Solution**
Add `canvas.Clear()` before each render iteration in `RenderManager.Render()` to force proper clearing of WinUI3's transparent rendering pipeline.
> Fix transparent background frame accumulation with axis rules

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5 Cookbook/RecipeBase.cs
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/General/Legend.cs
- src/ScottPlot5/ScottPlot5 Cookbook/Recipes/PlotTypes/Radar.cs
- src/ScottPlot5/ScottPlot5/Fonts.cs
- src/ScottPlot5/ScottPlot5/Plottables/Radar.cs
- src/ScottPlot5/ScottPlot5/Plottables/Signal.cs
- src/ScottPlot5/ScottPlot5/Primitives/Legend.cs
Quick PR to get things ready to publish packages soon:
* Add option to reset fonts https://github.com/ScottPlot/ScottPlot/pull/5013#issuecomment-3194643993
* Minimize untended behavior changes for legend markers https://github.com/ScottPlot/ScottPlot/pull/5006
* Radar: use new polar plot rotation and clockwise features #4884
> Fix: Fonts, Legend Markers, and Radar Rotation Direction

- CHANGELOG.md
- src/ScottPlot5/ScottPlot5/LegendLayouts/Wrapping.cs
- src/ScottPlot5/ScottPlot5/Primitives/Legend.cs
This PR addresses a regression introduced after [PR #5006](https://github.com/ScottPlot/ScottPlot/pull/5006), where the MarkerStyle.Size property stopped taking effect when a MarkerShapeDefault was set.
Fixes [#4999](https://github.com/ScottPlot/ScottPlot/issues/4999) (marker shape clipping by legend rectangle).
In the original PR, the logic was:
```cs
if (MarkerShapeDefault != MarkerShape.None)
{
item.MarkerStyle.Shape = item.MarkerShape != MarkerShape.None ? item.MarkerShape : MarkerShapeDefault;
// NOTE: tried this but size seems to be defaulting something to something small, 
// so you can barely see the shape, defaulting to font size for now
//item.MarkerStyle.Size = item.MarkerStyle.Size != 0 ? item.MarkerStyle.Size : item.LabelFontSize;
item.MarkerStyle.Size = item.LabelFontSize;
} …
```
> Legend Restore MarkerStyle.Size behavior and fix marker clipping inside rectangle
